# Layer 2 Backbone Exploration

This notebook runs the second-layer backbone comparison for the selected hard settings.

Fixed design:
- Architecture: `Unet`
- Encoder weights: `imagenet`
- Settings: `Single-TB`, `Shift-TA_TC-to-TB_10pct`, `Shift-TA_TB-to-TC_10pct`
- Backbones: `resnet34`, `efficientnet-b0`, `resnet50`

## 1. Setup

In [1]:
from pathlib import Path
import subprocess
import pandas as pd
from IPython.display import display, Markdown

PROJECT_ROOT = Path('/users/7/yu001011/csci5527/CSCI5527-final')
SCRIPT_DIR = PROJECT_ROOT / 'baseline_models_scripts'
RESULTS_DIR = SCRIPT_DIR / 'runs'
VENV_PY = Path('/users/7/yu001011/csci5527/.venv/bin/python')

PROJECT_ROOT, SCRIPT_DIR, RESULTS_DIR, VENV_PY

(PosixPath('/users/7/yu001011/csci5527/CSCI5527-final'),
 PosixPath('/users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts'),
 PosixPath('/users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs'),
 PosixPath('/users/7/yu001011/csci5527/.venv/bin/python'))

## 2. Experiment Design

In [2]:
ARCH = 'Unet'
ENCODER_WEIGHTS = 'imagenet'
EPOCHS = 100
BATCH_SIZE = 16
IMG_SIZE = 512
LR = 1e-4

SETTINGS = [
    'Single-TB',
    'Shift-TA_TC-to-TB_10pct',
    'Shift-TA_TB-to-TC_10pct',
]

BACKBONES = [
#     'resnet34',
    'efficientnet-b0',
    'resnet50',
]

pd.DataFrame([
    {'Setting': setting, 'Backbone': backbone}
    for setting in SETTINGS
    for backbone in BACKBONES
])

                   Setting         Backbone
0                Single-TB  efficientnet-b0
1                Single-TB         resnet50
2  Shift-TA_TC-to-TB_10pct  efficientnet-b0
3  Shift-TA_TC-to-TB_10pct         resnet50
4  Shift-TA_TB-to-TC_10pct  efficientnet-b0
5  Shift-TA_TB-to-TC_10pct         resnet50

## 3. Helper Functions

In [3]:
def result_filename(backbone: str) -> str:
    return f'layer2_{backbone}.csv'

def build_command(setting: str, backbone: str):
    return [
        str(VENV_PY),
        'train_ttd.py',
        '--project-root', str(PROJECT_ROOT),
        '--experiment', setting,
        '--arch', ARCH,
        '--encoder', backbone,
        '--encoder-weights', ENCODER_WEIGHTS,
        '--epochs', str(EPOCHS),
        '--batch-size', str(BATCH_SIZE),
        '--img-size', str(IMG_SIZE),
        '--lr', str(LR),
        '--results-name', result_filename(backbone),
    ]

def run_one(setting: str, backbone: str):
    cmd = build_command(setting, backbone)
    print('Running:', ' '.join(cmd))
    return subprocess.run(cmd, cwd=SCRIPT_DIR, check=True)

def run_all(settings, backbones):
    for backbone in backbones:
        for setting in settings:
            run_one(setting, backbone)

## 4. Preview Commands

Use this first to confirm the exact commands before running anything.

In [4]:
command_preview = pd.DataFrame([
    {
        'Setting': setting,
        'Backbone': backbone,
        'Command': ' '.join(build_command(setting, backbone)),
    }
    for setting in SETTINGS
    for backbone in BACKBONES
])

display(command_preview)

,Setting,Backbone,Command
0,Single-TB,efficientnet-b0,/users/7/yu001011/csci5527/.venv/bin/python tr...
1,Single-TB,resnet50,/users/7/yu001011/csci5527/.venv/bin/python tr...
2,Shift-TA_TC-to-TB_10pct,efficientnet-b0,/users/7/yu001011/csci5527/.venv/bin/python tr...
3,Shift-TA_TC-to-TB_10pct,resnet50,/users/7/yu001011/csci5527/.venv/bin/python tr...
4,Shift-TA_TB-to-TC_10pct,efficientnet-b0,/users/7/yu001011/csci5527/.venv/bin/python tr...
5,Shift-TA_TB-to-TC_10pct,resnet50,/users/7/yu001011/csci5527/.venv/bin/python tr...

## 5. Run a Single Experiment

Start here if you want to test one configuration first.

In [5]:
TEST_SETTING = 'Single-TB'
TEST_BACKBONE = 'resnet34'

# Uncomment to run:
# run_one(TEST_SETTING, TEST_BACKBONE)

In [6]:
! /users/7/yu001011/csci5527/.venv/bin/python -m pip install pandas

Requirement already satisfied: pandas in /users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## 6. Run the Full Layer 2 Grid

This runs all 9 experiments.

Warning: this may take a long time depending on GPU availability.

In [7]:
# Uncomment to run all experiments:
run_all(SETTINGS, BACKBONES)

Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Single-TB --arch Unet --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Single-TB | arch=Unet | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 424/424 [00:00<00:00, 1565.91it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 4479.70it/s]

Sanitizing test masks...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 20
 - Validation batches: 6
 - Testing batches: 3
  → Unet-efficientnet-b0-imagenet_Single-TB:   0%|          | 0/100 [00:06<?, ?it/s, IoU=0.0028, F1=0.0055]Epoch 0: T-Loss: 9.4832 | V-Loss: 9.3122 | IoU: 0.0028 | F1: 0.0055 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:   1%|          | 1/100 [00:12<11:05,  6.73s/it, IoU=0.0011, F1=0.0021]Epoch 1: T-Loss: 9.0274 | V-Loss: 8.6199 | IoU: 0.0011 | F1: 0.0021
  → Unet-efficientnet-b0-imagenet_Single-TB:   2%|▏         | 2/100 [00:19<10:06,  6.19s/it, IoU=0.0006, F1=0.0011]Epoch 2: T-Loss: 8.7489 | V-Loss: 8.4431 | IoU: 0.0006 | F1: 0.0011
  → Unet-efficientnet-b0-imagenet_Single-TB:   3%|▎         | 3/100 [00:25<10:32,  6.52s/it, IoU=0.0113, F1=0.0222]Epoch 3: T-Loss: 8.5593 | V-Loss: 8.3379 | IoU: 0.0113 | F1: 0.0222 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:   4%|▍         | 4/100 [00:32<10:23,  6.49s/it, IoU=0.1107, F1=0.1908]Epoch 4: T-Loss: 8.4039 | V-Loss: 8.1813 | IoU: 0.1107 | F1: 0.1908 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:   5%|▌         | 5/100 [00:38<10:12,  6.44s/it, IoU=0.1767, F1=0.2889]Epoch 5: T-Loss: 8.2413 | V-Loss: 7.9984 | IoU: 0.1767 | F1: 0.2889 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:   6%|▌         | 6/100 [00:44<09:59,  6.38s/it, IoU=0.1614, F1=0.2667]Epoch 6: T-Loss: 8.1374 | V-Loss: 7.8958 | IoU: 0.1614 | F1: 0.2667
  → Unet-efficientnet-b0-imagenet_Single-TB:   7%|▋         | 7/100 [00:50<09:34,  6.18s/it, IoU=0.0995, F1=0.1762]Epoch 7: T-Loss: 8.0152 | V-Loss: 7.9217 | IoU: 0.0995 | F1: 0.1762
  → Unet-efficientnet-b0-imagenet_Single-TB:   8%|▊         | 8/100 [00:55<09:19,  6.08s/it, IoU=0.1420, F1=0.2396]Epoch 8: T-Loss: 7.9377 | V-Loss: 7.7630 | IoU: 0.1420 | F1: 0.2396
  → Unet-efficientnet-b0-imagenet_Single-TB:   9%|▉         | 9/100 [01:01<09:03,  5.98s/it, IoU=0.1946, F1=0.3119]Epoch 9: T-Loss: 7.8609 | V-Loss: 7.6738 | IoU: 0.1946 | F1: 0.3119 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  10%|█         | 10/100 [01:07<08:54,  5.94s/it, IoU=0.1758, F1=0.2898]Epoch 10: T-Loss: 7.7503 | V-Loss: 7.6212 | IoU: 0.1758 | F1: 0.2898
  → Unet-efficientnet-b0-imagenet_Single-TB:  11%|█         | 11/100 [01:13<08:48,  5.93s/it, IoU=0.1917, F1=0.3107]Epoch 11: T-Loss: 7.6517 | V-Loss: 7.5498 | IoU: 0.1917 | F1: 0.3107
  → Unet-efficientnet-b0-imagenet_Single-TB:  12%|█▏        | 12/100 [01:19<08:41,  5.92s/it, IoU=0.2511, F1=0.3864]Epoch 12: T-Loss: 7.5472 | V-Loss: 7.4357 | IoU: 0.2511 | F1: 0.3864 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  13%|█▎        | 13/100 [01:25<08:32,  5.89s/it, IoU=0.2441, F1=0.3807]Epoch 13: T-Loss: 7.4891 | V-Loss: 7.3358 | IoU: 0.2441 | F1: 0.3807
  → Unet-efficientnet-b0-imagenet_Single-TB:  14%|█▍        | 14/100 [01:31<08:41,  6.07s/it, IoU=0.2367, F1=0.3682]Epoch 14: T-Loss: 7.3511 | V-Loss: 7.2264 | IoU: 0.2367 | F1: 0.3682
  → Unet-efficientnet-b0-imagenet_Single-TB:  15%|█▌        | 15/100 [01:37<08:30,  6.00s/it, IoU=0.2515, F1=0.3927]Epoch 15: T-Loss: 7.2906 | V-Loss: 7.1363 | IoU: 0.2515 | F1: 0.3927 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  16%|█▌        | 16/100 [01:44<08:29,  6.07s/it, IoU=0.2857, F1=0.4373]Epoch 16: T-Loss: 7.2257 | V-Loss: 7.0861 | IoU: 0.2857 | F1: 0.4373 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  17%|█▋        | 17/100 [01:51<08:29,  6.14s/it, IoU=0.2578, F1=0.3964]Epoch 17: T-Loss: 7.1130 | V-Loss: 6.9131 | IoU: 0.2578 | F1: 0.3964
  → Unet-efficientnet-b0-imagenet_Single-TB:  18%|█▊        | 18/100 [01:57<08:46,  6.42s/it, IoU=0.3213, F1=0.4808]Epoch 18: T-Loss: 7.0034 | V-Loss: 6.8569 | IoU: 0.3213 | F1: 0.4808 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  19%|█▉        | 19/100 [02:03<08:44,  6.47s/it, IoU=0.3317, F1=0.4930]Epoch 19: T-Loss: 6.9306 | V-Loss: 6.7422 | IoU: 0.3317 | F1: 0.4930 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  20%|██        | 20/100 [02:10<08:25,  6.32s/it, IoU=0.3203, F1=0.4762]Epoch 20: T-Loss: 6.8961 | V-Loss: 6.5502 | IoU: 0.3203 | F1: 0.4762
  → Unet-efficientnet-b0-imagenet_Single-TB:  21%|██        | 21/100 [02:15<08:17,  6.30s/it, IoU=0.3246, F1=0.4868]Epoch 21: T-Loss: 6.6879 | V-Loss: 6.6202 | IoU: 0.3246 | F1: 0.4868
  → Unet-efficientnet-b0-imagenet_Single-TB:  22%|██▏       | 22/100 [02:21<07:57,  6.12s/it, IoU=0.2993, F1=0.4558]Epoch 22: T-Loss: 6.7082 | V-Loss: 6.4401 | IoU: 0.2993 | F1: 0.4558
  → Unet-efficientnet-b0-imagenet_Single-TB:  23%|██▎       | 23/100 [02:27<07:49,  6.10s/it, IoU=0.2765, F1=0.4275]Epoch 23: T-Loss: 6.6374 | V-Loss: 6.4489 | IoU: 0.2765 | F1: 0.4275
  → Unet-efficientnet-b0-imagenet_Single-TB:  24%|██▍       | 24/100 [02:33<07:42,  6.09s/it, IoU=0.3107, F1=0.4693]Epoch 24: T-Loss: 6.5359 | V-Loss: 6.3335 | IoU: 0.3107 | F1: 0.4693
  → Unet-efficientnet-b0-imagenet_Single-TB:  25%|██▌       | 25/100 [02:39<07:28,  5.97s/it, IoU=0.3100, F1=0.4623]Epoch 25: T-Loss: 6.4609 | V-Loss: 6.2101 | IoU: 0.3100 | F1: 0.4623
  → Unet-efficientnet-b0-imagenet_Single-TB:  26%|██▌       | 26/100 [02:45<07:22,  5.99s/it, IoU=0.3301, F1=0.4888]Epoch 26: T-Loss: 6.3672 | V-Loss: 6.1892 | IoU: 0.3301 | F1: 0.4888
  → Unet-efficientnet-b0-imagenet_Single-TB:  27%|██▋       | 27/100 [02:51<07:13,  5.94s/it, IoU=0.3371, F1=0.4927]Epoch 27: T-Loss: 6.3983 | V-Loss: 6.1679 | IoU: 0.3371 | F1: 0.4927 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  28%|██▊       | 28/100 [02:57<07:09,  5.96s/it, IoU=0.3296, F1=0.4875]Epoch 28: T-Loss: 6.3252 | V-Loss: 6.1342 | IoU: 0.3296 | F1: 0.4875
  → Unet-efficientnet-b0-imagenet_Single-TB:  29%|██▉       | 29/100 [03:03<06:58,  5.89s/it, IoU=0.2616, F1=0.4029]Epoch 29: T-Loss: 6.3684 | V-Loss: 6.2149 | IoU: 0.2616 | F1: 0.4029
  → Unet-efficientnet-b0-imagenet_Single-TB:  30%|███       | 30/100 [03:09<07:00,  6.01s/it, IoU=0.3309, F1=0.4920]Epoch 30: T-Loss: 6.2535 | V-Loss: 6.1236 | IoU: 0.3309 | F1: 0.4920
  → Unet-efficientnet-b0-imagenet_Single-TB:  31%|███       | 31/100 [03:17<06:58,  6.07s/it, IoU=0.3333, F1=0.4925]Epoch 31: T-Loss: 6.2584 | V-Loss: 6.1007 | IoU: 0.3333 | F1: 0.4925
  → Unet-efficientnet-b0-imagenet_Single-TB:  32%|███▏      | 32/100 [03:24<07:17,  6.44s/it, IoU=0.3547, F1=0.5157]Epoch 32: T-Loss: 6.1879 | V-Loss: 6.0328 | IoU: 0.3547 | F1: 0.5157 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  33%|███▎      | 33/100 [03:30<07:38,  6.84s/it, IoU=0.3516, F1=0.5142]Epoch 33: T-Loss: 6.1443 | V-Loss: 6.1081 | IoU: 0.3516 | F1: 0.5142
  → Unet-efficientnet-b0-imagenet_Single-TB:  34%|███▍      | 34/100 [03:36<07:14,  6.59s/it, IoU=0.3624, F1=0.5231]Epoch 34: T-Loss: 6.1902 | V-Loss: 6.0133 | IoU: 0.3624 | F1: 0.5231 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  35%|███▌      | 35/100 [03:42<06:57,  6.42s/it, IoU=0.3556, F1=0.5169]Epoch 35: T-Loss: 6.1159 | V-Loss: 6.0121 | IoU: 0.3556 | F1: 0.5169
  → Unet-efficientnet-b0-imagenet_Single-TB:  36%|███▌      | 36/100 [03:48<06:37,  6.21s/it, IoU=0.3509, F1=0.5088]Epoch 36: T-Loss: 6.2282 | V-Loss: 5.9738 | IoU: 0.3509 | F1: 0.5088
  → Unet-efficientnet-b0-imagenet_Single-TB:  37%|███▋      | 37/100 [03:55<06:32,  6.23s/it, IoU=0.3652, F1=0.5272]Epoch 37: T-Loss: 6.0882 | V-Loss: 6.0650 | IoU: 0.3652 | F1: 0.5272 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  38%|███▊      | 38/100 [04:01<06:37,  6.41s/it, IoU=0.3664, F1=0.5304]Epoch 38: T-Loss: 6.1184 | V-Loss: 6.0119 | IoU: 0.3664 | F1: 0.5304 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  39%|███▉      | 39/100 [04:08<06:19,  6.22s/it, IoU=0.3412, F1=0.5029]Epoch 39: T-Loss: 6.0737 | V-Loss: 6.0101 | IoU: 0.3412 | F1: 0.5029
  → Unet-efficientnet-b0-imagenet_Single-TB:  40%|████      | 40/100 [04:14<06:31,  6.52s/it, IoU=0.3484, F1=0.5104]Epoch 40: T-Loss: 6.0904 | V-Loss: 5.9944 | IoU: 0.3484 | F1: 0.5104
  → Unet-efficientnet-b0-imagenet_Single-TB:  41%|████      | 41/100 [04:20<06:19,  6.43s/it, IoU=0.3750, F1=0.5386]Epoch 41: T-Loss: 6.1325 | V-Loss: 5.8989 | IoU: 0.3750 | F1: 0.5386 [Saved Best Model]

  → Unet-efficientnet-b0-imagenet_Single-TB:  42%|████▏     | 42/100 [04:27<06:08,  6.35s/it, IoU=0.3758, F1=0.5409]Epoch 42: T-Loss: 6.0580 | V-Loss: 5.9093 | IoU: 0.3758 | F1: 0.5409 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  43%|████▎     | 43/100 [04:34<06:03,  6.37s/it, IoU=0.3872, F1=0.5524]Epoch 43: T-Loss: 6.1475 | V-Loss: 5.9016 | IoU: 0.3872 | F1: 0.5524 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  44%|████▍     | 44/100 [04:40<06:08,  6.58s/it, IoU=0.3684, F1=0.5347]Epoch 44: T-Loss: 6.0286 | V-Loss: 5.9928 | IoU: 0.3684 | F1: 0.5347
  → Unet-efficientnet-b0-imagenet_Single-TB:  45%|████▌     | 45/100 [04:46<05:53,  6.42s/it, IoU=0.3796, F1=0.5443]Epoch 45: T-Loss: 6.0243 | V-Loss: 5.9483 | IoU: 0.3796 | F1: 0.5443
  → Unet-efficientnet-b0-imagenet_Single-TB:  46%|████▌     | 46/100 [04:52<05:37,  6.24s/it, IoU=0.3578, F1=0.5182]Epoch 46: T-Loss: 6.0078 | V-Loss: 5.8946 | IoU: 0.3578 | F1: 0.5182
  → Unet-efficientnet-b0-imagenet_Single-TB:  47%|████▋     | 47/100 [04:58<05:25,  6.13s/it, IoU=0.3893, F1=0.5500]Epoch 47: T-Loss: 5.9742 | V-Loss: 5.8632 | IoU: 0.3893 | F1: 0.5500 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  48%|████▊     | 48/100 [05:05<05:21,  6.18s/it, IoU=0.3756, F1=0.5355]Epoch 48: T-Loss: 5.9331 | V-Loss: 5.9429 | IoU: 0.3756 | F1: 0.5355
  → Unet-efficientnet-b0-imagenet_Single-TB:  49%|████▉     | 49/100 [05:11<05:20,  6.28s/it, IoU=0.4003, F1=0.5628]Epoch 49: T-Loss: 5.9782 | V-Loss: 5.8924 | IoU: 0.4003 | F1: 0.5628 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  50%|█████     | 50/100 [05:16<05:10,  6.21s/it, IoU=0.3837, F1=0.5474]Epoch 50: T-Loss: 5.9093 | V-Loss: 5.9352 | IoU: 0.3837 | F1: 0.5474
  → Unet-efficientnet-b0-imagenet_Single-TB:  51%|█████     | 51/100 [05:22<04:58,  6.08s/it, IoU=0.3961, F1=0.5568]Epoch 51: T-Loss: 6.0022 | V-Loss: 5.8647 | IoU: 0.3961 | F1: 0.5568
  → Unet-efficientnet-b0-imagenet_Single-TB:  52%|█████▏    | 52/100 [05:28<04:48,  6.02s/it, IoU=0.3976, F1=0.5639]Epoch 52: T-Loss: 5.9303 | V-Loss: 5.8767 | IoU: 0.3976 | F1: 0.5639
  → Unet-efficientnet-b0-imagenet_Single-TB:  53%|█████▎    | 53/100 [05:35<04:44,  6.05s/it, IoU=0.4087, F1=0.5738]Epoch 53: T-Loss: 5.9945 | V-Loss: 5.8430 | IoU: 0.4087 | F1: 0.5738 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Single-TB:  54%|█████▍    | 54/100 [05:42<04:42,  6.14s/it, IoU=0.4040, F1=0.5696]Epoch 54: T-Loss: 5.8894 | V-Loss: 5.8698 | IoU: 0.4040 | F1: 0.5696
  → Unet-efficientnet-b0-imagenet_Single-TB:  55%|█████▌    | 55/100 [05:48<04:47,  6.38s/it, IoU=0.3994, F1=0.5644]Epoch 55: T-Loss: 5.8529 | V-Loss: 5.8391 | IoU: 0.3994 | F1: 0.5644
  → Unet-efficientnet-b0-imagenet_Single-TB:  56%|█████▌    | 56/100 [05:54<04:34,  6.24s/it, IoU=0.4018, F1=0.5655]Epoch 56: T-Loss: 5.8940 | V-Loss: 5.8157 | IoU: 0.4018 | F1: 0.5655
  → Unet-efficientnet-b0-imagenet_Single-TB:  57%|█████▋    | 57/100 [06:00<04:27,  6.22s/it, IoU=0.4017, F1=0.5659]Epoch 57: T-Loss: 5.8435 | V-Loss: 5.8352 | IoU: 0.4017 | F1: 0.5659
  → Unet-efficientnet-b0-imagenet_Single-TB:  58%|█████▊    | 58/100 [06:05<04:14,  6.07s/it, IoU=0.3958, F1=0.5594]Epoch 58: T-Loss: 5.9840 | V-Loss: 5.8439 | IoU: 0.3958 | F1: 0.5594
  → Unet-efficientnet-b0-imagenet_Single-TB:  59%|█████▉    | 59/100 [06:12<04:05,  5.99s/it, IoU=0.3944, F1=0.5582]Epoch 59: T-Loss: 5.9236 | V-Loss: 5.8294 | IoU: 0.3944 | F1: 0.5582
  → Unet-efficientnet-b0-imagenet_Single-TB:  60%|██████    | 60/100 [06:18<04:06,  6.15s/it, IoU=0.3898, F1=0.5547]Epoch 60: T-Loss: 5.8163 | V-Loss: 5.8452 | IoU: 0.3898 | F1: 0.5547
  → Unet-efficientnet-b0-imagenet_Single-TB:  61%|██████    | 61/100 [06:24<03:54,  6.02s/it, IoU=0.3845, F1=0.5503]Epoch 61: T-Loss: 5.9246 | V-Loss: 5.9090 | IoU: 0.3845 | F1: 0.5503
  → Unet-efficientnet-b0-imagenet_Single-TB:  62%|██████▏   | 62/100 [06:30<03:54,  6.18s/it, IoU=0.3998, F1=0.5640]Epoch 62: T-Loss: 5.8005 | V-Loss: 5.8934 | IoU: 0.3998 | F1: 0.5640
  → Unet-efficientnet-b0-imagenet_Single-TB:  63%|██████▎   | 63/100 [06:38<03:45,  6.08s/it, IoU=0.4064, F1=0.5716]Epoch 63: T-Loss: 5.9348 | V-Loss: 5.8411 | IoU: 0.4064 | F1: 0.5716
  → Unet-efficientnet-b0-imagenet_Single-TB:  64%|██████▍   | 64/100 [06:45<03:55,  6.55s/it, IoU=0.4022, F1=0.5636]Epoch 64: T-Loss: 5.8399 | V-Loss: 5.8171 | IoU: 0.4022 | F1: 0.5636
  → Unet-efficientnet-b0-imagenet_Single-TB:  65%|██████▌   | 65/100 [06:51<03:55,  6.73s/it, IoU=0.4027, F1=0.5657]Epoch 65: T-Loss: 5.8253 | V-Loss: 5.8572 | IoU: 0.4027 | F1: 0.5657
  → Unet-efficientnet-b0-imagenet_Single-TB:  66%|██████▌   | 66/100 [06:58<03:40,  6.49s/it, IoU=0.3894, F1=0.5543]Epoch 66: T-Loss: 5.8653 | V-Loss: 5.8628 | IoU: 0.3894 | F1: 0.5543

============================================================
Early Stopping Triggered at Epoch 66
  - Best Validation Loss: 5.8157
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-efficientnet-b0-imagenet_Single-TB_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_efficientnet-b0.csv

Final results:
                                Experiment  Val_Loss  ...  Test_Recall  Test_Prec
0  Unet-efficientnet-b0-imagenet_Single-TB  5.843002  ...     0.390885   0.486734

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TC-to-TB_10pct --arch Unet --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Shift-TA_TC-to-TB_10pct | arch=Unet | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 936/936 [00:00<00:00, 1427.06it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 36981.37it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 45
 - Validation batches: 13
 - Testing batches: 3
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   0%|          | 0/100 [00:12<?, ?it/s, IoU=0.0668, F1=0.1198]Epoch 0: T-Loss: 8.9600 | V-Loss: 8.6262 | IoU: 0.0668 | F1: 0.1198 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   1%|          | 1/100 [00:26<21:36, 13.10s/it, IoU=0.2935, F1=0.4374]Epoch 1: T-Loss: 8.3231 | V-Loss: 8.2047 | IoU: 0.2935 | F1: 0.4374 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   2%|▏         | 2/100 [00:40<21:17, 13.03s/it, IoU=0.3087, F1=0.4542]Epoch 2: T-Loss: 7.7810 | V-Loss: 7.9229 | IoU: 0.3087 | F1: 0.4542 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   3%|▎         | 3/100 [00:53<22:09, 13.70s/it, IoU=0.3252, F1=0.4712]Epoch 3: T-Loss: 7.3311 | V-Loss: 7.5433 | IoU: 0.3252 | F1: 0.4712 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   4%|▍         | 4/100 [01:05<21:17, 13.30s/it, IoU=0.3432, F1=0.4864]Epoch 4: T-Loss: 6.9341 | V-Loss: 7.1562 | IoU: 0.3432 | F1: 0.4864 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   5%|▌         | 5/100 [01:18<20:37, 13.03s/it, IoU=0.3713, F1=0.5159]Epoch 5: T-Loss: 6.5804 | V-Loss: 6.8267 | IoU: 0.3713 | F1: 0.5159 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   6%|▌         | 6/100 [01:33<20:27, 13.05s/it, IoU=0.3259, F1=0.4703]Epoch 6: T-Loss: 6.3444 | V-Loss: 6.4918 | IoU: 0.3259 | F1: 0.4703
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   7%|▋         | 7/100 [01:47<20:45, 13.39s/it, IoU=0.4147, F1=0.5630]Epoch 7: T-Loss: 6.1940 | V-Loss: 6.3140 | IoU: 0.4147 | F1: 0.5630 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   8%|▊         | 8/100 [02:00<21:08, 13.79s/it, IoU=0.3981, F1=0.5482]Epoch 8: T-Loss: 6.0301 | V-Loss: 6.3578 | IoU: 0.3981 | F1: 0.5482
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   9%|▉         | 9/100 [02:14<20:34, 13.57s/it, IoU=0.4315, F1=0.5796]Epoch 9: T-Loss: 5.9645 | V-Loss: 6.0762 | IoU: 0.4315 | F1: 0.5796 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  10%|█         | 10/100 [02:26<20:19, 13.55s/it, IoU=0.3980, F1=0.5427]Epoch 10: T-Loss: 5.8831 | V-Loss: 6.0347 | IoU: 0.3980 | F1: 0.5427
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  11%|█         | 11/100 [02:40<19:39, 13.26s/it, IoU=0.4111, F1=0.5588]Epoch 11: T-Loss: 5.7966 | V-Loss: 5.9868 | IoU: 0.4111 | F1: 0.5588
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  12%|█▏        | 12/100 [02:53<19:31, 13.31s/it, IoU=0.4485, F1=0.5936]Epoch 12: T-Loss: 5.8030 | V-Loss: 5.8953 | IoU: 0.4485 | F1: 0.5936 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  13%|█▎        | 13/100 [03:07<19:09, 13.21s/it, IoU=0.4324, F1=0.5773]Epoch 13: T-Loss: 5.7536 | V-Loss: 5.8711 | IoU: 0.4324 | F1: 0.5773
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  14%|█▍        | 14/100 [03:19<19:17, 13.46s/it, IoU=0.4334, F1=0.5804]Epoch 14: T-Loss: 5.7066 | V-Loss: 5.8378 | IoU: 0.4334 | F1: 0.5804
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  15%|█▌        | 15/100 [03:32<18:40, 13.18s/it, IoU=0.4215, F1=0.5707]Epoch 15: T-Loss: 5.6881 | V-Loss: 5.8878 | IoU: 0.4215 | F1: 0.5707
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  16%|█▌        | 16/100 [03:47<18:15, 13.04s/it, IoU=0.4616, F1=0.6054]Epoch 16: T-Loss: 5.6505 | V-Loss: 5.8028 | IoU: 0.4616 | F1: 0.6054 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  17%|█▋        | 17/100 [04:01<19:00, 13.74s/it, IoU=0.4428, F1=0.5903]Epoch 17: T-Loss: 5.6190 | V-Loss: 5.8603 | IoU: 0.4428 | F1: 0.5903
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  18%|█▊        | 18/100 [04:14<18:33, 13.58s/it, IoU=0.4597, F1=0.6064]Epoch 18: T-Loss: 5.6095 | V-Loss: 5.7727 | IoU: 0.4597 | F1: 0.6064
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  19%|█▉        | 19/100 [04:26<18:04, 13.38s/it, IoU=0.4651, F1=0.6096]Epoch 19: T-Loss: 5.6086 | V-Loss: 5.7883 | IoU: 0.4651 | F1: 0.6096 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  20%|██        | 20/100 [04:39<17:37, 13.21s/it, IoU=0.4571, F1=0.6043]Epoch 20: T-Loss: 5.5659 | V-Loss: 5.7377 | IoU: 0.4571 | F1: 0.6043
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  21%|██        | 21/100 [04:51<17:10, 13.04s/it, IoU=0.4345, F1=0.5831]Epoch 21: T-Loss: 5.5707 | V-Loss: 5.7393 | IoU: 0.4345 | F1: 0.5831
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  22%|██▏       | 22/100 [05:03<16:36, 12.77s/it, IoU=0.4456, F1=0.5946]Epoch 22: T-Loss: 5.5081 | V-Loss: 5.7274 | IoU: 0.4456 | F1: 0.5946
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  23%|██▎       | 23/100 [05:16<16:09, 12.59s/it, IoU=0.4866, F1=0.6309]Epoch 23: T-Loss: 5.5409 | V-Loss: 5.7034 | IoU: 0.4866 | F1: 0.6309 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  24%|██▍       | 24/100 [05:28<15:59, 12.62s/it, IoU=0.4690, F1=0.6150]Epoch 24: T-Loss: 5.5222 | V-Loss: 5.6595 | IoU: 0.4690 | F1: 0.6150
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  25%|██▌       | 25/100 [05:41<15:42, 12.56s/it, IoU=0.4734, F1=0.6180]Epoch 25: T-Loss: 5.5277 | V-Loss: 5.6996 | IoU: 0.4734 | F1: 0.6180
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  26%|██▌       | 26/100 [05:54<15:23, 12.48s/it, IoU=0.4798, F1=0.6254]Epoch 26: T-Loss: 5.4785 | V-Loss: 5.6664 | IoU: 0.4798 | F1: 0.6254
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  27%|██▋       | 27/100 [06:06<15:20, 12.60s/it, IoU=0.4798, F1=0.6249]Epoch 27: T-Loss: 5.4961 | V-Loss: 5.6599 | IoU: 0.4798 | F1: 0.6249
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  28%|██▊       | 28/100 [06:19<15:04, 12.56s/it, IoU=0.4446, F1=0.5906]Epoch 28: T-Loss: 5.4534 | V-Loss: 5.6468 | IoU: 0.4446 | F1: 0.5906
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  29%|██▉       | 29/100 [06:31<14:57, 12.64s/it, IoU=0.4703, F1=0.6144]Epoch 29: T-Loss: 5.4758 | V-Loss: 5.6599 | IoU: 0.4703 | F1: 0.6144
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  30%|███       | 30/100 [06:43<14:36, 12.53s/it, IoU=0.4782, F1=0.6225]Epoch 30: T-Loss: 5.5002 | V-Loss: 5.6777 | IoU: 0.4782 | F1: 0.6225
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  31%|███       | 31/100 [06:56<14:18, 12.44s/it, IoU=0.4799, F1=0.6235]Epoch 31: T-Loss: 5.4709 | V-Loss: 5.6992 | IoU: 0.4799 | F1: 0.6235
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  32%|███▏      | 32/100 [07:10<14:15, 12.59s/it, IoU=0.4980, F1=0.6403]Epoch 32: T-Loss: 5.4293 | V-Loss: 5.6728 | IoU: 0.4980 | F1: 0.6403 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  33%|███▎      | 33/100 [07:25<14:25, 12.92s/it, IoU=0.4751, F1=0.6197]Epoch 33: T-Loss: 5.4559 | V-Loss: 5.6639 | IoU: 0.4751 | F1: 0.6197
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  34%|███▍      | 34/100 [07:39<15:03, 13.69s/it, IoU=0.4592, F1=0.6048]Epoch 34: T-Loss: 5.4099 | V-Loss: 5.6489 | IoU: 0.4592 | F1: 0.6048
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  35%|███▌      | 35/100 [07:54<14:49, 13.69s/it, IoU=0.4867, F1=0.6319]Epoch 35: T-Loss: 5.4185 | V-Loss: 5.6291 | IoU: 0.4867 | F1: 0.6319
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  36%|███▌      | 36/100 [08:07<14:51, 13.94s/it, IoU=0.4569, F1=0.6037]Epoch 36: T-Loss: 5.4466 | V-Loss: 5.6384 | IoU: 0.4569 | F1: 0.6037
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  37%|███▋      | 37/100 [08:20<14:29, 13.80s/it, IoU=0.4996, F1=0.6429]Epoch 37: T-Loss: 5.4192 | V-Loss: 5.6760 | IoU: 0.4996 | F1: 0.6429 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  38%|███▊      | 38/100 [08:33<14:06, 13.65s/it, IoU=0.4642, F1=0.6073]Epoch 38: T-Loss: 5.4319 | V-Loss: 5.6506 | IoU: 0.4642 | F1: 0.6073

  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  39%|███▉      | 39/100 [08:46<13:39, 13.43s/it, IoU=0.4732, F1=0.6163]Epoch 39: T-Loss: 5.3935 | V-Loss: 5.6381 | IoU: 0.4732 | F1: 0.6163
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  40%|████      | 40/100 [09:00<13:09, 13.16s/it, IoU=0.4527, F1=0.5993]Epoch 40: T-Loss: 5.4273 | V-Loss: 5.6309 | IoU: 0.4527 | F1: 0.5993
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  41%|████      | 41/100 [09:13<13:04, 13.30s/it, IoU=0.4442, F1=0.5924]Epoch 41: T-Loss: 5.4251 | V-Loss: 5.6541 | IoU: 0.4442 | F1: 0.5924
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  42%|████▏     | 42/100 [09:26<13:01, 13.47s/it, IoU=0.4961, F1=0.6399]Epoch 42: T-Loss: 5.3945 | V-Loss: 5.6408 | IoU: 0.4961 | F1: 0.6399
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  43%|████▎     | 43/100 [09:41<12:39, 13.32s/it, IoU=0.5027, F1=0.6455]Epoch 43: T-Loss: 5.3787 | V-Loss: 5.6149 | IoU: 0.5027 | F1: 0.6455 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  44%|████▍     | 44/100 [09:55<12:52, 13.80s/it, IoU=0.4978, F1=0.6425]Epoch 44: T-Loss: 5.4072 | V-Loss: 5.6353 | IoU: 0.4978 | F1: 0.6425
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  45%|████▌     | 45/100 [10:09<12:30, 13.65s/it, IoU=0.4969, F1=0.6411]Epoch 45: T-Loss: 5.3724 | V-Loss: 5.6410 | IoU: 0.4969 | F1: 0.6411
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  46%|████▌     | 46/100 [10:23<12:31, 13.91s/it, IoU=0.4683, F1=0.6124]Epoch 46: T-Loss: 5.3328 | V-Loss: 5.6661 | IoU: 0.4683 | F1: 0.6124
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  47%|████▋     | 47/100 [10:40<12:24, 14.04s/it, IoU=0.4768, F1=0.6200]Epoch 47: T-Loss: 5.3409 | V-Loss: 5.6665 | IoU: 0.4768 | F1: 0.6200
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  48%|████▊     | 48/100 [10:54<12:50, 14.81s/it, IoU=0.4827, F1=0.6277]Epoch 48: T-Loss: 5.4112 | V-Loss: 5.6422 | IoU: 0.4827 | F1: 0.6277
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  49%|████▉     | 49/100 [11:07<12:25, 14.62s/it, IoU=0.4887, F1=0.6338]Epoch 49: T-Loss: 5.3173 | V-Loss: 5.6262 | IoU: 0.4887 | F1: 0.6338
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  50%|█████     | 50/100 [11:21<11:43, 14.06s/it, IoU=0.4910, F1=0.6355]Epoch 50: T-Loss: 5.3354 | V-Loss: 5.6119 | IoU: 0.4910 | F1: 0.6355
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  51%|█████     | 51/100 [11:38<11:35, 14.18s/it, IoU=0.4758, F1=0.6195]Epoch 51: T-Loss: 5.3507 | V-Loss: 5.6507 | IoU: 0.4758 | F1: 0.6195
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  52%|█████▏    | 52/100 [11:51<11:59, 14.99s/it, IoU=0.4837, F1=0.6283]Epoch 52: T-Loss: 5.3752 | V-Loss: 5.6189 | IoU: 0.4837 | F1: 0.6283
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  53%|█████▎    | 53/100 [12:06<11:18, 14.44s/it, IoU=0.4860, F1=0.6312]Epoch 53: T-Loss: 5.3785 | V-Loss: 5.6225 | IoU: 0.4860 | F1: 0.6312
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  54%|█████▍    | 54/100 [12:21<11:10, 14.57s/it, IoU=0.4728, F1=0.6193]Epoch 54: T-Loss: 5.3611 | V-Loss: 5.6216 | IoU: 0.4728 | F1: 0.6193
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  55%|█████▌    | 55/100 [12:38<10:59, 14.66s/it, IoU=0.4748, F1=0.6190]Epoch 55: T-Loss: 5.3727 | V-Loss: 5.6195 | IoU: 0.4748 | F1: 0.6190
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  56%|█████▌    | 56/100 [12:52<11:13, 15.32s/it, IoU=0.4849, F1=0.6283]Epoch 56: T-Loss: 5.3568 | V-Loss: 5.6172 | IoU: 0.4849 | F1: 0.6283
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  57%|█████▋    | 57/100 [13:06<10:43, 14.97s/it, IoU=0.4940, F1=0.6364]Epoch 57: T-Loss: 5.3277 | V-Loss: 5.6305 | IoU: 0.4940 | F1: 0.6364
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  58%|█████▊    | 58/100 [13:19<10:09, 14.51s/it, IoU=0.4845, F1=0.6273]Epoch 58: T-Loss: 5.3047 | V-Loss: 5.5978 | IoU: 0.4845 | F1: 0.6273
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  59%|█████▉    | 59/100 [13:33<09:37, 14.10s/it, IoU=0.4894, F1=0.6322]Epoch 59: T-Loss: 5.3358 | V-Loss: 5.6086 | IoU: 0.4894 | F1: 0.6322
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  60%|██████    | 60/100 [13:46<09:20, 14.01s/it, IoU=0.4978, F1=0.6403]Epoch 60: T-Loss: 5.2864 | V-Loss: 5.6038 | IoU: 0.4978 | F1: 0.6403
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  61%|██████    | 61/100 [13:58<08:59, 13.83s/it, IoU=0.4883, F1=0.6312]Epoch 61: T-Loss: 5.3259 | V-Loss: 5.6138 | IoU: 0.4883 | F1: 0.6312
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  62%|██████▏   | 62/100 [14:11<08:28, 13.38s/it, IoU=0.5028, F1=0.6447]Epoch 62: T-Loss: 5.3129 | V-Loss: 5.6202 | IoU: 0.5028 | F1: 0.6447 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  63%|██████▎   | 63/100 [14:24<08:08, 13.19s/it, IoU=0.4849, F1=0.6291]Epoch 63: T-Loss: 5.3097 | V-Loss: 5.6125 | IoU: 0.4849 | F1: 0.6291
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  64%|██████▍   | 64/100 [14:39<07:53, 13.15s/it, IoU=0.4859, F1=0.6298]Epoch 64: T-Loss: 5.3439 | V-Loss: 5.6116 | IoU: 0.4859 | F1: 0.6298
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  65%|██████▌   | 65/100 [14:54<07:54, 13.56s/it, IoU=0.4820, F1=0.6265]Epoch 65: T-Loss: 5.3711 | V-Loss: 5.6069 | IoU: 0.4820 | F1: 0.6265
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  66%|██████▌   | 66/100 [15:07<07:55, 13.97s/it, IoU=0.4829, F1=0.6256]Epoch 66: T-Loss: 5.3668 | V-Loss: 5.6220 | IoU: 0.4829 | F1: 0.6256
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  67%|██████▋   | 67/100 [15:22<07:35, 13.81s/it, IoU=0.4880, F1=0.6318]Epoch 67: T-Loss: 5.2855 | V-Loss: 5.6042 | IoU: 0.4880 | F1: 0.6318
  → Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  68%|██████▊   | 68/100 [15:38<07:36, 14.25s/it, IoU=0.4953, F1=0.6372]Epoch 68: T-Loss: 5.2875 | V-Loss: 5.6128 | IoU: 0.4953 | F1: 0.6372

============================================================
Early Stopping Triggered at Epoch 68
  - Best Validation Loss: 5.5978
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_efficientnet-b0.csv

Final results:
                                              Experiment  ...  Test_Prec
0  Unet-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct  ...   0.449778

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TB-to-TC_10pct --arch Unet --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Shift-TA_TB-to-TC_10pct | arch=Unet | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 1028/1028 [00:00<00:00, 1203.63it/s]
Sanitizing Masks: 100%|██████████| 38/38 [00:00<00:00, 641.73it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 50
 - Validation batches: 15
 - Testing batches: 3
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   0%|          | 0/100 [00:15<?, ?it/s, IoU=0.0938, F1=0.1679]Epoch 0: T-Loss: 9.7263 | V-Loss: 9.1233 | IoU: 0.0938 | F1: 0.1679 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   1%|          | 1/100 [00:34<26:08, 15.84s/it, IoU=0.2613, F1=0.3992]Epoch 1: T-Loss: 8.7255 | V-Loss: 8.3814 | IoU: 0.2613 | F1: 0.3992 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   2%|▏         | 2/100 [00:51<28:26, 17.41s/it, IoU=0.3095, F1=0.4577]Epoch 2: T-Loss: 8.2056 | V-Loss: 7.9097 | IoU: 0.3095 | F1: 0.4577 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   3%|▎         | 3/100 [01:06<27:42, 17.14s/it, IoU=0.3842, F1=0.5394]Epoch 3: T-Loss: 7.7993 | V-Loss: 7.3893 | IoU: 0.3842 | F1: 0.5394 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   4%|▍         | 4/100 [01:24<26:37, 16.64s/it, IoU=0.3352, F1=0.4852]Epoch 4: T-Loss: 7.4247 | V-Loss: 6.9884 | IoU: 0.3352 | F1: 0.4852
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   5%|▌         | 5/100 [01:40<26:37, 16.81s/it, IoU=0.4013, F1=0.5577]Epoch 5: T-Loss: 7.0925 | V-Loss: 6.5938 | IoU: 0.4013 | F1: 0.5577 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   6%|▌         | 6/100 [01:57<25:56, 16.56s/it, IoU=0.3660, F1=0.5186]Epoch 6: T-Loss: 6.7876 | V-Loss: 6.2814 | IoU: 0.3660 | F1: 0.5186
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   7%|▋         | 7/100 [02:13<25:53, 16.70s/it, IoU=0.3837, F1=0.5353]Epoch 7: T-Loss: 6.5377 | V-Loss: 6.2441 | IoU: 0.3837 | F1: 0.5353
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   8%|▊         | 8/100 [02:28<25:15, 16.47s/it, IoU=0.3879, F1=0.5421]Epoch 8: T-Loss: 6.3704 | V-Loss: 6.0776 | IoU: 0.3879 | F1: 0.5421
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   9%|▉         | 9/100 [02:47<24:19, 16.04s/it, IoU=0.4688, F1=0.6229]Epoch 9: T-Loss: 6.2577 | V-Loss: 5.9656 | IoU: 0.4688 | F1: 0.6229 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  10%|█         | 10/100 [03:02<25:42, 17.14s/it, IoU=0.4471, F1=0.6035]Epoch 10: T-Loss: 6.0908 | V-Loss: 5.9230 | IoU: 0.4471 | F1: 0.6035
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  11%|█         | 11/100 [03:17<24:14, 16.35s/it, IoU=0.4485, F1=0.6056]Epoch 11: T-Loss: 6.0231 | V-Loss: 6.0298 | IoU: 0.4485 | F1: 0.6056
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  12%|█▏        | 12/100 [03:31<23:34, 16.07s/it, IoU=0.4648, F1=0.6213]Epoch 12: T-Loss: 5.9665 | V-Loss: 5.7385 | IoU: 0.4648 | F1: 0.6213
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  13%|█▎        | 13/100 [03:51<22:17, 15.37s/it, IoU=0.4523, F1=0.6071]Epoch 13: T-Loss: 5.9087 | V-Loss: 5.7225 | IoU: 0.4523 | F1: 0.6071
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  14%|█▍        | 14/100 [04:07<23:59, 16.73s/it, IoU=0.5029, F1=0.6575]Epoch 14: T-Loss: 5.8449 | V-Loss: 5.6488 | IoU: 0.5029 | F1: 0.6575 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  15%|█▌        | 15/100 [04:23<23:28, 16.57s/it, IoU=0.4909, F1=0.6473]Epoch 15: T-Loss: 5.8922 | V-Loss: 5.7253 | IoU: 0.4909 | F1: 0.6473
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  16%|█▌        | 16/100 [04:42<22:49, 16.30s/it, IoU=0.4771, F1=0.6334]Epoch 16: T-Loss: 5.7966 | V-Loss: 5.6150 | IoU: 0.4771 | F1: 0.6334
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  17%|█▋        | 17/100 [04:56<23:37, 17.08s/it, IoU=0.5093, F1=0.6621]Epoch 17: T-Loss: 5.8023 | V-Loss: 5.5836 | IoU: 0.5093 | F1: 0.6621 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  18%|█▊        | 18/100 [05:13<22:15, 16.29s/it, IoU=0.5158, F1=0.6680]Epoch 18: T-Loss: 5.7461 | V-Loss: 5.5580 | IoU: 0.5158 | F1: 0.6680 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  19%|█▉        | 19/100 [05:27<22:06, 16.37s/it, IoU=0.4901, F1=0.6448]Epoch 19: T-Loss: 5.7393 | V-Loss: 5.5697 | IoU: 0.4901 | F1: 0.6448
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  20%|██        | 20/100 [05:43<21:01, 15.77s/it, IoU=0.4860, F1=0.6400]Epoch 20: T-Loss: 5.7276 | V-Loss: 5.5278 | IoU: 0.4860 | F1: 0.6400
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  21%|██        | 21/100 [06:00<20:55, 15.89s/it, IoU=0.4857, F1=0.6395]Epoch 21: T-Loss: 5.7386 | V-Loss: 5.5285 | IoU: 0.4857 | F1: 0.6395
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  22%|██▏       | 22/100 [06:16<20:51, 16.04s/it, IoU=0.5275, F1=0.6778]Epoch 22: T-Loss: 5.6517 | V-Loss: 5.4992 | IoU: 0.5275 | F1: 0.6778 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  23%|██▎       | 23/100 [06:30<20:46, 16.19s/it, IoU=0.5425, F1=0.6923]Epoch 23: T-Loss: 5.6462 | V-Loss: 5.4639 | IoU: 0.5425 | F1: 0.6923 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  24%|██▍       | 24/100 [06:45<19:41, 15.55s/it, IoU=0.5231, F1=0.6758]Epoch 24: T-Loss: 5.6361 | V-Loss: 5.5081 | IoU: 0.5231 | F1: 0.6758
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  25%|██▌       | 25/100 [07:02<18:58, 15.19s/it, IoU=0.5365, F1=0.6862]Epoch 25: T-Loss: 5.6738 | V-Loss: 5.4757 | IoU: 0.5365 | F1: 0.6862
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  26%|██▌       | 26/100 [07:19<19:28, 15.78s/it, IoU=0.5407, F1=0.6913]Epoch 26: T-Loss: 5.6168 | V-Loss: 5.4618 | IoU: 0.5407 | F1: 0.6913
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  27%|██▋       | 27/100 [07:36<19:33, 16.08s/it, IoU=0.5507, F1=0.6999]Epoch 27: T-Loss: 5.6321 | V-Loss: 5.4525 | IoU: 0.5507 | F1: 0.6999 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  28%|██▊       | 28/100 [07:51<19:51, 16.54s/it, IoU=0.5095, F1=0.6629]Epoch 28: T-Loss: 5.6015 | V-Loss: 5.4501 | IoU: 0.5095 | F1: 0.6629
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  29%|██▉       | 29/100 [08:06<18:59, 16.05s/it, IoU=0.5167, F1=0.6708]Epoch 29: T-Loss: 5.5814 | V-Loss: 5.4727 | IoU: 0.5167 | F1: 0.6708
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  30%|███       | 30/100 [08:22<18:26, 15.81s/it, IoU=0.5225, F1=0.6753]Epoch 30: T-Loss: 5.5741 | V-Loss: 5.4539 | IoU: 0.5225 | F1: 0.6753
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  31%|███       | 31/100 [08:40<18:13, 15.84s/it, IoU=0.4275, F1=0.5815]Epoch 31: T-Loss: 5.5767 | V-Loss: 5.4709 | IoU: 0.4275 | F1: 0.5815
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  32%|███▏      | 32/100 [08:55<18:29, 16.31s/it, IoU=0.5349, F1=0.6866]Epoch 32: T-Loss: 5.5225 | V-Loss: 5.4137 | IoU: 0.5349 | F1: 0.6866
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  33%|███▎      | 33/100 [09:09<17:45, 15.91s/it, IoU=0.5340, F1=0.6842]Epoch 33: T-Loss: 5.5440 | V-Loss: 5.4095 | IoU: 0.5340 | F1: 0.6842
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  34%|███▍      | 34/100 [09:27<16:59, 15.45s/it, IoU=0.5355, F1=0.6872]Epoch 34: T-Loss: 5.5454 | V-Loss: 5.3860 | IoU: 0.5355 | F1: 0.6872
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  35%|███▌      | 35/100 [09:45<17:26, 16.10s/it, IoU=0.5792, F1=0.7259]Epoch 35: T-Loss: 5.5321 | V-Loss: 5.4208 | IoU: 0.5792 | F1: 0.7259 [Saved Best Model]
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  36%|███▌      | 36/100 [10:01<18:00, 16.88s/it, IoU=0.5464, F1=0.6972]Epoch 36: T-Loss: 5.5152 | V-Loss: 5.3815 | IoU: 0.5464 | F1: 0.6972
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  37%|███▋      | 37/100 [10:19<17:10, 16.36s/it, IoU=0.5601, F1=0.7103]Epoch 37: T-Loss: 5.5136 | V-Loss: 5.4197 | IoU: 0.5601 | F1: 0.7103
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  38%|███▊      | 38/100 [10:34<17:30, 16.94s/it, IoU=0.5460, F1=0.6950]Epoch 38: T-Loss: 5.5394 | V-Loss: 5.3883 | IoU: 0.5460 | F1: 0.6950

  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  39%|███▉      | 39/100 [10:51<16:44, 16.47s/it, IoU=0.5154, F1=0.6682]Epoch 39: T-Loss: 5.5051 | V-Loss: 5.4003 | IoU: 0.5154 | F1: 0.6682
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  40%|████      | 40/100 [11:07<16:31, 16.53s/it, IoU=0.5560, F1=0.7051]Epoch 40: T-Loss: 5.5036 | V-Loss: 5.3959 | IoU: 0.5560 | F1: 0.7051
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  41%|████      | 41/100 [11:25<16:11, 16.47s/it, IoU=0.5131, F1=0.6670]Epoch 41: T-Loss: 5.4935 | V-Loss: 5.3702 | IoU: 0.5131 | F1: 0.6670
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  42%|████▏     | 42/100 [11:44<16:26, 17.01s/it, IoU=0.5643, F1=0.7140]Epoch 42: T-Loss: 5.5336 | V-Loss: 5.3588 | IoU: 0.5643 | F1: 0.7140
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  43%|████▎     | 43/100 [12:00<16:34, 17.45s/it, IoU=0.5367, F1=0.6870]Epoch 43: T-Loss: 5.4596 | V-Loss: 5.3442 | IoU: 0.5367 | F1: 0.6870
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  44%|████▍     | 44/100 [12:20<15:57, 17.11s/it, IoU=0.5395, F1=0.6900]Epoch 44: T-Loss: 5.4744 | V-Loss: 5.3361 | IoU: 0.5395 | F1: 0.6900
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  45%|████▌     | 45/100 [12:34<16:18, 17.79s/it, IoU=0.5332, F1=0.6848]Epoch 45: T-Loss: 5.4840 | V-Loss: 5.3739 | IoU: 0.5332 | F1: 0.6848
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  46%|████▌     | 46/100 [12:50<15:02, 16.71s/it, IoU=0.4876, F1=0.6420]Epoch 46: T-Loss: 5.4592 | V-Loss: 5.3678 | IoU: 0.4876 | F1: 0.6420
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  47%|████▋     | 47/100 [13:07<14:31, 16.44s/it, IoU=0.5206, F1=0.6720]Epoch 47: T-Loss: 5.4564 | V-Loss: 5.3738 | IoU: 0.5206 | F1: 0.6720
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  48%|████▊     | 48/100 [13:27<14:30, 16.74s/it, IoU=0.5365, F1=0.6886]Epoch 48: T-Loss: 5.4214 | V-Loss: 5.3587 | IoU: 0.5365 | F1: 0.6886
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  49%|████▉     | 49/100 [13:43<14:57, 17.60s/it, IoU=0.5448, F1=0.6946]Epoch 49: T-Loss: 5.4482 | V-Loss: 5.3363 | IoU: 0.5448 | F1: 0.6946
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  50%|█████     | 50/100 [14:03<14:18, 17.17s/it, IoU=0.5598, F1=0.7080]Epoch 50: T-Loss: 5.4596 | V-Loss: 5.3599 | IoU: 0.5598 | F1: 0.7080
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  51%|█████     | 51/100 [14:20<14:49, 18.16s/it, IoU=0.5350, F1=0.6856]Epoch 51: T-Loss: 5.4729 | V-Loss: 5.3546 | IoU: 0.5350 | F1: 0.6856
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  52%|█████▏    | 52/100 [14:37<14:09, 17.70s/it, IoU=0.5381, F1=0.6889]Epoch 52: T-Loss: 5.4870 | V-Loss: 5.3496 | IoU: 0.5381 | F1: 0.6889
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  53%|█████▎    | 53/100 [14:54<13:39, 17.43s/it, IoU=0.5608, F1=0.7083]Epoch 53: T-Loss: 5.3938 | V-Loss: 5.3584 | IoU: 0.5608 | F1: 0.7083
  → Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  54%|█████▍    | 54/100 [15:13<13:25, 17.51s/it, IoU=0.5074, F1=0.6603]Epoch 54: T-Loss: 5.4305 | V-Loss: 5.3905 | IoU: 0.5074 | F1: 0.6603

============================================================
Early Stopping Triggered at Epoch 54
  - Best Validation Loss: 5.3361
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_efficientnet-b0.csv

Final results:
                                              Experiment  ...  Test_Prec
0  Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct  ...   0.510535

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Single-TB --arch Unet --encoder resnet50 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_resnet50.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Single-TB | arch=Unet | encoder=resnet50 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 424/424 [00:00<00:00, 43256.02it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 2323.58it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 20
 - Validation batches: 6
 - Testing batches: 3
  → Unet-resnet50-imagenet_Single-TB:   0%|          | 0/100 [00:11<?, ?it/s, IoU=0.0067, F1=0.0133]Epoch 0: T-Loss: 10.1992 | V-Loss: 9.8472 | IoU: 0.0067 | F1: 0.0133 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   1%|          | 1/100 [00:24<20:26, 12.39s/it, IoU=0.0363, F1=0.0679]Epoch 1: T-Loss: 9.2913 | V-Loss: 10.0159 | IoU: 0.0363 | F1: 0.0679 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   2%|▏         | 2/100 [00:32<19:54, 12.19s/it, IoU=0.0538, F1=0.0987]Epoch 2: T-Loss: 8.9499 | V-Loss: 8.7831 | IoU: 0.0538 | F1: 0.0987 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   3%|▎         | 3/100 [00:41<16:57, 10.49s/it, IoU=0.0491, F1=0.0914]Epoch 3: T-Loss: 8.7368 | V-Loss: 8.8966 | IoU: 0.0491 | F1: 0.0914
  → Unet-resnet50-imagenet_Single-TB:   4%|▍         | 4/100 [00:50<15:51,  9.91s/it, IoU=0.0571, F1=0.1048]Epoch 4: T-Loss: 8.5983 | V-Loss: 8.5623 | IoU: 0.0571 | F1: 0.1048 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   5%|▌         | 5/100 [00:59<14:52,  9.40s/it, IoU=0.1444, F1=0.2343]Epoch 5: T-Loss: 8.4570 | V-Loss: 8.4255 | IoU: 0.1444 | F1: 0.2343 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   6%|▌         | 6/100 [01:11<14:46,  9.43s/it, IoU=0.1753, F1=0.2784]Epoch 6: T-Loss: 8.3180 | V-Loss: 8.3671 | IoU: 0.1753 | F1: 0.2784 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:   7%|▋         | 7/100 [01:21<15:58, 10.31s/it, IoU=0.1144, F1=0.1947]Epoch 7: T-Loss: 8.2202 | V-Loss: 9.1769 | IoU: 0.1144 | F1: 0.1947
  → Unet-resnet50-imagenet_Single-TB:   8%|▊         | 8/100 [01:30<15:29, 10.10s/it, IoU=0.1536, F1=0.2510]Epoch 8: T-Loss: 8.1267 | V-Loss: 8.4136 | IoU: 0.1536 | F1: 0.2510
  → Unet-resnet50-imagenet_Single-TB:   9%|▉         | 9/100 [01:39<14:47,  9.75s/it, IoU=0.1808, F1=0.2874]Epoch 9: T-Loss: 8.0354 | V-Loss: 8.2074 | IoU: 0.1808 | F1: 0.2874 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  10%|█         | 10/100 [01:48<14:14,  9.50s/it, IoU=0.1073, F1=0.1855]Epoch 10: T-Loss: 7.9604 | V-Loss: 8.2208 | IoU: 0.1073 | F1: 0.1855
  → Unet-resnet50-imagenet_Single-TB:  11%|█         | 11/100 [01:57<13:50,  9.34s/it, IoU=0.1786, F1=0.2905]Epoch 11: T-Loss: 7.8891 | V-Loss: 7.6158 | IoU: 0.1786 | F1: 0.2905
  → Unet-resnet50-imagenet_Single-TB:  12%|█▏        | 12/100 [02:06<13:30,  9.21s/it, IoU=0.2536, F1=0.3932]Epoch 12: T-Loss: 7.8206 | V-Loss: 7.5353 | IoU: 0.2536 | F1: 0.3932 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  13%|█▎        | 13/100 [02:15<13:29,  9.31s/it, IoU=0.2079, F1=0.3270]Epoch 13: T-Loss: 7.7525 | V-Loss: 7.4793 | IoU: 0.2079 | F1: 0.3270
  → Unet-resnet50-imagenet_Single-TB:  14%|█▍        | 14/100 [02:24<13:08,  9.16s/it, IoU=0.2395, F1=0.3697]Epoch 14: T-Loss: 7.6684 | V-Loss: 7.5029 | IoU: 0.2395 | F1: 0.3697
  → Unet-resnet50-imagenet_Single-TB:  15%|█▌        | 15/100 [02:32<12:54,  9.11s/it, IoU=0.0984, F1=0.1725]Epoch 15: T-Loss: 7.5839 | V-Loss: 8.6210 | IoU: 0.0984 | F1: 0.1725
  → Unet-resnet50-imagenet_Single-TB:  16%|█▌        | 16/100 [02:39<12:18,  8.79s/it, IoU=0.1925, F1=0.3061]Epoch 16: T-Loss: 7.5297 | V-Loss: 7.3895 | IoU: 0.1925 | F1: 0.3061
  → Unet-resnet50-imagenet_Single-TB:  17%|█▋        | 17/100 [02:48<11:26,  8.27s/it, IoU=0.2220, F1=0.3422]Epoch 17: T-Loss: 7.4492 | V-Loss: 7.1693 | IoU: 0.2220 | F1: 0.3422
  → Unet-resnet50-imagenet_Single-TB:  18%|█▊        | 18/100 [02:54<11:18,  8.27s/it, IoU=0.2916, F1=0.4359]Epoch 18: T-Loss: 7.4316 | V-Loss: 7.0075 | IoU: 0.2916 | F1: 0.4359 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  19%|█▉        | 19/100 [03:04<10:39,  7.90s/it, IoU=0.3032, F1=0.4602]Epoch 19: T-Loss: 7.3261 | V-Loss: 7.0176 | IoU: 0.3032 | F1: 0.4602 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  20%|██        | 20/100 [03:16<11:13,  8.42s/it, IoU=0.2883, F1=0.4379]Epoch 20: T-Loss: 7.2677 | V-Loss: 6.8892 | IoU: 0.2883 | F1: 0.4379
  → Unet-resnet50-imagenet_Single-TB:  21%|██        | 21/100 [03:26<12:16,  9.32s/it, IoU=0.3022, F1=0.4531]Epoch 21: T-Loss: 7.1310 | V-Loss: 6.7191 | IoU: 0.3022 | F1: 0.4531
  → Unet-resnet50-imagenet_Single-TB:  22%|██▏       | 22/100 [03:37<12:19,  9.49s/it, IoU=0.1965, F1=0.3177]Epoch 22: T-Loss: 7.0200 | V-Loss: 6.9340 | IoU: 0.1965 | F1: 0.3177
  → Unet-resnet50-imagenet_Single-TB:  23%|██▎       | 23/100 [03:47<12:44,  9.92s/it, IoU=0.3781, F1=0.5424]Epoch 23: T-Loss: 6.9955 | V-Loss: 6.6286 | IoU: 0.3781 | F1: 0.5424 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  24%|██▍       | 24/100 [03:57<13:00, 10.27s/it, IoU=0.3312, F1=0.4897]Epoch 24: T-Loss: 6.9820 | V-Loss: 6.5404 | IoU: 0.3312 | F1: 0.4897
  → Unet-resnet50-imagenet_Single-TB:  25%|██▌       | 25/100 [04:07<12:32, 10.04s/it, IoU=0.2963, F1=0.4487]Epoch 25: T-Loss: 6.9441 | V-Loss: 6.5020 | IoU: 0.2963 | F1: 0.4487
  → Unet-resnet50-imagenet_Single-TB:  26%|██▌       | 26/100 [04:17<12:25, 10.07s/it, IoU=0.3384, F1=0.4958]Epoch 26: T-Loss: 6.7869 | V-Loss: 6.3440 | IoU: 0.3384 | F1: 0.4958
  → Unet-resnet50-imagenet_Single-TB:  27%|██▋       | 27/100 [04:29<12:04,  9.92s/it, IoU=0.3199, F1=0.4676]Epoch 27: T-Loss: 6.6882 | V-Loss: 6.3754 | IoU: 0.3199 | F1: 0.4676
  → Unet-resnet50-imagenet_Single-TB:  28%|██▊       | 28/100 [04:39<12:43, 10.61s/it, IoU=0.3314, F1=0.4845]Epoch 28: T-Loss: 6.6608 | V-Loss: 6.2588 | IoU: 0.3314 | F1: 0.4845
  → Unet-resnet50-imagenet_Single-TB:  29%|██▉       | 29/100 [04:48<12:14, 10.35s/it, IoU=0.3771, F1=0.5323]Epoch 29: T-Loss: 6.6583 | V-Loss: 6.3164 | IoU: 0.3771 | F1: 0.5323
  → Unet-resnet50-imagenet_Single-TB:  30%|███       | 30/100 [04:55<11:32,  9.89s/it, IoU=0.2773, F1=0.4249]Epoch 30: T-Loss: 6.5976 | V-Loss: 6.3945 | IoU: 0.2773 | F1: 0.4249
  → Unet-resnet50-imagenet_Single-TB:  31%|███       | 31/100 [05:05<10:26,  9.08s/it, IoU=0.3329, F1=0.4963]Epoch 31: T-Loss: 6.6868 | V-Loss: 6.2705 | IoU: 0.3329 | F1: 0.4963
  → Unet-resnet50-imagenet_Single-TB:  32%|███▏      | 32/100 [05:13<10:31,  9.28s/it, IoU=0.3281, F1=0.4728]Epoch 32: T-Loss: 6.6798 | V-Loss: 6.2258 | IoU: 0.3281 | F1: 0.4728
  → Unet-resnet50-imagenet_Single-TB:  33%|███▎      | 33/100 [05:22<09:54,  8.88s/it, IoU=0.3326, F1=0.4827]Epoch 33: T-Loss: 6.5108 | V-Loss: 6.1542 | IoU: 0.3326 | F1: 0.4827
  → Unet-resnet50-imagenet_Single-TB:  34%|███▍      | 34/100 [05:31<09:54,  9.00s/it, IoU=0.3602, F1=0.5170]Epoch 34: T-Loss: 6.4607 | V-Loss: 6.0935 | IoU: 0.3602 | F1: 0.5170
  → Unet-resnet50-imagenet_Single-TB:  35%|███▌      | 35/100 [05:39<09:40,  8.93s/it, IoU=0.4283, F1=0.5900]Epoch 35: T-Loss: 6.3865 | V-Loss: 6.0837 | IoU: 0.4283 | F1: 0.5900 [Saved Best Model]
  → Unet-resnet50-imagenet_Single-TB:  36%|███▌      | 36/100 [05:50<09:16,  8.70s/it, IoU=0.3652, F1=0.5184]Epoch 36: T-Loss: 6.4628 | V-Loss: 6.1012 | IoU: 0.3652 | F1: 0.5184
  → Unet-resnet50-imagenet_Single-TB:  37%|███▋      | 37/100 [05:59<09:47,  9.32s/it, IoU=0.3780, F1=0.5250]Epoch 37: T-Loss: 6.3266 | V-Loss: 6.0578 | IoU: 0.3780 | F1: 0.5250
  → Unet-resnet50-imagenet_Single-TB:  38%|███▊      | 38/100 [06:06<09:41,  9.38s/it, IoU=0.4176, F1=0.5710]Epoch 38: T-Loss: 6.3217 | V-Loss: 6.0413 | IoU: 0.4176 | F1: 0.5710
  → Unet-resnet50-imagenet_Single-TB:  39%|███▉      | 39/100 [06:14<08:55,  8.79s/it, IoU=0.3500, F1=0.4987]Epoch 39: T-Loss: 6.3726 | V-Loss: 6.1225 | IoU: 0.3500 | F1: 0.4987
  → Unet-resnet50-imagenet_Single-TB:  40%|████      | 40/100 [06:21<08:24,  8.41s/it, IoU=0.3581, F1=0.5199]Epoch 40: T-Loss: 6.3812 | V-Loss: 6.0332 | IoU: 0.3581 | F1: 0.5199
  → Unet-resnet50-imagenet_Single-TB:  41%|████      | 41/100 [06:29<07:55,  8.07s/it, IoU=0.3061, F1=0.4532]Epoch 41: T-Loss: 6.2858 | V-Loss: 6.1517 | IoU: 0.3061 | F1: 0.4532
  → Unet-resnet50-imagenet_Single-TB:  42%|████▏     | 42/100 [06:37<07:43,  8.00s/it, IoU=0.3296, F1=0.4834]Epoch 42: T-Loss: 6.3777 | V-Loss: 6.1023 | IoU: 0.3296 | F1: 0.4834
  → Unet-resnet50-imagenet_Single-TB:  43%|████▎     | 43/100 [06:50<07:36,  8.00s/it, IoU=0.3488, F1=0.5035]Epoch 43: T-Loss: 6.3791 | V-Loss: 6.0740 | IoU: 0.3488 | F1: 0.5035

  → Unet-resnet50-imagenet_Single-TB:  44%|████▍     | 44/100 [06:57<08:42,  9.34s/it, IoU=0.3699, F1=0.5223]Epoch 44: T-Loss: 6.3131 | V-Loss: 5.9870 | IoU: 0.3699 | F1: 0.5223
  → Unet-resnet50-imagenet_Single-TB:  45%|████▌     | 45/100 [07:03<07:58,  8.70s/it, IoU=0.3579, F1=0.5131]Epoch 45: T-Loss: 6.2793 | V-Loss: 5.9749 | IoU: 0.3579 | F1: 0.5131
  → Unet-resnet50-imagenet_Single-TB:  46%|████▌     | 46/100 [07:12<07:14,  8.05s/it, IoU=0.3555, F1=0.5071]Epoch 46: T-Loss: 6.1390 | V-Loss: 6.0241 | IoU: 0.3555 | F1: 0.5071
  → Unet-resnet50-imagenet_Single-TB:  47%|████▋     | 47/100 [07:20<07:21,  8.33s/it, IoU=0.3234, F1=0.4732]Epoch 47: T-Loss: 6.1522 | V-Loss: 6.0444 | IoU: 0.3234 | F1: 0.4732
  → Unet-resnet50-imagenet_Single-TB:  48%|████▊     | 48/100 [07:28<06:58,  8.05s/it, IoU=0.3715, F1=0.5234]Epoch 48: T-Loss: 6.2246 | V-Loss: 6.0573 | IoU: 0.3715 | F1: 0.5234
  → Unet-resnet50-imagenet_Single-TB:  49%|████▉     | 49/100 [07:36<06:49,  8.02s/it, IoU=0.2723, F1=0.4154]Epoch 49: T-Loss: 6.3294 | V-Loss: 6.1033 | IoU: 0.2723 | F1: 0.4154
  → Unet-resnet50-imagenet_Single-TB:  50%|█████     | 50/100 [07:46<06:43,  8.06s/it, IoU=0.3510, F1=0.5044]Epoch 50: T-Loss: 6.2162 | V-Loss: 5.8977 | IoU: 0.3510 | F1: 0.5044
  → Unet-resnet50-imagenet_Single-TB:  51%|█████     | 51/100 [07:54<07:04,  8.66s/it, IoU=0.3458, F1=0.4931]Epoch 51: T-Loss: 6.2464 | V-Loss: 5.9462 | IoU: 0.3458 | F1: 0.4931
  → Unet-resnet50-imagenet_Single-TB:  52%|█████▏    | 52/100 [08:03<06:46,  8.46s/it, IoU=0.3354, F1=0.4781]Epoch 52: T-Loss: 6.2035 | V-Loss: 5.9482 | IoU: 0.3354 | F1: 0.4781
  → Unet-resnet50-imagenet_Single-TB:  53%|█████▎    | 53/100 [08:14<06:44,  8.60s/it, IoU=0.3079, F1=0.4484]Epoch 53: T-Loss: 6.1435 | V-Loss: 6.0137 | IoU: 0.3079 | F1: 0.4484
  → Unet-resnet50-imagenet_Single-TB:  54%|█████▍    | 54/100 [08:24<07:07,  9.30s/it, IoU=0.3609, F1=0.5116]Epoch 54: T-Loss: 6.1821 | V-Loss: 5.9348 | IoU: 0.3609 | F1: 0.5116
  → Unet-resnet50-imagenet_Single-TB:  55%|█████▌    | 55/100 [08:32<07:07,  9.50s/it, IoU=0.3730, F1=0.5205]Epoch 55: T-Loss: 6.1066 | V-Loss: 5.9561 | IoU: 0.3730 | F1: 0.5205
  → Unet-resnet50-imagenet_Single-TB:  56%|█████▌    | 56/100 [08:41<06:47,  9.26s/it, IoU=0.3755, F1=0.5219]Epoch 56: T-Loss: 6.1258 | V-Loss: 5.9780 | IoU: 0.3755 | F1: 0.5219
  → Unet-resnet50-imagenet_Single-TB:  57%|█████▋    | 57/100 [08:49<06:29,  9.05s/it, IoU=0.3989, F1=0.5480]Epoch 57: T-Loss: 6.0503 | V-Loss: 5.9142 | IoU: 0.3989 | F1: 0.5480
  → Unet-resnet50-imagenet_Single-TB:  58%|█████▊    | 58/100 [08:57<06:03,  8.66s/it, IoU=0.3886, F1=0.5392]Epoch 58: T-Loss: 6.0994 | V-Loss: 5.8611 | IoU: 0.3886 | F1: 0.5392
  → Unet-resnet50-imagenet_Single-TB:  59%|█████▉    | 59/100 [09:05<05:45,  8.44s/it, IoU=0.3765, F1=0.5267]Epoch 59: T-Loss: 6.0078 | V-Loss: 5.8773 | IoU: 0.3765 | F1: 0.5267
  → Unet-resnet50-imagenet_Single-TB:  60%|██████    | 60/100 [09:16<05:41,  8.54s/it, IoU=0.3669, F1=0.5165]Epoch 60: T-Loss: 5.9971 | V-Loss: 5.9358 | IoU: 0.3669 | F1: 0.5165
  → Unet-resnet50-imagenet_Single-TB:  61%|██████    | 61/100 [09:25<05:58,  9.19s/it, IoU=0.3755, F1=0.5262]Epoch 61: T-Loss: 5.9811 | V-Loss: 5.8694 | IoU: 0.3755 | F1: 0.5262
  → Unet-resnet50-imagenet_Single-TB:  62%|██████▏   | 62/100 [09:33<05:41,  8.98s/it, IoU=0.3701, F1=0.5212]Epoch 62: T-Loss: 6.1046 | V-Loss: 5.8508 | IoU: 0.3701 | F1: 0.5212
  → Unet-resnet50-imagenet_Single-TB:  63%|██████▎   | 63/100 [09:41<05:29,  8.90s/it, IoU=0.3660, F1=0.5153]Epoch 63: T-Loss: 6.0209 | V-Loss: 5.8876 | IoU: 0.3660 | F1: 0.5153
  → Unet-resnet50-imagenet_Single-TB:  64%|██████▍   | 64/100 [09:50<05:07,  8.55s/it, IoU=0.3901, F1=0.5363]Epoch 64: T-Loss: 5.9522 | V-Loss: 5.8961 | IoU: 0.3901 | F1: 0.5363
  → Unet-resnet50-imagenet_Single-TB:  65%|██████▌   | 65/100 [09:59<05:07,  8.79s/it, IoU=0.3985, F1=0.5472]Epoch 65: T-Loss: 5.9835 | V-Loss: 5.8695 | IoU: 0.3985 | F1: 0.5472
  → Unet-resnet50-imagenet_Single-TB:  66%|██████▌   | 66/100 [10:10<04:57,  8.74s/it, IoU=0.4047, F1=0.5569]Epoch 66: T-Loss: 6.0279 | V-Loss: 5.8332 | IoU: 0.4047 | F1: 0.5569
  → Unet-resnet50-imagenet_Single-TB:  67%|██████▋   | 67/100 [10:20<05:09,  9.39s/it, IoU=0.3908, F1=0.5370]Epoch 67: T-Loss: 5.8905 | V-Loss: 5.8635 | IoU: 0.3908 | F1: 0.5370
  → Unet-resnet50-imagenet_Single-TB:  68%|██████▊   | 68/100 [10:28<05:11,  9.72s/it, IoU=0.3776, F1=0.5269]Epoch 68: T-Loss: 5.8940 | V-Loss: 5.8605 | IoU: 0.3776 | F1: 0.5269
  → Unet-resnet50-imagenet_Single-TB:  69%|██████▉   | 69/100 [10:37<04:37,  8.96s/it, IoU=0.3984, F1=0.5479]Epoch 69: T-Loss: 5.8983 | V-Loss: 5.8283 | IoU: 0.3984 | F1: 0.5479
  → Unet-resnet50-imagenet_Single-TB:  70%|███████   | 70/100 [10:47<04:30,  9.02s/it, IoU=0.3703, F1=0.5162]Epoch 70: T-Loss: 5.9731 | V-Loss: 5.9286 | IoU: 0.3703 | F1: 0.5162
  → Unet-resnet50-imagenet_Single-TB:  71%|███████   | 71/100 [10:57<04:33,  9.44s/it, IoU=0.3690, F1=0.5137]Epoch 71: T-Loss: 5.9934 | V-Loss: 5.8807 | IoU: 0.3690 | F1: 0.5137
  → Unet-resnet50-imagenet_Single-TB:  72%|███████▏  | 72/100 [11:05<04:26,  9.51s/it, IoU=0.3864, F1=0.5376]Epoch 72: T-Loss: 6.0113 | V-Loss: 5.8536 | IoU: 0.3864 | F1: 0.5376
  → Unet-resnet50-imagenet_Single-TB:  73%|███████▎  | 73/100 [11:15<04:05,  9.10s/it, IoU=0.3810, F1=0.5323]Epoch 73: T-Loss: 5.9036 | V-Loss: 5.8459 | IoU: 0.3810 | F1: 0.5323
  → Unet-resnet50-imagenet_Single-TB:  74%|███████▍  | 74/100 [11:24<04:01,  9.30s/it, IoU=0.3872, F1=0.5381]Epoch 74: T-Loss: 5.9562 | V-Loss: 5.8300 | IoU: 0.3872 | F1: 0.5381
  → Unet-resnet50-imagenet_Single-TB:  75%|███████▌  | 75/100 [11:34<03:54,  9.39s/it, IoU=0.3927, F1=0.5455]Epoch 75: T-Loss: 5.9456 | V-Loss: 5.8036 | IoU: 0.3927 | F1: 0.5455
  → Unet-resnet50-imagenet_Single-TB:  76%|███████▌  | 76/100 [11:42<03:44,  9.36s/it, IoU=0.3977, F1=0.5496]Epoch 76: T-Loss: 5.8435 | V-Loss: 5.8137 | IoU: 0.3977 | F1: 0.5496
  → Unet-resnet50-imagenet_Single-TB:  77%|███████▋  | 77/100 [11:53<03:30,  9.14s/it, IoU=0.3945, F1=0.5463]Epoch 77: T-Loss: 5.8663 | V-Loss: 5.8088 | IoU: 0.3945 | F1: 0.5463
  → Unet-resnet50-imagenet_Single-TB:  78%|███████▊  | 78/100 [11:59<03:29,  9.52s/it, IoU=0.3897, F1=0.5393]Epoch 78: T-Loss: 5.9296 | V-Loss: 5.8234 | IoU: 0.3897 | F1: 0.5393
  → Unet-resnet50-imagenet_Single-TB:  79%|███████▉  | 79/100 [12:08<03:02,  8.70s/it, IoU=0.3914, F1=0.5409]Epoch 79: T-Loss: 5.9367 | V-Loss: 5.8351 | IoU: 0.3914 | F1: 0.5409
  → Unet-resnet50-imagenet_Single-TB:  80%|████████  | 80/100 [12:18<02:52,  8.64s/it, IoU=0.3859, F1=0.5366]Epoch 80: T-Loss: 5.8726 | V-Loss: 5.8564 | IoU: 0.3859 | F1: 0.5366
  → Unet-resnet50-imagenet_Single-TB:  81%|████████  | 81/100 [12:27<02:52,  9.08s/it, IoU=0.3847, F1=0.5336]Epoch 81: T-Loss: 5.8683 | V-Loss: 5.8748 | IoU: 0.3847 | F1: 0.5336
  → Unet-resnet50-imagenet_Single-TB:  82%|████████▏ | 82/100 [12:36<02:42,  9.01s/it, IoU=0.3923, F1=0.5419]Epoch 82: T-Loss: 5.9431 | V-Loss: 5.8681 | IoU: 0.3923 | F1: 0.5419
  → Unet-resnet50-imagenet_Single-TB:  83%|████████▎ | 83/100 [12:46<02:33,  9.01s/it, IoU=0.3999, F1=0.5524]Epoch 83: T-Loss: 5.8988 | V-Loss: 5.8294 | IoU: 0.3999 | F1: 0.5524
  → Unet-resnet50-imagenet_Single-TB:  84%|████████▍ | 84/100 [12:54<02:29,  9.36s/it, IoU=0.3936, F1=0.5457]Epoch 84: T-Loss: 5.9228 | V-Loss: 5.8168 | IoU: 0.3936 | F1: 0.5457
  → Unet-resnet50-imagenet_Single-TB:  85%|████████▌ | 85/100 [13:02<02:11,  8.79s/it, IoU=0.3868, F1=0.5394]Epoch 85: T-Loss: 5.8876 | V-Loss: 5.8330 | IoU: 0.3868 | F1: 0.5394

============================================================
Early Stopping Triggered at Epoch 85
  - Best Validation Loss: 5.8036
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-resnet50-imagenet_Single-TB_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_resnet50.csv

Final results:
                         Experiment  Val_Loss  ...  Test_Recall  Test_Prec
0  Unet-resnet50-imagenet_Single-TB   6.08367  ...     0.497126   0.496959

[1 rows x 11 columns]

Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TC-to-TB_10pct --arch Unet --encoder resnet50 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_resnet50.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Shift-TA_TC-to-TB_10pct | arch=Unet | encoder=resnet50 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 936/936 [00:01<00:00, 785.00it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 36785.42it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 45
 - Validation batches: 13
 - Testing batches: 3
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   0%|          | 0/100 [00:21<?, ?it/s, IoU=0.1466, F1=0.2444]Epoch 0: T-Loss: 9.8842 | V-Loss: 9.2023 | IoU: 0.1466 | F1: 0.2444 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   1%|          | 1/100 [00:38<36:35, 22.18s/it, IoU=0.2574, F1=0.3956]Epoch 1: T-Loss: 8.7073 | V-Loss: 8.4319 | IoU: 0.2574 | F1: 0.3956 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   2%|▏         | 2/100 [01:01<31:02, 19.01s/it, IoU=0.3247, F1=0.4705]Epoch 2: T-Loss: 8.3342 | V-Loss: 8.1197 | IoU: 0.3247 | F1: 0.4705 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   3%|▎         | 3/100 [01:20<33:42, 20.85s/it, IoU=0.3253, F1=0.4775]Epoch 3: T-Loss: 8.0501 | V-Loss: 7.9037 | IoU: 0.3253 | F1: 0.4775 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   4%|▍         | 4/100 [01:43<32:21, 20.22s/it, IoU=0.2914, F1=0.4318]Epoch 4: T-Loss: 7.8188 | V-Loss: 7.6846 | IoU: 0.2914 | F1: 0.4318
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   5%|▌         | 5/100 [02:03<33:15, 21.01s/it, IoU=0.3798, F1=0.5321]Epoch 5: T-Loss: 7.6312 | V-Loss: 7.5020 | IoU: 0.3798 | F1: 0.5321 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   6%|▌         | 6/100 [02:23<32:21, 20.65s/it, IoU=0.2483, F1=0.3800]Epoch 6: T-Loss: 7.4478 | V-Loss: 9.4063 | IoU: 0.2483 | F1: 0.3800
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   7%|▋         | 7/100 [02:47<31:45, 20.49s/it, IoU=0.4323, F1=0.5829]Epoch 7: T-Loss: 7.2755 | V-Loss: 7.2590 | IoU: 0.4323 | F1: 0.5829 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   8%|▊         | 8/100 [03:05<33:19, 21.74s/it, IoU=0.3699, F1=0.5185]Epoch 8: T-Loss: 7.0782 | V-Loss: 7.1668 | IoU: 0.3699 | F1: 0.5185
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:   9%|▉         | 9/100 [03:26<30:55, 20.39s/it, IoU=0.3736, F1=0.5263]Epoch 9: T-Loss: 6.9592 | V-Loss: 7.1641 | IoU: 0.3736 | F1: 0.5263
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  10%|█         | 10/100 [03:48<30:52, 20.58s/it, IoU=0.4638, F1=0.6102]Epoch 10: T-Loss: 6.8509 | V-Loss: 6.8181 | IoU: 0.4638 | F1: 0.6102 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  11%|█         | 11/100 [04:11<31:15, 21.07s/it, IoU=0.4614, F1=0.6086]Epoch 11: T-Loss: 6.6744 | V-Loss: 6.7266 | IoU: 0.4614 | F1: 0.6086
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  12%|█▏        | 12/100 [04:35<31:43, 21.64s/it, IoU=0.4868, F1=0.6333]Epoch 12: T-Loss: 6.5831 | V-Loss: 6.5752 | IoU: 0.4868 | F1: 0.6333 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  13%|█▎        | 13/100 [05:00<32:29, 22.41s/it, IoU=0.4813, F1=0.6211]Epoch 13: T-Loss: 6.4509 | V-Loss: 6.5257 | IoU: 0.4813 | F1: 0.6211
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  14%|█▍        | 14/100 [05:27<33:11, 23.15s/it, IoU=0.4690, F1=0.6081]Epoch 14: T-Loss: 6.4056 | V-Loss: 6.3479 | IoU: 0.4690 | F1: 0.6081
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  15%|█▌        | 15/100 [05:49<34:30, 24.36s/it, IoU=0.5039, F1=0.6458]Epoch 15: T-Loss: 6.2987 | V-Loss: 6.3018 | IoU: 0.5039 | F1: 0.6458 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  16%|█▌        | 16/100 [06:13<33:02, 23.60s/it, IoU=0.4854, F1=0.6266]Epoch 16: T-Loss: 6.2076 | V-Loss: 6.3998 | IoU: 0.4854 | F1: 0.6266
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  17%|█▋        | 17/100 [06:33<32:50, 23.74s/it, IoU=0.4960, F1=0.6358]Epoch 17: T-Loss: 6.1579 | V-Loss: 6.1316 | IoU: 0.4960 | F1: 0.6358
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  18%|█▊        | 18/100 [06:58<30:42, 22.47s/it, IoU=0.4945, F1=0.6355]Epoch 18: T-Loss: 6.0909 | V-Loss: 6.1751 | IoU: 0.4945 | F1: 0.6355
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  19%|█▉        | 19/100 [07:29<31:34, 23.39s/it, IoU=0.5049, F1=0.6498]Epoch 19: T-Loss: 6.0179 | V-Loss: 6.0001 | IoU: 0.5049 | F1: 0.6498 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  20%|██        | 20/100 [07:58<34:08, 25.61s/it, IoU=0.5007, F1=0.6418]Epoch 20: T-Loss: 5.9566 | V-Loss: 5.9279 | IoU: 0.5007 | F1: 0.6418
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  21%|██        | 21/100 [08:20<35:06, 26.67s/it, IoU=0.4646, F1=0.6177]Epoch 21: T-Loss: 5.9449 | V-Loss: 5.9615 | IoU: 0.4646 | F1: 0.6177
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  22%|██▏       | 22/100 [08:45<32:49, 25.25s/it, IoU=0.5113, F1=0.6527]Epoch 22: T-Loss: 5.8738 | V-Loss: 5.9010 | IoU: 0.5113 | F1: 0.6527 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  23%|██▎       | 23/100 [09:05<32:18, 25.17s/it, IoU=0.4630, F1=0.6131]Epoch 23: T-Loss: 5.9440 | V-Loss: 5.9631 | IoU: 0.4630 | F1: 0.6131
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  24%|██▍       | 24/100 [09:26<29:50, 23.56s/it, IoU=0.4945, F1=0.6368]Epoch 24: T-Loss: 5.8345 | V-Loss: 5.9124 | IoU: 0.4945 | F1: 0.6368
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  25%|██▌       | 25/100 [09:49<28:32, 22.84s/it, IoU=0.5129, F1=0.6539]Epoch 25: T-Loss: 5.9163 | V-Loss: 5.8375 | IoU: 0.5129 | F1: 0.6539 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  26%|██▌       | 26/100 [10:09<28:23, 23.02s/it, IoU=0.5128, F1=0.6540]Epoch 26: T-Loss: 5.7846 | V-Loss: 5.8379 | IoU: 0.5128 | F1: 0.6540
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  27%|██▋       | 27/100 [10:31<26:42, 21.96s/it, IoU=0.4878, F1=0.6292]Epoch 27: T-Loss: 5.7516 | V-Loss: 5.8152 | IoU: 0.4878 | F1: 0.6292
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  28%|██▊       | 28/100 [10:56<26:24, 22.01s/it, IoU=0.5420, F1=0.6790]Epoch 28: T-Loss: 5.7419 | V-Loss: 5.7764 | IoU: 0.5420 | F1: 0.6790 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  29%|██▉       | 29/100 [11:12<26:57, 22.79s/it, IoU=0.5280, F1=0.6687]Epoch 29: T-Loss: 5.6784 | V-Loss: 5.8109 | IoU: 0.5280 | F1: 0.6687
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  30%|███       | 30/100 [11:32<24:11, 20.73s/it, IoU=0.5144, F1=0.6593]Epoch 30: T-Loss: 5.6979 | V-Loss: 5.8546 | IoU: 0.5144 | F1: 0.6593
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  31%|███       | 31/100 [11:49<23:48, 20.70s/it, IoU=0.4817, F1=0.6294]Epoch 31: T-Loss: 5.7917 | V-Loss: 5.9013 | IoU: 0.4817 | F1: 0.6294
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  32%|███▏      | 32/100 [12:04<21:59, 19.41s/it, IoU=0.4965, F1=0.6400]Epoch 32: T-Loss: 5.7640 | V-Loss: 5.7935 | IoU: 0.4965 | F1: 0.6400
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  33%|███▎      | 33/100 [12:21<20:25, 18.29s/it, IoU=0.5343, F1=0.6775]Epoch 33: T-Loss: 5.7131 | V-Loss: 5.7173 | IoU: 0.5343 | F1: 0.6775
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  34%|███▍      | 34/100 [12:39<19:35, 17.81s/it, IoU=0.5040, F1=0.6444]Epoch 34: T-Loss: 5.6547 | V-Loss: 5.7993 | IoU: 0.5040 | F1: 0.6444
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  35%|███▌      | 35/100 [12:56<19:13, 17.75s/it, IoU=0.5314, F1=0.6728]Epoch 35: T-Loss: 5.6576 | V-Loss: 5.7194 | IoU: 0.5314 | F1: 0.6728
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  36%|███▌      | 36/100 [13:14<18:54, 17.73s/it, IoU=0.5329, F1=0.6760]Epoch 36: T-Loss: 5.6395 | V-Loss: 5.7045 | IoU: 0.5329 | F1: 0.6760
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  37%|███▋      | 37/100 [13:32<18:36, 17.72s/it, IoU=0.5459, F1=0.6879]Epoch 37: T-Loss: 5.5724 | V-Loss: 5.7497 | IoU: 0.5459 | F1: 0.6879 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  38%|███▊      | 38/100 [13:51<18:19, 17.74s/it, IoU=0.5374, F1=0.6782]Epoch 38: T-Loss: 5.6171 | V-Loss: 5.6779 | IoU: 0.5374 | F1: 0.6782
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  39%|███▉      | 39/100 [14:09<18:18, 18.01s/it, IoU=0.5259, F1=0.6634]Epoch 39: T-Loss: 5.6223 | V-Loss: 5.7417 | IoU: 0.5259 | F1: 0.6634
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  40%|████      | 40/100 [14:30<18:11, 18.19s/it, IoU=0.5150, F1=0.6557]Epoch 40: T-Loss: 5.5654 | V-Loss: 5.8412 | IoU: 0.5150 | F1: 0.6557

  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  41%|████      | 41/100 [14:45<18:32, 18.85s/it, IoU=0.5387, F1=0.6770]Epoch 41: T-Loss: 5.5878 | V-Loss: 5.6972 | IoU: 0.5387 | F1: 0.6770
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  42%|████▏     | 42/100 [15:02<17:17, 17.88s/it, IoU=0.5442, F1=0.6828]Epoch 42: T-Loss: 5.5582 | V-Loss: 5.6400 | IoU: 0.5442 | F1: 0.6828
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  43%|████▎     | 43/100 [15:27<16:47, 17.68s/it, IoU=0.5417, F1=0.6804]Epoch 43: T-Loss: 5.5210 | V-Loss: 5.6273 | IoU: 0.5417 | F1: 0.6804
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  44%|████▍     | 44/100 [15:44<18:22, 19.69s/it, IoU=0.5309, F1=0.6683]Epoch 44: T-Loss: 5.5575 | V-Loss: 5.7226 | IoU: 0.5309 | F1: 0.6683
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  45%|████▌     | 45/100 [16:02<17:28, 19.06s/it, IoU=0.5513, F1=0.6893]Epoch 45: T-Loss: 5.5434 | V-Loss: 5.7175 | IoU: 0.5513 | F1: 0.6893 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  46%|████▌     | 46/100 [16:19<16:50, 18.71s/it, IoU=0.5267, F1=0.6649]Epoch 46: T-Loss: 5.5955 | V-Loss: 5.7504 | IoU: 0.5267 | F1: 0.6649
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  47%|████▋     | 47/100 [16:34<15:52, 17.97s/it, IoU=0.5344, F1=0.6745]Epoch 47: T-Loss: 5.4848 | V-Loss: 5.7358 | IoU: 0.5344 | F1: 0.6745
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  48%|████▊     | 48/100 [16:51<14:59, 17.31s/it, IoU=0.5109, F1=0.6536]Epoch 48: T-Loss: 5.5439 | V-Loss: 5.7880 | IoU: 0.5109 | F1: 0.6536
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  49%|████▉     | 49/100 [17:07<14:33, 17.13s/it, IoU=0.5334, F1=0.6745]Epoch 49: T-Loss: 5.4983 | V-Loss: 5.7282 | IoU: 0.5334 | F1: 0.6745
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  50%|█████     | 50/100 [17:23<14:06, 16.92s/it, IoU=0.5348, F1=0.6748]Epoch 50: T-Loss: 5.5320 | V-Loss: 5.7532 | IoU: 0.5348 | F1: 0.6748
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  51%|█████     | 51/100 [17:41<13:30, 16.54s/it, IoU=0.5284, F1=0.6697]Epoch 51: T-Loss: 5.5468 | V-Loss: 5.7567 | IoU: 0.5284 | F1: 0.6697
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  52%|█████▏    | 52/100 [18:00<13:31, 16.90s/it, IoU=0.5261, F1=0.6695]Epoch 52: T-Loss: 5.4612 | V-Loss: 5.7367 | IoU: 0.5261 | F1: 0.6695
  → Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct:  53%|█████▎    | 53/100 [18:16<13:44, 17.55s/it, IoU=0.5356, F1=0.6740]Epoch 53: T-Loss: 5.4800 | V-Loss: 5.6752 | IoU: 0.5356 | F1: 0.6740

============================================================
Early Stopping Triggered at Epoch 53
  - Best Validation Loss: 5.6273
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_resnet50.csv

Final results:
                                       Experiment  ...  Test_Prec
0  Unet-resnet50-imagenet_Shift-TA_TC-to-TB_10pct  ...   0.414485

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TB-to-TC_10pct --arch Unet --encoder resnet50 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer2_resnet50.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA H100
Using device: cuda:0

===== Running Shift-TA_TB-to-TC_10pct | arch=Unet | encoder=resnet50 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 1028/1028 [00:00<00:00, 2739.07it/s]
Sanitizing Masks: 100%|██████████| 38/38 [00:00<00:00, 3827.47it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 50
 - Validation batches: 15
 - Testing batches: 3
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   0%|          | 0/100 [00:19<?, ?it/s, IoU=0.1928, F1=0.3187]Epoch 0: T-Loss: 9.3341 | V-Loss: 8.5501 | IoU: 0.1928 | F1: 0.3187 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   1%|          | 1/100 [00:38<32:38, 19.78s/it, IoU=0.2591, F1=0.4018]Epoch 1: T-Loss: 8.4067 | V-Loss: 8.0538 | IoU: 0.2591 | F1: 0.4018 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   2%|▏         | 2/100 [00:57<31:38, 19.37s/it, IoU=0.3514, F1=0.5022]Epoch 2: T-Loss: 7.9691 | V-Loss: 7.6264 | IoU: 0.3514 | F1: 0.5022 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   3%|▎         | 3/100 [01:16<31:01, 19.19s/it, IoU=0.3464, F1=0.5036]Epoch 3: T-Loss: 7.6279 | V-Loss: 7.4014 | IoU: 0.3464 | F1: 0.5036
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   4%|▍         | 4/100 [01:35<30:33, 19.10s/it, IoU=0.3415, F1=0.4856]Epoch 4: T-Loss: 7.2875 | V-Loss: 6.9374 | IoU: 0.3415 | F1: 0.4856
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   5%|▌         | 5/100 [01:53<30:15, 19.11s/it, IoU=0.4196, F1=0.5756]Epoch 5: T-Loss: 7.0419 | V-Loss: 6.7879 | IoU: 0.4196 | F1: 0.5756 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   6%|▌         | 6/100 [02:16<29:26, 18.80s/it, IoU=0.3707, F1=0.5107]Epoch 6: T-Loss: 6.8228 | V-Loss: 6.6279 | IoU: 0.3707 | F1: 0.5107
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   7%|▋         | 7/100 [02:36<30:56, 19.96s/it, IoU=0.4298, F1=0.5881]Epoch 7: T-Loss: 6.6285 | V-Loss: 6.4429 | IoU: 0.4298 | F1: 0.5881 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   8%|▊         | 8/100 [02:55<30:42, 20.03s/it, IoU=0.5152, F1=0.6705]Epoch 8: T-Loss: 6.4657 | V-Loss: 6.1584 | IoU: 0.5152 | F1: 0.6705 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:   9%|▉         | 9/100 [03:16<30:02, 19.81s/it, IoU=0.4726, F1=0.6268]Epoch 9: T-Loss: 6.3426 | V-Loss: 6.1084 | IoU: 0.4726 | F1: 0.6268
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  10%|█         | 10/100 [03:36<30:06, 20.07s/it, IoU=0.4486, F1=0.6059]Epoch 10: T-Loss: 6.2008 | V-Loss: 6.0009 | IoU: 0.4486 | F1: 0.6059
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  11%|█         | 11/100 [03:55<29:34, 19.94s/it, IoU=0.4738, F1=0.6266]Epoch 11: T-Loss: 6.1587 | V-Loss: 5.9195 | IoU: 0.4738 | F1: 0.6266
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  12%|█▏        | 12/100 [04:18<28:53, 19.70s/it, IoU=0.5046, F1=0.6597]Epoch 12: T-Loss: 6.0658 | V-Loss: 5.8692 | IoU: 0.5046 | F1: 0.6597
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  13%|█▎        | 13/100 [04:40<30:09, 20.80s/it, IoU=0.5169, F1=0.6654]Epoch 13: T-Loss: 6.1280 | V-Loss: 5.7509 | IoU: 0.5169 | F1: 0.6654 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  14%|█▍        | 14/100 [05:02<30:17, 21.14s/it, IoU=0.5575, F1=0.7038]Epoch 14: T-Loss: 6.0506 | V-Loss: 5.7057 | IoU: 0.5575 | F1: 0.7038 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  15%|█▌        | 15/100 [05:23<30:15, 21.36s/it, IoU=0.5020, F1=0.6490]Epoch 15: T-Loss: 5.8995 | V-Loss: 5.7271 | IoU: 0.5020 | F1: 0.6490
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  16%|█▌        | 16/100 [05:47<29:44, 21.25s/it, IoU=0.4769, F1=0.6291]Epoch 16: T-Loss: 5.8930 | V-Loss: 5.7663 | IoU: 0.4769 | F1: 0.6291
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  17%|█▋        | 17/100 [06:06<30:19, 21.92s/it, IoU=0.5380, F1=0.6881]Epoch 17: T-Loss: 5.8794 | V-Loss: 5.8235 | IoU: 0.5380 | F1: 0.6881
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  18%|█▊        | 18/100 [06:26<29:03, 21.26s/it, IoU=0.5352, F1=0.6846]Epoch 18: T-Loss: 5.9215 | V-Loss: 5.6965 | IoU: 0.5352 | F1: 0.6846
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  19%|█▉        | 19/100 [06:50<28:15, 20.93s/it, IoU=0.5195, F1=0.6732]Epoch 19: T-Loss: 5.8735 | V-Loss: 5.6734 | IoU: 0.5195 | F1: 0.6732
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  20%|██        | 20/100 [07:11<29:04, 21.80s/it, IoU=0.5413, F1=0.6886]Epoch 20: T-Loss: 5.8605 | V-Loss: 5.6500 | IoU: 0.5413 | F1: 0.6886
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  21%|██        | 21/100 [07:32<28:17, 21.49s/it, IoU=0.5394, F1=0.6887]Epoch 21: T-Loss: 5.8166 | V-Loss: 5.5611 | IoU: 0.5394 | F1: 0.6887
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  22%|██▏       | 22/100 [07:53<27:54, 21.47s/it, IoU=0.5569, F1=0.7063]Epoch 22: T-Loss: 5.8207 | V-Loss: 5.6309 | IoU: 0.5569 | F1: 0.7063
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  23%|██▎       | 23/100 [08:13<27:04, 21.09s/it, IoU=0.5596, F1=0.7055]Epoch 23: T-Loss: 5.8033 | V-Loss: 5.4887 | IoU: 0.5596 | F1: 0.7055 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  24%|██▍       | 24/100 [08:32<26:32, 20.95s/it, IoU=0.5582, F1=0.7043]Epoch 24: T-Loss: 5.8451 | V-Loss: 5.5832 | IoU: 0.5582 | F1: 0.7043
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  25%|██▌       | 25/100 [08:53<25:13, 20.18s/it, IoU=0.5352, F1=0.6768]Epoch 25: T-Loss: 5.7866 | V-Loss: 5.8161 | IoU: 0.5352 | F1: 0.6768
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  26%|██▌       | 26/100 [09:14<25:13, 20.45s/it, IoU=0.5596, F1=0.7035]Epoch 26: T-Loss: 5.8335 | V-Loss: 5.6046 | IoU: 0.5596 | F1: 0.7035 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  27%|██▋       | 27/100 [09:33<25:14, 20.75s/it, IoU=0.5522, F1=0.6922]Epoch 27: T-Loss: 5.7306 | V-Loss: 5.5243 | IoU: 0.5522 | F1: 0.6922
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  28%|██▊       | 28/100 [09:53<24:14, 20.20s/it, IoU=0.5690, F1=0.7148]Epoch 28: T-Loss: 5.6815 | V-Loss: 5.6294 | IoU: 0.5690 | F1: 0.7148 [Saved Best Model]
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  29%|██▉       | 29/100 [10:14<23:43, 20.05s/it, IoU=0.5659, F1=0.7118]Epoch 29: T-Loss: 5.7438 | V-Loss: 5.5528 | IoU: 0.5659 | F1: 0.7118
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  30%|███       | 30/100 [10:33<23:49, 20.42s/it, IoU=0.5670, F1=0.7129]Epoch 30: T-Loss: 5.7205 | V-Loss: 5.8162 | IoU: 0.5670 | F1: 0.7129
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  31%|███       | 31/100 [10:54<22:48, 19.84s/it, IoU=0.5573, F1=0.6997]Epoch 31: T-Loss: 5.8383 | V-Loss: 5.5627 | IoU: 0.5573 | F1: 0.6997
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  32%|███▏      | 32/100 [11:16<23:10, 20.45s/it, IoU=0.5622, F1=0.7059]Epoch 32: T-Loss: 5.7131 | V-Loss: 5.5872 | IoU: 0.5622 | F1: 0.7059
  → Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct:  33%|███▎      | 33/100 [11:36<23:11, 20.78s/it, IoU=0.5619, F1=0.7063]Epoch 33: T-Loss: 5.7244 | V-Loss: 5.5752 | IoU: 0.5619 | F1: 0.7063

============================================================
Early Stopping Triggered at Epoch 33
  - Best Validation Loss: 5.4887
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer2_resnet50.csv

Final results:
                                       Experiment  ...  Test_Prec
0  Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct  ...   0.424765

[1 rows x 11 columns]

## 7. Load Layer 2 Results

Run this after some or all experiments finish.

In [8]:
def load_layer2_results(backbones):
    frames = []
    for backbone in backbones:
        path = RESULTS_DIR / result_filename(backbone)
        if path.exists():
            df = pd.read_csv(path)
            df['Backbone'] = backbone
            frames.append(df)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)

layer2_df = load_layer2_results(BACKBONES)
layer2_df

,Experiment,Val_Loss,Val_IoU,Val_F1,Val_Recall,Val_Prec,Test_Loss,Test_IoU,Test_F1,Test_Recall,Test_Prec,Backbone
0,Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-T...,5.420809,0.579151,0.725868,0.777058,0.697560,5.524915,0.377296,0.545845,0.586488,0.510535,efficientnet-b0
1,Unet-resnet50-imagenet_Shift-TA_TB-to-TC_10pct,5.629375,0.569046,0.714772,0.764933,0.692679,6.058224,0.264646,0.416388,0.433505,0.424765,resnet50

## 8. Clean Experiment Labels

In [9]:
if not layer2_df.empty:
    layer2_df = layer2_df.copy()
    layer2_df['Setting'] = layer2_df['Experiment'].str.replace(r'^Unet-[^-]+-imagenet_', '', regex=True)
    display(layer2_df[['Backbone', 'Setting', 'Test_IoU', 'Test_F1', 'Test_Recall', 'Test_Prec']])
else:
    display(Markdown('No Layer 2 result files found yet.'))

,Backbone,Setting,Test_IoU,Test_F1,Test_Recall,Test_Prec
0,efficientnet-b0,Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-T...,0.377296,0.545845,0.586488,0.510535
1,resnet50,Shift-TA_TB-to-TC_10pct,0.264646,0.416388,0.433505,0.424765

## 9. Pivot Table for Comparison

In [10]:
if not layer2_df.empty:
    pivot_iou = layer2_df.pivot(index='Setting', columns='Backbone', values='Test_IoU')
    pivot_f1 = layer2_df.pivot(index='Setting', columns='Backbone', values='Test_F1')
    display(Markdown('### Test IoU'))
    display(pivot_iou)
    display(Markdown('### Test F1'))
    display(pivot_f1)
else:
    display(Markdown('No results available to pivot yet.'))

### Test IoU

Backbone                                            efficientnet-b0  resnet50
Setting
Shift-TA_TB-to-TC_10pct                                         NaN  0.264646
Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC...         0.377296       NaN

### Test F1

Backbone                                            efficientnet-b0  resnet50
Setting
Shift-TA_TB-to-TC_10pct                                         NaN  0.416388
Unet-efficientnet-b0-imagenet_Shift-TA_TB-to-TC...         0.545845       NaN

## 10. Quick Discussion Prompts

Use these after results are loaded:

- Which backbone gives the best `Test_IoU` on `Single-TB`?
- Does `efficientnet-b0` improve the domain-shift settings compared with `resnet34`?
- Does `resnet50` help because of greater depth, or is `efficientnet-b0` still stronger?
- Are the gains mostly from recall, precision, or both?