# Layer 3 Architecture Exploration (FPN vs DeepLabV3Plus vs Unet++)

This notebook compares segmentation architectures while keeping the backbone fixed.

Fixed design:
- Backbone: `resnet34`
- Encoder weights: `imagenet`
- Architectures: `FPN`, `DeepLabV3Plus`, `UnetPlusPlus` (this is the argument name used by `train_ttd.py`)
- Settings: `Single-TB`, `Shift-TA_TC-to-TB_10pct`, `Shift-TA_TB-to-TC_100pct`

## 1. Setup

In [20]:
from pathlib import Path
import subprocess
import pandas as pd
from IPython.display import display, Markdown

PROJECT_ROOT = Path('/users/7/yu001011/csci5527/CSCI5527-final')
SCRIPT_DIR = PROJECT_ROOT / 'baseline_models_scripts'
RESULTS_DIR = SCRIPT_DIR / 'runs'
VENV_PY = Path('/users/7/yu001011/csci5527/.venv/bin/python')

PROJECT_ROOT, SCRIPT_DIR, RESULTS_DIR, VENV_PY

(PosixPath('/users/7/yu001011/csci5527/CSCI5527-final'),
 PosixPath('/users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts'),
 PosixPath('/users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs'),
 PosixPath('/users/7/yu001011/csci5527/.venv/bin/python'))

## 2. Experiment Design

In [21]:
BACKBONE = 'efficientnet-b0' # resnet34 / efficientnet-b0
ENCODER_WEIGHTS = 'imagenet'
EPOCHS = 100
BATCH_SIZE = 16
IMG_SIZE = 512
LR = 1e-4

SETTINGS = [
    'Single-TB',
    'Shift-TA_TC-to-TB_10pct',
    'Shift-TA_TB-to-TC_10pct',
]

ARCHES = [
    'FPN',
    'DeepLabV3Plus',
    'UnetPlusPlus',
#     'Segformer',
]

pd.DataFrame([
    {'Setting': setting, 'Architecture': arch}
    for setting in SETTINGS
    for arch in ARCHES
])

                   Setting   Architecture
0                Single-TB            FPN
1                Single-TB  DeepLabV3Plus
2                Single-TB   UnetPlusPlus
3  Shift-TA_TC-to-TB_10pct            FPN
4  Shift-TA_TC-to-TB_10pct  DeepLabV3Plus
5  Shift-TA_TC-to-TB_10pct   UnetPlusPlus
6  Shift-TA_TB-to-TC_10pct            FPN
7  Shift-TA_TB-to-TC_10pct  DeepLabV3Plus
8  Shift-TA_TB-to-TC_10pct   UnetPlusPlus

## 3. Helper Functions

In [22]:
def result_filename(arch: str) -> str:
    safe_arch = arch.replace('+', 'plus').replace(' ', '_').lower()
    return f'layer3_arch_{safe_arch}_{BACKBONE}.csv'

def build_command(setting: str, arch: str):
    return [
        str(VENV_PY),
        'train_ttd.py',
        '--project-root', str(PROJECT_ROOT),
        '--experiment', setting,
        '--arch', arch,
        '--encoder', BACKBONE,
        '--encoder-weights', ENCODER_WEIGHTS,
        '--epochs', str(EPOCHS),
        '--batch-size', str(BATCH_SIZE),
        '--img-size', str(IMG_SIZE),
        '--lr', str(LR),
        '--results-name', result_filename(arch),
    ]

def run_one(setting: str, arch: str):
    cmd = build_command(setting, arch)
    print('Running:', ' '.join(cmd))
    return subprocess.run(cmd, cwd=SCRIPT_DIR, check=True)

def run_all(settings, arches):
    for arch in arches:
        for setting in settings:
            run_one(setting, arch)

## 4. Preview Commands

In [23]:
command_preview = pd.DataFrame([
    {
        'Setting': setting,
        'Architecture': arch,
        'Command': ' '.join(build_command(setting, arch)),
    }
    for setting in SETTINGS
    for arch in ARCHES
])

display(command_preview)

,Setting,Architecture,Command
0,Single-TB,FPN,/users/7/yu001011/csci5527/.venv/bin/python tr...
1,Single-TB,DeepLabV3Plus,/users/7/yu001011/csci5527/.venv/bin/python tr...
2,Single-TB,UnetPlusPlus,/users/7/yu001011/csci5527/.venv/bin/python tr...
3,Shift-TA_TC-to-TB_10pct,FPN,/users/7/yu001011/csci5527/.venv/bin/python tr...
4,Shift-TA_TC-to-TB_10pct,DeepLabV3Plus,/users/7/yu001011/csci5527/.venv/bin/python tr...
5,Shift-TA_TC-to-TB_10pct,UnetPlusPlus,/users/7/yu001011/csci5527/.venv/bin/python tr...
6,Shift-TA_TB-to-TC_10pct,FPN,/users/7/yu001011/csci5527/.venv/bin/python tr...
7,Shift-TA_TB-to-TC_10pct,DeepLabV3Plus,/users/7/yu001011/csci5527/.venv/bin/python tr...
8,Shift-TA_TB-to-TC_10pct,UnetPlusPlus,/users/7/yu001011/csci5527/.venv/bin/python tr...

## 5. Run a Single Experiment

In [24]:
TEST_SETTING = 'Single-TB'
TEST_ARCH = 'Unet'

# Uncomment to run:
# run_one(TEST_SETTING, TEST_ARCH)

## 6. Run the Full Layer 2 Grid

In [25]:
# Uncomment to run all experiments:
run_all(SETTINGS, ARCHES)

Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Single-TB --arch FPN --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_fpn_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Single-TB | arch=FPN | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 424/424 [00:00<00:00, 3495.53it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 3274.35it/s]

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 20
 - Validation batches: 6
 - Testing batches: 3
  → FPN-efficientnet-b0-imagenet_Single-TB:   0%|          | 0/100 [00:24<?, ?it/s, IoU=0.0000, F1=0.0001]Epoch 0: T-Loss: 9.4169 | V-Loss: 8.1089 | IoU: 0.0000 | F1: 0.0001 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   1%|          | 1/100 [00:33<41:32, 25.18s/it, IoU=0.0389, F1=0.0743]Epoch 1: T-Loss: 8.1022 | V-Loss: 7.7637 | IoU: 0.0389 | F1: 0.0743 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   2%|▏         | 2/100 [00:42<24:40, 15.11s/it, IoU=0.1512, F1=0.2587]Epoch 2: T-Loss: 7.7761 | V-Loss: 7.0946 | IoU: 0.1512 | F1: 0.2587 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   3%|▎         | 3/100 [00:51<20:04, 12.42s/it, IoU=0.1667, F1=0.2815]Epoch 3: T-Loss: 7.4702 | V-Loss: 6.9498 | IoU: 0.1667 | F1: 0.2815 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   4%|▍         | 4/100 [01:03<18:13, 11.39s/it, IoU=0.1858, F1=0.3088]Epoch 4: T-Loss: 7.3174 | V-Loss: 6.8655 | IoU: 0.1858 | F1: 0.3088 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   5%|▌         | 5/100 [01:10<17:59, 11.37s/it, IoU=0.1918, F1=0.3183]Epoch 5: T-Loss: 7.1642 | V-Loss: 6.8290 | IoU: 0.1918 | F1: 0.3183 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   6%|▌         | 6/100 [01:21<15:47, 10.08s/it, IoU=0.2189, F1=0.3559]Epoch 6: T-Loss: 7.1053 | V-Loss: 6.7456 | IoU: 0.2189 | F1: 0.3559 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   7%|▋         | 7/100 [01:36<15:43, 10.14s/it, IoU=0.2341, F1=0.3756]Epoch 7: T-Loss: 6.9840 | V-Loss: 6.6669 | IoU: 0.2341 | F1: 0.3756 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   8%|▊         | 8/100 [01:44<17:51, 11.65s/it, IoU=0.2422, F1=0.3864]Epoch 8: T-Loss: 7.0333 | V-Loss: 6.6061 | IoU: 0.2422 | F1: 0.3864 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:   9%|▉         | 9/100 [02:02<15:50, 10.44s/it, IoU=0.2448, F1=0.3882]Epoch 9: T-Loss: 6.9576 | V-Loss: 6.5676 | IoU: 0.2448 | F1: 0.3882 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  10%|█         | 10/100 [02:13<19:20, 12.89s/it, IoU=0.2439, F1=0.3855]Epoch 10: T-Loss: 6.8564 | V-Loss: 6.5816 | IoU: 0.2439 | F1: 0.3855
  → FPN-efficientnet-b0-imagenet_Single-TB:  11%|█         | 11/100 [02:20<18:12, 12.27s/it, IoU=0.2441, F1=0.3856]Epoch 11: T-Loss: 6.8829 | V-Loss: 6.5284 | IoU: 0.2441 | F1: 0.3856
  → FPN-efficientnet-b0-imagenet_Single-TB:  12%|█▏        | 12/100 [02:29<15:45, 10.75s/it, IoU=0.2672, F1=0.4174]Epoch 12: T-Loss: 6.7843 | V-Loss: 6.4386 | IoU: 0.2672 | F1: 0.4174 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  13%|█▎        | 13/100 [02:39<14:44, 10.17s/it, IoU=0.2749, F1=0.4234]Epoch 13: T-Loss: 6.7017 | V-Loss: 6.4554 | IoU: 0.2749 | F1: 0.4234 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  14%|█▍        | 14/100 [02:47<14:42, 10.26s/it, IoU=0.2797, F1=0.4291]Epoch 14: T-Loss: 6.6548 | V-Loss: 6.4026 | IoU: 0.2797 | F1: 0.4291 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  15%|█▌        | 15/100 [02:57<13:36,  9.60s/it, IoU=0.2748, F1=0.4241]Epoch 15: T-Loss: 6.6742 | V-Loss: 6.3948 | IoU: 0.2748 | F1: 0.4241
  → FPN-efficientnet-b0-imagenet_Single-TB:  16%|█▌        | 16/100 [03:10<13:27,  9.61s/it, IoU=0.2694, F1=0.4195]Epoch 16: T-Loss: 6.7522 | V-Loss: 6.4218 | IoU: 0.2694 | F1: 0.4195
  → FPN-efficientnet-b0-imagenet_Single-TB:  17%|█▋        | 17/100 [03:18<14:29, 10.47s/it, IoU=0.2431, F1=0.3869]Epoch 17: T-Loss: 6.6761 | V-Loss: 6.5031 | IoU: 0.2431 | F1: 0.3869
  → FPN-efficientnet-b0-imagenet_Single-TB:  18%|█▊        | 18/100 [03:25<13:27,  9.84s/it, IoU=0.2748, F1=0.4260]Epoch 18: T-Loss: 6.6116 | V-Loss: 6.3771 | IoU: 0.2748 | F1: 0.4260
  → FPN-efficientnet-b0-imagenet_Single-TB:  19%|█▉        | 19/100 [03:34<12:03,  8.93s/it, IoU=0.2672, F1=0.4147]Epoch 19: T-Loss: 6.7084 | V-Loss: 6.3702 | IoU: 0.2672 | F1: 0.4147
  → FPN-efficientnet-b0-imagenet_Single-TB:  20%|██        | 20/100 [03:43<11:54,  8.93s/it, IoU=0.2877, F1=0.4371]Epoch 20: T-Loss: 6.6572 | V-Loss: 6.2900 | IoU: 0.2877 | F1: 0.4371 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  21%|██        | 21/100 [03:50<11:50,  8.99s/it, IoU=0.2825, F1=0.4315]Epoch 21: T-Loss: 6.5604 | V-Loss: 6.3081 | IoU: 0.2825 | F1: 0.4315
  → FPN-efficientnet-b0-imagenet_Single-TB:  22%|██▏       | 22/100 [03:58<11:09,  8.58s/it, IoU=0.2970, F1=0.4498]Epoch 22: T-Loss: 6.6530 | V-Loss: 6.2658 | IoU: 0.2970 | F1: 0.4498 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  23%|██▎       | 23/100 [04:06<10:40,  8.32s/it, IoU=0.2705, F1=0.4201]Epoch 23: T-Loss: 6.5793 | V-Loss: 6.3256 | IoU: 0.2705 | F1: 0.4201
  → FPN-efficientnet-b0-imagenet_Single-TB:  24%|██▍       | 24/100 [04:13<10:22,  8.19s/it, IoU=0.2910, F1=0.4411]Epoch 24: T-Loss: 6.5159 | V-Loss: 6.2863 | IoU: 0.2910 | F1: 0.4411
  → FPN-efficientnet-b0-imagenet_Single-TB:  25%|██▌       | 25/100 [04:19<09:42,  7.77s/it, IoU=0.3045, F1=0.4600]Epoch 25: T-Loss: 6.5253 | V-Loss: 6.2583 | IoU: 0.3045 | F1: 0.4600 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Single-TB:  26%|██▌       | 26/100 [04:26<09:10,  7.44s/it, IoU=0.2989, F1=0.4514]Epoch 26: T-Loss: 6.5401 | V-Loss: 6.2488 | IoU: 0.2989 | F1: 0.4514
  → FPN-efficientnet-b0-imagenet_Single-TB:  27%|██▋       | 27/100 [04:34<08:50,  7.26s/it, IoU=0.3001, F1=0.4516]Epoch 27: T-Loss: 6.4763 | V-Loss: 6.2421 | IoU: 0.3001 | F1: 0.4516
  → FPN-efficientnet-b0-imagenet_Single-TB:  28%|██▊       | 28/100 [04:40<08:40,  7.23s/it, IoU=0.2944, F1=0.4450]Epoch 28: T-Loss: 6.4618 | V-Loss: 6.2687 | IoU: 0.2944 | F1: 0.4450
  → FPN-efficientnet-b0-imagenet_Single-TB:  29%|██▉       | 29/100 [04:50<08:22,  7.08s/it, IoU=0.2956, F1=0.4475]Epoch 29: T-Loss: 6.4283 | V-Loss: 6.2695 | IoU: 0.2956 | F1: 0.4475
  → FPN-efficientnet-b0-imagenet_Single-TB:  30%|███       | 30/100 [05:01<09:17,  7.96s/it, IoU=0.2921, F1=0.4419]Epoch 30: T-Loss: 6.5423 | V-Loss: 6.2693 | IoU: 0.2921 | F1: 0.4419
  → FPN-efficientnet-b0-imagenet_Single-TB:  31%|███       | 31/100 [05:12<09:59,  8.68s/it, IoU=0.2966, F1=0.4472]Epoch 31: T-Loss: 6.4265 | V-Loss: 6.2695 | IoU: 0.2966 | F1: 0.4472
  → FPN-efficientnet-b0-imagenet_Single-TB:  32%|███▏      | 32/100 [05:24<10:44,  9.48s/it, IoU=0.2846, F1=0.4365]Epoch 32: T-Loss: 6.4005 | V-Loss: 6.2838 | IoU: 0.2846 | F1: 0.4365
  → FPN-efficientnet-b0-imagenet_Single-TB:  33%|███▎      | 33/100 [05:32<11:29, 10.29s/it, IoU=0.2934, F1=0.4441]Epoch 33: T-Loss: 6.3712 | V-Loss: 6.2444 | IoU: 0.2934 | F1: 0.4441
  → FPN-efficientnet-b0-imagenet_Single-TB:  34%|███▍      | 34/100 [05:41<10:36,  9.65s/it, IoU=0.2835, F1=0.4287]Epoch 34: T-Loss: 6.2966 | V-Loss: 6.2792 | IoU: 0.2835 | F1: 0.4287
  → FPN-efficientnet-b0-imagenet_Single-TB:  35%|███▌      | 35/100 [05:50<10:15,  9.48s/it, IoU=0.2890, F1=0.4414]Epoch 35: T-Loss: 6.5582 | V-Loss: 6.2603 | IoU: 0.2890 | F1: 0.4414
  → FPN-efficientnet-b0-imagenet_Single-TB:  36%|███▌      | 36/100 [05:59<09:40,  9.07s/it, IoU=0.2815, F1=0.4315]Epoch 36: T-Loss: 6.3754 | V-Loss: 6.3077 | IoU: 0.2815 | F1: 0.4315
  → FPN-efficientnet-b0-imagenet_Single-TB:  37%|███▋      | 37/100 [06:10<09:47,  9.33s/it, IoU=0.2792, F1=0.4260]Epoch 37: T-Loss: 6.4547 | V-Loss: 6.2733 | IoU: 0.2792 | F1: 0.4260

============================================================
Early Stopping Triggered at Epoch 37
  - Best Validation Loss: 6.2421
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/FPN-efficientnet-b0-imagenet_Single-TB_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_fpn_efficientnet-b0.csv

Final results:
                               Experiment  Val_Loss  ...  Test_Recall  Test_Prec
0  FPN-efficientnet-b0-imagenet_Single-TB  6.258277  ...     0.388011   0.439543

[1 rows x 11 columns]

Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TC-to-TB_10pct --arch FPN --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_fpn_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TC-to-TB_10pct | arch=FPN | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 936/936 [00:00<00:00, 3543.96it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 14191.92it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 45
 - Validation batches: 13
 - Testing batches: 3
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   0%|          | 0/100 [00:55<?, ?it/s, IoU=0.3192, F1=0.4604]Epoch 0: T-Loss: 7.5426 | V-Loss: 6.9492 | IoU: 0.3192 | F1: 0.4604 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   1%|          | 1/100 [01:21<1:31:04, 55.20s/it, IoU=0.3347, F1=0.4841]Epoch 1: T-Loss: 6.7507 | V-Loss: 6.5484 | IoU: 0.3347 | F1: 0.4841 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   2%|▏         | 2/100 [01:38<1:02:14, 38.10s/it, IoU=0.3761, F1=0.5267]Epoch 2: T-Loss: 6.5063 | V-Loss: 6.4213 | IoU: 0.3761 | F1: 0.5267 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   3%|▎         | 3/100 [01:54<46:13, 28.59s/it, IoU=0.3558, F1=0.5053]Epoch 3: T-Loss: 6.3618 | V-Loss: 6.3574 | IoU: 0.3558 | F1: 0.5053
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   4%|▍         | 4/100 [02:10<37:35, 23.49s/it, IoU=0.3722, F1=0.5224]Epoch 4: T-Loss: 6.2850 | V-Loss: 6.2729 | IoU: 0.3722 | F1: 0.5224
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   5%|▌         | 5/100 [02:28<32:59, 20.84s/it, IoU=0.3695, F1=0.5202]Epoch 5: T-Loss: 6.2316 | V-Loss: 6.2445 | IoU: 0.3695 | F1: 0.5202
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   6%|▌         | 6/100 [02:44<31:01, 19.80s/it, IoU=0.3945, F1=0.5461]Epoch 6: T-Loss: 6.2097 | V-Loss: 6.2879 | IoU: 0.3945 | F1: 0.5461 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   7%|▋         | 7/100 [03:01<28:56, 18.67s/it, IoU=0.3886, F1=0.5405]Epoch 7: T-Loss: 6.1091 | V-Loss: 6.1705 | IoU: 0.3886 | F1: 0.5405
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   8%|▊         | 8/100 [03:19<27:59, 18.26s/it, IoU=0.4092, F1=0.5603]Epoch 8: T-Loss: 6.1067 | V-Loss: 6.1676 | IoU: 0.4092 | F1: 0.5603 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   9%|▉         | 9/100 [03:46<27:21, 18.04s/it, IoU=0.3907, F1=0.5432]Epoch 9: T-Loss: 6.0576 | V-Loss: 6.1423 | IoU: 0.3907 | F1: 0.5432
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  10%|█         | 10/100 [04:01<31:01, 20.68s/it, IoU=0.4181, F1=0.5713]Epoch 10: T-Loss: 6.0452 | V-Loss: 6.0995 | IoU: 0.4181 | F1: 0.5713 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  11%|█         | 11/100 [04:16<28:31, 19.23s/it, IoU=0.4038, F1=0.5548]Epoch 11: T-Loss: 6.0057 | V-Loss: 6.1384 | IoU: 0.4038 | F1: 0.5548
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  12%|█▏        | 12/100 [04:36<26:17, 17.93s/it, IoU=0.4347, F1=0.5868]Epoch 12: T-Loss: 5.9471 | V-Loss: 6.1048 | IoU: 0.4347 | F1: 0.5868 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  13%|█▎        | 13/100 [04:54<26:49, 18.50s/it, IoU=0.3780, F1=0.5301]Epoch 13: T-Loss: 5.9387 | V-Loss: 6.1499 | IoU: 0.3780 | F1: 0.5301
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  14%|█▍        | 14/100 [05:09<26:02, 18.17s/it, IoU=0.4014, F1=0.5520]Epoch 14: T-Loss: 5.9352 | V-Loss: 6.0651 | IoU: 0.4014 | F1: 0.5520
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  15%|█▌        | 15/100 [05:24<24:19, 17.17s/it, IoU=0.4283, F1=0.5824]Epoch 15: T-Loss: 5.8590 | V-Loss: 6.0583 | IoU: 0.4283 | F1: 0.5824
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  16%|█▌        | 16/100 [05:44<23:25, 16.73s/it, IoU=0.4049, F1=0.5576]Epoch 16: T-Loss: 5.9297 | V-Loss: 6.0229 | IoU: 0.4049 | F1: 0.5576
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  17%|█▋        | 17/100 [06:01<24:31, 17.73s/it, IoU=0.4340, F1=0.5870]Epoch 17: T-Loss: 5.8865 | V-Loss: 6.0230 | IoU: 0.4340 | F1: 0.5870
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  18%|█▊        | 18/100 [06:22<23:49, 17.44s/it, IoU=0.3936, F1=0.5440]Epoch 18: T-Loss: 5.8300 | V-Loss: 6.0176 | IoU: 0.3936 | F1: 0.5440
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  19%|█▉        | 19/100 [06:48<25:08, 18.62s/it, IoU=0.4242, F1=0.5773]Epoch 19: T-Loss: 5.8530 | V-Loss: 5.9634 | IoU: 0.4242 | F1: 0.5773
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  20%|██        | 20/100 [07:11<27:32, 20.66s/it, IoU=0.4391, F1=0.5901]Epoch 20: T-Loss: 5.8301 | V-Loss: 5.9883 | IoU: 0.4391 | F1: 0.5901 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  21%|██        | 21/100 [07:47<28:14, 21.44s/it, IoU=0.4149, F1=0.5661]Epoch 21: T-Loss: 5.8353 | V-Loss: 5.9889 | IoU: 0.4149 | F1: 0.5661
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  22%|██▏       | 22/100 [08:16<33:32, 25.80s/it, IoU=0.4288, F1=0.5814]Epoch 22: T-Loss: 5.8186 | V-Loss: 5.9319 | IoU: 0.4288 | F1: 0.5814
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  23%|██▎       | 23/100 [08:39<34:26, 26.84s/it, IoU=0.4510, F1=0.6042]Epoch 23: T-Loss: 5.8109 | V-Loss: 5.9838 | IoU: 0.4510 | F1: 0.6042 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  24%|██▍       | 24/100 [08:57<32:16, 25.47s/it, IoU=0.4172, F1=0.5706]Epoch 24: T-Loss: 5.8287 | V-Loss: 6.0202 | IoU: 0.4172 | F1: 0.5706
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  25%|██▌       | 25/100 [09:13<29:01, 23.22s/it, IoU=0.4558, F1=0.6068]Epoch 25: T-Loss: 5.7595 | V-Loss: 5.9397 | IoU: 0.4558 | F1: 0.6068 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  26%|██▌       | 26/100 [09:33<26:05, 21.16s/it, IoU=0.4507, F1=0.6026]Epoch 26: T-Loss: 5.7708 | V-Loss: 5.9448 | IoU: 0.4507 | F1: 0.6026
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  27%|██▋       | 27/100 [09:49<25:18, 20.81s/it, IoU=0.4485, F1=0.5994]Epoch 27: T-Loss: 5.7640 | V-Loss: 5.9107 | IoU: 0.4485 | F1: 0.5994
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  28%|██▊       | 28/100 [10:08<23:13, 19.35s/it, IoU=0.4415, F1=0.5914]Epoch 28: T-Loss: 5.7114 | V-Loss: 5.9356 | IoU: 0.4415 | F1: 0.5914
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  29%|██▉       | 29/100 [10:27<22:42, 19.19s/it, IoU=0.4581, F1=0.6082]Epoch 29: T-Loss: 5.7306 | V-Loss: 5.9302 | IoU: 0.4581 | F1: 0.6082 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  30%|███       | 30/100 [10:44<22:26, 19.23s/it, IoU=0.4262, F1=0.5776]Epoch 30: T-Loss: 5.7350 | V-Loss: 5.9244 | IoU: 0.4262 | F1: 0.5776
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  31%|███       | 31/100 [11:01<21:11, 18.43s/it, IoU=0.4540, F1=0.6052]Epoch 31: T-Loss: 5.7242 | V-Loss: 5.8876 | IoU: 0.4540 | F1: 0.6052
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  32%|███▏      | 32/100 [11:23<20:25, 18.03s/it, IoU=0.4421, F1=0.5947]Epoch 32: T-Loss: 5.7909 | V-Loss: 5.8693 | IoU: 0.4421 | F1: 0.5947
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  33%|███▎      | 33/100 [11:41<21:24, 19.17s/it, IoU=0.4507, F1=0.6027]Epoch 33: T-Loss: 5.7507 | V-Loss: 5.8555 | IoU: 0.4507 | F1: 0.6027
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  34%|███▍      | 34/100 [12:00<20:51, 18.96s/it, IoU=0.4256, F1=0.5777]Epoch 34: T-Loss: 5.7202 | V-Loss: 5.8988 | IoU: 0.4256 | F1: 0.5777
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  35%|███▌      | 35/100 [12:17<20:37, 19.03s/it, IoU=0.4377, F1=0.5888]Epoch 35: T-Loss: 5.7085 | V-Loss: 5.8798 | IoU: 0.4377 | F1: 0.5888
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  36%|███▌      | 36/100 [12:35<19:32, 18.32s/it, IoU=0.4621, F1=0.6122]Epoch 36: T-Loss: 5.7102 | V-Loss: 5.8769 | IoU: 0.4621 | F1: 0.6122 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  37%|███▋      | 37/100 [12:53<19:12, 18.30s/it, IoU=0.4605, F1=0.6102]Epoch 37: T-Loss: 5.6315 | V-Loss: 5.8742 | IoU: 0.4605 | F1: 0.6102
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  38%|███▊      | 38/100 [13:10<18:47, 18.19s/it, IoU=0.4511, F1=0.6025]Epoch 38: T-Loss: 5.6670 | V-Loss: 5.8753 | IoU: 0.4511 | F1: 0.6025

  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  39%|███▉      | 39/100 [13:25<18:03, 17.77s/it, IoU=0.4666, F1=0.6168]Epoch 39: T-Loss: 5.6730 | V-Loss: 5.8443 | IoU: 0.4666 | F1: 0.6168 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  40%|████      | 40/100 [13:43<17:06, 17.11s/it, IoU=0.4559, F1=0.6074]Epoch 40: T-Loss: 5.6377 | V-Loss: 5.8373 | IoU: 0.4559 | F1: 0.6074
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  41%|████      | 41/100 [14:02<16:54, 17.20s/it, IoU=0.4580, F1=0.6091]Epoch 41: T-Loss: 5.6618 | V-Loss: 5.8712 | IoU: 0.4580 | F1: 0.6091
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  42%|████▏     | 42/100 [14:21<17:04, 17.66s/it, IoU=0.4628, F1=0.6142]Epoch 42: T-Loss: 5.6370 | V-Loss: 5.8853 | IoU: 0.4628 | F1: 0.6142
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  43%|████▎     | 43/100 [14:36<17:11, 18.10s/it, IoU=0.4705, F1=0.6215]Epoch 43: T-Loss: 5.6384 | V-Loss: 5.8249 | IoU: 0.4705 | F1: 0.6215 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  44%|████▍     | 44/100 [14:50<16:06, 17.25s/it, IoU=0.4472, F1=0.6003]Epoch 44: T-Loss: 5.6073 | V-Loss: 5.8185 | IoU: 0.4472 | F1: 0.6003
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  45%|████▌     | 45/100 [15:05<15:02, 16.40s/it, IoU=0.4711, F1=0.6226]Epoch 45: T-Loss: 5.6291 | V-Loss: 5.8195 | IoU: 0.4711 | F1: 0.6226 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  46%|████▌     | 46/100 [15:21<14:25, 16.02s/it, IoU=0.4682, F1=0.6198]Epoch 46: T-Loss: 5.6044 | V-Loss: 5.8350 | IoU: 0.4682 | F1: 0.6198
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  47%|████▋     | 47/100 [15:40<13:55, 15.77s/it, IoU=0.4624, F1=0.6137]Epoch 47: T-Loss: 5.6128 | V-Loss: 5.8159 | IoU: 0.4624 | F1: 0.6137
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  48%|████▊     | 48/100 [15:56<14:35, 16.84s/it, IoU=0.4667, F1=0.6183]Epoch 48: T-Loss: 5.6234 | V-Loss: 5.8461 | IoU: 0.4667 | F1: 0.6183
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  49%|████▉     | 49/100 [16:17<13:58, 16.45s/it, IoU=0.4665, F1=0.6177]Epoch 49: T-Loss: 5.6401 | V-Loss: 5.8234 | IoU: 0.4665 | F1: 0.6177
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  50%|█████     | 50/100 [16:31<14:50, 17.82s/it, IoU=0.4734, F1=0.6242]Epoch 50: T-Loss: 5.6048 | V-Loss: 5.8426 | IoU: 0.4734 | F1: 0.6242 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  51%|█████     | 51/100 [16:45<13:41, 16.77s/it, IoU=0.4686, F1=0.6198]Epoch 51: T-Loss: 5.6096 | V-Loss: 5.8191 | IoU: 0.4686 | F1: 0.6198
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  52%|█████▏    | 52/100 [17:03<12:48, 16.00s/it, IoU=0.4705, F1=0.6215]Epoch 52: T-Loss: 5.5789 | V-Loss: 5.7833 | IoU: 0.4705 | F1: 0.6215
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  53%|█████▎    | 53/100 [17:20<13:05, 16.72s/it, IoU=0.4668, F1=0.6180]Epoch 53: T-Loss: 5.6063 | V-Loss: 5.8237 | IoU: 0.4668 | F1: 0.6180
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  54%|█████▍    | 54/100 [17:41<12:45, 16.64s/it, IoU=0.4727, F1=0.6233]Epoch 54: T-Loss: 5.6048 | V-Loss: 5.8299 | IoU: 0.4727 | F1: 0.6233
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  55%|█████▌    | 55/100 [17:59<13:22, 17.84s/it, IoU=0.4729, F1=0.6231]Epoch 55: T-Loss: 5.5425 | V-Loss: 5.8220 | IoU: 0.4729 | F1: 0.6231
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  56%|█████▌    | 56/100 [18:14<13:14, 18.05s/it, IoU=0.4756, F1=0.6259]Epoch 56: T-Loss: 5.5902 | V-Loss: 5.8213 | IoU: 0.4756 | F1: 0.6259 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  57%|█████▋    | 57/100 [18:29<12:12, 17.04s/it, IoU=0.4687, F1=0.6195]Epoch 57: T-Loss: 5.5515 | V-Loss: 5.8243 | IoU: 0.4687 | F1: 0.6195
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  58%|█████▊    | 58/100 [18:44<11:26, 16.35s/it, IoU=0.4748, F1=0.6248]Epoch 58: T-Loss: 5.5510 | V-Loss: 5.8044 | IoU: 0.4748 | F1: 0.6248
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  59%|█████▉    | 59/100 [19:00<11:00, 16.12s/it, IoU=0.4669, F1=0.6182]Epoch 59: T-Loss: 5.5590 | V-Loss: 5.8162 | IoU: 0.4669 | F1: 0.6182
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  60%|██████    | 60/100 [19:15<10:38, 15.95s/it, IoU=0.4722, F1=0.6229]Epoch 60: T-Loss: 5.5980 | V-Loss: 5.8036 | IoU: 0.4722 | F1: 0.6229
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  61%|██████    | 61/100 [19:29<10:09, 15.64s/it, IoU=0.4703, F1=0.6207]Epoch 61: T-Loss: 5.5838 | V-Loss: 5.8148 | IoU: 0.4703 | F1: 0.6207
  → FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  62%|██████▏   | 62/100 [19:44<09:39, 15.25s/it, IoU=0.4727, F1=0.6232]Epoch 62: T-Loss: 5.5959 | V-Loss: 5.8193 | IoU: 0.4727 | F1: 0.6232

============================================================
Early Stopping Triggered at Epoch 62
  - Best Validation Loss: 5.7833
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_fpn_efficientnet-b0.csv

Final results:
                                             Experiment  ...  Test_Prec
0  FPN-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct  ...   0.374789

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TB-to-TC_10pct --arch FPN --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_fpn_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TB-to-TC_10pct | arch=FPN | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 1028/1028 [00:00<00:00, 6702.24it/s]
Sanitizing Masks: 100%|██████████| 38/38 [00:00<00:00, 3932.00it/s]

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 50
 - Validation batches: 15
 - Testing batches: 3
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   0%|          | 0/100 [00:25<?, ?it/s, IoU=0.2907, F1=0.4225]Epoch 0: T-Loss: 7.4969 | V-Loss: 6.7007 | IoU: 0.2907 | F1: 0.4225 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   1%|          | 1/100 [00:43<43:05, 26.12s/it, IoU=0.3416, F1=0.4911]Epoch 1: T-Loss: 6.7884 | V-Loss: 6.4020 | IoU: 0.3416 | F1: 0.4911 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   2%|▏         | 2/100 [00:59<34:21, 21.03s/it, IoU=0.3556, F1=0.5090]Epoch 2: T-Loss: 6.5663 | V-Loss: 6.2493 | IoU: 0.3556 | F1: 0.5090 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   3%|▎         | 3/100 [01:22<30:20, 18.77s/it, IoU=0.3977, F1=0.5585]Epoch 3: T-Loss: 6.4656 | V-Loss: 6.2059 | IoU: 0.3977 | F1: 0.5585 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   4%|▍         | 4/100 [01:39<32:23, 20.25s/it, IoU=0.4126, F1=0.5724]Epoch 4: T-Loss: 6.3858 | V-Loss: 6.0750 | IoU: 0.4126 | F1: 0.5724 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   5%|▌         | 5/100 [01:57<30:22, 19.18s/it, IoU=0.4383, F1=0.5994]Epoch 5: T-Loss: 6.3036 | V-Loss: 6.0926 | IoU: 0.4383 | F1: 0.5994 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   6%|▌         | 6/100 [02:15<29:30, 18.83s/it, IoU=0.4466, F1=0.6066]Epoch 6: T-Loss: 6.2556 | V-Loss: 5.9979 | IoU: 0.4466 | F1: 0.6066 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   7%|▋         | 7/100 [02:34<28:41, 18.51s/it, IoU=0.4448, F1=0.6035]Epoch 7: T-Loss: 6.2151 | V-Loss: 5.9461 | IoU: 0.4448 | F1: 0.6035
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   8%|▊         | 8/100 [02:57<28:51, 18.82s/it, IoU=0.4408, F1=0.5999]Epoch 8: T-Loss: 6.1610 | V-Loss: 5.9222 | IoU: 0.4408 | F1: 0.5999
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   9%|▉         | 9/100 [03:18<30:04, 19.83s/it, IoU=0.4457, F1=0.6040]Epoch 9: T-Loss: 6.1607 | V-Loss: 5.9062 | IoU: 0.4457 | F1: 0.6040
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  10%|█         | 10/100 [03:50<30:35, 20.40s/it, IoU=0.4571, F1=0.6151]Epoch 10: T-Loss: 6.1121 | V-Loss: 5.9090 | IoU: 0.4571 | F1: 0.6151 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  11%|█         | 11/100 [04:09<35:23, 23.87s/it, IoU=0.4540, F1=0.6114]Epoch 11: T-Loss: 6.0877 | V-Loss: 5.9001 | IoU: 0.4540 | F1: 0.6114
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  12%|█▏        | 12/100 [04:29<32:49, 22.38s/it, IoU=0.4565, F1=0.6144]Epoch 12: T-Loss: 6.0520 | V-Loss: 5.8794 | IoU: 0.4565 | F1: 0.6144
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  13%|█▎        | 13/100 [04:48<31:23, 21.65s/it, IoU=0.4463, F1=0.6036]Epoch 13: T-Loss: 6.0243 | V-Loss: 5.8599 | IoU: 0.4463 | F1: 0.6036
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  14%|█▍        | 14/100 [05:09<30:06, 21.01s/it, IoU=0.4584, F1=0.6159]Epoch 14: T-Loss: 5.9955 | V-Loss: 5.8429 | IoU: 0.4584 | F1: 0.6159 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  15%|█▌        | 15/100 [05:27<29:40, 20.94s/it, IoU=0.4681, F1=0.6271]Epoch 15: T-Loss: 5.9995 | V-Loss: 5.8393 | IoU: 0.4681 | F1: 0.6271 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  16%|█▌        | 16/100 [05:46<28:02, 20.03s/it, IoU=0.4500, F1=0.6088]Epoch 16: T-Loss: 6.0191 | V-Loss: 5.8342 | IoU: 0.4500 | F1: 0.6088
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  17%|█▋        | 17/100 [06:05<27:18, 19.75s/it, IoU=0.4635, F1=0.6223]Epoch 17: T-Loss: 6.0091 | V-Loss: 5.8076 | IoU: 0.4635 | F1: 0.6223
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  18%|█▊        | 18/100 [06:22<26:43, 19.55s/it, IoU=0.4526, F1=0.6103]Epoch 18: T-Loss: 5.9759 | V-Loss: 5.8118 | IoU: 0.4526 | F1: 0.6103
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  19%|█▉        | 19/100 [06:40<25:26, 18.84s/it, IoU=0.4771, F1=0.6353]Epoch 19: T-Loss: 5.9217 | V-Loss: 5.7870 | IoU: 0.4771 | F1: 0.6353 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  20%|██        | 20/100 [07:02<24:37, 18.46s/it, IoU=0.4690, F1=0.6251]Epoch 20: T-Loss: 5.9087 | V-Loss: 5.8004 | IoU: 0.4690 | F1: 0.6251
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  21%|██        | 21/100 [07:24<25:38, 19.48s/it, IoU=0.4679, F1=0.6262]Epoch 21: T-Loss: 5.9174 | V-Loss: 5.7818 | IoU: 0.4679 | F1: 0.6262
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  22%|██▏       | 22/100 [07:44<26:19, 20.25s/it, IoU=0.4715, F1=0.6298]Epoch 22: T-Loss: 5.9103 | V-Loss: 5.7817 | IoU: 0.4715 | F1: 0.6298
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  23%|██▎       | 23/100 [08:00<25:44, 20.06s/it, IoU=0.4839, F1=0.6412]Epoch 23: T-Loss: 5.8873 | V-Loss: 5.7872 | IoU: 0.4839 | F1: 0.6412 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  24%|██▍       | 24/100 [08:22<24:14, 19.14s/it, IoU=0.4953, F1=0.6526]Epoch 24: T-Loss: 5.9155 | V-Loss: 5.7446 | IoU: 0.4953 | F1: 0.6526 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  25%|██▌       | 25/100 [08:40<24:57, 19.97s/it, IoU=0.4801, F1=0.6362]Epoch 25: T-Loss: 5.9032 | V-Loss: 5.7036 | IoU: 0.4801 | F1: 0.6362
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  26%|██▌       | 26/100 [08:58<23:54, 19.39s/it, IoU=0.4850, F1=0.6420]Epoch 26: T-Loss: 5.8714 | V-Loss: 5.7114 | IoU: 0.4850 | F1: 0.6420
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  27%|██▋       | 27/100 [09:18<22:49, 18.76s/it, IoU=0.4674, F1=0.6245]Epoch 27: T-Loss: 5.8732 | V-Loss: 5.7191 | IoU: 0.4674 | F1: 0.6245
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  28%|██▊       | 28/100 [09:38<23:06, 19.25s/it, IoU=0.4757, F1=0.6334]Epoch 28: T-Loss: 5.8314 | V-Loss: 5.7146 | IoU: 0.4757 | F1: 0.6334
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  29%|██▉       | 29/100 [09:55<22:53, 19.35s/it, IoU=0.4761, F1=0.6347]Epoch 29: T-Loss: 5.8264 | V-Loss: 5.7450 | IoU: 0.4761 | F1: 0.6347
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  30%|███       | 30/100 [10:14<21:40, 18.58s/it, IoU=0.4720, F1=0.6291]Epoch 30: T-Loss: 5.8029 | V-Loss: 5.7167 | IoU: 0.4720 | F1: 0.6291
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  31%|███       | 31/100 [10:34<21:40, 18.85s/it, IoU=0.4931, F1=0.6512]Epoch 31: T-Loss: 5.7993 | V-Loss: 5.7068 | IoU: 0.4931 | F1: 0.6512
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  32%|███▏      | 32/100 [10:56<21:51, 19.28s/it, IoU=0.4845, F1=0.6423]Epoch 32: T-Loss: 5.7941 | V-Loss: 5.7206 | IoU: 0.4845 | F1: 0.6423
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  33%|███▎      | 33/100 [11:15<22:25, 20.07s/it, IoU=0.4599, F1=0.6174]Epoch 33: T-Loss: 5.7968 | V-Loss: 5.7057 | IoU: 0.4599 | F1: 0.6174
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  34%|███▍      | 34/100 [11:36<21:32, 19.58s/it, IoU=0.4539, F1=0.6117]Epoch 34: T-Loss: 5.8242 | V-Loss: 5.7226 | IoU: 0.4539 | F1: 0.6117
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  35%|███▌      | 35/100 [12:00<21:50, 20.16s/it, IoU=0.5082, F1=0.6644]Epoch 35: T-Loss: 5.7997 | V-Loss: 5.6952 | IoU: 0.5082 | F1: 0.6644 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  36%|███▌      | 36/100 [12:21<22:50, 21.41s/it, IoU=0.4984, F1=0.6542]Epoch 36: T-Loss: 5.8135 | V-Loss: 5.6955 | IoU: 0.4984 | F1: 0.6542
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  37%|███▋      | 37/100 [12:41<22:17, 21.24s/it, IoU=0.4897, F1=0.6448]Epoch 37: T-Loss: 5.8235 | V-Loss: 5.7154 | IoU: 0.4897 | F1: 0.6448
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  38%|███▊      | 38/100 [13:05<21:28, 20.79s/it, IoU=0.4856, F1=0.6423]Epoch 38: T-Loss: 5.7600 | V-Loss: 5.6955 | IoU: 0.4856 | F1: 0.6423

  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  39%|███▉      | 39/100 [13:29<22:11, 21.83s/it, IoU=0.4827, F1=0.6364]Epoch 39: T-Loss: 5.7681 | V-Loss: 5.6844 | IoU: 0.4827 | F1: 0.6364
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  40%|████      | 40/100 [14:00<22:22, 22.37s/it, IoU=0.4995, F1=0.6536]Epoch 40: T-Loss: 5.8142 | V-Loss: 5.7203 | IoU: 0.4995 | F1: 0.6536
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  41%|████      | 41/100 [14:21<24:36, 25.03s/it, IoU=0.4956, F1=0.6497]Epoch 41: T-Loss: 5.7242 | V-Loss: 5.7157 | IoU: 0.4956 | F1: 0.6497
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  42%|████▏     | 42/100 [14:41<22:53, 23.68s/it, IoU=0.4915, F1=0.6482]Epoch 42: T-Loss: 5.7385 | V-Loss: 5.6975 | IoU: 0.4915 | F1: 0.6482
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  43%|████▎     | 43/100 [15:01<21:31, 22.66s/it, IoU=0.4864, F1=0.6420]Epoch 43: T-Loss: 5.7516 | V-Loss: 5.6766 | IoU: 0.4864 | F1: 0.6420
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  44%|████▍     | 44/100 [15:26<20:15, 21.71s/it, IoU=0.4993, F1=0.6566]Epoch 44: T-Loss: 5.7533 | V-Loss: 5.6966 | IoU: 0.4993 | F1: 0.6566
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  45%|████▌     | 45/100 [15:53<20:53, 22.79s/it, IoU=0.4954, F1=0.6506]Epoch 45: T-Loss: 5.7174 | V-Loss: 5.6880 | IoU: 0.4954 | F1: 0.6506
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  46%|████▌     | 46/100 [16:09<21:35, 23.99s/it, IoU=0.5037, F1=0.6593]Epoch 46: T-Loss: 5.7326 | V-Loss: 5.6968 | IoU: 0.5037 | F1: 0.6593
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  47%|████▋     | 47/100 [16:27<19:09, 21.68s/it, IoU=0.5112, F1=0.6659]Epoch 47: T-Loss: 5.7157 | V-Loss: 5.6853 | IoU: 0.5112 | F1: 0.6659 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  48%|████▊     | 48/100 [16:44<17:59, 20.76s/it, IoU=0.4974, F1=0.6526]Epoch 48: T-Loss: 5.6960 | V-Loss: 5.6580 | IoU: 0.4974 | F1: 0.6526
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  49%|████▉     | 49/100 [17:00<16:27, 19.35s/it, IoU=0.5133, F1=0.6689]Epoch 49: T-Loss: 5.7403 | V-Loss: 5.6856 | IoU: 0.5133 | F1: 0.6689 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  50%|█████     | 50/100 [17:19<15:32, 18.64s/it, IoU=0.4912, F1=0.6460]Epoch 50: T-Loss: 5.7071 | V-Loss: 5.6446 | IoU: 0.4912 | F1: 0.6460
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  51%|█████     | 51/100 [17:44<15:04, 18.45s/it, IoU=0.5138, F1=0.6685]Epoch 51: T-Loss: 5.7003 | V-Loss: 5.6655 | IoU: 0.5138 | F1: 0.6685 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  52%|█████▏    | 52/100 [18:03<16:20, 20.43s/it, IoU=0.5062, F1=0.6615]Epoch 52: T-Loss: 5.6732 | V-Loss: 5.6488 | IoU: 0.5062 | F1: 0.6615
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  53%|█████▎    | 53/100 [18:30<15:45, 20.12s/it, IoU=0.5065, F1=0.6619]Epoch 53: T-Loss: 5.7076 | V-Loss: 5.6444 | IoU: 0.5065 | F1: 0.6619
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  54%|█████▍    | 54/100 [18:56<17:06, 22.31s/it, IoU=0.5091, F1=0.6650]Epoch 54: T-Loss: 5.6868 | V-Loss: 5.6301 | IoU: 0.5091 | F1: 0.6650
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  55%|█████▌    | 55/100 [19:14<17:33, 23.41s/it, IoU=0.5058, F1=0.6608]Epoch 55: T-Loss: 5.7074 | V-Loss: 5.6588 | IoU: 0.5058 | F1: 0.6608
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  56%|█████▌    | 56/100 [19:49<15:52, 21.64s/it, IoU=0.5063, F1=0.6625]Epoch 56: T-Loss: 5.6802 | V-Loss: 5.6520 | IoU: 0.5063 | F1: 0.6625
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  57%|█████▋    | 57/100 [20:16<18:18, 25.55s/it, IoU=0.5112, F1=0.6662]Epoch 57: T-Loss: 5.6928 | V-Loss: 5.6540 | IoU: 0.5112 | F1: 0.6662
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  58%|█████▊    | 58/100 [20:33<18:17, 26.14s/it, IoU=0.5119, F1=0.6665]Epoch 58: T-Loss: 5.6672 | V-Loss: 5.6576 | IoU: 0.5119 | F1: 0.6665
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  59%|█████▉    | 59/100 [20:59<16:02, 23.46s/it, IoU=0.5148, F1=0.6701]Epoch 59: T-Loss: 5.6498 | V-Loss: 5.6639 | IoU: 0.5148 | F1: 0.6701 [Saved Best Model]
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  60%|██████    | 60/100 [21:19<16:10, 24.26s/it, IoU=0.5105, F1=0.6658]Epoch 60: T-Loss: 5.7047 | V-Loss: 5.6573 | IoU: 0.5105 | F1: 0.6658
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  61%|██████    | 61/100 [21:37<14:49, 22.80s/it, IoU=0.5062, F1=0.6614]Epoch 61: T-Loss: 5.6707 | V-Loss: 5.6481 | IoU: 0.5062 | F1: 0.6614
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  62%|██████▏   | 62/100 [21:57<13:29, 21.29s/it, IoU=0.5028, F1=0.6574]Epoch 62: T-Loss: 5.6510 | V-Loss: 5.6375 | IoU: 0.5028 | F1: 0.6574
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  63%|██████▎   | 63/100 [22:20<12:59, 21.07s/it, IoU=0.5051, F1=0.6608]Epoch 63: T-Loss: 5.6294 | V-Loss: 5.6600 | IoU: 0.5051 | F1: 0.6608
  → FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  64%|██████▍   | 64/100 [22:39<13:02, 21.73s/it, IoU=0.5110, F1=0.6660]Epoch 64: T-Loss: 5.6571 | V-Loss: 5.6895 | IoU: 0.5110 | F1: 0.6660

============================================================
Early Stopping Triggered at Epoch 64
  - Best Validation Loss: 5.6301
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_fpn_efficientnet-b0.csv

Final results:
                                             Experiment  ...  Test_Prec
0  FPN-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct  ...   0.427644

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Single-TB --arch DeepLabV3Plus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_deeplabv3plus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Single-TB | arch=DeepLabV3Plus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 424/424 [00:00<00:00, 14843.13it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 1982.32it/s]

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 20
 - Validation batches: 6
 - Testing batches: 3
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   0%|          | 0/100 [00:15<?, ?it/s, IoU=0.0029, F1=0.0058]Epoch 0: T-Loss: 10.5898 | V-Loss: 10.8229 | IoU: 0.0029 | F1: 0.0058 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   1%|          | 1/100 [00:22<25:27, 15.43s/it, IoU=0.0019, F1=0.0038]Epoch 1: T-Loss: 9.7683 | V-Loss: 10.2558 | IoU: 0.0019 | F1: 0.0038
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   2%|▏         | 2/100 [00:29<17:13, 10.55s/it, IoU=0.0004, F1=0.0009]Epoch 2: T-Loss: 8.9522 | V-Loss: 9.2768 | IoU: 0.0004 | F1: 0.0009
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   3%|▎         | 3/100 [00:37<14:42,  9.10s/it, IoU=0.0001, F1=0.0003]Epoch 3: T-Loss: 8.6193 | V-Loss: 8.7639 | IoU: 0.0001 | F1: 0.0003
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   4%|▍         | 4/100 [00:47<13:38,  8.52s/it, IoU=0.0000, F1=0.0000]Epoch 4: T-Loss: 8.4698 | V-Loss: 8.4616 | IoU: 0.0000 | F1: 0.0000
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   5%|▌         | 5/100 [00:54<14:10,  8.96s/it, IoU=0.0000, F1=0.0000]Epoch 5: T-Loss: 8.3784 | V-Loss: 8.2736 | IoU: 0.0000 | F1: 0.0000
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   6%|▌         | 6/100 [01:02<13:01,  8.32s/it, IoU=0.0036, F1=0.0070]Epoch 6: T-Loss: 8.2863 | V-Loss: 8.1809 | IoU: 0.0036 | F1: 0.0070 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   7%|▋         | 7/100 [01:11<13:02,  8.41s/it, IoU=0.0435, F1=0.0829]Epoch 7: T-Loss: 8.2250 | V-Loss: 8.0965 | IoU: 0.0435 | F1: 0.0829 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   8%|▊         | 8/100 [01:21<13:07,  8.56s/it, IoU=0.0739, F1=0.1321]Epoch 8: T-Loss: 8.1553 | V-Loss: 8.0351 | IoU: 0.0739 | F1: 0.1321 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:   9%|▉         | 9/100 [01:33<13:22,  8.81s/it, IoU=0.0660, F1=0.1209]Epoch 9: T-Loss: 8.0972 | V-Loss: 7.9767 | IoU: 0.0660 | F1: 0.1209
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  10%|█         | 10/100 [01:42<14:47,  9.87s/it, IoU=0.0883, F1=0.1585]Epoch 10: T-Loss: 8.0412 | V-Loss: 7.8860 | IoU: 0.0883 | F1: 0.1585 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  11%|█         | 11/100 [01:51<14:06,  9.51s/it, IoU=0.0726, F1=0.1330]Epoch 11: T-Loss: 7.9857 | V-Loss: 7.8468 | IoU: 0.0726 | F1: 0.1330
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  12%|█▏        | 12/100 [01:59<13:51,  9.45s/it, IoU=0.1009, F1=0.1784]Epoch 12: T-Loss: 7.9560 | V-Loss: 7.7523 | IoU: 0.1009 | F1: 0.1784 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  13%|█▎        | 13/100 [02:07<13:02,  8.99s/it, IoU=0.1048, F1=0.1839]Epoch 13: T-Loss: 7.8907 | V-Loss: 7.6484 | IoU: 0.1048 | F1: 0.1839 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  14%|█▍        | 14/100 [02:14<12:31,  8.74s/it, IoU=0.1073, F1=0.1879]Epoch 14: T-Loss: 7.8582 | V-Loss: 7.5792 | IoU: 0.1073 | F1: 0.1879 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  15%|█▌        | 15/100 [02:23<11:45,  8.31s/it, IoU=0.1267, F1=0.2170]Epoch 15: T-Loss: 7.7923 | V-Loss: 7.4944 | IoU: 0.1267 | F1: 0.2170 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  16%|█▌        | 16/100 [02:30<11:37,  8.30s/it, IoU=0.1811, F1=0.2956]Epoch 16: T-Loss: 7.7249 | V-Loss: 7.3395 | IoU: 0.1811 | F1: 0.2956 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  17%|█▋        | 17/100 [02:37<11:18,  8.17s/it, IoU=0.1467, F1=0.2492]Epoch 17: T-Loss: 7.6654 | V-Loss: 7.3168 | IoU: 0.1467 | F1: 0.2492
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  18%|█▊        | 18/100 [02:45<10:40,  7.81s/it, IoU=0.1844, F1=0.3024]Epoch 18: T-Loss: 7.6328 | V-Loss: 7.2079 | IoU: 0.1844 | F1: 0.3024 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  19%|█▉        | 19/100 [02:53<10:16,  7.61s/it, IoU=0.2022, F1=0.3258]Epoch 19: T-Loss: 7.5568 | V-Loss: 7.1499 | IoU: 0.2022 | F1: 0.3258 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  20%|██        | 20/100 [03:01<10:25,  7.82s/it, IoU=0.2022, F1=0.3256]Epoch 20: T-Loss: 7.4705 | V-Loss: 7.1297 | IoU: 0.2022 | F1: 0.3256
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  21%|██        | 21/100 [03:10<10:15,  7.79s/it, IoU=0.2185, F1=0.3483]Epoch 21: T-Loss: 7.4006 | V-Loss: 7.1056 | IoU: 0.2185 | F1: 0.3483 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  22%|██▏       | 22/100 [03:17<10:35,  8.14s/it, IoU=0.2253, F1=0.3568]Epoch 22: T-Loss: 7.3728 | V-Loss: 6.9711 | IoU: 0.2253 | F1: 0.3568 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  23%|██▎       | 23/100 [03:24<10:15,  7.99s/it, IoU=0.2380, F1=0.3716]Epoch 23: T-Loss: 7.2915 | V-Loss: 6.9155 | IoU: 0.2380 | F1: 0.3716 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  24%|██▍       | 24/100 [03:32<09:48,  7.75s/it, IoU=0.2289, F1=0.3596]Epoch 24: T-Loss: 7.1972 | V-Loss: 6.9051 | IoU: 0.2289 | F1: 0.3596
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  25%|██▌       | 25/100 [03:40<09:36,  7.69s/it, IoU=0.2418, F1=0.3793]Epoch 25: T-Loss: 7.1490 | V-Loss: 6.8395 | IoU: 0.2418 | F1: 0.3793 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  26%|██▌       | 26/100 [03:47<09:35,  7.78s/it, IoU=0.2576, F1=0.3927]Epoch 26: T-Loss: 7.1121 | V-Loss: 6.8341 | IoU: 0.2576 | F1: 0.3927 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  27%|██▋       | 27/100 [03:56<09:17,  7.63s/it, IoU=0.2687, F1=0.4103]Epoch 27: T-Loss: 7.0645 | V-Loss: 6.7434 | IoU: 0.2687 | F1: 0.4103 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  28%|██▊       | 28/100 [04:05<09:39,  8.05s/it, IoU=0.2530, F1=0.3963]Epoch 28: T-Loss: 7.0725 | V-Loss: 6.8033 | IoU: 0.2530 | F1: 0.3963
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  29%|██▉       | 29/100 [04:14<09:49,  8.30s/it, IoU=0.2579, F1=0.3985]Epoch 29: T-Loss: 6.9618 | V-Loss: 6.7228 | IoU: 0.2579 | F1: 0.3985
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  30%|███       | 30/100 [04:24<09:57,  8.54s/it, IoU=0.2714, F1=0.4138]Epoch 30: T-Loss: 6.8916 | V-Loss: 6.6839 | IoU: 0.2714 | F1: 0.4138 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  31%|███       | 31/100 [04:33<10:18,  8.96s/it, IoU=0.2847, F1=0.4283]Epoch 31: T-Loss: 6.9364 | V-Loss: 6.6522 | IoU: 0.2847 | F1: 0.4283 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  32%|███▏      | 32/100 [04:43<10:14,  9.04s/it, IoU=0.2726, F1=0.4168]Epoch 32: T-Loss: 6.8283 | V-Loss: 6.6968 | IoU: 0.2726 | F1: 0.4168
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  33%|███▎      | 33/100 [04:52<10:10,  9.11s/it, IoU=0.2964, F1=0.4428]Epoch 33: T-Loss: 6.8111 | V-Loss: 6.5876 | IoU: 0.2964 | F1: 0.4428 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  34%|███▍      | 34/100 [05:01<10:00,  9.10s/it, IoU=0.2997, F1=0.4479]Epoch 34: T-Loss: 6.7349 | V-Loss: 6.5515 | IoU: 0.2997 | F1: 0.4479 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  35%|███▌      | 35/100 [05:10<10:01,  9.26s/it, IoU=0.2929, F1=0.4408]Epoch 35: T-Loss: 6.6928 | V-Loss: 6.5678 | IoU: 0.2929 | F1: 0.4408
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  36%|███▌      | 36/100 [05:17<09:35,  8.99s/it, IoU=0.2864, F1=0.4312]Epoch 36: T-Loss: 6.7561 | V-Loss: 6.5739 | IoU: 0.2864 | F1: 0.4312
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  37%|███▋      | 37/100 [05:26<08:54,  8.48s/it, IoU=0.2845, F1=0.4295]Epoch 37: T-Loss: 6.6993 | V-Loss: 6.5286 | IoU: 0.2845 | F1: 0.4295
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  38%|███▊      | 38/100 [05:39<09:01,  8.73s/it, IoU=0.2942, F1=0.4429]Epoch 38: T-Loss: 6.7108 | V-Loss: 6.4959 | IoU: 0.2942 | F1: 0.4429

  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  39%|███▉      | 39/100 [05:47<09:54,  9.75s/it, IoU=0.3016, F1=0.4520]Epoch 39: T-Loss: 6.6021 | V-Loss: 6.4782 | IoU: 0.3016 | F1: 0.4520 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  40%|████      | 40/100 [05:54<09:23,  9.38s/it, IoU=0.2941, F1=0.4412]Epoch 40: T-Loss: 6.6107 | V-Loss: 6.4334 | IoU: 0.2941 | F1: 0.4412
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  41%|████      | 41/100 [06:02<08:33,  8.71s/it, IoU=0.3011, F1=0.4504]Epoch 41: T-Loss: 6.5966 | V-Loss: 6.4209 | IoU: 0.3011 | F1: 0.4504
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  42%|████▏     | 42/100 [06:10<08:10,  8.46s/it, IoU=0.3120, F1=0.4631]Epoch 42: T-Loss: 6.5969 | V-Loss: 6.3771 | IoU: 0.3120 | F1: 0.4631 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  43%|████▎     | 43/100 [06:17<07:55,  8.34s/it, IoU=0.2984, F1=0.4469]Epoch 43: T-Loss: 6.5530 | V-Loss: 6.3866 | IoU: 0.2984 | F1: 0.4469
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  44%|████▍     | 44/100 [06:24<07:26,  7.97s/it, IoU=0.3169, F1=0.4688]Epoch 44: T-Loss: 6.5049 | V-Loss: 6.3932 | IoU: 0.3169 | F1: 0.4688 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  45%|████▌     | 45/100 [06:32<07:07,  7.77s/it, IoU=0.3186, F1=0.4725]Epoch 45: T-Loss: 6.5271 | V-Loss: 6.3696 | IoU: 0.3186 | F1: 0.4725 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  46%|████▌     | 46/100 [06:40<06:55,  7.70s/it, IoU=0.3080, F1=0.4601]Epoch 46: T-Loss: 6.4803 | V-Loss: 6.3660 | IoU: 0.3080 | F1: 0.4601
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  47%|████▋     | 47/100 [06:47<06:53,  7.80s/it, IoU=0.3112, F1=0.4646]Epoch 47: T-Loss: 6.4824 | V-Loss: 6.3489 | IoU: 0.3112 | F1: 0.4646
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  48%|████▊     | 48/100 [06:54<06:32,  7.55s/it, IoU=0.3060, F1=0.4571]Epoch 48: T-Loss: 6.5067 | V-Loss: 6.3229 | IoU: 0.3060 | F1: 0.4571
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  49%|████▉     | 49/100 [07:01<06:15,  7.37s/it, IoU=0.3036, F1=0.4554]Epoch 49: T-Loss: 6.5123 | V-Loss: 6.3399 | IoU: 0.3036 | F1: 0.4554
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  50%|█████     | 50/100 [07:08<06:09,  7.38s/it, IoU=0.2920, F1=0.4401]Epoch 50: T-Loss: 6.5210 | V-Loss: 6.3481 | IoU: 0.2920 | F1: 0.4401
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  51%|█████     | 51/100 [07:16<05:55,  7.26s/it, IoU=0.2960, F1=0.4446]Epoch 51: T-Loss: 6.4214 | V-Loss: 6.3566 | IoU: 0.2960 | F1: 0.4446
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  52%|█████▏    | 52/100 [07:23<05:52,  7.34s/it, IoU=0.2952, F1=0.4437]Epoch 52: T-Loss: 6.4410 | V-Loss: 6.3484 | IoU: 0.2952 | F1: 0.4437
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  53%|█████▎    | 53/100 [07:32<05:41,  7.28s/it, IoU=0.2987, F1=0.4490]Epoch 53: T-Loss: 6.5361 | V-Loss: 6.3494 | IoU: 0.2987 | F1: 0.4490
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  54%|█████▍    | 54/100 [07:40<05:59,  7.81s/it, IoU=0.3030, F1=0.4556]Epoch 54: T-Loss: 6.3937 | V-Loss: 6.3275 | IoU: 0.3030 | F1: 0.4556
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  55%|█████▌    | 55/100 [07:49<05:45,  7.69s/it, IoU=0.2980, F1=0.4477]Epoch 55: T-Loss: 6.4412 | V-Loss: 6.3393 | IoU: 0.2980 | F1: 0.4477
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  56%|█████▌    | 56/100 [07:59<06:02,  8.24s/it, IoU=0.3054, F1=0.4580]Epoch 56: T-Loss: 6.4003 | V-Loss: 6.3365 | IoU: 0.3054 | F1: 0.4580
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  57%|█████▋    | 57/100 [08:10<06:12,  8.67s/it, IoU=0.3145, F1=0.4686]Epoch 57: T-Loss: 6.3371 | V-Loss: 6.3174 | IoU: 0.3145 | F1: 0.4686
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  58%|█████▊    | 58/100 [08:20<06:36,  9.44s/it, IoU=0.3032, F1=0.4558]Epoch 58: T-Loss: 6.3905 | V-Loss: 6.3092 | IoU: 0.3032 | F1: 0.4558
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  59%|█████▉    | 59/100 [08:31<06:36,  9.67s/it, IoU=0.2990, F1=0.4507]Epoch 59: T-Loss: 6.3982 | V-Loss: 6.2851 | IoU: 0.2990 | F1: 0.4507
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  60%|██████    | 60/100 [08:41<06:43, 10.09s/it, IoU=0.3024, F1=0.4523]Epoch 60: T-Loss: 6.4022 | V-Loss: 6.3264 | IoU: 0.3024 | F1: 0.4523
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  61%|██████    | 61/100 [08:54<06:34, 10.12s/it, IoU=0.3073, F1=0.4579]Epoch 61: T-Loss: 6.3978 | V-Loss: 6.3135 | IoU: 0.3073 | F1: 0.4579
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  62%|██████▏   | 62/100 [09:07<06:55, 10.94s/it, IoU=0.3181, F1=0.4717]Epoch 62: T-Loss: 6.3669 | V-Loss: 6.2923 | IoU: 0.3181 | F1: 0.4717
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  63%|██████▎   | 63/100 [09:17<07:08, 11.59s/it, IoU=0.3205, F1=0.4736]Epoch 63: T-Loss: 6.4268 | V-Loss: 6.2902 | IoU: 0.3205 | F1: 0.4736 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  64%|██████▍   | 64/100 [09:29<06:37, 11.03s/it, IoU=0.3114, F1=0.4627]Epoch 64: T-Loss: 6.3282 | V-Loss: 6.3123 | IoU: 0.3114 | F1: 0.4627
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  65%|██████▌   | 65/100 [09:39<06:33, 11.24s/it, IoU=0.3090, F1=0.4596]Epoch 65: T-Loss: 6.4139 | V-Loss: 6.3035 | IoU: 0.3090 | F1: 0.4596
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  66%|██████▌   | 66/100 [09:50<06:14, 11.03s/it, IoU=0.3155, F1=0.4672]Epoch 66: T-Loss: 6.3722 | V-Loss: 6.2691 | IoU: 0.3155 | F1: 0.4672
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  67%|██████▋   | 67/100 [10:00<06:00, 10.92s/it, IoU=0.3166, F1=0.4684]Epoch 67: T-Loss: 6.3137 | V-Loss: 6.2807 | IoU: 0.3166 | F1: 0.4684
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  68%|██████▊   | 68/100 [10:11<05:41, 10.68s/it, IoU=0.3192, F1=0.4713]Epoch 68: T-Loss: 6.3668 | V-Loss: 6.2674 | IoU: 0.3192 | F1: 0.4713
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  69%|██████▉   | 69/100 [10:22<05:29, 10.62s/it, IoU=0.3165, F1=0.4682]Epoch 69: T-Loss: 6.3579 | V-Loss: 6.2669 | IoU: 0.3165 | F1: 0.4682
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  70%|███████   | 70/100 [10:31<05:23, 10.79s/it, IoU=0.3108, F1=0.4604]Epoch 70: T-Loss: 6.3246 | V-Loss: 6.2909 | IoU: 0.3108 | F1: 0.4604
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  71%|███████   | 71/100 [10:39<04:57, 10.24s/it, IoU=0.3151, F1=0.4663]Epoch 71: T-Loss: 6.3401 | V-Loss: 6.2974 | IoU: 0.3151 | F1: 0.4663
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  72%|███████▏  | 72/100 [10:46<04:26,  9.53s/it, IoU=0.3116, F1=0.4624]Epoch 72: T-Loss: 6.3256 | V-Loss: 6.2933 | IoU: 0.3116 | F1: 0.4624
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  73%|███████▎  | 73/100 [10:56<03:58,  8.84s/it, IoU=0.3106, F1=0.4612]Epoch 73: T-Loss: 6.3282 | V-Loss: 6.3002 | IoU: 0.3106 | F1: 0.4612
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  74%|███████▍  | 74/100 [11:07<03:57,  9.12s/it, IoU=0.3075, F1=0.4569]Epoch 74: T-Loss: 6.3010 | V-Loss: 6.2869 | IoU: 0.3075 | F1: 0.4569
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  75%|███████▌  | 75/100 [11:18<04:06,  9.87s/it, IoU=0.3030, F1=0.4512]Epoch 75: T-Loss: 6.3654 | V-Loss: 6.2809 | IoU: 0.3030 | F1: 0.4512
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  76%|███████▌  | 76/100 [11:29<04:06, 10.26s/it, IoU=0.3055, F1=0.4547]Epoch 76: T-Loss: 6.2926 | V-Loss: 6.2811 | IoU: 0.3055 | F1: 0.4547
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  77%|███████▋  | 77/100 [11:38<03:54, 10.20s/it, IoU=0.3086, F1=0.4582]Epoch 77: T-Loss: 6.2689 | V-Loss: 6.2851 | IoU: 0.3086 | F1: 0.4582
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  78%|███████▊  | 78/100 [11:50<03:40, 10.01s/it, IoU=0.3081, F1=0.4580]Epoch 78: T-Loss: 6.2946 | V-Loss: 6.2800 | IoU: 0.3081 | F1: 0.4580
  → DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB:  79%|███████▉  | 79/100 [12:01<03:41, 10.55s/it, IoU=0.3104, F1=0.4613]Epoch 79: T-Loss: 6.3023 | V-Loss: 6.2741 | IoU: 0.3104 | F1: 0.4613

============================================================
Early Stopping Triggered at Epoch 79
  - Best Validation Loss: 6.2669
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================

Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_deeplabv3plus_efficientnet-b0.csv

Final results:
                                         Experiment  ...  Test_Prec
0  DeepLabV3Plus-efficientnet-b0-imagenet_Single-TB  ...   0.356652

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TC-to-TB_10pct --arch DeepLabV3Plus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_deeplabv3plus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TC-to-TB_10pct | arch=DeepLabV3Plus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 936/936 [00:00<00:00, 14825.06it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 13758.39it/s]

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 45
 - Validation batches: 13
 - Testing batches: 3
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   0%|          | 0/100 [00:35<?, ?it/s, IoU=0.0867, F1=0.1555]Epoch 0: T-Loss: 10.0734 | V-Loss: 9.9840 | IoU: 0.0867 | F1: 0.1555 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   1%|          | 1/100 [01:02<59:11, 35.88s/it, IoU=0.1020, F1=0.1801]Epoch 1: T-Loss: 8.6208 | V-Loss: 8.5636 | IoU: 0.1020 | F1: 0.1801 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   2%|▏         | 2/100 [01:30<49:24, 30.25s/it, IoU=0.1445, F1=0.2423]Epoch 2: T-Loss: 8.1929 | V-Loss: 7.9415 | IoU: 0.1445 | F1: 0.2423 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   3%|▎         | 3/100 [02:02<47:47, 29.56s/it, IoU=0.2301, F1=0.3574]Epoch 3: T-Loss: 7.8106 | V-Loss: 7.5787 | IoU: 0.2301 | F1: 0.3574 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   4%|▍         | 4/100 [02:26<48:56, 30.59s/it, IoU=0.2633, F1=0.3974]Epoch 4: T-Loss: 7.4897 | V-Loss: 7.3095 | IoU: 0.2633 | F1: 0.3974 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   5%|▌         | 5/100 [02:54<44:32, 28.14s/it, IoU=0.3240, F1=0.4697]Epoch 5: T-Loss: 7.2676 | V-Loss: 7.1378 | IoU: 0.3240 | F1: 0.4697 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   6%|▌         | 6/100 [03:13<44:07, 28.16s/it, IoU=0.3363, F1=0.4816]Epoch 6: T-Loss: 6.9912 | V-Loss: 7.0903 | IoU: 0.3363 | F1: 0.4816 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   7%|▋         | 7/100 [03:32<38:48, 25.03s/it, IoU=0.3663, F1=0.5134]Epoch 7: T-Loss: 6.8110 | V-Loss: 6.9358 | IoU: 0.3663 | F1: 0.5134 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   8%|▊         | 8/100 [03:50<35:36, 23.22s/it, IoU=0.3569, F1=0.5022]Epoch 8: T-Loss: 6.6804 | V-Loss: 6.8743 | IoU: 0.3569 | F1: 0.5022
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   9%|▉         | 9/100 [04:16<32:34, 21.48s/it, IoU=0.3820, F1=0.5325]Epoch 9: T-Loss: 6.5628 | V-Loss: 6.6576 | IoU: 0.3820 | F1: 0.5325 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  10%|█         | 10/100 [04:37<34:14, 22.83s/it, IoU=0.3447, F1=0.4944]Epoch 10: T-Loss: 6.4465 | V-Loss: 6.5679 | IoU: 0.3447 | F1: 0.4944
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  11%|█         | 11/100 [04:57<32:48, 22.12s/it, IoU=0.3689, F1=0.5194]Epoch 11: T-Loss: 6.3059 | V-Loss: 6.4516 | IoU: 0.3689 | F1: 0.5194
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  12%|█▏        | 12/100 [05:20<31:29, 21.47s/it, IoU=0.3498, F1=0.4986]Epoch 12: T-Loss: 6.2746 | V-Loss: 6.3952 | IoU: 0.3498 | F1: 0.4986
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  13%|█▎        | 13/100 [05:39<32:01, 22.09s/it, IoU=0.3479, F1=0.4963]Epoch 13: T-Loss: 6.3069 | V-Loss: 6.2739 | IoU: 0.3479 | F1: 0.4963
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  14%|█▍        | 14/100 [05:55<30:11, 21.06s/it, IoU=0.3803, F1=0.5327]Epoch 14: T-Loss: 6.1996 | V-Loss: 6.2824 | IoU: 0.3803 | F1: 0.5327
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  15%|█▌        | 15/100 [06:14<27:47, 19.62s/it, IoU=0.3693, F1=0.5197]Epoch 15: T-Loss: 6.1182 | V-Loss: 6.2460 | IoU: 0.3693 | F1: 0.5197
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  16%|█▌        | 16/100 [06:31<27:12, 19.44s/it, IoU=0.3951, F1=0.5463]Epoch 16: T-Loss: 6.0958 | V-Loss: 6.1707 | IoU: 0.3951 | F1: 0.5463 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  17%|█▋        | 17/100 [06:48<25:57, 18.77s/it, IoU=0.4116, F1=0.5636]Epoch 17: T-Loss: 6.0352 | V-Loss: 6.1431 | IoU: 0.4116 | F1: 0.5636 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  18%|█▊        | 18/100 [07:07<24:59, 18.28s/it, IoU=0.4043, F1=0.5560]Epoch 18: T-Loss: 6.0036 | V-Loss: 6.1216 | IoU: 0.4043 | F1: 0.5560
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  19%|█▉        | 19/100 [07:29<24:40, 18.28s/it, IoU=0.3921, F1=0.5449]Epoch 19: T-Loss: 5.9963 | V-Loss: 6.0606 | IoU: 0.3921 | F1: 0.5449
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  20%|██        | 20/100 [07:47<26:05, 19.57s/it, IoU=0.3983, F1=0.5532]Epoch 20: T-Loss: 5.9400 | V-Loss: 6.0960 | IoU: 0.3983 | F1: 0.5532
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  21%|██        | 21/100 [08:09<25:01, 19.01s/it, IoU=0.4153, F1=0.5685]Epoch 21: T-Loss: 5.9358 | V-Loss: 6.0400 | IoU: 0.4153 | F1: 0.5685 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  22%|██▏       | 22/100 [08:32<26:00, 20.01s/it, IoU=0.4045, F1=0.5567]Epoch 22: T-Loss: 5.9367 | V-Loss: 5.9978 | IoU: 0.4045 | F1: 0.5567
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  23%|██▎       | 23/100 [09:02<26:37, 20.74s/it, IoU=0.4093, F1=0.5610]Epoch 23: T-Loss: 5.9110 | V-Loss: 6.0535 | IoU: 0.4093 | F1: 0.5610
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  24%|██▍       | 24/100 [09:33<29:55, 23.63s/it, IoU=0.3854, F1=0.5361]Epoch 24: T-Loss: 5.9029 | V-Loss: 6.0530 | IoU: 0.3854 | F1: 0.5361
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  25%|██▌       | 25/100 [10:04<32:07, 25.70s/it, IoU=0.3940, F1=0.5419]Epoch 25: T-Loss: 5.8651 | V-Loss: 6.0394 | IoU: 0.3940 | F1: 0.5419
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  26%|██▌       | 26/100 [10:34<33:45, 27.37s/it, IoU=0.4211, F1=0.5715]Epoch 26: T-Loss: 5.8812 | V-Loss: 5.9700 | IoU: 0.4211 | F1: 0.5715 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  27%|██▋       | 27/100 [11:07<34:24, 28.29s/it, IoU=0.4165, F1=0.5674]Epoch 27: T-Loss: 5.8824 | V-Loss: 5.9754 | IoU: 0.4165 | F1: 0.5674
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  28%|██▊       | 28/100 [11:35<35:28, 29.56s/it, IoU=0.4088, F1=0.5599]Epoch 28: T-Loss: 5.8431 | V-Loss: 5.9705 | IoU: 0.4088 | F1: 0.5599
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  29%|██▉       | 29/100 [12:01<34:26, 29.11s/it, IoU=0.4234, F1=0.5738]Epoch 29: T-Loss: 5.8525 | V-Loss: 5.9743 | IoU: 0.4234 | F1: 0.5738 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  30%|███       | 30/100 [12:36<33:05, 28.37s/it, IoU=0.4139, F1=0.5642]Epoch 30: T-Loss: 5.8302 | V-Loss: 5.9717 | IoU: 0.4139 | F1: 0.5642
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  31%|███       | 31/100 [13:12<34:34, 30.06s/it, IoU=0.4060, F1=0.5548]Epoch 31: T-Loss: 5.8073 | V-Loss: 5.9905 | IoU: 0.4060 | F1: 0.5548
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  32%|███▏      | 32/100 [13:44<36:10, 31.91s/it, IoU=0.3868, F1=0.5353]Epoch 32: T-Loss: 5.7872 | V-Loss: 5.9812 | IoU: 0.3868 | F1: 0.5353
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  33%|███▎      | 33/100 [14:12<35:51, 32.12s/it, IoU=0.4138, F1=0.5627]Epoch 33: T-Loss: 5.7813 | V-Loss: 5.9500 | IoU: 0.4138 | F1: 0.5627
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  34%|███▍      | 34/100 [14:31<33:46, 30.70s/it, IoU=0.4277, F1=0.5763]Epoch 34: T-Loss: 5.7716 | V-Loss: 5.9592 | IoU: 0.4277 | F1: 0.5763 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  35%|███▌      | 35/100 [14:54<29:41, 27.41s/it, IoU=0.4162, F1=0.5662]Epoch 35: T-Loss: 5.7781 | V-Loss: 5.9386 | IoU: 0.4162 | F1: 0.5662
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  36%|███▌      | 36/100 [15:20<27:35, 25.87s/it, IoU=0.4193, F1=0.5704]Epoch 36: T-Loss: 5.7842 | V-Loss: 5.9443 | IoU: 0.4193 | F1: 0.5704

  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  37%|███▋      | 37/100 [16:07<27:07, 25.84s/it, IoU=0.4060, F1=0.5558]Epoch 37: T-Loss: 5.7811 | V-Loss: 5.9618 | IoU: 0.4060 | F1: 0.5558
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  38%|███▊      | 38/100 [16:37<33:28, 32.39s/it, IoU=0.4111, F1=0.5597]Epoch 38: T-Loss: 5.7491 | V-Loss: 5.9149 | IoU: 0.4111 | F1: 0.5597
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  39%|███▉      | 39/100 [17:00<32:16, 31.75s/it, IoU=0.4202, F1=0.5701]Epoch 39: T-Loss: 5.7449 | V-Loss: 5.9092 | IoU: 0.4202 | F1: 0.5701
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  40%|████      | 40/100 [17:47<28:55, 28.93s/it, IoU=0.4280, F1=0.5783]Epoch 40: T-Loss: 5.7460 | V-Loss: 5.9002 | IoU: 0.4280 | F1: 0.5783 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  41%|████      | 41/100 [18:17<33:46, 34.35s/it, IoU=0.4492, F1=0.5993]Epoch 41: T-Loss: 5.6861 | V-Loss: 5.8915 | IoU: 0.4492 | F1: 0.5993 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  42%|████▏     | 42/100 [18:40<31:56, 33.05s/it, IoU=0.4319, F1=0.5818]Epoch 42: T-Loss: 5.7079 | V-Loss: 5.8989 | IoU: 0.4319 | F1: 0.5818
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  43%|████▎     | 43/100 [19:01<28:36, 30.11s/it, IoU=0.4335, F1=0.5831]Epoch 43: T-Loss: 5.7617 | V-Loss: 5.9051 | IoU: 0.4335 | F1: 0.5831
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  44%|████▍     | 44/100 [19:26<25:33, 27.39s/it, IoU=0.4298, F1=0.5809]Epoch 44: T-Loss: 5.7561 | V-Loss: 5.9048 | IoU: 0.4298 | F1: 0.5809
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  45%|████▌     | 45/100 [19:55<24:16, 26.49s/it, IoU=0.4347, F1=0.5826]Epoch 45: T-Loss: 5.7362 | V-Loss: 5.8899 | IoU: 0.4347 | F1: 0.5826
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  46%|████▌     | 46/100 [20:27<24:44, 27.49s/it, IoU=0.4191, F1=0.5645]Epoch 46: T-Loss: 5.6823 | V-Loss: 5.9190 | IoU: 0.4191 | F1: 0.5645
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  47%|████▋     | 47/100 [20:52<25:22, 28.74s/it, IoU=0.4473, F1=0.5954]Epoch 47: T-Loss: 5.7152 | V-Loss: 5.9222 | IoU: 0.4473 | F1: 0.5954
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  48%|████▊     | 48/100 [21:15<23:49, 27.48s/it, IoU=0.4364, F1=0.5851]Epoch 48: T-Loss: 5.7281 | V-Loss: 5.8858 | IoU: 0.4364 | F1: 0.5851
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  49%|████▉     | 49/100 [21:43<22:21, 26.31s/it, IoU=0.4319, F1=0.5827]Epoch 49: T-Loss: 5.6950 | V-Loss: 5.9063 | IoU: 0.4319 | F1: 0.5827
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  50%|█████     | 50/100 [22:11<22:14, 26.69s/it, IoU=0.4481, F1=0.5978]Epoch 50: T-Loss: 5.6595 | V-Loss: 5.8914 | IoU: 0.4481 | F1: 0.5978
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  51%|█████     | 51/100 [22:34<22:09, 27.13s/it, IoU=0.4374, F1=0.5862]Epoch 51: T-Loss: 5.6780 | V-Loss: 5.8783 | IoU: 0.4374 | F1: 0.5862
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  52%|█████▏    | 52/100 [23:04<20:51, 26.07s/it, IoU=0.4260, F1=0.5758]Epoch 52: T-Loss: 5.6237 | V-Loss: 5.9004 | IoU: 0.4260 | F1: 0.5758
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  53%|█████▎    | 53/100 [23:30<21:17, 27.17s/it, IoU=0.4406, F1=0.5884]Epoch 53: T-Loss: 5.6355 | V-Loss: 5.8708 | IoU: 0.4406 | F1: 0.5884
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  54%|█████▍    | 54/100 [23:55<20:24, 26.62s/it, IoU=0.4429, F1=0.5916]Epoch 54: T-Loss: 5.6876 | V-Loss: 5.8605 | IoU: 0.4429 | F1: 0.5916
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  55%|█████▌    | 55/100 [24:19<19:40, 26.24s/it, IoU=0.4436, F1=0.5938]Epoch 55: T-Loss: 5.6590 | V-Loss: 5.8555 | IoU: 0.4436 | F1: 0.5938
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  56%|█████▌    | 56/100 [24:43<18:46, 25.60s/it, IoU=0.4438, F1=0.5923]Epoch 56: T-Loss: 5.7075 | V-Loss: 5.8529 | IoU: 0.4438 | F1: 0.5923
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  57%|█████▋    | 57/100 [25:09<18:04, 25.22s/it, IoU=0.4263, F1=0.5750]Epoch 57: T-Loss: 5.6607 | V-Loss: 5.8586 | IoU: 0.4263 | F1: 0.5750
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  58%|█████▊    | 58/100 [25:33<17:40, 25.24s/it, IoU=0.4399, F1=0.5882]Epoch 58: T-Loss: 5.6165 | V-Loss: 5.8580 | IoU: 0.4399 | F1: 0.5882
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  59%|█████▉    | 59/100 [25:56<17:01, 24.91s/it, IoU=0.4454, F1=0.5939]Epoch 59: T-Loss: 5.6825 | V-Loss: 5.8643 | IoU: 0.4454 | F1: 0.5939
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  60%|██████    | 60/100 [26:20<16:13, 24.33s/it, IoU=0.4457, F1=0.5946]Epoch 60: T-Loss: 5.6530 | V-Loss: 5.8540 | IoU: 0.4457 | F1: 0.5946
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  61%|██████    | 61/100 [26:42<15:46, 24.28s/it, IoU=0.4425, F1=0.5904]Epoch 61: T-Loss: 5.6608 | V-Loss: 5.8464 | IoU: 0.4425 | F1: 0.5904
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  62%|██████▏   | 62/100 [27:04<14:57, 23.62s/it, IoU=0.4487, F1=0.5982]Epoch 62: T-Loss: 5.6328 | V-Loss: 5.8385 | IoU: 0.4487 | F1: 0.5982
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  63%|██████▎   | 63/100 [27:27<14:12, 23.05s/it, IoU=0.4412, F1=0.5893]Epoch 63: T-Loss: 5.6280 | V-Loss: 5.8598 | IoU: 0.4412 | F1: 0.5893
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  64%|██████▍   | 64/100 [27:56<13:55, 23.22s/it, IoU=0.4389, F1=0.5891]Epoch 64: T-Loss: 5.5986 | V-Loss: 5.8597 | IoU: 0.4389 | F1: 0.5891
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  65%|██████▌   | 65/100 [28:21<14:28, 24.82s/it, IoU=0.4463, F1=0.5956]Epoch 65: T-Loss: 5.6136 | V-Loss: 5.8528 | IoU: 0.4463 | F1: 0.5956
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  66%|██████▌   | 66/100 [28:46<14:11, 25.04s/it, IoU=0.4435, F1=0.5931]Epoch 66: T-Loss: 5.6182 | V-Loss: 5.8469 | IoU: 0.4435 | F1: 0.5931
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  67%|██████▋   | 67/100 [29:08<13:44, 24.97s/it, IoU=0.4414, F1=0.5914]Epoch 67: T-Loss: 5.6324 | V-Loss: 5.8484 | IoU: 0.4414 | F1: 0.5914
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  68%|██████▊   | 68/100 [29:30<12:48, 24.02s/it, IoU=0.4530, F1=0.6016]Epoch 68: T-Loss: 5.5815 | V-Loss: 5.8431 | IoU: 0.4530 | F1: 0.6016 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  69%|██████▉   | 69/100 [29:55<12:03, 23.34s/it, IoU=0.4549, F1=0.6049]Epoch 69: T-Loss: 5.5571 | V-Loss: 5.8521 | IoU: 0.4549 | F1: 0.6049 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  70%|███████   | 70/100 [30:21<11:59, 23.97s/it, IoU=0.4156, F1=0.5654]Epoch 70: T-Loss: 5.6328 | V-Loss: 5.8254 | IoU: 0.4156 | F1: 0.5654
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  71%|███████   | 71/100 [30:43<11:54, 24.63s/it, IoU=0.4449, F1=0.5943]Epoch 71: T-Loss: 5.6507 | V-Loss: 5.8384 | IoU: 0.4449 | F1: 0.5943
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  72%|███████▏  | 72/100 [31:11<11:02, 23.66s/it, IoU=0.4577, F1=0.6066]Epoch 72: T-Loss: 5.6166 | V-Loss: 5.8386 | IoU: 0.4577 | F1: 0.6066 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  73%|███████▎  | 73/100 [31:32<11:14, 24.98s/it, IoU=0.4572, F1=0.6062]Epoch 73: T-Loss: 5.6178 | V-Loss: 5.8277 | IoU: 0.4572 | F1: 0.6062
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  74%|███████▍  | 74/100 [31:49<10:22, 23.93s/it, IoU=0.4496, F1=0.5989]Epoch 74: T-Loss: 5.6243 | V-Loss: 5.8298 | IoU: 0.4496 | F1: 0.5989
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  75%|███████▌  | 75/100 [32:17<09:00, 21.61s/it, IoU=0.4529, F1=0.6020]Epoch 75: T-Loss: 5.6074 | V-Loss: 5.8280 | IoU: 0.4529 | F1: 0.6020

  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  76%|███████▌  | 76/100 [32:43<09:26, 23.61s/it, IoU=0.4551, F1=0.6036]Epoch 76: T-Loss: 5.5736 | V-Loss: 5.8328 | IoU: 0.4551 | F1: 0.6036
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  77%|███████▋  | 77/100 [33:10<09:22, 24.47s/it, IoU=0.4485, F1=0.5975]Epoch 77: T-Loss: 5.5635 | V-Loss: 5.8302 | IoU: 0.4485 | F1: 0.5975
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  78%|███████▊  | 78/100 [33:35<09:12, 25.13s/it, IoU=0.4554, F1=0.6040]Epoch 78: T-Loss: 5.5935 | V-Loss: 5.8346 | IoU: 0.4554 | F1: 0.6040
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  79%|███████▉  | 79/100 [34:07<08:44, 24.96s/it, IoU=0.4517, F1=0.6007]Epoch 79: T-Loss: 5.5742 | V-Loss: 5.8246 | IoU: 0.4517 | F1: 0.6007
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  80%|████████  | 80/100 [34:36<09:06, 27.32s/it, IoU=0.4479, F1=0.5968]Epoch 80: T-Loss: 5.6284 | V-Loss: 5.8294 | IoU: 0.4479 | F1: 0.5968
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  81%|████████  | 81/100 [34:56<08:44, 27.61s/it, IoU=0.4475, F1=0.5967]Epoch 81: T-Loss: 5.5957 | V-Loss: 5.8343 | IoU: 0.4475 | F1: 0.5967
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  82%|████████▏ | 82/100 [35:16<07:38, 25.48s/it, IoU=0.4477, F1=0.5970]Epoch 82: T-Loss: 5.6121 | V-Loss: 5.8292 | IoU: 0.4477 | F1: 0.5970
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  83%|████████▎ | 83/100 [35:41<06:43, 23.73s/it, IoU=0.4496, F1=0.5989]Epoch 83: T-Loss: 5.6109 | V-Loss: 5.8335 | IoU: 0.4496 | F1: 0.5989
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  84%|████████▍ | 84/100 [36:03<06:26, 24.16s/it, IoU=0.4480, F1=0.5975]Epoch 84: T-Loss: 5.6214 | V-Loss: 5.8351 | IoU: 0.4480 | F1: 0.5975
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  85%|████████▌ | 85/100 [36:21<05:50, 23.37s/it, IoU=0.4486, F1=0.5983]Epoch 85: T-Loss: 5.6135 | V-Loss: 5.8289 | IoU: 0.4486 | F1: 0.5983
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  86%|████████▌ | 86/100 [36:39<05:07, 21.95s/it, IoU=0.4479, F1=0.5977]Epoch 86: T-Loss: 5.5951 | V-Loss: 5.8317 | IoU: 0.4479 | F1: 0.5977
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  87%|████████▋ | 87/100 [36:59<04:29, 20.74s/it, IoU=0.4488, F1=0.5984]Epoch 87: T-Loss: 5.5837 | V-Loss: 5.8341 | IoU: 0.4488 | F1: 0.5984
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  88%|████████▊ | 88/100 [37:24<04:04, 20.38s/it, IoU=0.4443, F1=0.5942]Epoch 88: T-Loss: 5.6311 | V-Loss: 5.8345 | IoU: 0.4443 | F1: 0.5942
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  89%|████████▉ | 89/100 [37:43<03:59, 21.76s/it, IoU=0.4468, F1=0.5964]Epoch 89: T-Loss: 5.6056 | V-Loss: 5.8307 | IoU: 0.4468 | F1: 0.5964

============================================================
Early Stopping Triggered at Epoch 89
  - Best Validation Loss: 5.8246
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_deeplabv3plus_efficientnet-b0.csv

Final results:
                                                       Experiment  ...  Test_Prec
0  DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct  ...   0.308966

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TB-to-TC_10pct --arch DeepLabV3Plus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_deeplabv3plus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TB-to-TC_10pct | arch=DeepLabV3Plus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 1028/1028 [00:00<00:00, 3912.85it/s]
Sanitizing Masks: 100%|██████████| 38/38 [00:00<00:00, 3589.40it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 50
 - Validation batches: 15
 - Testing batches: 3
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   0%|          | 0/100 [00:31<?, ?it/s, IoU=0.0529, F1=0.0985]Epoch 0: T-Loss: 10.1950 | V-Loss: 9.3254 | IoU: 0.0529 | F1: 0.0985 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   1%|          | 1/100 [00:51<52:29, 31.82s/it, IoU=0.1192, F1=0.2088]Epoch 1: T-Loss: 8.5995 | V-Loss: 8.2185 | IoU: 0.1192 | F1: 0.2088 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   2%|▏         | 2/100 [01:09<40:12, 24.61s/it, IoU=0.1973, F1=0.3177]Epoch 2: T-Loss: 8.1673 | V-Loss: 7.7860 | IoU: 0.1973 | F1: 0.3177 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   3%|▎         | 3/100 [01:35<34:54, 21.59s/it, IoU=0.2410, F1=0.3760]Epoch 3: T-Loss: 7.8487 | V-Loss: 7.4245 | IoU: 0.2410 | F1: 0.3760 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   4%|▍         | 4/100 [01:58<37:43, 23.58s/it, IoU=0.2627, F1=0.4052]Epoch 4: T-Loss: 7.6239 | V-Loss: 7.1560 | IoU: 0.2627 | F1: 0.4052 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   5%|▌         | 5/100 [02:21<36:50, 23.27s/it, IoU=0.3371, F1=0.4896]Epoch 5: T-Loss: 7.4064 | V-Loss: 7.0029 | IoU: 0.3371 | F1: 0.4896 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   6%|▌         | 6/100 [02:42<36:13, 23.12s/it, IoU=0.3710, F1=0.5284]Epoch 6: T-Loss: 7.1745 | V-Loss: 6.8141 | IoU: 0.3710 | F1: 0.5284 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   7%|▋         | 7/100 [03:00<34:45, 22.43s/it, IoU=0.4049, F1=0.5639]Epoch 7: T-Loss: 7.0030 | V-Loss: 6.6082 | IoU: 0.4049 | F1: 0.5639 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   8%|▊         | 8/100 [03:17<32:20, 21.09s/it, IoU=0.3904, F1=0.5474]Epoch 8: T-Loss: 6.8334 | V-Loss: 6.5293 | IoU: 0.3904 | F1: 0.5474
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   9%|▉         | 9/100 [03:34<30:04, 19.83s/it, IoU=0.3965, F1=0.5562]Epoch 9: T-Loss: 6.7107 | V-Loss: 6.3910 | IoU: 0.3965 | F1: 0.5562
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  10%|█         | 10/100 [03:52<28:27, 18.97s/it, IoU=0.4046, F1=0.5638]Epoch 10: T-Loss: 6.6447 | V-Loss: 6.3328 | IoU: 0.4046 | F1: 0.5638
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  11%|█         | 11/100 [04:09<27:24, 18.48s/it, IoU=0.4211, F1=0.5806]Epoch 11: T-Loss: 6.5158 | V-Loss: 6.2486 | IoU: 0.4211 | F1: 0.5806 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  12%|█▏        | 12/100 [04:27<26:32, 18.10s/it, IoU=0.3972, F1=0.5568]Epoch 12: T-Loss: 6.4361 | V-Loss: 6.2772 | IoU: 0.3972 | F1: 0.5568
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  13%|█▎        | 13/100 [04:44<26:08, 18.03s/it, IoU=0.4141, F1=0.5728]Epoch 13: T-Loss: 6.3720 | V-Loss: 6.1852 | IoU: 0.4141 | F1: 0.5728
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  14%|█▍        | 14/100 [05:06<25:30, 17.80s/it, IoU=0.4212, F1=0.5805]Epoch 14: T-Loss: 6.3007 | V-Loss: 6.1249 | IoU: 0.4212 | F1: 0.5805 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  15%|█▌        | 15/100 [05:27<26:59, 19.05s/it, IoU=0.4171, F1=0.5741]Epoch 15: T-Loss: 6.3015 | V-Loss: 6.0704 | IoU: 0.4171 | F1: 0.5741
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  16%|█▌        | 16/100 [05:49<27:39, 19.76s/it, IoU=0.4197, F1=0.5775]Epoch 16: T-Loss: 6.1956 | V-Loss: 6.0477 | IoU: 0.4197 | F1: 0.5775
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  17%|█▋        | 17/100 [06:10<28:03, 20.28s/it, IoU=0.4210, F1=0.5773]Epoch 17: T-Loss: 6.1778 | V-Loss: 6.0048 | IoU: 0.4210 | F1: 0.5773
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  18%|█▊        | 18/100 [06:29<27:52, 20.40s/it, IoU=0.4363, F1=0.5953]Epoch 18: T-Loss: 6.1987 | V-Loss: 5.9805 | IoU: 0.4363 | F1: 0.5953 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  19%|█▉        | 19/100 [06:48<27:20, 20.25s/it, IoU=0.4351, F1=0.5924]Epoch 19: T-Loss: 6.1528 | V-Loss: 5.9619 | IoU: 0.4351 | F1: 0.5924
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  20%|██        | 20/100 [07:10<26:17, 19.72s/it, IoU=0.4363, F1=0.5937]Epoch 20: T-Loss: 6.0840 | V-Loss: 5.9680 | IoU: 0.4363 | F1: 0.5937
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  21%|██        | 21/100 [07:28<26:46, 20.34s/it, IoU=0.4371, F1=0.5949]Epoch 21: T-Loss: 6.0421 | V-Loss: 5.9320 | IoU: 0.4371 | F1: 0.5949 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  22%|██▏       | 22/100 [07:46<25:49, 19.86s/it, IoU=0.4411, F1=0.5998]Epoch 22: T-Loss: 6.0857 | V-Loss: 5.9114 | IoU: 0.4411 | F1: 0.5998 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  23%|██▎       | 23/100 [08:04<24:39, 19.21s/it, IoU=0.3474, F1=0.4977]Epoch 23: T-Loss: 6.0804 | V-Loss: 5.9434 | IoU: 0.3474 | F1: 0.4977
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  24%|██▍       | 24/100 [08:22<23:54, 18.88s/it, IoU=0.4126, F1=0.5699]Epoch 24: T-Loss: 6.0759 | V-Loss: 5.9441 | IoU: 0.4126 | F1: 0.5699
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  25%|██▌       | 25/100 [08:40<23:19, 18.65s/it, IoU=0.4312, F1=0.5887]Epoch 25: T-Loss: 6.0376 | V-Loss: 5.9092 | IoU: 0.4312 | F1: 0.5887
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  26%|██▌       | 26/100 [08:57<22:24, 18.16s/it, IoU=0.4416, F1=0.6010]Epoch 26: T-Loss: 6.0006 | V-Loss: 5.9110 | IoU: 0.4416 | F1: 0.6010 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  27%|██▋       | 27/100 [09:15<21:57, 18.05s/it, IoU=0.4489, F1=0.6079]Epoch 27: T-Loss: 6.0031 | V-Loss: 5.8859 | IoU: 0.4489 | F1: 0.6079 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  28%|██▊       | 28/100 [09:46<21:28, 17.90s/it, IoU=0.4560, F1=0.6131]Epoch 28: T-Loss: 5.9752 | V-Loss: 5.8399 | IoU: 0.4560 | F1: 0.6131 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  29%|██▉       | 29/100 [10:11<26:04, 22.04s/it, IoU=0.4364, F1=0.5929]Epoch 29: T-Loss: 5.9459 | V-Loss: 5.8496 | IoU: 0.4364 | F1: 0.5929
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  30%|███       | 30/100 [10:37<26:40, 22.87s/it, IoU=0.4505, F1=0.6078]Epoch 30: T-Loss: 5.9527 | V-Loss: 5.8522 | IoU: 0.4505 | F1: 0.6078
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  31%|███       | 31/100 [10:55<27:14, 23.69s/it, IoU=0.4321, F1=0.5888]Epoch 31: T-Loss: 5.9659 | V-Loss: 5.8621 | IoU: 0.4321 | F1: 0.5888
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  32%|███▏      | 32/100 [11:17<24:55, 22.00s/it, IoU=0.4460, F1=0.6026]Epoch 32: T-Loss: 5.9234 | V-Loss: 5.8329 | IoU: 0.4460 | F1: 0.6026
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  33%|███▎      | 33/100 [11:39<24:42, 22.13s/it, IoU=0.4564, F1=0.6138]Epoch 33: T-Loss: 5.9749 | V-Loss: 5.8246 | IoU: 0.4564 | F1: 0.6138 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  34%|███▍      | 34/100 [11:58<24:11, 21.99s/it, IoU=0.4519, F1=0.6090]Epoch 34: T-Loss: 5.9667 | V-Loss: 5.8106 | IoU: 0.4519 | F1: 0.6090
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  35%|███▌      | 35/100 [12:16<22:52, 21.11s/it, IoU=0.4428, F1=0.6011]Epoch 35: T-Loss: 5.9276 | V-Loss: 5.8416 | IoU: 0.4428 | F1: 0.6011
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  36%|███▌      | 36/100 [12:33<21:32, 20.19s/it, IoU=0.4591, F1=0.6184]Epoch 36: T-Loss: 5.8951 | V-Loss: 5.8149 | IoU: 0.4591 | F1: 0.6184 [Saved Best Model]

  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  37%|███▋      | 37/100 [12:50<20:08, 19.18s/it, IoU=0.4649, F1=0.6219]Epoch 37: T-Loss: 5.8985 | V-Loss: 5.8105 | IoU: 0.4649 | F1: 0.6219 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  38%|███▊      | 38/100 [13:08<19:07, 18.50s/it, IoU=0.4515, F1=0.6082]Epoch 38: T-Loss: 5.9027 | V-Loss: 5.7983 | IoU: 0.4515 | F1: 0.6082
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  39%|███▉      | 39/100 [13:25<18:34, 18.27s/it, IoU=0.4608, F1=0.6193]Epoch 39: T-Loss: 5.9046 | V-Loss: 5.7912 | IoU: 0.4608 | F1: 0.6193
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  40%|████      | 40/100 [13:53<18:03, 18.05s/it, IoU=0.4604, F1=0.6180]Epoch 40: T-Loss: 5.8516 | V-Loss: 5.7826 | IoU: 0.4604 | F1: 0.6180
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  41%|████      | 41/100 [14:11<20:39, 21.00s/it, IoU=0.4546, F1=0.6140]Epoch 41: T-Loss: 5.8615 | V-Loss: 5.7770 | IoU: 0.4546 | F1: 0.6140
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  42%|████▏     | 42/100 [14:31<19:16, 19.94s/it, IoU=0.4347, F1=0.5923]Epoch 42: T-Loss: 5.8354 | V-Loss: 5.7759 | IoU: 0.4347 | F1: 0.5923
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  43%|████▎     | 43/100 [14:52<18:58, 19.98s/it, IoU=0.4503, F1=0.6098]Epoch 43: T-Loss: 5.8347 | V-Loss: 5.7608 | IoU: 0.4503 | F1: 0.6098
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  44%|████▍     | 44/100 [15:18<19:08, 20.50s/it, IoU=0.4750, F1=0.6348]Epoch 44: T-Loss: 5.8625 | V-Loss: 5.7593 | IoU: 0.4750 | F1: 0.6348 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  45%|████▌     | 45/100 [15:39<20:12, 22.04s/it, IoU=0.4683, F1=0.6272]Epoch 45: T-Loss: 5.7939 | V-Loss: 5.7605 | IoU: 0.4683 | F1: 0.6272
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  46%|████▌     | 46/100 [15:57<19:32, 21.72s/it, IoU=0.4382, F1=0.5993]Epoch 46: T-Loss: 5.8183 | V-Loss: 5.7582 | IoU: 0.4382 | F1: 0.5993
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  47%|████▋     | 47/100 [16:15<18:17, 20.70s/it, IoU=0.4796, F1=0.6387]Epoch 47: T-Loss: 5.8406 | V-Loss: 5.7525 | IoU: 0.4796 | F1: 0.6387 [Saved Best Model]
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  48%|████▊     | 48/100 [16:36<17:15, 19.91s/it, IoU=0.4589, F1=0.6174]Epoch 48: T-Loss: 5.8199 | V-Loss: 5.7469 | IoU: 0.4589 | F1: 0.6174
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  49%|████▉     | 49/100 [16:55<17:14, 20.28s/it, IoU=0.4414, F1=0.5968]Epoch 49: T-Loss: 5.8345 | V-Loss: 5.7745 | IoU: 0.4414 | F1: 0.5968
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  50%|█████     | 50/100 [17:15<16:22, 19.64s/it, IoU=0.4386, F1=0.5964]Epoch 50: T-Loss: 5.8014 | V-Loss: 5.7554 | IoU: 0.4386 | F1: 0.5964
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  51%|█████     | 51/100 [17:33<16:18, 19.97s/it, IoU=0.4544, F1=0.6128]Epoch 51: T-Loss: 5.8325 | V-Loss: 5.7607 | IoU: 0.4544 | F1: 0.6128
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  52%|█████▏    | 52/100 [17:51<15:24, 19.26s/it, IoU=0.4407, F1=0.5989]Epoch 52: T-Loss: 5.8378 | V-Loss: 5.7393 | IoU: 0.4407 | F1: 0.5989
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  53%|█████▎    | 53/100 [18:11<14:43, 18.80s/it, IoU=0.4548, F1=0.6129]Epoch 53: T-Loss: 5.7797 | V-Loss: 5.7457 | IoU: 0.4548 | F1: 0.6129
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  54%|█████▍    | 54/100 [18:35<14:43, 19.20s/it, IoU=0.4606, F1=0.6192]Epoch 54: T-Loss: 5.7972 | V-Loss: 5.7315 | IoU: 0.4606 | F1: 0.6192
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  55%|█████▌    | 55/100 [18:55<15:25, 20.57s/it, IoU=0.4525, F1=0.6117]Epoch 55: T-Loss: 5.7679 | V-Loss: 5.7226 | IoU: 0.4525 | F1: 0.6117
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  56%|█████▌    | 56/100 [19:18<15:08, 20.65s/it, IoU=0.4602, F1=0.6180]Epoch 56: T-Loss: 5.7806 | V-Loss: 5.7284 | IoU: 0.4602 | F1: 0.6180
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  57%|█████▋    | 57/100 [19:40<15:11, 21.20s/it, IoU=0.4473, F1=0.6048]Epoch 57: T-Loss: 5.7998 | V-Loss: 5.7171 | IoU: 0.4473 | F1: 0.6048
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  58%|█████▊    | 58/100 [20:15<15:05, 21.57s/it, IoU=0.4598, F1=0.6175]Epoch 58: T-Loss: 5.7724 | V-Loss: 5.7091 | IoU: 0.4598 | F1: 0.6175
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  59%|█████▉    | 59/100 [20:34<17:28, 25.58s/it, IoU=0.4585, F1=0.6160]Epoch 59: T-Loss: 5.7666 | V-Loss: 5.7146 | IoU: 0.4585 | F1: 0.6160
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  60%|██████    | 60/100 [20:52<15:42, 23.57s/it, IoU=0.4497, F1=0.6078]Epoch 60: T-Loss: 5.7661 | V-Loss: 5.7139 | IoU: 0.4497 | F1: 0.6078
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  61%|██████    | 61/100 [21:09<14:07, 21.72s/it, IoU=0.4573, F1=0.6143]Epoch 61: T-Loss: 5.7648 | V-Loss: 5.7302 | IoU: 0.4573 | F1: 0.6143
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  62%|██████▏   | 62/100 [21:40<13:01, 20.56s/it, IoU=0.4598, F1=0.6178]Epoch 62: T-Loss: 5.7846 | V-Loss: 5.7198 | IoU: 0.4598 | F1: 0.6178
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  63%|██████▎   | 63/100 [22:00<14:27, 23.46s/it, IoU=0.4564, F1=0.6140]Epoch 63: T-Loss: 5.7595 | V-Loss: 5.7139 | IoU: 0.4564 | F1: 0.6140
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  64%|██████▍   | 64/100 [22:28<13:27, 22.44s/it, IoU=0.4500, F1=0.6051]Epoch 64: T-Loss: 5.7667 | V-Loss: 5.7132 | IoU: 0.4500 | F1: 0.6051
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  65%|██████▌   | 65/100 [23:05<14:10, 24.30s/it, IoU=0.4531, F1=0.6114]Epoch 65: T-Loss: 5.7490 | V-Loss: 5.7019 | IoU: 0.4531 | F1: 0.6114
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  66%|██████▌   | 66/100 [23:22<15:47, 27.85s/it, IoU=0.4525, F1=0.6096]Epoch 66: T-Loss: 5.7723 | V-Loss: 5.6939 | IoU: 0.4525 | F1: 0.6096
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  67%|██████▋   | 67/100 [23:39<13:36, 24.73s/it, IoU=0.4580, F1=0.6153]Epoch 67: T-Loss: 5.7341 | V-Loss: 5.7091 | IoU: 0.4580 | F1: 0.6153
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  68%|██████▊   | 68/100 [23:58<12:01, 22.54s/it, IoU=0.4666, F1=0.6250]Epoch 68: T-Loss: 5.7644 | V-Loss: 5.6903 | IoU: 0.4666 | F1: 0.6250
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  69%|██████▉   | 69/100 [24:16<10:59, 21.27s/it, IoU=0.4521, F1=0.6110]Epoch 69: T-Loss: 5.7751 | V-Loss: 5.6969 | IoU: 0.4521 | F1: 0.6110
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  70%|███████   | 70/100 [24:33<10:09, 20.32s/it, IoU=0.4649, F1=0.6243]Epoch 70: T-Loss: 5.7879 | V-Loss: 5.6974 | IoU: 0.4649 | F1: 0.6243
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  71%|███████   | 71/100 [24:53<09:25, 19.49s/it, IoU=0.4653, F1=0.6239]Epoch 71: T-Loss: 5.7616 | V-Loss: 5.6951 | IoU: 0.4653 | F1: 0.6239
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  72%|███████▏  | 72/100 [25:13<09:09, 19.63s/it, IoU=0.4703, F1=0.6289]Epoch 72: T-Loss: 5.7205 | V-Loss: 5.6926 | IoU: 0.4703 | F1: 0.6289
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  73%|███████▎  | 73/100 [25:30<08:49, 19.60s/it, IoU=0.4587, F1=0.6165]Epoch 73: T-Loss: 5.7540 | V-Loss: 5.6913 | IoU: 0.4587 | F1: 0.6165
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  74%|███████▍  | 74/100 [25:47<08:08, 18.78s/it, IoU=0.4660, F1=0.6242]Epoch 74: T-Loss: 5.7306 | V-Loss: 5.6849 | IoU: 0.4660 | F1: 0.6242
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  75%|███████▌  | 75/100 [26:09<07:41, 18.48s/it, IoU=0.4594, F1=0.6179]Epoch 75: T-Loss: 5.7197 | V-Loss: 5.6926 | IoU: 0.4594 | F1: 0.6179

  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  76%|███████▌  | 76/100 [26:28<07:46, 19.43s/it, IoU=0.4710, F1=0.6288]Epoch 76: T-Loss: 5.7077 | V-Loss: 5.6893 | IoU: 0.4710 | F1: 0.6288
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  77%|███████▋  | 77/100 [26:45<07:22, 19.23s/it, IoU=0.4652, F1=0.6237]Epoch 77: T-Loss: 5.7308 | V-Loss: 5.6837 | IoU: 0.4652 | F1: 0.6237
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  78%|███████▊  | 78/100 [27:08<06:51, 18.71s/it, IoU=0.4688, F1=0.6265]Epoch 78: T-Loss: 5.6958 | V-Loss: 5.6807 | IoU: 0.4688 | F1: 0.6265
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  79%|███████▉  | 79/100 [27:25<06:58, 19.91s/it, IoU=0.4636, F1=0.6217]Epoch 79: T-Loss: 5.7616 | V-Loss: 5.6787 | IoU: 0.4636 | F1: 0.6217
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  80%|████████  | 80/100 [27:42<06:18, 18.93s/it, IoU=0.4688, F1=0.6271]Epoch 80: T-Loss: 5.7119 | V-Loss: 5.6816 | IoU: 0.4688 | F1: 0.6271
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  81%|████████  | 81/100 [28:00<05:52, 18.55s/it, IoU=0.4739, F1=0.6319]Epoch 81: T-Loss: 5.7478 | V-Loss: 5.6819 | IoU: 0.4739 | F1: 0.6319
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  82%|████████▏ | 82/100 [28:17<05:28, 18.24s/it, IoU=0.4674, F1=0.6246]Epoch 82: T-Loss: 5.7290 | V-Loss: 5.6779 | IoU: 0.4674 | F1: 0.6246
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  83%|████████▎ | 83/100 [28:36<05:01, 17.76s/it, IoU=0.4685, F1=0.6260]Epoch 83: T-Loss: 5.7317 | V-Loss: 5.6788 | IoU: 0.4685 | F1: 0.6260
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  84%|████████▍ | 84/100 [28:53<04:51, 18.20s/it, IoU=0.4676, F1=0.6253]Epoch 84: T-Loss: 5.6993 | V-Loss: 5.6774 | IoU: 0.4676 | F1: 0.6253
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  85%|████████▌ | 85/100 [29:11<04:30, 18.02s/it, IoU=0.4693, F1=0.6270]Epoch 85: T-Loss: 5.7289 | V-Loss: 5.6735 | IoU: 0.4693 | F1: 0.6270
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  86%|████████▌ | 86/100 [29:28<04:10, 17.92s/it, IoU=0.4685, F1=0.6263]Epoch 86: T-Loss: 5.7261 | V-Loss: 5.6743 | IoU: 0.4685 | F1: 0.6263
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  87%|████████▋ | 87/100 [29:46<03:50, 17.73s/it, IoU=0.4727, F1=0.6304]Epoch 87: T-Loss: 5.7378 | V-Loss: 5.6765 | IoU: 0.4727 | F1: 0.6304
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  88%|████████▊ | 88/100 [30:12<03:30, 17.58s/it, IoU=0.4691, F1=0.6270]Epoch 88: T-Loss: 5.7092 | V-Loss: 5.6742 | IoU: 0.4691 | F1: 0.6270
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  89%|████████▉ | 89/100 [30:33<03:42, 20.22s/it, IoU=0.4716, F1=0.6296]Epoch 89: T-Loss: 5.6991 | V-Loss: 5.6733 | IoU: 0.4716 | F1: 0.6296
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  90%|█████████ | 90/100 [30:51<03:24, 20.40s/it, IoU=0.4662, F1=0.6243]Epoch 90: T-Loss: 5.7303 | V-Loss: 5.6761 | IoU: 0.4662 | F1: 0.6243
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  91%|█████████ | 91/100 [31:08<02:56, 19.62s/it, IoU=0.4712, F1=0.6295]Epoch 91: T-Loss: 5.6978 | V-Loss: 5.6758 | IoU: 0.4712 | F1: 0.6295
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  92%|█████████▏| 92/100 [31:27<02:30, 18.82s/it, IoU=0.4720, F1=0.6300]Epoch 92: T-Loss: 5.7133 | V-Loss: 5.6744 | IoU: 0.4720 | F1: 0.6300
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  93%|█████████▎| 93/100 [31:46<02:12, 18.93s/it, IoU=0.4709, F1=0.6289]Epoch 93: T-Loss: 5.7267 | V-Loss: 5.6754 | IoU: 0.4709 | F1: 0.6289
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  94%|█████████▍| 94/100 [32:07<01:53, 18.92s/it, IoU=0.4687, F1=0.6268]Epoch 94: T-Loss: 5.6977 | V-Loss: 5.6747 | IoU: 0.4687 | F1: 0.6268
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  95%|█████████▌| 95/100 [32:26<01:37, 19.60s/it, IoU=0.4687, F1=0.6272]Epoch 95: T-Loss: 5.6959 | V-Loss: 5.6755 | IoU: 0.4687 | F1: 0.6272
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  96%|█████████▌| 96/100 [32:44<01:18, 19.60s/it, IoU=0.4695, F1=0.6278]Epoch 96: T-Loss: 5.7238 | V-Loss: 5.6760 | IoU: 0.4695 | F1: 0.6278
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  97%|█████████▋| 97/100 [33:04<00:56, 18.93s/it, IoU=0.4679, F1=0.6261]Epoch 97: T-Loss: 5.7347 | V-Loss: 5.6743 | IoU: 0.4679 | F1: 0.6261
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  98%|█████████▊| 98/100 [33:26<00:38, 19.33s/it, IoU=0.4711, F1=0.6291]Epoch 98: T-Loss: 5.7199 | V-Loss: 5.6731 | IoU: 0.4711 | F1: 0.6291
  → DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  99%|█████████▉| 99/100 [33:43<00:20, 20.08s/it, IoU=0.4693, F1=0.6275]Epoch 99: T-Loss: 5.6764 | V-Loss: 5.6766 | IoU: 0.4693 | F1: 0.6275
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_deeplabv3plus_efficientnet-b0.csv

Final results:
                                                       Experiment  ...  Test_Prec
0  DeepLabV3Plus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct  ...   0.381635

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Single-TB --arch UnetPlusPlus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_unetplusplus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Single-TB | arch=UnetPlusPlus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...
Sanitizing test masks...

Sanitizing Masks: 100%|██████████| 424/424 [00:00<00:00, 18656.80it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 3403.37it/s]

Generating Dataloaders...

Pipeline Ready:
 - Training batches: 20
 - Validation batches: 6
 - Testing batches: 3
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   0%|          | 0/100 [00:14<?, ?it/s, IoU=0.0022, F1=0.0043]Epoch 0: T-Loss: 10.2031 | V-Loss: 9.6024 | IoU: 0.0022 | F1: 0.0043 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   1%|          | 1/100 [00:25<23:48, 14.43s/it, IoU=0.0005, F1=0.0010]Epoch 1: T-Loss: 9.4763 | V-Loss: 9.0219 | IoU: 0.0005 | F1: 0.0010
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   2%|▏         | 2/100 [00:37<20:47, 12.73s/it, IoU=0.0003, F1=0.0006]Epoch 2: T-Loss: 9.0244 | V-Loss: 8.7882 | IoU: 0.0003 | F1: 0.0006
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   3%|▎         | 3/100 [00:49<19:27, 12.03s/it, IoU=0.0040, F1=0.0079]Epoch 3: T-Loss: 8.7561 | V-Loss: 8.8108 | IoU: 0.0040 | F1: 0.0079 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   4%|▍         | 4/100 [01:03<19:40, 12.30s/it, IoU=0.0385, F1=0.0716]Epoch 4: T-Loss: 8.5887 | V-Loss: 8.6700 | IoU: 0.0385 | F1: 0.0716 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   5%|▌         | 5/100 [01:13<20:07, 12.71s/it, IoU=0.0782, F1=0.1390]Epoch 5: T-Loss: 8.4670 | V-Loss: 8.3768 | IoU: 0.0782 | F1: 0.1390 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   6%|▌         | 6/100 [01:25<18:33, 11.84s/it, IoU=0.0836, F1=0.1460]Epoch 6: T-Loss: 8.3579 | V-Loss: 8.2872 | IoU: 0.0836 | F1: 0.1460 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   7%|▋         | 7/100 [01:36<18:48, 12.14s/it, IoU=0.0766, F1=0.1366]Epoch 7: T-Loss: 8.2678 | V-Loss: 8.2244 | IoU: 0.0766 | F1: 0.1366
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   8%|▊         | 8/100 [01:46<17:44, 11.57s/it, IoU=0.1215, F1=0.2091]Epoch 8: T-Loss: 8.1869 | V-Loss: 8.0520 | IoU: 0.1215 | F1: 0.2091 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:   9%|▉         | 9/100 [02:01<16:58, 11.19s/it, IoU=0.0957, F1=0.1705]Epoch 9: T-Loss: 8.0942 | V-Loss: 8.0606 | IoU: 0.0957 | F1: 0.1705
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  10%|█         | 10/100 [02:14<18:22, 12.26s/it, IoU=0.1316, F1=0.2266]Epoch 10: T-Loss: 8.0382 | V-Loss: 7.8977 | IoU: 0.1316 | F1: 0.2266 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  11%|█         | 11/100 [02:27<18:38, 12.57s/it, IoU=0.1743, F1=0.2887]Epoch 11: T-Loss: 7.9665 | V-Loss: 7.7394 | IoU: 0.1743 | F1: 0.2887 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  12%|█▏        | 12/100 [02:40<18:39, 12.72s/it, IoU=0.1339, F1=0.2293]Epoch 12: T-Loss: 7.9037 | V-Loss: 7.7415 | IoU: 0.1339 | F1: 0.2293
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  13%|█▎        | 13/100 [02:50<18:24, 12.70s/it, IoU=0.1962, F1=0.3175]Epoch 13: T-Loss: 7.8487 | V-Loss: 7.5427 | IoU: 0.1962 | F1: 0.3175 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  14%|█▍        | 14/100 [03:00<17:08, 11.96s/it, IoU=0.1688, F1=0.2801]Epoch 14: T-Loss: 7.7792 | V-Loss: 7.5409 | IoU: 0.1688 | F1: 0.2801
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  15%|█▌        | 15/100 [03:10<16:02, 11.32s/it, IoU=0.2223, F1=0.3513]Epoch 15: T-Loss: 7.7000 | V-Loss: 7.4427 | IoU: 0.2223 | F1: 0.3513 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  16%|█▌        | 16/100 [03:20<15:21, 10.97s/it, IoU=0.2179, F1=0.3493]Epoch 16: T-Loss: 7.6403 | V-Loss: 7.3496 | IoU: 0.2179 | F1: 0.3493
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  17%|█▋        | 17/100 [03:30<14:40, 10.60s/it, IoU=0.2031, F1=0.3259]Epoch 17: T-Loss: 7.5752 | V-Loss: 7.2764 | IoU: 0.2031 | F1: 0.3259
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  18%|█▊        | 18/100 [03:43<14:21, 10.50s/it, IoU=0.2208, F1=0.3513]Epoch 18: T-Loss: 7.5561 | V-Loss: 7.2184 | IoU: 0.2208 | F1: 0.3513
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  19%|█▉        | 19/100 [03:54<14:54, 11.04s/it, IoU=0.2210, F1=0.3494]Epoch 19: T-Loss: 7.4636 | V-Loss: 7.1243 | IoU: 0.2210 | F1: 0.3494
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  20%|██        | 20/100 [04:05<14:54, 11.18s/it, IoU=0.2822, F1=0.4294]Epoch 20: T-Loss: 7.3701 | V-Loss: 7.0090 | IoU: 0.2822 | F1: 0.4294 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  21%|██        | 21/100 [04:15<14:36, 11.10s/it, IoU=0.2260, F1=0.3569]Epoch 21: T-Loss: 7.3043 | V-Loss: 6.9676 | IoU: 0.2260 | F1: 0.3569
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  22%|██▏       | 22/100 [04:25<13:55, 10.71s/it, IoU=0.2821, F1=0.4306]Epoch 22: T-Loss: 7.2109 | V-Loss: 6.8988 | IoU: 0.2821 | F1: 0.4306
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  23%|██▎       | 23/100 [04:35<13:30, 10.53s/it, IoU=0.2697, F1=0.4132]Epoch 23: T-Loss: 7.1737 | V-Loss: 6.8005 | IoU: 0.2697 | F1: 0.4132
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  24%|██▍       | 24/100 [04:45<13:06, 10.34s/it, IoU=0.2478, F1=0.3817]Epoch 24: T-Loss: 7.0308 | V-Loss: 6.7176 | IoU: 0.2478 | F1: 0.3817
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  25%|██▌       | 25/100 [04:55<12:50, 10.27s/it, IoU=0.2687, F1=0.4163]Epoch 25: T-Loss: 6.9137 | V-Loss: 6.6463 | IoU: 0.2687 | F1: 0.4163
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  26%|██▌       | 26/100 [05:08<12:34, 10.20s/it, IoU=0.2860, F1=0.4354]Epoch 26: T-Loss: 6.9146 | V-Loss: 6.5361 | IoU: 0.2860 | F1: 0.4354 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  27%|██▋       | 27/100 [05:18<13:23, 11.00s/it, IoU=0.2540, F1=0.3969]Epoch 27: T-Loss: 6.7702 | V-Loss: 6.4933 | IoU: 0.2540 | F1: 0.3969
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  28%|██▊       | 28/100 [05:29<12:59, 10.83s/it, IoU=0.2839, F1=0.4394]Epoch 28: T-Loss: 6.6555 | V-Loss: 6.5407 | IoU: 0.2839 | F1: 0.4394
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  29%|██▉       | 29/100 [05:40<12:54, 10.91s/it, IoU=0.3069, F1=0.4598]Epoch 29: T-Loss: 6.6722 | V-Loss: 6.4686 | IoU: 0.3069 | F1: 0.4598 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  30%|███       | 30/100 [05:52<12:34, 10.78s/it, IoU=0.2468, F1=0.3810]Epoch 30: T-Loss: 6.5808 | V-Loss: 6.3906 | IoU: 0.2468 | F1: 0.3810
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  31%|███       | 31/100 [06:02<12:53, 11.20s/it, IoU=0.2876, F1=0.4426]Epoch 31: T-Loss: 6.5328 | V-Loss: 6.5132 | IoU: 0.2876 | F1: 0.4426
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  32%|███▏      | 32/100 [06:13<12:13, 10.79s/it, IoU=0.2334, F1=0.3701]Epoch 32: T-Loss: 6.4947 | V-Loss: 6.5453 | IoU: 0.2334 | F1: 0.3701
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  33%|███▎      | 33/100 [06:23<12:03, 10.80s/it, IoU=0.2891, F1=0.4385]Epoch 33: T-Loss: 6.4827 | V-Loss: 6.3852 | IoU: 0.2891 | F1: 0.4385
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  34%|███▍      | 34/100 [06:33<11:42, 10.64s/it, IoU=0.2933, F1=0.4471]Epoch 34: T-Loss: 6.4486 | V-Loss: 6.3551 | IoU: 0.2933 | F1: 0.4471
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  35%|███▌      | 35/100 [06:44<11:24, 10.54s/it, IoU=0.3125, F1=0.4689]Epoch 35: T-Loss: 6.3321 | V-Loss: 6.2781 | IoU: 0.3125 | F1: 0.4689 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  36%|███▌      | 36/100 [06:57<11:13, 10.53s/it, IoU=0.2818, F1=0.4239]Epoch 36: T-Loss: 6.2998 | V-Loss: 6.2307 | IoU: 0.2818 | F1: 0.4239
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  37%|███▋      | 37/100 [07:10<11:48, 11.24s/it, IoU=0.3041, F1=0.4569]Epoch 37: T-Loss: 6.2797 | V-Loss: 6.2206 | IoU: 0.3041 | F1: 0.4569
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  38%|███▊      | 38/100 [07:22<12:20, 11.94s/it, IoU=0.3137, F1=0.4675]Epoch 38: T-Loss: 6.2547 | V-Loss: 6.1967 | IoU: 0.3137 | F1: 0.4675 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  39%|███▉      | 39/100 [07:32<12:07, 11.92s/it, IoU=0.3221, F1=0.4766]Epoch 39: T-Loss: 6.3178 | V-Loss: 6.1143 | IoU: 0.3221 | F1: 0.4766 [Saved Best Model]

  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  40%|████      | 40/100 [07:43<11:25, 11.43s/it, IoU=0.3223, F1=0.4770]Epoch 40: T-Loss: 6.2282 | V-Loss: 6.0750 | IoU: 0.3223 | F1: 0.4770 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  41%|████      | 41/100 [07:54<11:03, 11.25s/it, IoU=0.2963, F1=0.4488]Epoch 41: T-Loss: 6.1763 | V-Loss: 6.0872 | IoU: 0.2963 | F1: 0.4488
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  42%|████▏     | 42/100 [08:05<10:46, 11.15s/it, IoU=0.3311, F1=0.4913]Epoch 42: T-Loss: 6.1280 | V-Loss: 6.1268 | IoU: 0.3311 | F1: 0.4913 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  43%|████▎     | 43/100 [08:16<10:32, 11.10s/it, IoU=0.3254, F1=0.4747]Epoch 43: T-Loss: 6.1571 | V-Loss: 6.0876 | IoU: 0.3254 | F1: 0.4747
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  44%|████▍     | 44/100 [08:26<10:16, 11.01s/it, IoU=0.3378, F1=0.4943]Epoch 44: T-Loss: 6.1954 | V-Loss: 6.0215 | IoU: 0.3378 | F1: 0.4943 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  45%|████▌     | 45/100 [08:36<09:57, 10.86s/it, IoU=0.3589, F1=0.5233]Epoch 45: T-Loss: 6.1114 | V-Loss: 6.0680 | IoU: 0.3589 | F1: 0.5233 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  46%|████▌     | 46/100 [08:49<09:35, 10.66s/it, IoU=0.3355, F1=0.4921]Epoch 46: T-Loss: 6.2143 | V-Loss: 6.0066 | IoU: 0.3355 | F1: 0.4921
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  47%|████▋     | 47/100 [08:59<09:45, 11.05s/it, IoU=0.3261, F1=0.4791]Epoch 47: T-Loss: 6.1524 | V-Loss: 6.0145 | IoU: 0.3261 | F1: 0.4791
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  48%|████▊     | 48/100 [09:09<09:21, 10.79s/it, IoU=0.3448, F1=0.5072]Epoch 48: T-Loss: 6.0848 | V-Loss: 6.0199 | IoU: 0.3448 | F1: 0.5072
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  49%|████▉     | 49/100 [09:18<08:58, 10.55s/it, IoU=0.3479, F1=0.5093]Epoch 49: T-Loss: 6.1139 | V-Loss: 5.9912 | IoU: 0.3479 | F1: 0.5093
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  50%|█████     | 50/100 [09:28<08:31, 10.22s/it, IoU=0.3004, F1=0.4436]Epoch 50: T-Loss: 6.1396 | V-Loss: 6.0513 | IoU: 0.3004 | F1: 0.4436
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  51%|█████     | 51/100 [09:38<08:14, 10.09s/it, IoU=0.3405, F1=0.4983]Epoch 51: T-Loss: 6.0300 | V-Loss: 6.0457 | IoU: 0.3405 | F1: 0.4983
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  52%|█████▏    | 52/100 [09:47<07:56,  9.94s/it, IoU=0.3253, F1=0.4732]Epoch 52: T-Loss: 5.9209 | V-Loss: 5.9940 | IoU: 0.3253 | F1: 0.4732
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  53%|█████▎    | 53/100 [09:57<07:40,  9.80s/it, IoU=0.3550, F1=0.5113]Epoch 53: T-Loss: 5.9447 | V-Loss: 5.9821 | IoU: 0.3550 | F1: 0.5113
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  54%|█████▍    | 54/100 [10:07<07:30,  9.80s/it, IoU=0.3428, F1=0.4972]Epoch 54: T-Loss: 5.9843 | V-Loss: 6.0400 | IoU: 0.3428 | F1: 0.4972
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  55%|█████▌    | 55/100 [10:18<07:27,  9.94s/it, IoU=0.3405, F1=0.4931]Epoch 55: T-Loss: 5.9694 | V-Loss: 6.0104 | IoU: 0.3405 | F1: 0.4931
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  56%|█████▌    | 56/100 [10:28<07:24, 10.09s/it, IoU=0.3651, F1=0.5244]Epoch 56: T-Loss: 6.0038 | V-Loss: 5.9604 | IoU: 0.3651 | F1: 0.5244 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  57%|█████▋    | 57/100 [10:39<07:19, 10.21s/it, IoU=0.3555, F1=0.5133]Epoch 57: T-Loss: 6.0625 | V-Loss: 5.9660 | IoU: 0.3555 | F1: 0.5133
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  58%|█████▊    | 58/100 [10:48<07:15, 10.36s/it, IoU=0.3501, F1=0.5044]Epoch 58: T-Loss: 5.9574 | V-Loss: 5.9552 | IoU: 0.3501 | F1: 0.5044
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  59%|█████▉    | 59/100 [10:59<06:53, 10.09s/it, IoU=0.3533, F1=0.5117]Epoch 59: T-Loss: 5.9949 | V-Loss: 5.9443 | IoU: 0.3533 | F1: 0.5117
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  60%|██████    | 60/100 [11:09<06:47, 10.18s/it, IoU=0.3519, F1=0.5115]Epoch 60: T-Loss: 5.9286 | V-Loss: 5.9820 | IoU: 0.3519 | F1: 0.5115
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  61%|██████    | 61/100 [11:18<06:35, 10.14s/it, IoU=0.3554, F1=0.5145]Epoch 61: T-Loss: 5.9493 | V-Loss: 6.0010 | IoU: 0.3554 | F1: 0.5145
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  62%|██████▏   | 62/100 [11:28<06:18,  9.96s/it, IoU=0.3389, F1=0.4911]Epoch 62: T-Loss: 5.9537 | V-Loss: 5.9353 | IoU: 0.3389 | F1: 0.4911
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  63%|██████▎   | 63/100 [11:38<06:05,  9.89s/it, IoU=0.3453, F1=0.5048]Epoch 63: T-Loss: 5.9298 | V-Loss: 6.0200 | IoU: 0.3453 | F1: 0.5048
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  64%|██████▍   | 64/100 [11:48<05:53,  9.82s/it, IoU=0.3535, F1=0.5112]Epoch 64: T-Loss: 5.8769 | V-Loss: 5.9611 | IoU: 0.3535 | F1: 0.5112
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  65%|██████▌   | 65/100 [11:57<05:44,  9.85s/it, IoU=0.3489, F1=0.5066]Epoch 65: T-Loss: 5.9611 | V-Loss: 5.9936 | IoU: 0.3489 | F1: 0.5066
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  66%|██████▌   | 66/100 [12:07<05:31,  9.76s/it, IoU=0.3416, F1=0.4989]Epoch 66: T-Loss: 6.0146 | V-Loss: 5.9934 | IoU: 0.3416 | F1: 0.4989
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  67%|██████▋   | 67/100 [12:16<05:19,  9.67s/it, IoU=0.3516, F1=0.5094]Epoch 67: T-Loss: 5.9567 | V-Loss: 5.9716 | IoU: 0.3516 | F1: 0.5094
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  68%|██████▊   | 68/100 [12:26<05:08,  9.63s/it, IoU=0.3487, F1=0.5022]Epoch 68: T-Loss: 5.9080 | V-Loss: 5.9987 | IoU: 0.3487 | F1: 0.5022
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  69%|██████▉   | 69/100 [12:37<05:03,  9.78s/it, IoU=0.3466, F1=0.4984]Epoch 69: T-Loss: 5.8965 | V-Loss: 5.9914 | IoU: 0.3466 | F1: 0.4984
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  70%|███████   | 70/100 [12:47<04:59,  9.99s/it, IoU=0.3468, F1=0.5026]Epoch 70: T-Loss: 5.8897 | V-Loss: 5.9529 | IoU: 0.3468 | F1: 0.5026
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  71%|███████   | 71/100 [12:56<04:51, 10.04s/it, IoU=0.3533, F1=0.5113]Epoch 71: T-Loss: 5.8269 | V-Loss: 5.9674 | IoU: 0.3533 | F1: 0.5113
  → UnetPlusPlus-efficientnet-b0-imagenet_Single-TB:  72%|███████▏  | 72/100 [13:08<04:37,  9.90s/it, IoU=0.3589, F1=0.5171]Epoch 72: T-Loss: 5.8216 | V-Loss: 5.9587 | IoU: 0.3589 | F1: 0.5171

============================================================
Early Stopping Triggered at Epoch 72
  - Best Validation Loss: 5.9353
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/UnetPlusPlus-efficientnet-b0-imagenet_Single-TB_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_unetplusplus_efficientnet-b0.csv

Final results:
                                        Experiment  ...  Test_Prec
0  UnetPlusPlus-efficientnet-b0-imagenet_Single-TB  ...   0.417515

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TC-to-TB_10pct --arch UnetPlusPlus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_unetplusplus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TC-to-TB_10pct | arch=UnetPlusPlus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 936/936 [00:00<00:00, 2262.96it/s]
Sanitizing Masks: 100%|██████████| 48/48 [00:00<00:00, 15881.25it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 45
 - Validation batches: 13
 - Testing batches: 3
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   0%|          | 0/100 [00:22<?, ?it/s, IoU=0.1642, F1=0.2737]Epoch 0: T-Loss: 9.3583 | V-Loss: 8.5377 | IoU: 0.1642 | F1: 0.2737 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   1%|          | 1/100 [00:45<38:07, 23.11s/it, IoU=0.2633, F1=0.4021]Epoch 1: T-Loss: 8.5533 | V-Loss: 8.0154 | IoU: 0.2633 | F1: 0.4021 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   2%|▏         | 2/100 [01:10<36:46, 22.52s/it, IoU=0.3165, F1=0.4624]Epoch 2: T-Loss: 8.0750 | V-Loss: 7.7781 | IoU: 0.3165 | F1: 0.4624 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   3%|▎         | 3/100 [01:35<38:43, 23.95s/it, IoU=0.3226, F1=0.4675]Epoch 3: T-Loss: 7.7196 | V-Loss: 7.4121 | IoU: 0.3226 | F1: 0.4675 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   4%|▍         | 4/100 [02:00<38:31, 24.08s/it, IoU=0.2166, F1=0.3401]Epoch 4: T-Loss: 7.3871 | V-Loss: 7.1834 | IoU: 0.2166 | F1: 0.3401
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   5%|▌         | 5/100 [02:20<38:53, 24.56s/it, IoU=0.3456, F1=0.4913]Epoch 5: T-Loss: 7.0191 | V-Loss: 6.7158 | IoU: 0.3456 | F1: 0.4913 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   6%|▌         | 6/100 [02:42<36:20, 23.19s/it, IoU=0.3157, F1=0.4583]Epoch 6: T-Loss: 6.6838 | V-Loss: 6.5916 | IoU: 0.3157 | F1: 0.4583
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   7%|▋         | 7/100 [03:05<35:14, 22.74s/it, IoU=0.4321, F1=0.5840]Epoch 7: T-Loss: 6.4332 | V-Loss: 6.4032 | IoU: 0.4321 | F1: 0.5840 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   8%|▊         | 8/100 [03:25<34:36, 22.57s/it, IoU=0.3868, F1=0.5394]Epoch 8: T-Loss: 6.2429 | V-Loss: 6.3186 | IoU: 0.3868 | F1: 0.5394
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:   9%|▉         | 9/100 [03:46<33:18, 21.96s/it, IoU=0.4288, F1=0.5744]Epoch 9: T-Loss: 6.1281 | V-Loss: 6.0965 | IoU: 0.4288 | F1: 0.5744
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  10%|█         | 10/100 [04:08<32:36, 21.73s/it, IoU=0.4272, F1=0.5703]Epoch 10: T-Loss: 6.0423 | V-Loss: 6.0265 | IoU: 0.4272 | F1: 0.5703
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  11%|█         | 11/100 [04:33<32:13, 21.73s/it, IoU=0.4292, F1=0.5783]Epoch 11: T-Loss: 5.9508 | V-Loss: 6.1470 | IoU: 0.4292 | F1: 0.5783
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  12%|█▏        | 12/100 [04:54<33:16, 22.69s/it, IoU=0.4337, F1=0.5823]Epoch 12: T-Loss: 5.9506 | V-Loss: 5.9278 | IoU: 0.4337 | F1: 0.5823 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  13%|█▎        | 13/100 [05:22<32:25, 22.36s/it, IoU=0.4577, F1=0.6035]Epoch 13: T-Loss: 5.8114 | V-Loss: 5.9197 | IoU: 0.4577 | F1: 0.6035 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  14%|█▍        | 14/100 [05:51<34:27, 24.04s/it, IoU=0.4573, F1=0.6010]Epoch 14: T-Loss: 5.7934 | V-Loss: 5.8534 | IoU: 0.4573 | F1: 0.6010
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  15%|█▌        | 15/100 [06:15<35:51, 25.31s/it, IoU=0.4557, F1=0.6019]Epoch 15: T-Loss: 5.7142 | V-Loss: 5.8824 | IoU: 0.4557 | F1: 0.6019
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  16%|█▌        | 16/100 [06:37<34:51, 24.90s/it, IoU=0.4364, F1=0.5841]Epoch 16: T-Loss: 5.7300 | V-Loss: 5.9426 | IoU: 0.4364 | F1: 0.5841
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  17%|█▋        | 17/100 [07:00<33:26, 24.18s/it, IoU=0.4532, F1=0.5958]Epoch 17: T-Loss: 5.6679 | V-Loss: 5.8420 | IoU: 0.4532 | F1: 0.5958
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  18%|█▊        | 18/100 [07:24<32:22, 23.69s/it, IoU=0.4496, F1=0.5951]Epoch 18: T-Loss: 5.6874 | V-Loss: 5.8111 | IoU: 0.4496 | F1: 0.5951
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  19%|█▉        | 19/100 [07:45<32:05, 23.77s/it, IoU=0.4857, F1=0.6302]Epoch 19: T-Loss: 5.6265 | V-Loss: 5.7860 | IoU: 0.4857 | F1: 0.6302 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  20%|██        | 20/100 [08:06<30:41, 23.02s/it, IoU=0.4619, F1=0.6047]Epoch 20: T-Loss: 5.6639 | V-Loss: 5.8261 | IoU: 0.4619 | F1: 0.6047
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  21%|██        | 21/100 [08:27<29:30, 22.41s/it, IoU=0.4808, F1=0.6211]Epoch 21: T-Loss: 5.5442 | V-Loss: 5.7531 | IoU: 0.4808 | F1: 0.6211
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  22%|██▏       | 22/100 [08:48<28:33, 21.97s/it, IoU=0.4730, F1=0.6170]Epoch 22: T-Loss: 5.5456 | V-Loss: 5.7442 | IoU: 0.4730 | F1: 0.6170
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  23%|██▎       | 23/100 [09:11<27:59, 21.81s/it, IoU=0.4734, F1=0.6158]Epoch 23: T-Loss: 5.5316 | V-Loss: 5.7358 | IoU: 0.4734 | F1: 0.6158
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  24%|██▍       | 24/100 [09:32<28:01, 22.12s/it, IoU=0.4782, F1=0.6235]Epoch 24: T-Loss: 5.5046 | V-Loss: 5.7377 | IoU: 0.4782 | F1: 0.6235
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  25%|██▌       | 25/100 [09:53<27:08, 21.72s/it, IoU=0.4558, F1=0.6008]Epoch 25: T-Loss: 5.5338 | V-Loss: 5.7073 | IoU: 0.4558 | F1: 0.6008
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  26%|██▌       | 26/100 [10:14<26:33, 21.53s/it, IoU=0.4752, F1=0.6198]Epoch 26: T-Loss: 5.5027 | V-Loss: 5.6964 | IoU: 0.4752 | F1: 0.6198
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  27%|██▋       | 27/100 [10:38<26:06, 21.46s/it, IoU=0.4689, F1=0.6122]Epoch 27: T-Loss: 5.5652 | V-Loss: 5.7372 | IoU: 0.4689 | F1: 0.6122
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  28%|██▊       | 28/100 [11:01<26:19, 21.94s/it, IoU=0.4823, F1=0.6241]Epoch 28: T-Loss: 5.4777 | V-Loss: 5.6886 | IoU: 0.4823 | F1: 0.6241
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  29%|██▉       | 29/100 [11:24<26:30, 22.40s/it, IoU=0.5097, F1=0.6517]Epoch 29: T-Loss: 5.4504 | V-Loss: 5.6403 | IoU: 0.5097 | F1: 0.6517 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  30%|███       | 30/100 [11:48<26:15, 22.50s/it, IoU=0.4782, F1=0.6240]Epoch 30: T-Loss: 5.4887 | V-Loss: 5.6255 | IoU: 0.4782 | F1: 0.6240
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  31%|███       | 31/100 [12:15<26:37, 23.15s/it, IoU=0.4688, F1=0.6136]Epoch 31: T-Loss: 5.5031 | V-Loss: 5.6715 | IoU: 0.4688 | F1: 0.6136
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  32%|███▏      | 32/100 [12:42<27:32, 24.30s/it, IoU=0.4886, F1=0.6302]Epoch 32: T-Loss: 5.4507 | V-Loss: 5.6589 | IoU: 0.4886 | F1: 0.6302
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  33%|███▎      | 33/100 [13:07<27:59, 25.07s/it, IoU=0.5027, F1=0.6450]Epoch 33: T-Loss: 5.4190 | V-Loss: 5.6417 | IoU: 0.5027 | F1: 0.6450
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  34%|███▍      | 34/100 [13:30<27:30, 25.01s/it, IoU=0.4618, F1=0.6067]Epoch 34: T-Loss: 5.4727 | V-Loss: 5.6385 | IoU: 0.4618 | F1: 0.6067
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  35%|███▌      | 35/100 [13:54<26:19, 24.30s/it, IoU=0.5028, F1=0.6454]Epoch 35: T-Loss: 5.4484 | V-Loss: 5.6240 | IoU: 0.5028 | F1: 0.6454
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  36%|███▌      | 36/100 [14:27<25:54, 24.28s/it, IoU=0.5015, F1=0.6435]Epoch 36: T-Loss: 5.4364 | V-Loss: 5.6734 | IoU: 0.5015 | F1: 0.6435
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  37%|███▋      | 37/100 [14:50<28:09, 26.81s/it, IoU=0.5147, F1=0.6557]Epoch 37: T-Loss: 5.4336 | V-Loss: 5.6400 | IoU: 0.5147 | F1: 0.6557 [Saved Best Model]

  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  38%|███▊      | 38/100 [15:19<26:48, 25.94s/it, IoU=0.5085, F1=0.6512]Epoch 38: T-Loss: 5.4081 | V-Loss: 5.6524 | IoU: 0.5085 | F1: 0.6512
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  39%|███▉      | 39/100 [15:44<27:07, 26.67s/it, IoU=0.4985, F1=0.6420]Epoch 39: T-Loss: 5.3783 | V-Loss: 5.6445 | IoU: 0.4985 | F1: 0.6420
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  40%|████      | 40/100 [16:07<26:02, 26.05s/it, IoU=0.5045, F1=0.6485]Epoch 40: T-Loss: 5.3825 | V-Loss: 5.5811 | IoU: 0.5045 | F1: 0.6485
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  41%|████      | 41/100 [16:30<24:47, 25.22s/it, IoU=0.4658, F1=0.6123]Epoch 41: T-Loss: 5.4196 | V-Loss: 5.6569 | IoU: 0.4658 | F1: 0.6123
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  42%|████▏     | 42/100 [16:56<23:52, 24.70s/it, IoU=0.5080, F1=0.6515]Epoch 42: T-Loss: 5.3793 | V-Loss: 5.5872 | IoU: 0.5080 | F1: 0.6515
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  43%|████▎     | 43/100 [17:19<23:38, 24.88s/it, IoU=0.5059, F1=0.6509]Epoch 43: T-Loss: 5.3873 | V-Loss: 5.6036 | IoU: 0.5059 | F1: 0.6509
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  44%|████▍     | 44/100 [17:44<22:51, 24.49s/it, IoU=0.4962, F1=0.6403]Epoch 44: T-Loss: 5.3764 | V-Loss: 5.6076 | IoU: 0.4962 | F1: 0.6403
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  45%|████▌     | 45/100 [18:11<22:26, 24.48s/it, IoU=0.4976, F1=0.6439]Epoch 45: T-Loss: 5.3789 | V-Loss: 5.5712 | IoU: 0.4976 | F1: 0.6439
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  46%|████▌     | 46/100 [18:35<22:47, 25.32s/it, IoU=0.5153, F1=0.6576]Epoch 46: T-Loss: 5.3704 | V-Loss: 5.5792 | IoU: 0.5153 | F1: 0.6576 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  47%|████▋     | 47/100 [19:00<22:12, 25.14s/it, IoU=0.5053, F1=0.6485]Epoch 47: T-Loss: 5.3356 | V-Loss: 5.5956 | IoU: 0.5053 | F1: 0.6485
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  48%|████▊     | 48/100 [19:23<21:37, 24.94s/it, IoU=0.5145, F1=0.6566]Epoch 48: T-Loss: 5.3197 | V-Loss: 5.6464 | IoU: 0.5145 | F1: 0.6566
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  49%|████▉     | 49/100 [19:48<20:45, 24.42s/it, IoU=0.5118, F1=0.6554]Epoch 49: T-Loss: 5.3538 | V-Loss: 5.5645 | IoU: 0.5118 | F1: 0.6554
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  50%|█████     | 50/100 [20:12<20:17, 24.34s/it, IoU=0.5154, F1=0.6582]Epoch 50: T-Loss: 5.3264 | V-Loss: 5.5749 | IoU: 0.5154 | F1: 0.6582 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  51%|█████     | 51/100 [20:36<19:58, 24.46s/it, IoU=0.4858, F1=0.6310]Epoch 51: T-Loss: 5.3440 | V-Loss: 5.5872 | IoU: 0.4858 | F1: 0.6310
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  52%|█████▏    | 52/100 [20:59<19:29, 24.36s/it, IoU=0.5182, F1=0.6598]Epoch 52: T-Loss: 5.3121 | V-Loss: 5.6046 | IoU: 0.5182 | F1: 0.6598 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  53%|█████▎    | 53/100 [21:25<18:40, 23.84s/it, IoU=0.5209, F1=0.6629]Epoch 53: T-Loss: 5.3356 | V-Loss: 5.6002 | IoU: 0.5209 | F1: 0.6629 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  54%|█████▍    | 54/100 [21:48<18:51, 24.60s/it, IoU=0.5049, F1=0.6480]Epoch 54: T-Loss: 5.3644 | V-Loss: 5.6130 | IoU: 0.5049 | F1: 0.6480
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  55%|█████▌    | 55/100 [22:11<17:58, 23.97s/it, IoU=0.4943, F1=0.6389]Epoch 55: T-Loss: 5.3227 | V-Loss: 5.5993 | IoU: 0.4943 | F1: 0.6389
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  56%|█████▌    | 56/100 [22:32<17:24, 23.74s/it, IoU=0.4977, F1=0.6399]Epoch 56: T-Loss: 5.2999 | V-Loss: 5.6540 | IoU: 0.4977 | F1: 0.6399
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  57%|█████▋    | 57/100 [22:55<16:18, 22.75s/it, IoU=0.5059, F1=0.6490]Epoch 57: T-Loss: 5.2969 | V-Loss: 5.6095 | IoU: 0.5059 | F1: 0.6490
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  58%|█████▊    | 58/100 [23:18<16:01, 22.90s/it, IoU=0.5090, F1=0.6524]Epoch 58: T-Loss: 5.2988 | V-Loss: 5.6070 | IoU: 0.5090 | F1: 0.6524
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct:  59%|█████▉    | 59/100 [23:48<15:48, 23.15s/it, IoU=0.4815, F1=0.6249]Epoch 59: T-Loss: 5.3349 | V-Loss: 5.6074 | IoU: 0.4815 | F1: 0.6249

============================================================
Early Stopping Triggered at Epoch 59
  - Best Validation Loss: 5.5645
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_unetplusplus_efficientnet-b0.csv

Final results:
                                                      Experiment  ...  Test_Prec
0  UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TC-to-TB_10pct  ...   0.475318

[1 rows x 11 columns]
Running: /users/7/yu001011/csci5527/.venv/bin/python train_ttd.py --project-root /users/7/yu001011/csci5527/CSCI5527-final --experiment Shift-TA_TB-to-TC_10pct --arch UnetPlusPlus --encoder efficientnet-b0 --encoder-weights imagenet --epochs 100 --batch-size 16 --img-size 512 --lr 0.0001 --results-name layer3_arch_unetplusplus_efficientnet-b0.csv
Python executable: /users/7/yu001011/csci5527/.venv/bin/python
Torch version: 2.11.0+cu126
CUDA available: True
CUDA device count: 1
GPU 0: NVIDIA A100-SXM4-40GB
Using device: cuda:0

===== Running Shift-TA_TB-to-TC_10pct | arch=UnetPlusPlus | encoder=efficientnet-b0 =====
Loading CSV metadata...
Sanitizing training and validation masks...

Sanitizing Masks: 100%|██████████| 1028/1028 [00:00<00:00, 3215.30it/s]
Sanitizing Masks: 100%|██████████| 38/38 [00:00<00:00, 2933.13it/s]

Sanitizing test masks...
Generating Dataloaders...

Pipeline Ready:
 - Training batches: 50
 - Validation batches: 15
 - Testing batches: 3
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   0%|          | 0/100 [00:43<?, ?it/s, IoU=0.0993, F1=0.1760]Epoch 0: T-Loss: 9.3801 | V-Loss: 8.9251 | IoU: 0.0993 | F1: 0.1760 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   1%|          | 1/100 [01:26<1:11:06, 43.10s/it, IoU=0.1724, F1=0.2843]Epoch 1: T-Loss: 8.5929 | V-Loss: 8.2602 | IoU: 0.1724 | F1: 0.2843 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   2%|▏         | 2/100 [02:09<1:10:44, 43.31s/it, IoU=0.2521, F1=0.3871]Epoch 2: T-Loss: 8.0348 | V-Loss: 7.8329 | IoU: 0.2521 | F1: 0.3871 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   3%|▎         | 3/100 [02:46<1:09:59, 43.29s/it, IoU=0.1752, F1=0.2850]Epoch 3: T-Loss: 7.6110 | V-Loss: 7.5838 | IoU: 0.1752 | F1: 0.2850
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   4%|▍         | 4/100 [03:19<1:05:09, 40.72s/it, IoU=0.1960, F1=0.3067]Epoch 4: T-Loss: 7.1910 | V-Loss: 7.1007 | IoU: 0.1960 | F1: 0.3067
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   5%|▌         | 5/100 [03:57<59:54, 37.84s/it, IoU=0.3036, F1=0.4456]  Epoch 5: T-Loss: 6.8522 | V-Loss: 6.8358 | IoU: 0.3036 | F1: 0.4456 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   6%|▌         | 6/100 [04:31<59:36, 38.04s/it, IoU=0.3095, F1=0.4551]Epoch 6: T-Loss: 6.5678 | V-Loss: 6.4418 | IoU: 0.3095 | F1: 0.4551 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   7%|▋         | 7/100 [05:00<56:53, 36.70s/it, IoU=0.3687, F1=0.5240]Epoch 7: T-Loss: 6.3647 | V-Loss: 6.2307 | IoU: 0.3687 | F1: 0.5240 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   8%|▊         | 8/100 [05:29<52:24, 34.17s/it, IoU=0.3053, F1=0.4476]Epoch 8: T-Loss: 6.2173 | V-Loss: 6.0852 | IoU: 0.3053 | F1: 0.4476
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:   9%|▉         | 9/100 [05:55<49:17, 32.50s/it, IoU=0.4054, F1=0.5650]Epoch 9: T-Loss: 6.1254 | V-Loss: 5.9434 | IoU: 0.4054 | F1: 0.5650 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  10%|█         | 10/100 [06:23<45:50, 30.56s/it, IoU=0.4338, F1=0.5921]Epoch 10: T-Loss: 6.0281 | V-Loss: 5.8335 | IoU: 0.4338 | F1: 0.5921 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  11%|█         | 11/100 [06:55<44:27, 29.97s/it, IoU=0.4366, F1=0.5932]Epoch 11: T-Loss: 5.9268 | V-Loss: 5.7522 | IoU: 0.4366 | F1: 0.5932 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  12%|█▏        | 12/100 [07:30<44:40, 30.45s/it, IoU=0.4347, F1=0.5910]Epoch 12: T-Loss: 5.8821 | V-Loss: 5.6982 | IoU: 0.4347 | F1: 0.5910
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  13%|█▎        | 13/100 [08:01<46:00, 31.72s/it, IoU=0.4602, F1=0.6170]Epoch 13: T-Loss: 5.8840 | V-Loss: 5.6075 | IoU: 0.4602 | F1: 0.6170 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  14%|█▍        | 14/100 [08:38<45:06, 31.48s/it, IoU=0.4646, F1=0.6204]Epoch 14: T-Loss: 5.8649 | V-Loss: 5.6041 | IoU: 0.4646 | F1: 0.6204 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  15%|█▌        | 15/100 [09:08<47:16, 33.37s/it, IoU=0.4844, F1=0.6381]Epoch 15: T-Loss: 5.7968 | V-Loss: 5.6158 | IoU: 0.4844 | F1: 0.6381 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  16%|█▌        | 16/100 [09:48<45:07, 32.23s/it, IoU=0.5182, F1=0.6710]Epoch 16: T-Loss: 5.7325 | V-Loss: 5.5984 | IoU: 0.5182 | F1: 0.6710 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  17%|█▋        | 17/100 [10:20<47:55, 34.65s/it, IoU=0.4866, F1=0.6373]Epoch 17: T-Loss: 5.7558 | V-Loss: 5.5490 | IoU: 0.4866 | F1: 0.6373
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  18%|█▊        | 18/100 [10:47<45:56, 33.62s/it, IoU=0.4986, F1=0.6494]Epoch 18: T-Loss: 5.6832 | V-Loss: 5.5077 | IoU: 0.4986 | F1: 0.6494
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  19%|█▉        | 19/100 [11:16<42:56, 31.81s/it, IoU=0.5295, F1=0.6800]Epoch 19: T-Loss: 5.6673 | V-Loss: 5.5384 | IoU: 0.5295 | F1: 0.6800 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  20%|██        | 20/100 [11:49<41:22, 31.03s/it, IoU=0.4749, F1=0.6280]Epoch 20: T-Loss: 5.6750 | V-Loss: 5.5359 | IoU: 0.4749 | F1: 0.6280
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  21%|██        | 21/100 [12:23<41:32, 31.55s/it, IoU=0.5122, F1=0.6652]Epoch 21: T-Loss: 5.6317 | V-Loss: 5.5024 | IoU: 0.5122 | F1: 0.6652
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  22%|██▏       | 22/100 [13:01<41:47, 32.15s/it, IoU=0.5091, F1=0.6587]Epoch 22: T-Loss: 5.6242 | V-Loss: 5.5461 | IoU: 0.5091 | F1: 0.6587
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  23%|██▎       | 23/100 [13:33<43:38, 34.01s/it, IoU=0.5187, F1=0.6688]Epoch 23: T-Loss: 5.6213 | V-Loss: 5.5374 | IoU: 0.5187 | F1: 0.6688
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  24%|██▍       | 24/100 [14:04<42:16, 33.37s/it, IoU=0.5309, F1=0.6792]Epoch 24: T-Loss: 5.6127 | V-Loss: 5.4946 | IoU: 0.5309 | F1: 0.6792 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  25%|██▌       | 25/100 [14:47<41:00, 32.81s/it, IoU=0.5295, F1=0.6773]Epoch 25: T-Loss: 5.5549 | V-Loss: 5.4534 | IoU: 0.5295 | F1: 0.6773
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  26%|██▌       | 26/100 [15:25<44:02, 35.71s/it, IoU=0.5517, F1=0.6990]Epoch 26: T-Loss: 5.5921 | V-Loss: 5.4400 | IoU: 0.5517 | F1: 0.6990 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  27%|██▋       | 27/100 [16:04<44:14, 36.36s/it, IoU=0.5203, F1=0.6711]Epoch 27: T-Loss: 5.5197 | V-Loss: 5.4373 | IoU: 0.5203 | F1: 0.6711
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  28%|██▊       | 28/100 [16:37<44:38, 37.21s/it, IoU=0.5432, F1=0.6935]Epoch 28: T-Loss: 5.5140 | V-Loss: 5.4597 | IoU: 0.5432 | F1: 0.6935
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  29%|██▉       | 29/100 [17:05<42:32, 35.95s/it, IoU=0.5019, F1=0.6540]Epoch 29: T-Loss: 5.5420 | V-Loss: 5.4512 | IoU: 0.5019 | F1: 0.6540
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  30%|███       | 30/100 [17:34<39:10, 33.58s/it, IoU=0.5173, F1=0.6697]Epoch 30: T-Loss: 5.5074 | V-Loss: 5.4339 | IoU: 0.5173 | F1: 0.6697
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  31%|███       | 31/100 [18:03<37:01, 32.20s/it, IoU=0.5426, F1=0.6908]Epoch 31: T-Loss: 5.5155 | V-Loss: 5.4409 | IoU: 0.5426 | F1: 0.6908
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  32%|███▏      | 32/100 [18:36<35:31, 31.35s/it, IoU=0.5257, F1=0.6753]Epoch 32: T-Loss: 5.4947 | V-Loss: 5.4335 | IoU: 0.5257 | F1: 0.6753
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  33%|███▎      | 33/100 [19:09<35:21, 31.66s/it, IoU=0.5223, F1=0.6708]Epoch 33: T-Loss: 5.5139 | V-Loss: 5.4310 | IoU: 0.5223 | F1: 0.6708
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  34%|███▍      | 34/100 [19:43<35:24, 32.18s/it, IoU=0.5353, F1=0.6860]Epoch 34: T-Loss: 5.5210 | V-Loss: 5.4301 | IoU: 0.5353 | F1: 0.6860
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  35%|███▌      | 35/100 [20:13<35:29, 32.76s/it, IoU=0.5179, F1=0.6683]Epoch 35: T-Loss: 5.4843 | V-Loss: 5.4405 | IoU: 0.5179 | F1: 0.6683
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  36%|███▌      | 36/100 [20:47<34:04, 31.94s/it, IoU=0.5122, F1=0.6651]Epoch 36: T-Loss: 5.4591 | V-Loss: 5.4409 | IoU: 0.5122 | F1: 0.6651

  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  37%|███▋      | 37/100 [21:20<34:00, 32.39s/it, IoU=0.5133, F1=0.6640]Epoch 37: T-Loss: 5.4779 | V-Loss: 5.4079 | IoU: 0.5133 | F1: 0.6640
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  38%|███▊      | 38/100 [21:53<33:39, 32.57s/it, IoU=0.5337, F1=0.6838]Epoch 38: T-Loss: 5.4864 | V-Loss: 5.3948 | IoU: 0.5337 | F1: 0.6838
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  39%|███▉      | 39/100 [22:26<33:20, 32.79s/it, IoU=0.5404, F1=0.6899]Epoch 39: T-Loss: 5.4835 | V-Loss: 5.4203 | IoU: 0.5404 | F1: 0.6899
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  40%|████      | 40/100 [23:03<32:44, 32.74s/it, IoU=0.5334, F1=0.6852]Epoch 40: T-Loss: 5.4833 | V-Loss: 5.3914 | IoU: 0.5334 | F1: 0.6852
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  41%|████      | 41/100 [23:36<33:29, 34.06s/it, IoU=0.5439, F1=0.6942]Epoch 41: T-Loss: 5.4732 | V-Loss: 5.3884 | IoU: 0.5439 | F1: 0.6942
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  42%|████▏     | 42/100 [24:07<32:43, 33.86s/it, IoU=0.5363, F1=0.6862]Epoch 42: T-Loss: 5.4252 | V-Loss: 5.4162 | IoU: 0.5363 | F1: 0.6862
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  43%|████▎     | 43/100 [24:38<31:25, 33.08s/it, IoU=0.5411, F1=0.6904]Epoch 43: T-Loss: 5.4449 | V-Loss: 5.3916 | IoU: 0.5411 | F1: 0.6904
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  44%|████▍     | 44/100 [25:10<30:03, 32.20s/it, IoU=0.5582, F1=0.7051]Epoch 44: T-Loss: 5.4633 | V-Loss: 5.3665 | IoU: 0.5582 | F1: 0.7051 [Saved Best Model]
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  45%|████▌     | 45/100 [25:49<29:30, 32.19s/it, IoU=0.5440, F1=0.6941]Epoch 45: T-Loss: 5.4064 | V-Loss: 5.4136 | IoU: 0.5440 | F1: 0.6941
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  46%|████▌     | 46/100 [26:31<30:46, 34.20s/it, IoU=0.5555, F1=0.7059]Epoch 46: T-Loss: 5.4699 | V-Loss: 5.4394 | IoU: 0.5555 | F1: 0.7059
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  47%|████▋     | 47/100 [27:18<32:21, 36.63s/it, IoU=0.5472, F1=0.6967]Epoch 47: T-Loss: 5.4339 | V-Loss: 5.3966 | IoU: 0.5472 | F1: 0.6967
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  48%|████▊     | 48/100 [27:57<34:31, 39.84s/it, IoU=0.5192, F1=0.6694]Epoch 48: T-Loss: 5.4187 | V-Loss: 5.3965 | IoU: 0.5192 | F1: 0.6694
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  49%|████▉     | 49/100 [28:27<33:40, 39.62s/it, IoU=0.5576, F1=0.7054]Epoch 49: T-Loss: 5.4534 | V-Loss: 5.3933 | IoU: 0.5576 | F1: 0.7054
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  50%|█████     | 50/100 [29:03<30:35, 36.72s/it, IoU=0.5464, F1=0.6958]Epoch 50: T-Loss: 5.4009 | V-Loss: 5.3738 | IoU: 0.5464 | F1: 0.6958
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  51%|█████     | 51/100 [29:41<29:37, 36.28s/it, IoU=0.5482, F1=0.6977]Epoch 51: T-Loss: 5.5051 | V-Loss: 5.4076 | IoU: 0.5482 | F1: 0.6977
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  52%|█████▏    | 52/100 [30:15<29:38, 37.05s/it, IoU=0.5324, F1=0.6807]Epoch 52: T-Loss: 5.4240 | V-Loss: 5.4096 | IoU: 0.5324 | F1: 0.6807
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  53%|█████▎    | 53/100 [30:44<28:09, 35.95s/it, IoU=0.5306, F1=0.6795]Epoch 53: T-Loss: 5.4333 | V-Loss: 5.4277 | IoU: 0.5306 | F1: 0.6795
  → UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct:  54%|█████▍    | 54/100 [31:21<26:00, 33.92s/it, IoU=0.5202, F1=0.6681]Epoch 54: T-Loss: 5.4054 | V-Loss: 5.4012 | IoU: 0.5202 | F1: 0.6681

============================================================
Early Stopping Triggered at Epoch 54
  - Best Validation Loss: 5.3665
  - Patience Exhausted: 10/10 epochs without improvement
  - Stopping training now.
============================================================
Charts saved to /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/figures/
Visualization saved to figures/UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct_visualization.png
Saved interim results to: /users/7/yu001011/csci5527/CSCI5527-final/baseline_models_scripts/runs/layer3_arch_unetplusplus_efficientnet-b0.csv

Final results:
                                                      Experiment  ...  Test_Prec
0  UnetPlusPlus-efficientnet-b0-imagenet_Shift-TA_TB-to-TC_10pct  ...   0.529954

[1 rows x 11 columns]

## 7. Load Architecture Results

In [26]:
def load_arch_results(arches):
    frames = []
    for arch in arches:
        path = RESULTS_DIR / result_filename(arch)
        if path.exists():
            df = pd.read_csv(path)
            df['Architecture'] = arch
            frames.append(df)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)

arch_df = load_arch_results(ARCHES)
arch_df

Empty DataFrame
Columns: []
Index: []

## 8. Pivot Table for Comparison

In [27]:
if not arch_df.empty:
    arch_df = arch_df.copy()
    arch_df['Setting'] = arch_df['Experiment'].str.replace(r'^.+?_.+?_', '', regex=True)
    pivot_iou = arch_df.pivot(index='Setting', columns='Architecture', values='Test_IoU')
    pivot_f1 = arch_df.pivot(index='Setting', columns='Architecture', values='Test_F1')
    display(Markdown('### Test IoU'))
    display(pivot_iou)
    display(Markdown('### Test F1'))
    display(pivot_f1)
else:
    display(Markdown('No results available yet.'))

No results available yet.