# SAM3 TTD Few-Shot Experiment Runner

Run the **Experiment Selection** cell first. The notebook supports two workflows:

1. Single experiment: set `EXPERIMENT_KEY`, then call `run_train(EXPERIMENT_KEY)` / `run_eval(EXPERIMENT_KEY)` from the helper cell.
2. Batch experiment: run the **Batch Train + Eval** cell to process all stable 5 / 10 / 25 / 50-shot experiments for `Single-TB`, `Shift-TA_TC-to-TB_10pct`, and `Shift-TA_TB-to-TC_10pct`.

The batch order intentionally runs all `Single-TB` YAMLs first. This matches the safer ordering used after the earlier dtype / gradient issues.

In [1]:
# Experiment Selection
from pathlib import Path

PROJECT_ROOT = Path("/users/7/yu001011/csci5527")
SAM3_WORK_ROOT = PROJECT_ROOT / "CSCI5527-final" / "SAM3"
SAM3_REPO_ROOT = PROJECT_ROOT / "sam3"

# Experiment key constants. These let you write EXPERIMENT_KEY without quotes.
single_tb_5shot_stable_lowlr_v1 = "single_tb_5shot_stable_lowlr_v1"
single_tb_10shot_stable_lowlr_v1 = "single_tb_10shot_stable_lowlr_v1"
single_tb_25shot_stable_lowlr_v1 = "single_tb_25shot_stable_lowlr_v1"
single_tb_50shot_stable_lowlr_v1 = "single_tb_50shot_stable_lowlr_v1"
shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1 = "shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1"
shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1 = "shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1"
shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1 = "shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1"
shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1 = "shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1"
shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1 = "shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1"
shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1 = "shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1"
shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1 = "shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1"
shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1 = "shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1"
single_tb_5shot_clean_fp32_v1 = "single_tb_5shot_clean_fp32_v1"
single_tb_10shot_clean_fp32_v1 = "single_tb_10shot_clean_fp32_v1"
single_tb_25shot_clean_fp32_v1 = "single_tb_25shot_clean_fp32_v1"
single_tb_50shot_clean_fp32_v1 = "single_tb_50shot_clean_fp32_v1"
shift_ta_tc_to_tb_10pct_5shot_clean_fp32_v1 = "shift_ta_tc_to_tb_10pct_5shot_clean_fp32_v1"
shift_ta_tc_to_tb_10pct_10shot_clean_fp32_v1 = "shift_ta_tc_to_tb_10pct_10shot_clean_fp32_v1"
shift_ta_tc_to_tb_10pct_25shot_clean_fp32_v1 = "shift_ta_tc_to_tb_10pct_25shot_clean_fp32_v1"
shift_ta_tc_to_tb_10pct_50shot_clean_fp32_v1 = "shift_ta_tc_to_tb_10pct_50shot_clean_fp32_v1"
shift_ta_tb_to_tc_10pct_5shot_clean_fp32_v1 = "shift_ta_tb_to_tc_10pct_5shot_clean_fp32_v1"
shift_ta_tb_to_tc_10pct_10shot_clean_fp32_v1 = "shift_ta_tb_to_tc_10pct_10shot_clean_fp32_v1"
shift_ta_tb_to_tc_10pct_25shot_clean_fp32_v1 = "shift_ta_tb_to_tc_10pct_25shot_clean_fp32_v1"
shift_ta_tb_to_tc_10pct_50shot_clean_fp32_v1 = "shift_ta_tb_to_tc_10pct_50shot_clean_fp32_v1"

# Single-experiment default. Change this when you want to inspect one run with the IoU cell.
EXPERIMENT_KEY = single_tb_5shot_stable_lowlr_v1

EXPERIMENT_GROUPS = {
    "single_tb": "Single-TB",
    "shift_ta_tc_to_tb_10pct": "Shift-TA_TC-to-TB_10pct",
    "shift_ta_tb_to_tc_10pct": "Shift-TA_TB-to-TC_10pct",
}

# Important: keep Single-TB first. Running these YAMLs first avoids the earlier dtype/gradient issue.
BATCH_GROUP_ORDER = [
    "single_tb",
    "shift_ta_tc_to_tb_10pct",
    "shift_ta_tb_to_tc_10pct",
]
BATCH_SHOTS = [5, 10, 25, 50]
BATCH_RUN_TAG = "stable_lowlr_v1"

EXPERIMENTS = {}

def register_experiment(group_key, shot_per_class, run_tag):
    experiment_name = EXPERIMENT_GROUPS[group_key]
    config_stem = f"ttd_{group_key}_{shot_per_class}shot_textseg_{run_tag}"
    run_root = SAM3_WORK_ROOT / "fewshot_data" / experiment_name / f"{shot_per_class}_shot_per_class"
    run_dir = SAM3_WORK_ROOT / "outputs" / "fewshot_runs" / experiment_name / f"{shot_per_class}_shot_per_class_{run_tag}"
    key = f"{group_key}_{shot_per_class}shot_{run_tag}"
    EXPERIMENTS[key] = {
        "key": key,
        "experiment_name": experiment_name,
        "group_key": group_key,
        "shot_per_class": shot_per_class,
        "run_tag": run_tag,
        "run_root": run_root,
        "run_dir": run_dir,
        "train_config": f"configs/ttd_fewshot/{config_stem}.yaml",
        "test_config": f"configs/ttd_fewshot/{config_stem}_test_eval.yaml",
    }

for group_key in EXPERIMENT_GROUPS:
    for shot_per_class in (5, 10, 25, 50):
        register_experiment(group_key, shot_per_class, "stable_lowlr_v1")
        register_experiment(group_key, shot_per_class, "clean_fp32_v1")

BATCH_EXPERIMENT_KEYS = [
    f"{group_key}_{shot_per_class}shot_{BATCH_RUN_TAG}"
    for group_key in BATCH_GROUP_ORDER
    for shot_per_class in BATCH_SHOTS
]

def set_experiment(experiment_key):
    if experiment_key not in EXPERIMENTS:
        available = "\n".join(f"  - {key}" for key in sorted(EXPERIMENTS))
        raise KeyError(f"Unknown EXPERIMENT_KEY: {experiment_key}\nAvailable keys:\n{available}")

    experiment = EXPERIMENTS[experiment_key]
    train_config = experiment["train_config"]
    test_config = experiment["test_config"]
    run_root = experiment["run_root"]
    run_dir = experiment["run_dir"]
    checkpoint = run_dir / "checkpoints" / "checkpoint.pt"
    gt_json = run_root / "test" / "_annotations.coco.json"
    pred_json = run_dir / "dumps" / "ttd" / "test" / "coco_predictions_segm.json"

    train_config_path = SAM3_REPO_ROOT / "sam3" / "train" / train_config
    test_config_path = SAM3_REPO_ROOT / "sam3" / "train" / test_config
    for label, path in {
        "train config": train_config_path,
        "test config": test_config_path,
        "dataset root": run_root,
        "test ground truth": gt_json,
    }.items():
        if not path.exists():
            raise FileNotFoundError(f"Missing {label}: {path}")

    globals().update({
        "EXPERIMENT_KEY": experiment_key,
        "EXPERIMENT": experiment,
        "TRAIN_CONFIG": train_config,
        "TEST_CONFIG": test_config,
        "RUN_ROOT": run_root,
        "RUN_DIR": run_dir,
        "CHECKPOINT": checkpoint,
        "GT_JSON": gt_json,
        "PRED_JSON": pred_json,
        "TRAIN_CONFIG_PATH": train_config_path,
        "TEST_CONFIG_PATH": test_config_path,
    })
    return experiment

EXPERIMENT = set_experiment(EXPERIMENT_KEY)

print("Selected experiment:", EXPERIMENT_KEY)
print("Experiment name:", EXPERIMENT["experiment_name"])
print("Shot per class:", EXPERIMENT["shot_per_class"])
print("Run tag:", EXPERIMENT["run_tag"])
print("Training config:", TRAIN_CONFIG)
print("Test eval config:", TEST_CONFIG)
print("Dataset root:", RUN_ROOT)
print("Output dir:", RUN_DIR)
print("\nBatch run order:")
for idx, key in enumerate(BATCH_EXPERIMENT_KEYS, start=1):
    exp = EXPERIMENTS[key]
    print(f"{idx:02d}. {key} -> {exp['experiment_name']} / {exp['shot_per_class']}-shot")

Selected experiment: single_tb_5shot_stable_lowlr_v1
Experiment name: Single-TB
Shot per class: 5
Run tag: stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_single_tb_5shot_textseg_stable_lowlr_v1.yaml
Test eval config: configs/ttd_fewshot/ttd_single_tb_5shot_textseg_stable_lowlr_v1_test_eval.yaml
Dataset root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/5_shot_per_class
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/5_shot_per_class_stable_lowlr_v1

Batch run order:
01. single_tb_5shot_stable_lowlr_v1 -> Single-TB / 5-shot
02. single_tb_10shot_stable_lowlr_v1 -> Single-TB / 10-shot
03. single_tb_25shot_stable_lowlr_v1 -> Single-TB / 25-shot
04. single_tb_50shot_stable_lowlr_v1 -> Single-TB / 50-shot
05. shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1 -> Shift-TA_TC-to-TB_10pct / 5-shot
06. shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1 -> Shift-TA_TC-to-TB_10pct / 10-shot
07. shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1 -> Shift-TA_TC-to-TB_10pct / 25-shot
08. shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1 -> Shift-TA_TC-to-TB_10pct / 50-shot
09. shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1 -> Shift-TA_TB-to-TC_10pct / 5-shot
10. shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1 -> Shift-TA_TB-to-TC_10pct / 10-shot
11. shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1 -> Shift-TA_TB-to-TC_10pct / 25-shot
12. shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1 -> Shift-TA_TB-to-TC_10pct / 50-shot

In [2]:
# Train/Eval Helpers
import os
import subprocess
import sys
from datetime import datetime

if "EXPERIMENTS" not in globals():
    raise RuntimeError("Run the Experiment Selection cell first.")

RUN_ENV = os.environ.copy()
RUN_ENV.setdefault("HYDRA_FULL_ERROR", "1")

def _train_cmd(config):
    return [
        sys.executable,
        "-m", "sam3.train.train",
        "-c", config,
        "--use-cluster", "0",
        "--num-gpus", "1",
    ]

def _run_sam3_command(cmd, label, experiment_key):
    print("=" * 100)
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {label}: {experiment_key}")
    print("Command:", " ".join(cmd))
    return subprocess.run(cmd, check=True, cwd=str(SAM3_REPO_ROOT), env=RUN_ENV)

def run_train(experiment_key=None, skip_existing=True):
    experiment_key = experiment_key or EXPERIMENT_KEY
    experiment = set_experiment(experiment_key)
    print("Selected experiment:", experiment_key)
    print("Training config:", TRAIN_CONFIG)
    print("Output dir:", RUN_DIR)

    if skip_existing and CHECKPOINT.exists():
        print("Skipping train because checkpoint already exists:", CHECKPOINT)
        return "skipped"

    _run_sam3_command(_train_cmd(TRAIN_CONFIG), "TRAIN", experiment_key)
    print("Checkpoint:", CHECKPOINT)
    print("Checkpoint exists:", CHECKPOINT.exists())
    return "trained"

def run_eval(experiment_key=None, skip_existing=True):
    experiment_key = experiment_key or EXPERIMENT_KEY
    experiment = set_experiment(experiment_key)
    print("Selected experiment:", experiment_key)
    print("Test eval config:", TEST_CONFIG)
    print("Using checkpoint:", CHECKPOINT)

    if not CHECKPOINT.exists():
        raise FileNotFoundError(f"Train checkpoint not found yet: {CHECKPOINT}")
    if skip_existing and PRED_JSON.exists() and PRED_JSON.stat().st_size > 2:
        print("Skipping eval because prediction file already exists:", PRED_JSON)
        return "skipped"

    _run_sam3_command(_train_cmd(TEST_CONFIG), "TEST EVAL", experiment_key)
    print("Prediction file:", PRED_JSON)
    print("Prediction exists:", PRED_JSON.exists())
    return "evaluated"

def run_train_and_eval_many(
    experiment_keys,
    do_train=True,
    do_eval=True,
    skip_existing_train=True,
    skip_existing_eval=True,
    stop_on_error=True,
):
    results = []
    for idx, experiment_key in enumerate(experiment_keys, start=1):
        experiment = EXPERIMENTS[experiment_key]
        print("\n" + "#" * 100)
        print(
            f"Batch item {idx}/{len(experiment_keys)}: {experiment_key} "
            f"({experiment['experiment_name']}, {experiment['shot_per_class']}-shot)"
        )
        train_status = "not_requested"
        eval_status = "not_requested"
        error = None
        try:
            if do_train:
                train_status = run_train(experiment_key, skip_existing=skip_existing_train)
            if do_eval:
                eval_status = run_eval(experiment_key, skip_existing=skip_existing_eval)
        except Exception as exc:
            error = repr(exc)
            print(f"ERROR in {experiment_key}: {error}")
            if stop_on_error:
                raise
        results.append({
            "experiment_key": experiment_key,
            "experiment_name": experiment["experiment_name"],
            "shot_per_class": experiment["shot_per_class"],
            "run_tag": experiment["run_tag"],
            "train_status": train_status,
            "eval_status": eval_status,
            "checkpoint": str(CHECKPOINT),
            "prediction_json": str(PRED_JSON),
            "error": error,
        })
    return results

In [3]:
# Batch Train + Eval: all stable few-shot experiments
# This runs Single-TB first, then the two domain-shift combinations.
# Set SKIP_EXISTING_* to False if you want to force reruns.

if "BATCH_EXPERIMENT_KEYS" not in globals():
    raise RuntimeError("Run the Experiment Selection cell first.")
if "run_train_and_eval_many" not in globals():
    raise RuntimeError("Run the Train/Eval Helpers cell first.")

BATCH_DO_TRAIN = True
BATCH_DO_EVAL = True
SKIP_EXISTING_TRAIN = True
SKIP_EXISTING_EVAL = True
STOP_ON_ERROR = True

batch_results = run_train_and_eval_many(
    BATCH_EXPERIMENT_KEYS,
    do_train=BATCH_DO_TRAIN,
    do_eval=BATCH_DO_EVAL,
    skip_existing_train=SKIP_EXISTING_TRAIN,
    skip_existing_eval=SKIP_EXISTING_EVAL,
    stop_on_error=STOP_ON_ERROR,
)

try:
    import pandas as pd
    display(pd.DataFrame(batch_results))
except Exception:
    for row in batch_results:
        print(row)

####################################################################################################
Batch item 1/12: single_tb_5shot_stable_lowlr_v1 (Single-TB, 5-shot)
Selected experiment: single_tb_5shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_single_tb_5shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/5_shot_per_class_stable_lowlr_v1
Skipping train because checkpoint already exists: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Selected experiment: single_tb_5shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_single_tb_5shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Skipping eval because prediction file already exists: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/5_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json

####################################################################################################
Batch item 2/12: single_tb_10shot_stable_lowlr_v1 (Single-TB, 10-shot)
Selected experiment: single_tb_10shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_single_tb_10shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 11:18:18] TRAIN: single_tb_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_10shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 11:18:52,774 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 11:18:52,862 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 11:18:52,862 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=43046
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 11:18:52,863 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:18:52,872 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 11:19:11,643 trainer.py:1150: ====================
INFO 2026-05-03 11:19:11,709 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 11:19:11,713 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 11:19:17,070 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 11:19:17,072 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:19:17,072 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 11:19:17,080 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 94
Raw dataset length = 20

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 11:21:13,506 train_utils.py: 269: Train Epoch: [0][ 0/20] | Batch Time: 115.01 (115.01) | Data Time: 9.35 (9.35) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 1.57e+02 (1.57e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:21:37,004 train_utils.py: 269: Train Epoch: [0][10/20] | Batch Time: 2.34 (12.59) | Data Time: 0.00 (0.86) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 2.30e+02 (1.07e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:21:58,509 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 11:21:58,509 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:21:58,510 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 84.97378282546997, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.036432874388992786, 'Losses/train_all_loss_giou': 0.13217055201530456, 'Losses/train_all_loss_bbox_o2m': 0.18162281513214112, 'Losses/train_all_loss_giou_o2m': 0.6510825514793396, 'Losses/train_all_loss_ce': 0.008244136767461895, 'Losses/train_all_ce_f1': 0.15000000298023225, 'Losses/train_all_presence_loss': 0.1671146810054779, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.06691164188086987, 'Losses/train_all_ce_f1_o2m': 0.3324603244662285, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0058483453933149574, 'Losses/train_all_loss_dice': 0.36221170127391816, 'Losses/train_all_loss_mask_o2m': 0.04759092656895518, 'Losses/train_all_loss_dice_o2m': 2.5947237730026247, 'Losses/train_all_loss_bbox_aux_0': 0.051942954584956166, 'Losses/train_all_loss_giou_aux_0': 0.16776471138000487, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06609569266438484, 'Losses/train_all_loss_giou_aux_0_o2m': 0.24496703147888182, 'Losses/train_all_loss_ce_aux_0': 0.008376030577346682, 'Losses/train_all_ce_f1_aux_0': 0.11666666865348815, 'Losses/train_all_presence_loss_aux_0': 0.1528198138810694, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.032553767785429955, 'Losses/train_all_ce_f1_aux_0_o2m': 0.1515151545405388, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.049976061284542087, 'Losses/train_all_loss_giou_aux_1': 0.15354591310024263, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.04551187977194786, 'Losses/train_all_loss_giou_aux_1_o2m': 0.18334144353866577, 'Losses/train_all_loss_ce_aux_1': 0.008209577575325967, 'Losses/train_all_ce_f1_aux_1': 0.13333333432674407, 'Losses/train_all_presence_loss_aux_1': 0.15551182734780014, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03655685037374497, 'Losses/train_all_ce_f1_aux_1_o2m': 0.19094017446041106, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04709078520536423, 'Losses/train_all_loss_giou_aux_2': 0.1520070970058441, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.040940575674176215, 'Losses/train_all_loss_giou_aux_2_o2m': 0.18869733810424805, 'Losses/train_all_loss_ce_aux_2': 0.007953970320522785, 'Losses/train_all_ce_f1_aux_2': 0.16666666865348817, 'Losses/train_all_presence_loss_aux_2': 0.1589231512043625, 'Losses/train_all_presence_dec_acc_aux_2': 0.8, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03716367147862911, 'Losses/train_all_ce_f1_aux_2_o2m': 0.15714286118745804, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04631050936877727, 'Losses/train_all_loss_giou_aux_3': 0.1491983115673065, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.04000230953097343, 'Losses/train_all_loss_giou_aux_3_o2m': 0.19311282634735108, 'Losses/train_all_loss_ce_aux_3': 0.00790939382277429, 'Losses/train_all_ce_f1_aux_3': 0.21666666865348816, 'Losses/train_all_presence_loss_aux_3': 0.15900913025252522, 'Losses/train_all_presence_dec_acc_aux_3': 0.8, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0377702796831727, 'Losses/train_all_ce_f1_aux_3_o2m': 0.20000000298023224, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03842969909310341, 'Losses/train_all_loss_giou_aux_4': 0.13859410881996154, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.03107046112418175, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1551297664642334, 'Losses/train_all_loss_ce_aux_4': 0.008138005901128054, 'Losses/train_all_ce_f1_aux_4': 0.1833333343267441, 'Losses/train_all_presence_loss_aux_4': 0.1658703511580825, 'Losses/train_all_presence_dec_acc_aux_4': 0.8, 'Losses/train_all_loss_ce_aux_4_o2m': 0.038686664588749406, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2033333361148834, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 84.97378282546997, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.010398612194694578, 'Losses/train_all_loss_semantic_dice': 0.36525956988334657, 'Losses/train_all_miou_semantic_seg': 0.5873720780014992, 'Trainer/where': 0.2375, 'Trainer/epoch': 0, 'Trainer/steps_train': 20}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:22:24,348 train_utils.py: 269: Train Epoch: [1][ 0/20] | Batch Time: 9.69 (9.69) | Data Time: 7.18 (7.18) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.99e+02 (1.99e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:22:45,893 train_utils.py: 269: Train Epoch: [1][10/20] | Batch Time: 2.17 (2.84) | Data Time: 0.00 (0.67) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.20e+02 (1.04e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:23:07,174 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 11:23:07,175 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:23:07,175 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 89.1782477080822, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.04793300237506628, 'Losses/train_all_loss_giou': 0.13960179388523103, 'Losses/train_all_loss_bbox_o2m': 0.17478434666991233, 'Losses/train_all_loss_giou_o2m': 0.7090060710906982, 'Losses/train_all_loss_ce': 0.008219833113253116, 'Losses/train_all_ce_f1': 0.2833333373069763, 'Losses/train_all_presence_loss': 0.17970854663290084, 'Losses/train_all_presence_dec_acc': 0.85, 'Losses/train_all_loss_ce_o2m': 0.06254685297608376, 'Losses/train_all_ce_f1_o2m': 0.4187590256333351, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.006222319114021957, 'Losses/train_all_loss_dice': 0.35906506776809693, 'Losses/train_all_loss_mask_o2m': 0.05436628218740225, 'Losses/train_all_loss_dice_o2m': 2.5626532316207884, 'Losses/train_all_loss_bbox_aux_0': 0.055141684412956235, 'Losses/train_all_loss_giou_aux_0': 0.17126401364803315, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.07330571990460158, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2565991938114166, 'Losses/train_all_loss_ce_aux_0': 0.00787821845151484, 'Losses/train_all_ce_f1_aux_0': 0.225, 'Losses/train_all_presence_loss_aux_0': 0.17064648088999093, 'Losses/train_all_presence_dec_acc_aux_0': 0.85, 'Losses/train_all_loss_ce_aux_0_o2m': 0.03155826181173325, 'Losses/train_all_ce_f1_aux_0_o2m': 0.15651515424251555, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.037214488722383976, 'Losses/train_all_loss_giou_aux_1': 0.12758075892925264, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.08163842111825943, 'Losses/train_all_loss_giou_aux_1_o2m': 0.25045146942138674, 'Losses/train_all_loss_ce_aux_1': 0.00792036964558065, 'Losses/train_all_ce_f1_aux_1': 0.20000000298023224, 'Losses/train_all_presence_loss_aux_1': 0.1779320349916816, 'Losses/train_all_presence_dec_acc_aux_1': 0.85, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03812607694417238, 'Losses/train_all_ce_f1_aux_1_o2m': 0.16358586102724076, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04182641673833132, 'Losses/train_all_loss_giou_aux_2': 0.12513443529605867, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.06579873804003, 'Losses/train_all_loss_giou_aux_2_o2m': 0.2356857717037201, 'Losses/train_all_loss_ce_aux_2': 0.008134836703538895, 'Losses/train_all_ce_f1_aux_2': 0.21666666865348816, 'Losses/train_all_presence_loss_aux_2': 0.17873961171135305, 'Losses/train_all_presence_dec_acc_aux_2': 0.85, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03853984605520964, 'Losses/train_all_ce_f1_aux_2_o2m': 0.1472222238779068, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04183888509869575, 'Losses/train_all_loss_giou_aux_3': 0.12673918008804322, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06817687451839446, 'Losses/train_all_loss_giou_aux_3_o2m': 0.22460024952888488, 'Losses/train_all_loss_ce_aux_3': 0.008175492053851485, 'Losses/train_all_ce_f1_aux_3': 0.24166666865348815, 'Losses/train_all_presence_loss_aux_3': 0.17077934378758072, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0390170332044363, 'Losses/train_all_ce_f1_aux_3_o2m': 0.17722222506999968, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.04257865324616432, 'Losses/train_all_loss_giou_aux_4': 0.14187251329421996, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06651002429425716, 'Losses/train_all_loss_giou_aux_4_o2m': 0.22017979621887207, 'Losses/train_all_loss_ce_aux_4': 0.007943877996876837, 'Losses/train_all_ce_f1_aux_4': 0.2500000029802322, 'Losses/train_all_presence_loss_aux_4': 0.1755184591282159, 'Losses/train_all_presence_dec_acc_aux_4': 0.85, 'Losses/train_all_loss_ce_aux_4_o2m': 0.039418501779437065, 'Losses/train_all_ce_f1_aux_4_o2m': 0.17873737663030625, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 89.1782477080822, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.011651278543286025, 'Losses/train_all_loss_semantic_dice': 0.371769392490387, 'Losses/train_all_miou_semantic_seg': 0.5818778837099672, 'Trainer/where': 0.4875, 'Trainer/epoch': 1, 'Trainer/steps_train': 40}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:23:40,852 train_utils.py: 269: Train Epoch: [2][ 0/20] | Batch Time: 12.09 (12.09) | Data Time: 9.83 (9.83) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.78e+00 (2.78e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:24:02,603 train_utils.py: 269: Train Epoch: [2][10/20] | Batch Time: 2.37 (3.08) | Data Time: 0.00 (0.91) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.40e+02 (8.91e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:24:23,700 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:24:23,700 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:24:23,700 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 74.7443980038166, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.047584929317235944, 'Losses/train_all_loss_giou': 0.15102287530899047, 'Losses/train_all_loss_bbox_o2m': 0.1388036474585533, 'Losses/train_all_loss_giou_o2m': 0.5499643385410309, 'Losses/train_all_loss_ce': 0.008012418868020177, 'Losses/train_all_ce_f1': 0.2583333343267441, 'Losses/train_all_presence_loss': 0.1371856221696362, 'Losses/train_all_presence_dec_acc': 0.9, 'Losses/train_all_loss_ce_o2m': 0.05471402872353792, 'Losses/train_all_ce_f1_o2m': 0.5070940226316452, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.004661011439748108, 'Losses/train_all_loss_dice': 0.3661336123943329, 'Losses/train_all_loss_mask_o2m': 0.03382125627249479, 'Losses/train_all_loss_dice_o2m': 2.228656530380249, 'Losses/train_all_loss_bbox_aux_0': 0.04100506417453289, 'Losses/train_all_loss_giou_aux_0': 0.1656339704990387, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05689268447458744, 'Losses/train_all_loss_giou_aux_0_o2m': 0.23437659144401551, 'Losses/train_all_loss_ce_aux_0': 0.007850945135578513, 'Losses/train_all_ce_f1_aux_0': 0.13333333432674407, 'Losses/train_all_presence_loss_aux_0': 0.12565884753712453, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.032833745889365676, 'Losses/train_all_ce_f1_aux_0_o2m': 0.1333333358168602, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.039733347855508326, 'Losses/train_all_loss_giou_aux_1': 0.13729268908500672, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.056078102067112924, 'Losses/train_all_loss_giou_aux_1_o2m': 0.21175482273101806, 'Losses/train_all_loss_ce_aux_1': 0.008023894811049103, 'Losses/train_all_ce_f1_aux_1': 0.15833333432674407, 'Losses/train_all_presence_loss_aux_1': 0.12137073306366801, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03551608864217996, 'Losses/train_all_ce_f1_aux_1_o2m': 0.15871795117855073, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04163912907242775, 'Losses/train_all_loss_giou_aux_2': 0.1383047193288803, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.054333103075623515, 'Losses/train_all_loss_giou_aux_2_o2m': 0.2052062451839447, 'Losses/train_all_loss_ce_aux_2': 0.008139602933079004, 'Losses/train_all_ce_f1_aux_2': 0.20833333432674409, 'Losses/train_all_presence_loss_aux_2': 0.13028217060491443, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03580739889293909, 'Losses/train_all_ce_f1_aux_2_o2m': 0.15769342184066773, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04486179761588573, 'Losses/train_all_loss_giou_aux_3': 0.13287250697612762, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.07095042169094086, 'Losses/train_all_loss_giou_aux_3_o2m': 0.23262081146240235, 'Losses/train_all_loss_ce_aux_3': 0.008254562923684716, 'Losses/train_all_ce_f1_aux_3': 0.20833333432674409, 'Losses/train_all_presence_loss_aux_3': 0.12985057526966556, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03638175651431084, 'Losses/train_all_ce_f1_aux_3_o2m': 0.16912199258804322, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.044539650157094005, 'Losses/train_all_loss_giou_aux_4': 0.1394893169403076, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.08777491748332977, 'Losses/train_all_loss_giou_aux_4_o2m': 0.27190572023391724, 'Losses/train_all_loss_ce_aux_4': 0.007991988770663738, 'Losses/train_all_ce_f1_aux_4': 0.2583333343267441, 'Losses/train_all_presence_loss_aux_4': 0.13222532708896323, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03642447292804718, 'Losses/train_all_ce_f1_aux_4_o2m': 0.19316239655017853, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 74.7443980038166, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.010652759135700763, 'Losses/train_all_loss_semantic_dice': 0.3664876326918602, 'Losses/train_all_miou_semantic_seg': 0.5853046957403422, 'Trainer/where': 0.7375, 'Trainer/epoch': 2, 'Trainer/steps_train': 60}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:24:52,583 train_utils.py: 269: Train Epoch: [3][ 0/20] | Batch Time: 9.53 (9.53) | Data Time: 7.33 (7.33) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 2.15e+00 (2.15e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:25:14,259 train_utils.py: 269: Train Epoch: [3][10/20] | Batch Time: 2.35 (2.84) | Data Time: 0.00 (0.68) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 1.30e+02 (6.16e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:25:35,044 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:25:35,044 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:25:35,044 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 76.57752337753773, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.02876642011106014, 'Losses/train_all_loss_giou': 0.11256397664546966, 'Losses/train_all_loss_bbox_o2m': 0.22462881430983545, 'Losses/train_all_loss_giou_o2m': 0.6314805448055267, 'Losses/train_all_loss_ce': 0.008549510594457388, 'Losses/train_all_ce_f1': 0.2033333346247673, 'Losses/train_all_presence_loss': 0.11704765418544412, 'Losses/train_all_presence_dec_acc': 0.85, 'Losses/train_all_loss_ce_o2m': 0.06550870202481747, 'Losses/train_all_ce_f1_o2m': 0.4377777844667435, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.005055659334175289, 'Losses/train_all_loss_dice': 0.3525456637144089, 'Losses/train_all_loss_mask_o2m': 0.0423428044654429, 'Losses/train_all_loss_dice_o2m': 2.5166654765605925, 'Losses/train_all_loss_bbox_aux_0': 0.031332175433635714, 'Losses/train_all_loss_giou_aux_0': 0.1304266035556793, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05556855536997318, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2163801074028015, 'Losses/train_all_loss_ce_aux_0': 0.00863245758228004, 'Losses/train_all_ce_f1_aux_0': 0.16166666895151138, 'Losses/train_all_presence_loss_aux_0': 0.10828551459126175, 'Losses/train_all_presence_dec_acc_aux_0': 0.85, 'Losses/train_all_loss_ce_aux_0_o2m': 0.035641595162451266, 'Losses/train_all_ce_f1_aux_0_o2m': 0.10333333611488342, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.025600946322083474, 'Losses/train_all_loss_giou_aux_1': 0.0842786818742752, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.04707145653665066, 'Losses/train_all_loss_giou_aux_1_o2m': 0.17199227213859558, 'Losses/train_all_loss_ce_aux_1': 0.008891599671915173, 'Losses/train_all_ce_f1_aux_1': 0.19500000029802322, 'Losses/train_all_presence_loss_aux_1': 0.11615074293222279, 'Losses/train_all_presence_dec_acc_aux_1': 0.85, 'Losses/train_all_loss_ce_aux_1_o2m': 0.04100634548813105, 'Losses/train_all_ce_f1_aux_1_o2m': 0.15880453288555146, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.019870227575302123, 'Losses/train_all_loss_giou_aux_2': 0.0893942266702652, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03903044331818819, 'Losses/train_all_loss_giou_aux_2_o2m': 0.14216406345367433, 'Losses/train_all_loss_ce_aux_2': 0.008922156319022179, 'Losses/train_all_ce_f1_aux_2': 0.24166666865348815, 'Losses/train_all_presence_loss_aux_2': 0.11147301886230707, 'Losses/train_all_presence_dec_acc_aux_2': 0.85, 'Losses/train_all_loss_ce_aux_2_o2m': 0.04119311086833477, 'Losses/train_all_ce_f1_aux_2_o2m': 0.14427350759506224, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.033313597179949285, 'Losses/train_all_loss_giou_aux_3': 0.10912443399429321, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.04762888345867396, 'Losses/train_all_loss_giou_aux_3_o2m': 0.16186652183532715, 'Losses/train_all_loss_ce_aux_3': 0.008331731287762522, 'Losses/train_all_ce_f1_aux_3': 0.2366666689515114, 'Losses/train_all_presence_loss_aux_3': 0.11395342026371509, 'Losses/train_all_presence_dec_acc_aux_3': 0.85, 'Losses/train_all_loss_ce_aux_3_o2m': 0.042081912606954576, 'Losses/train_all_ce_f1_aux_3_o2m': 0.1691819339990616, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.026556400395929814, 'Losses/train_all_loss_giou_aux_4': 0.10853896141052247, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.049004497565329076, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15860068202018737, 'Losses/train_all_loss_ce_aux_4': 0.008543659467250109, 'Losses/train_all_ce_f1_aux_4': 0.21166666895151137, 'Losses/train_all_presence_loss_aux_4': 0.11673662895336748, 'Losses/train_all_presence_dec_acc_aux_4': 0.85, 'Losses/train_all_loss_ce_aux_4_o2m': 0.04270023051649332, 'Losses/train_all_ce_f1_aux_4_o2m': 0.15855922251939775, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 76.57752337753773, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.01086188422050327, 'Losses/train_all_loss_semantic_dice': 0.35799983739852903, 'Losses/train_all_miou_semantic_seg': 0.5890297858044505, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_train': 80}
INFO 2026-05-03 11:25:54,340 train_utils.py: 269: Val Epoch: [3][ 0/94] | Batch Time: 1.23 (1.23) | Data Time: 0.23 (0.23) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:02,773 train_utils.py: 269: Val Epoch: [3][10/94] | Batch Time: 0.65 (0.88) | Data Time: 0.02 (0.12) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:09,659 train_utils.py: 269: Val Epoch: [3][20/94] | Batch Time: 0.81 (0.79) | Data Time: 0.18 (0.09) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:16,293 train_utils.py: 269: Val Epoch: [3][30/94] | Batch Time: 0.66 (0.75) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:22,909 train_utils.py: 269: Val Epoch: [3][40/94] | Batch Time: 0.66 (0.73) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:29,726 train_utils.py: 269: Val Epoch: [3][50/94] | Batch Time: 0.65 (0.72) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:36,345 train_utils.py: 269: Val Epoch: [3][60/94] | Batch Time: 0.65 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:42,973 train_utils.py: 269: Val Epoch: [3][70/94] | Batch Time: 0.64 (0.70) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:49,606 train_utils.py: 269: Val Epoch: [3][80/94] | Batch Time: 0.65 (0.70) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:26:56,385 train_utils.py: 269: Val Epoch: [3][90/94] | Batch Time: 0.65 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 11:26:58,326 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:26:58,327 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:26:58,327 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 11:26:58,327 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 11:26:58,702 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 11:26:58,843 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
INFO 2026-05-03 11:26:58,993 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.03s)
creating index...
index created!
INFO 2026-05-03 11:26:59,023 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.30s).
Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.027
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.081
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.025
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.064
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.267
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.055
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.081
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.096
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.019
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.160
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 11:26:59,371 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.027408306570050205, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.08102386567699485, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.025216584158415843, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.006681890442805279, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.0640548975536342, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.2666666666666666, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.055319148936170216, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.08085106382978721, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.09574468085106383, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.019230769230769232, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.16, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_val': 94}

[rank0]:[W503 11:27:00.900964151 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: single_tb_10shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_single_tb_10shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 11:27:02] TEST EVAL: single_tb_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_10shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/10_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/10_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/10_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 11:27:11,183 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 11:27:11,197 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 11:27:11,197 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=44482
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 11:27:11,199 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:27:11,199 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 11:27:29,388 trainer.py:1150: ====================
INFO 2026-05-03 11:27:29,389 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 11:27:29,395 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 11:27:32,662 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 11:27:32,663 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:27:32,663 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 11:27:32,671 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 11:27:32.656086337 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 11:27:33,054 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 11:28:02,772 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 20.41 (20.41) | Data Time: 0.06 (0.06) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:28:10,411 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.86 (2.55) | Data Time: 0.22 (0.09) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:28:17,676 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.82 (1.68) | Data Time: 0.17 (0.09) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:28:25,011 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.69 (1.38) | Data Time: 0.05 (0.09) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:28:32,146 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.68 (1.21) | Data Time: 0.04 (0.08) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:28:36,891 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:28:36,891 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:28:36,892 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 11:28:36,892 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 11:28:37,132 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 11:28:37,211 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 11:28:37,234 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 11:28:37,248 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.027
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.017
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.029
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.027
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.300
INFO 2026-05-03 11:28:37,351 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.005847842608572483, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.026573248601454557, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.0005756389592447617, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.017353770487581913, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.010856650882479554, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.01343873517786561, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.029166666666666664, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.054166666666666675, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.054166666666666675, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.026666666666666665, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.075, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.3, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 11:28:37.843050098 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 3/12: single_tb_25shot_stable_lowlr_v1 (Single-TB, 25-shot)
Selected experiment: single_tb_25shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_single_tb_25shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 11:28:40] TRAIN: single_tb_25shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_25shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/25_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 25
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 11:28:49,635 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 11:28:49,644 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 11:28:49,644 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=31030
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 11:28:49,645 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:28:49,649 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 11:29:02,536 trainer.py:1150: ====================
INFO 2026-05-03 11:29:02,537 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 11:29:02,541 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 11:29:04,393 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 11:29:04,394 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:29:04,394 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 11:29:04,401 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 94
Raw dataset length = 50

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 11:30:46,524 train_utils.py: 269: Train Epoch: [0][ 0/50] | Batch Time: 101.55 (101.55) | Data Time: 7.43 (7.43) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 1.32e+02 (1.32e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:31:08,957 train_utils.py: 269: Train Epoch: [0][10/50] | Batch Time: 2.35 (11.27) | Data Time: 0.00 (0.68) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 2.02e+02 (1.04e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:31:30,553 train_utils.py: 269: Train Epoch: [0][20/50] | Batch Time: 2.17 (6.93) | Data Time: 0.03 (0.36) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 1.53e+02 (9.55e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:31:52,362 train_utils.py: 269: Train Epoch: [0][30/50] | Batch Time: 2.17 (5.40) | Data Time: 0.00 (0.25) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.56e+02 (9.48e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:32:14,014 train_utils.py: 269: Train Epoch: [0][40/50] | Batch Time: 2.16 (4.61) | Data Time: 0.05 (0.19) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 6.56e+00 (9.46e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:32:35,506 trainer.py:1042: Estimated time remaining: 00d 00h 10m
INFO 2026-05-03 11:32:35,506 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:32:35,506 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 91.77843282699585, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03889249483123422, 'Losses/train_all_loss_giou': 0.15408970832824706, 'Losses/train_all_loss_bbox_o2m': 0.14707188710570335, 'Losses/train_all_loss_giou_o2m': 0.6095131993293762, 'Losses/train_all_loss_ce': 0.008354995008558035, 'Losses/train_all_ce_f1': 0.20466666877269746, 'Losses/train_all_presence_loss': 0.25555061545222996, 'Losses/train_all_presence_dec_acc': 0.76, 'Losses/train_all_loss_ce_o2m': 0.0665949584543705, 'Losses/train_all_ce_f1_o2m': 0.2507783383131027, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0040368479490280156, 'Losses/train_all_loss_dice': 0.3614021348953247, 'Losses/train_all_loss_mask_o2m': 0.030627094302326442, 'Losses/train_all_loss_dice_o2m': 2.323445591926575, 'Losses/train_all_loss_bbox_aux_0': 0.05184850448742509, 'Losses/train_all_loss_giou_aux_0': 0.20930628657341002, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.09990311704576016, 'Losses/train_all_loss_giou_aux_0_o2m': 0.38155983209609984, 'Losses/train_all_loss_ce_aux_0': 0.008053547646850347, 'Losses/train_all_ce_f1_aux_0': 0.14666666746139526, 'Losses/train_all_presence_loss_aux_0': 0.2437910666130483, 'Losses/train_all_presence_dec_acc_aux_0': 0.74, 'Losses/train_all_loss_ce_aux_0_o2m': 0.03182250037789345, 'Losses/train_all_ce_f1_aux_0_o2m': 0.10710623025894166, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.05079529212787747, 'Losses/train_all_loss_giou_aux_1': 0.18042158603668212, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.08956615682691335, 'Losses/train_all_loss_giou_aux_1_o2m': 0.3193513488769531, 'Losses/train_all_loss_ce_aux_1': 0.008109452445060015, 'Losses/train_all_ce_f1_aux_1': 0.15800000131130218, 'Losses/train_all_presence_loss_aux_1': 0.2536417045816779, 'Losses/train_all_presence_dec_acc_aux_1': 0.76, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03724402964115143, 'Losses/train_all_ce_f1_aux_1_o2m': 0.14666955590248107, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04627678716555238, 'Losses/train_all_loss_giou_aux_2': 0.17083061575889588, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.09201094688847661, 'Losses/train_all_loss_giou_aux_2_o2m': 0.3075583004951477, 'Losses/train_all_loss_ce_aux_2': 0.008277656808495522, 'Losses/train_all_ce_f1_aux_2': 0.1813333350419998, 'Losses/train_all_presence_loss_aux_2': 0.24998173637315632, 'Losses/train_all_presence_dec_acc_aux_2': 0.74, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03826758801937103, 'Losses/train_all_ce_f1_aux_2_o2m': 0.1454285740852356, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.044253037758171555, 'Losses/train_all_loss_giou_aux_3': 0.15826491594314576, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06912062339484691, 'Losses/train_all_loss_giou_aux_3_o2m': 0.26650419235229494, 'Losses/train_all_loss_ce_aux_3': 0.008411051221191884, 'Losses/train_all_ce_f1_aux_3': 0.20466666877269746, 'Losses/train_all_presence_loss_aux_3': 0.24977951588109135, 'Losses/train_all_presence_dec_acc_aux_3': 0.74, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0391235277056694, 'Losses/train_all_ce_f1_aux_3_o2m': 0.12298412919044495, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.043115957640111446, 'Losses/train_all_loss_giou_aux_4': 0.1591750681400299, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06988306231796741, 'Losses/train_all_loss_giou_aux_4_o2m': 0.26987978935241697, 'Losses/train_all_loss_ce_aux_4': 0.0082982531003654, 'Losses/train_all_ce_f1_aux_4': 0.19466666877269745, 'Losses/train_all_presence_loss_aux_4': 0.25392810443416236, 'Losses/train_all_presence_dec_acc_aux_4': 0.76, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03965087465941906, 'Losses/train_all_ce_f1_aux_4_o2m': 0.12200866103172302, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 91.77843282699585, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.009421867625787854, 'Losses/train_all_loss_semantic_dice': 0.36815019965171814, 'Losses/train_all_miou_semantic_seg': 0.5820144482702017, 'Trainer/where': 0.245, 'Trainer/epoch': 0, 'Trainer/steps_train': 50}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:33:09,781 train_utils.py: 269: Train Epoch: [1][ 0/50] | Batch Time: 11.55 (11.55) | Data Time: 9.31 (9.31) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.93e+02 (1.93e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:33:31,534 train_utils.py: 269: Train Epoch: [1][10/50] | Batch Time: 2.33 (3.03) | Data Time: 0.00 (0.86) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.26e+01 (9.93e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:33:53,146 train_utils.py: 269: Train Epoch: [1][20/50] | Batch Time: 2.17 (2.62) | Data Time: 0.02 (0.46) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.24e+02 (9.79e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:34:14,882 train_utils.py: 269: Train Epoch: [1][30/50] | Batch Time: 2.17 (2.47) | Data Time: 0.00 (0.31) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.75e+02 (8.39e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:34:36,758 train_utils.py: 269: Train Epoch: [1][40/50] | Batch Time: 2.18 (2.40) | Data Time: 0.00 (0.24) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.46e+02 (9.02e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:34:58,715 trainer.py:1042: Estimated time remaining: 00d 00h 03m
INFO 2026-05-03 11:34:58,715 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:34:58,715 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 89.28978211522103, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03747702106833458, 'Losses/train_all_loss_giou': 0.13878699541091918, 'Losses/train_all_loss_bbox_o2m': 0.2491161821782589, 'Losses/train_all_loss_giou_o2m': 0.704622859954834, 'Losses/train_all_loss_ce': 0.0082864342443645, 'Losses/train_all_ce_f1': 0.21333333730697632, 'Losses/train_all_presence_loss': 0.2423313917312771, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.06635924946516752, 'Losses/train_all_ce_f1_o2m': 0.28910023808479307, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002906542210839689, 'Losses/train_all_loss_dice': 0.3430912351608276, 'Losses/train_all_loss_mask_o2m': 0.02439135981723666, 'Losses/train_all_loss_dice_o2m': 2.4268232655525206, 'Losses/train_all_loss_bbox_aux_0': 0.05495957437902689, 'Losses/train_all_loss_giou_aux_0': 0.1917737078666687, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.10701360374689102, 'Losses/train_all_loss_giou_aux_0_o2m': 0.33509269475936887, 'Losses/train_all_loss_ce_aux_0': 0.00796770626679063, 'Losses/train_all_ce_f1_aux_0': 0.1800000023841858, 'Losses/train_all_presence_loss_aux_0': 0.23008166522951798, 'Losses/train_all_presence_dec_acc_aux_0': 0.8, 'Losses/train_all_loss_ce_aux_0_o2m': 0.031652793511748316, 'Losses/train_all_ce_f1_aux_0_o2m': 0.12000288903713226, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.04748550798743963, 'Losses/train_all_loss_giou_aux_1': 0.1632935357093811, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.09279670044779778, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2916801238059998, 'Losses/train_all_loss_ce_aux_1': 0.008076850604265929, 'Losses/train_all_ce_f1_aux_1': 0.16666666865348817, 'Losses/train_all_presence_loss_aux_1': 0.23693092268193142, 'Losses/train_all_presence_dec_acc_aux_1': 0.78, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03593799792230129, 'Losses/train_all_ce_f1_aux_1_o2m': 0.13530158936977388, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04060869719833136, 'Losses/train_all_loss_giou_aux_2': 0.14985895037651062, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.06295291908085346, 'Losses/train_all_loss_giou_aux_2_o2m': 0.2635233449935913, 'Losses/train_all_loss_ce_aux_2': 0.008246049005538224, 'Losses/train_all_ce_f1_aux_2': 0.15666666865348816, 'Losses/train_all_presence_loss_aux_2': 0.24325824482832104, 'Losses/train_all_presence_dec_acc_aux_2': 0.78, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03645236350595951, 'Losses/train_all_ce_f1_aux_2_o2m': 0.1442568564414978, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03882636491209269, 'Losses/train_all_loss_giou_aux_3': 0.14222776174545287, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.059382032193243506, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2603750205039978, 'Losses/train_all_loss_ce_aux_3': 0.00837071442976594, 'Losses/train_all_ce_f1_aux_3': 0.2033333361148834, 'Losses/train_all_presence_loss_aux_3': 0.24399392924271524, 'Losses/train_all_presence_dec_acc_aux_3': 0.78, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03738633371889591, 'Losses/train_all_ce_f1_aux_3_o2m': 0.1432063513994217, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03844236083328724, 'Losses/train_all_loss_giou_aux_4': 0.1405695366859436, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05954158090054989, 'Losses/train_all_loss_giou_aux_4_o2m': 0.2609205913543701, 'Losses/train_all_loss_ce_aux_4': 0.00823347769677639, 'Losses/train_all_ce_f1_aux_4': 0.21000000357627868, 'Losses/train_all_presence_loss_aux_4': 0.24576402545440942, 'Losses/train_all_presence_dec_acc_aux_4': 0.78, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03754326820373535, 'Losses/train_all_ce_f1_aux_4_o2m': 0.14066666841506958, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 89.28978211522103, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.00860398172866553, 'Losses/train_all_loss_semantic_dice': 0.35643484354019167, 'Losses/train_all_miou_semantic_seg': 0.593669011045713, 'Trainer/where': 0.495, 'Trainer/epoch': 1, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:35:29,985 train_utils.py: 269: Train Epoch: [2][ 0/50] | Batch Time: 10.28 (10.28) | Data Time: 7.93 (7.93) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 6.01e-01 (6.01e-01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:35:51,826 train_utils.py: 269: Train Epoch: [2][10/50] | Batch Time: 2.37 (2.92) | Data Time: 0.03 (0.74) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.01e+02 (6.97e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:36:13,580 train_utils.py: 269: Train Epoch: [2][20/50] | Batch Time: 2.16 (2.57) | Data Time: 0.00 (0.39) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.34e+02 (8.86e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:36:35,336 train_utils.py: 269: Train Epoch: [2][30/50] | Batch Time: 2.17 (2.44) | Data Time: 0.03 (0.27) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.91e+02 (1.07e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:36:57,047 train_utils.py: 269: Train Epoch: [2][40/50] | Batch Time: 2.17 (2.37) | Data Time: 0.00 (0.21) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 1.41e+02 (8.87e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:37:18,161 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 11:37:18,161 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:37:18,162 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 86.42225505255163, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.0418366352468729, 'Losses/train_all_loss_giou': 0.14265037417411805, 'Losses/train_all_loss_bbox_o2m': 0.232697015106678, 'Losses/train_all_loss_giou_o2m': 0.6516853380203247, 'Losses/train_all_loss_ce': 0.008053342439234256, 'Losses/train_all_ce_f1': 0.19466666877269745, 'Losses/train_all_presence_loss': 0.257937238290906, 'Losses/train_all_presence_dec_acc': 0.74, 'Losses/train_all_loss_ce_o2m': 0.0636358580738306, 'Losses/train_all_ce_f1_o2m': 0.2956385910511017, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0023468445462640373, 'Losses/train_all_loss_dice': 0.3222289550304413, 'Losses/train_all_loss_mask_o2m': 0.019115961026400327, 'Losses/train_all_loss_dice_o2m': 2.200782423019409, 'Losses/train_all_loss_bbox_aux_0': 0.04717025887221098, 'Losses/train_all_loss_giou_aux_0': 0.16677850842475891, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.09019071601331234, 'Losses/train_all_loss_giou_aux_0_o2m': 0.3086833477020264, 'Losses/train_all_loss_ce_aux_0': 0.007976174410432578, 'Losses/train_all_ce_f1_aux_0': 0.11133333504199981, 'Losses/train_all_presence_loss_aux_0': 0.2529477092716843, 'Losses/train_all_presence_dec_acc_aux_0': 0.78, 'Losses/train_all_loss_ce_aux_0_o2m': 0.030825252942740917, 'Losses/train_all_ce_f1_aux_0_o2m': 0.1481962502002716, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.048898511314764616, 'Losses/train_all_loss_giou_aux_1': 0.15420358300209044, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.08733760798349977, 'Losses/train_all_loss_giou_aux_1_o2m': 0.27853753328323366, 'Losses/train_all_loss_ce_aux_1': 0.0077403347194194795, 'Losses/train_all_ce_f1_aux_1': 0.21000000238418579, 'Losses/train_all_presence_loss_aux_1': 0.24606108110921923, 'Losses/train_all_presence_dec_acc_aux_1': 0.76, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03409759782254696, 'Losses/train_all_ce_f1_aux_1_o2m': 0.13453968465328217, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.048156341947615144, 'Losses/train_all_loss_giou_aux_2': 0.1489175081253052, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.0778431292064488, 'Losses/train_all_loss_giou_aux_2_o2m': 0.25657793760299685, 'Losses/train_all_loss_ce_aux_2': 0.0078135172650218, 'Losses/train_all_ce_f1_aux_2': 0.2200000023841858, 'Losses/train_all_presence_loss_aux_2': 0.25545709010388234, 'Losses/train_all_presence_dec_acc_aux_2': 0.76, 'Losses/train_all_loss_ce_aux_2_o2m': 0.0353162944316864, 'Losses/train_all_ce_f1_aux_2_o2m': 0.13070130109786987, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04908339586108923, 'Losses/train_all_loss_giou_aux_3': 0.15242327094078065, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.07761085316538811, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2535342955589294, 'Losses/train_all_loss_ce_aux_3': 0.007836616951972247, 'Losses/train_all_ce_f1_aux_3': 0.2033333361148834, 'Losses/train_all_presence_loss_aux_3': 0.2516657731606392, 'Losses/train_all_presence_dec_acc_aux_3': 0.76, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03596447855234146, 'Losses/train_all_ce_f1_aux_3_o2m': 0.1424848508834839, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.04570432376116514, 'Losses/train_all_loss_giou_aux_4': 0.14590495586395263, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.08221028618514538, 'Losses/train_all_loss_giou_aux_4_o2m': 0.2596624755859375, 'Losses/train_all_loss_ce_aux_4': 0.007879005391150712, 'Losses/train_all_ce_f1_aux_4': 0.2000000023841858, 'Losses/train_all_presence_loss_aux_4': 0.2562574798293645, 'Losses/train_all_presence_dec_acc_aux_4': 0.76, 'Losses/train_all_loss_ce_aux_4_o2m': 0.036381490752100946, 'Losses/train_all_ce_f1_aux_4_o2m': 0.1463838404417038, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 86.42225505255163, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.008306787651963531, 'Losses/train_all_loss_semantic_dice': 0.3391235411167145, 'Losses/train_all_miou_semantic_seg': 0.6058002050127834, 'Trainer/where': 0.745, 'Trainer/epoch': 2, 'Trainer/steps_train': 150}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:37:53,278 train_utils.py: 269: Train Epoch: [3][ 0/50] | Batch Time: 11.99 (11.99) | Data Time: 9.70 (9.70) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 4.26e+01 (4.26e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:38:14,891 train_utils.py: 269: Train Epoch: [3][10/50] | Batch Time: 2.34 (3.05) | Data Time: 0.00 (0.89) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 9.48e+01 (1.01e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:38:36,372 train_utils.py: 269: Train Epoch: [3][20/50] | Batch Time: 2.14 (2.62) | Data Time: 0.00 (0.47) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 1.32e+00 (9.05e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:38:58,108 train_utils.py: 269: Train Epoch: [3][30/50] | Batch Time: 2.16 (2.48) | Data Time: 0.02 (0.33) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.05e+02 (9.36e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:39:19,682 train_utils.py: 269: Train Epoch: [3][40/50] | Batch Time: 2.17 (2.40) | Data Time: 0.00 (0.25) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.66e+02 (9.14e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:39:40,224 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:39:40,224 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:39:40,225 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 88.91323125995696, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.029354870971292257, 'Losses/train_all_loss_giou': 0.12811996459960937, 'Losses/train_all_loss_bbox_o2m': 0.2114202131330967, 'Losses/train_all_loss_giou_o2m': 0.6728525567054748, 'Losses/train_all_loss_ce': 0.007969971913844347, 'Losses/train_all_ce_f1': 0.22466666996479034, 'Losses/train_all_presence_loss': 0.2861489342243294, 'Losses/train_all_presence_dec_acc': 0.78, 'Losses/train_all_loss_ce_o2m': 0.06437530249357223, 'Losses/train_all_ce_f1_o2m': 0.3116413116455078, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0024523743463214487, 'Losses/train_all_loss_dice': 0.30997793316841127, 'Losses/train_all_loss_mask_o2m': 0.017321539809927344, 'Losses/train_all_loss_dice_o2m': 2.1926963901519776, 'Losses/train_all_loss_bbox_aux_0': 0.04391781773418188, 'Losses/train_all_loss_giou_aux_0': 0.19068456053733826, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.08097865104675293, 'Losses/train_all_loss_giou_aux_0_o2m': 0.3201545190811157, 'Losses/train_all_loss_ce_aux_0': 0.007740103006362915, 'Losses/train_all_ce_f1_aux_0': 0.18666666865348816, 'Losses/train_all_presence_loss_aux_0': 0.2935786907708098, 'Losses/train_all_presence_dec_acc_aux_0': 0.76, 'Losses/train_all_loss_ce_aux_0_o2m': 0.029100798293948172, 'Losses/train_all_ce_f1_aux_0_o2m': 0.19091575503349303, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.032259036116302015, 'Losses/train_all_loss_giou_aux_1': 0.13857748985290527, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.07135300759226083, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2889606022834778, 'Losses/train_all_loss_ce_aux_1': 0.008310748301446437, 'Losses/train_all_ce_f1_aux_1': 0.1900000023841858, 'Losses/train_all_presence_loss_aux_1': 0.28035975620208775, 'Losses/train_all_presence_dec_acc_aux_1': 0.76, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03312718614935875, 'Losses/train_all_ce_f1_aux_1_o2m': 0.17019047915935517, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.032002684138715265, 'Losses/train_all_loss_giou_aux_2': 0.13544708251953125, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.0661299087293446, 'Losses/train_all_loss_giou_aux_2_o2m': 0.24198498964309692, 'Losses/train_all_loss_ce_aux_2': 0.008077871073037386, 'Losses/train_all_ce_f1_aux_2': 0.1800000023841858, 'Losses/train_all_presence_loss_aux_2': 0.2930677150671545, 'Losses/train_all_presence_dec_acc_aux_2': 0.78, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03440929763019085, 'Losses/train_all_ce_f1_aux_2_o2m': 0.1757460343837738, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02907335601747036, 'Losses/train_all_loss_giou_aux_3': 0.11974662899971009, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06737758740782737, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2426047158241272, 'Losses/train_all_loss_ce_aux_3': 0.008095384407788515, 'Losses/train_all_ce_f1_aux_3': 0.2333333361148834, 'Losses/train_all_presence_loss_aux_3': 0.2883402883382223, 'Losses/train_all_presence_dec_acc_aux_3': 0.76, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03469284139573574, 'Losses/train_all_ce_f1_aux_3_o2m': 0.1500952398777008, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.02883578239008784, 'Losses/train_all_loss_giou_aux_4': 0.12612395167350768, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06957568909972905, 'Losses/train_all_loss_giou_aux_4_o2m': 0.2422255277633667, 'Losses/train_all_loss_ce_aux_4': 0.007997806221246719, 'Losses/train_all_ce_f1_aux_4': 0.22333333611488343, 'Losses/train_all_presence_loss_aux_4': 0.2940369947576255, 'Losses/train_all_presence_dec_acc_aux_4': 0.78, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03512711577117443, 'Losses/train_all_ce_f1_aux_4_o2m': 0.15377777934074402, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 88.91323125995696, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.007726551904343068, 'Losses/train_all_loss_semantic_dice': 0.3326560604572296, 'Losses/train_all_miou_semantic_seg': 0.6110932449251414, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_train': 200}
INFO 2026-05-03 11:40:03,962 train_utils.py: 269: Val Epoch: [3][ 0/94] | Batch Time: 0.91 (0.91) | Data Time: 0.19 (0.19) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:11,011 train_utils.py: 269: Val Epoch: [3][10/94] | Batch Time: 0.70 (0.72) | Data Time: 0.06 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:17,963 train_utils.py: 269: Val Epoch: [3][20/94] | Batch Time: 0.69 (0.71) | Data Time: 0.05 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:24,811 train_utils.py: 269: Val Epoch: [3][30/94] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:31,727 train_utils.py: 269: Val Epoch: [3][40/94] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:38,509 train_utils.py: 269: Val Epoch: [3][50/94] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:45,499 train_utils.py: 269: Val Epoch: [3][60/94] | Batch Time: 0.74 (0.70) | Data Time: 0.10 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 11:40:52,298 train_utils.py: 269: Val Epoch: [3][70/94] | Batch Time: 0.67 (0.69) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:40:59,283 train_utils.py: 269: Val Epoch: [3][80/94] | Batch Time: 0.67 (0.69) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:41:05,957 train_utils.py: 269: Val Epoch: [3][90/94] | Batch Time: 0.67 (0.69) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:41:07,976 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:41:07,976 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:41:07,976 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 11:41:07,976 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 11:41:08,193 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 11:41:08,349 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
INFO 2026-05-03 11:41:08,502 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.03s)
creating index...
index created!
INFO 2026-05-03 11:41:08,533 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.15s).
Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.048
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.204
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.025
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.028
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.093
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.283
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.087
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.111
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.132
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.200
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 11:41:08,736 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.048208731071448185, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.20395393565183867, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.025450682331609423, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.0277349459699088, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.09339216258213136, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.28333333333333327, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.08723404255319149, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.11063829787234043, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.13191489361702127, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.053846153846153856, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.2, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_val': 94}

[rank0]:[W503 11:41:09.121903626 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: single_tb_25shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_single_tb_25shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 11:41:11] TEST EVAL: single_tb_25shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_25shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/25_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 25
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/25_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/25_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/25_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 11:41:18,269 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 11:41:18,274 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 11:41:18,274 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=45885
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 11:41:18,275 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:41:18,275 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 11:41:34,636 trainer.py:1150: ====================
INFO 2026-05-03 11:41:34,636 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 11:41:34,640 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 11:41:37,600 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 11:41:37,601 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:41:37,601 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 11:41:37,608 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 11:41:37.595882898 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 11:41:37,869 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 11:42:12,509 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 19.73 (19.73) | Data Time: 0.06 (0.06) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:42:19,397 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.65 (2.42) | Data Time: 0.02 (0.07) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:42:26,506 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.67 (1.61) | Data Time: 0.07 (0.09) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:42:33,133 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.73 (1.30) | Data Time: 0.15 (0.08) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:42:39,501 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.73 (1.14) | Data Time: 0.14 (0.07) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 11:42:44,077 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 11:42:44,077 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:42:44,077 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 11:42:44,077 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 11:42:44,443 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 11:42:44,591 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 11:42:44,607 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 11:42:44,621 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.063
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.014
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.042
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.062
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.040
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.113
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.300
INFO 2026-05-03 11:42:44,721 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.012311526069549744, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.06281665627832633, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.0006972528238739367, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.021828367117311745, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.02161569211794702, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.01410931174089069, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.04166666666666667, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.0625, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.075, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.04, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.1125, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.3, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 11:42:45.059832695 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 4/12: single_tb_50shot_stable_lowlr_v1 (Single-TB, 50-shot)
Selected experiment: single_tb_50shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_single_tb_50shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 11:42:46] TRAIN: single_tb_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_50shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 11:42:55,154 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 11:42:55,168 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 11:42:55,168 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=29736
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 11:42:55,169 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:42:55,174 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 11:43:08,694 trainer.py:1150: ====================
INFO 2026-05-03 11:43:08,695 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 11:43:08,699 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 11:43:10,091 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 11:43:10,092 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 11:43:10,092 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 11:43:10,100 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

Raw dataset length = 94
Raw dataset length = 100

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:45:13,323 train_utils.py: 269: Train Epoch: [0][ 10/100] | Batch Time: 2.16 (11.16) | Data Time: 0.05 (0.56) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 7.06e-01 (5.19e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:45:35,097 train_utils.py: 269: Train Epoch: [0][ 20/100] | Batch Time: 2.17 (6.88) | Data Time: 0.00 (0.30) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 9.71e+01 (6.69e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:45:56,901 train_utils.py: 269: Train Epoch: [0][ 30/100] | Batch Time: 2.17 (5.37) | Data Time: 0.06 (0.21) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.41e+02 (8.22e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:46:18,719 train_utils.py: 269: Train Epoch: [0][ 40/100] | Batch Time: 2.16 (4.59) | Data Time: 0.00 (0.16) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 4.70e+00 (7.76e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:46:40,599 train_utils.py: 269: Train Epoch: [0][ 50/100] | Batch Time: 2.17 (4.12) | Data Time: 0.06 (0.13) | Mem (GB): 16.00 (16.53/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.34e+02 (8.28e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:47:02,475 train_utils.py: 269: Train Epoch: [0][ 60/100] | Batch Time: 2.16 (3.80) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.44/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.86e+00 (7.94e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:47:24,400 train_utils.py: 269: Train Epoch: [0][ 70/100] | Batch Time: 2.20 (3.58) | Data Time: 0.03 (0.10) | Mem (GB): 16.00 (16.38/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.68e+02 (8.19e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:47:46,387 train_utils.py: 269: Train Epoch: [0][ 80/100] | Batch Time: 2.18 (3.41) | Data Time: 0.00 (0.09) | Mem (GB): 16.00 (16.33/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 3.22e+02 (8.86e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:48:08,339 train_utils.py: 269: Train Epoch: [0][ 90/100] | Batch Time: 2.19 (3.27) | Data Time: 0.03 (0.08) | Mem (GB): 16.00 (16.30/43.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.08e+02 (8.66e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:48:29,593 trainer.py:1042: Estimated time remaining: 00d 00h 15m
INFO 2026-05-03 11:48:29,593 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:48:29,594 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 86.75600387051702, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03219202068634331, 'Losses/train_all_loss_giou': 0.13999850153923035, 'Losses/train_all_loss_bbox_o2m': 0.2014672877267003, 'Losses/train_all_loss_giou_o2m': 0.818741979598999, 'Losses/train_all_loss_ce': 0.0078846503701061, 'Losses/train_all_ce_f1': 0.22733333498239516, 'Losses/train_all_presence_loss': 0.23568308305169922, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.06313773106783628, 'Losses/train_all_ce_f1_o2m': 0.38412231504917144, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0034949760738527402, 'Losses/train_all_loss_dice': 0.32255806148052213, 'Losses/train_all_loss_mask_o2m': 0.0289132089773193, 'Losses/train_all_loss_dice_o2m': 2.280737134218216, 'Losses/train_all_loss_bbox_aux_0': 0.040221275184303525, 'Losses/train_all_loss_giou_aux_0': 0.18613886952400208, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.0698541685193777, 'Losses/train_all_loss_giou_aux_0_o2m': 0.31275835275650027, 'Losses/train_all_loss_ce_aux_0': 0.007787207132205367, 'Losses/train_all_ce_f1_aux_0': 0.1650000011920929, 'Losses/train_all_presence_loss_aux_0': 0.23450506380642763, 'Losses/train_all_presence_dec_acc_aux_0': 0.82, 'Losses/train_all_loss_ce_aux_0_o2m': 0.0317892687395215, 'Losses/train_all_ce_f1_aux_0_o2m': 0.16284271597862243, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.0361810374353081, 'Losses/train_all_loss_giou_aux_1': 0.15152352094650268, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06825659489259124, 'Losses/train_all_loss_giou_aux_1_o2m': 0.28098912715911867, 'Losses/train_all_loss_ce_aux_1': 0.007811862886883319, 'Losses/train_all_ce_f1_aux_1': 0.23066666811704636, 'Losses/train_all_presence_loss_aux_1': 0.23445047664281446, 'Losses/train_all_presence_dec_acc_aux_1': 0.82, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03565588250756264, 'Losses/train_all_ce_f1_aux_1_o2m': 0.18931890666484832, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.036113659292459487, 'Losses/train_all_loss_giou_aux_2': 0.14785159766674041, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.06703688446432352, 'Losses/train_all_loss_giou_aux_2_o2m': 0.27409255743026734, 'Losses/train_all_loss_ce_aux_2': 0.007701599067077041, 'Losses/train_all_ce_f1_aux_2': 0.23566666811704637, 'Losses/train_all_presence_loss_aux_2': 0.23290945517015643, 'Losses/train_all_presence_dec_acc_aux_2': 0.81, 'Losses/train_all_loss_ce_aux_2_o2m': 0.036725091077387334, 'Losses/train_all_ce_f1_aux_2_o2m': 0.17549206644296647, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03345567169599235, 'Losses/train_all_loss_giou_aux_3': 0.14183069944381713, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06408653456717729, 'Losses/train_all_loss_giou_aux_3_o2m': 0.26268097400665286, 'Losses/train_all_loss_ce_aux_3': 0.007882302119396627, 'Losses/train_all_ce_f1_aux_3': 0.22285714477300644, 'Losses/train_all_presence_loss_aux_3': 0.23194193135248498, 'Losses/train_all_presence_dec_acc_aux_3': 0.81, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03765564598143101, 'Losses/train_all_ce_f1_aux_3_o2m': 0.18465629130601882, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.033154552206397056, 'Losses/train_all_loss_giou_aux_4': 0.14069340884685516, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.0650995592866093, 'Losses/train_all_loss_giou_aux_4_o2m': 0.26989147782325745, 'Losses/train_all_loss_ce_aux_4': 0.00781477076932788, 'Losses/train_all_ce_f1_aux_4': 0.224000001847744, 'Losses/train_all_presence_loss_aux_4': 0.23458701411262153, 'Losses/train_all_presence_dec_acc_aux_4': 0.8, 'Losses/train_all_loss_ce_aux_4_o2m': 0.038141416236758235, 'Losses/train_all_ce_f1_aux_4_o2m': 0.18687266528606414, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 86.75600387051702, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.010185587025189307, 'Losses/train_all_loss_semantic_dice': 0.33888120859861376, 'Losses/train_all_miou_semantic_seg': 0.6061658956483007, 'Trainer/where': 0.2475, 'Trainer/epoch': 0, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:48:58,993 train_utils.py: 269: Train Epoch: [1][  0/100] | Batch Time: 11.85 (11.85) | Data Time: 9.53 (9.53) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 1.37e+02 (1.37e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:49:20,890 train_utils.py: 269: Train Epoch: [1][ 10/100] | Batch Time: 2.36 (3.07) | Data Time: 0.05 (0.88) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 2.72e-01 (6.21e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:49:42,633 train_utils.py: 269: Train Epoch: [1][ 20/100] | Batch Time: 2.17 (2.64) | Data Time: 0.00 (0.47) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 1.55e+02 (7.71e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:50:04,426 train_utils.py: 269: Train Epoch: [1][ 30/100] | Batch Time: 2.18 (2.49) | Data Time: 0.05 (0.32) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.84e+02 (6.75e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:50:26,309 train_utils.py: 269: Train Epoch: [1][ 40/100] | Batch Time: 2.16 (2.42) | Data Time: 0.00 (0.25) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 4.08e-01 (8.15e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:50:48,162 train_utils.py: 269: Train Epoch: [1][ 50/100] | Batch Time: 2.17 (2.37) | Data Time: 0.04 (0.20) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 3.30e-01 (7.63e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:51:10,086 train_utils.py: 269: Train Epoch: [1][ 60/100] | Batch Time: 2.16 (2.34) | Data Time: 0.00 (0.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 7.10e-02 (7.64e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:51:31,887 train_utils.py: 269: Train Epoch: [1][ 70/100] | Batch Time: 2.17 (2.32) | Data Time: 0.05 (0.15) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 6.36e-02 (7.82e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:51:53,825 train_utils.py: 269: Train Epoch: [1][ 80/100] | Batch Time: 2.19 (2.30) | Data Time: 0.00 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 2.18e+02 (7.59e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:52:15,816 train_utils.py: 269: Train Epoch: [1][ 90/100] | Batch Time: 2.18 (2.29) | Data Time: 0.01 (0.12) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 6.65e+00 (7.91e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:52:38,148 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 11:52:38,149 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:52:38,149 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 89.75610491934698, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03570864520967007, 'Losses/train_all_loss_giou': 0.1382206743955612, 'Losses/train_all_loss_bbox_o2m': 0.18661004036664963, 'Losses/train_all_loss_giou_o2m': 0.7715583062171936, 'Losses/train_all_loss_ce': 0.007209125435911119, 'Losses/train_all_ce_f1': 0.274666668176651, 'Losses/train_all_presence_loss': 0.3068591945266417, 'Losses/train_all_presence_dec_acc': 0.79, 'Losses/train_all_loss_ce_o2m': 0.05979580618441105, 'Losses/train_all_ce_f1_o2m': 0.4109238573908806, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0023669680702732877, 'Losses/train_all_loss_dice': 0.301708487868309, 'Losses/train_all_loss_mask_o2m': 0.01873166050063446, 'Losses/train_all_loss_dice_o2m': 2.1668980395793915, 'Losses/train_all_loss_bbox_aux_0': 0.03905073794536293, 'Losses/train_all_loss_giou_aux_0': 0.1669011515378952, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06819475457072258, 'Losses/train_all_loss_giou_aux_0_o2m': 0.3144358718395233, 'Losses/train_all_loss_ce_aux_0': 0.007354242615401745, 'Losses/train_all_ce_f1_aux_0': 0.20733333498239517, 'Losses/train_all_presence_loss_aux_0': 0.31094833485130946, 'Losses/train_all_presence_dec_acc_aux_0': 0.79, 'Losses/train_all_loss_ce_aux_0_o2m': 0.02821521949954331, 'Losses/train_all_ce_f1_aux_0_o2m': 0.16905311703681947, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03508222562260926, 'Losses/train_all_loss_giou_aux_1': 0.14217703640460969, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06848984491080046, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2700494742393494, 'Losses/train_all_loss_ce_aux_1': 0.007054635570384562, 'Losses/train_all_ce_f1_aux_1': 0.2650000011920929, 'Losses/train_all_presence_loss_aux_1': 0.29117534135976714, 'Losses/train_all_presence_dec_acc_aux_1': 0.79, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03196643527597189, 'Losses/train_all_ce_f1_aux_1_o2m': 0.18925053060054778, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03571661957539618, 'Losses/train_all_loss_giou_aux_2': 0.1419803410768509, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05843792480416596, 'Losses/train_all_loss_giou_aux_2_o2m': 0.24830745339393615, 'Losses/train_all_loss_ce_aux_2': 0.007066343161277473, 'Losses/train_all_ce_f1_aux_2': 0.2666666680574417, 'Losses/train_all_presence_loss_aux_2': 0.3035646921544412, 'Losses/train_all_presence_dec_acc_aux_2': 0.79, 'Losses/train_all_loss_ce_aux_2_o2m': 0.0328092996776104, 'Losses/train_all_ce_f1_aux_2_o2m': 0.1879513853788376, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03717440419830382, 'Losses/train_all_loss_giou_aux_3': 0.14343772292137147, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06488321170210838, 'Losses/train_all_loss_giou_aux_3_o2m': 0.255773845911026, 'Losses/train_all_loss_ce_aux_3': 0.007096013822592795, 'Losses/train_all_ce_f1_aux_3': 0.279000001847744, 'Losses/train_all_presence_loss_aux_3': 0.3038853571055279, 'Losses/train_all_presence_dec_acc_aux_3': 0.79, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03336086954921484, 'Losses/train_all_ce_f1_aux_3_o2m': 0.215648355782032, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03495247202925384, 'Losses/train_all_loss_giou_aux_4': 0.1380140721797943, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.056417420879006384, 'Losses/train_all_loss_giou_aux_4_o2m': 0.2461346924304962, 'Losses/train_all_loss_ce_aux_4': 0.007180464174598456, 'Losses/train_all_ce_f1_aux_4': 0.2763333350419998, 'Losses/train_all_presence_loss_aux_4': 0.3067384808100633, 'Losses/train_all_presence_dec_acc_aux_4': 0.79, 'Losses/train_all_loss_ce_aux_4_o2m': 0.034103061109781264, 'Losses/train_all_ce_f1_aux_4_o2m': 0.18587057769298554, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 89.75610491934698, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.008383999720681459, 'Losses/train_all_loss_semantic_dice': 0.3132467550039291, 'Losses/train_all_miou_semantic_seg': 0.6264096785429865, 'Trainer/where': 0.4975, 'Trainer/epoch': 1, 'Trainer/steps_train': 200}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:53:14,010 train_utils.py: 269: Train Epoch: [2][  0/100] | Batch Time: 13.23 (13.23) | Data Time: 10.71 (10.71) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.17e-03 (1.17e-03) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:53:35,876 train_utils.py: 269: Train Epoch: [2][ 10/100] | Batch Time: 2.35 (3.19) | Data Time: 0.01 (0.99) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 2.82e-03 (6.56e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:53:57,542 train_utils.py: 269: Train Epoch: [2][ 20/100] | Batch Time: 2.16 (2.70) | Data Time: 0.00 (0.52) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 2.78e-02 (6.98e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:54:19,193 train_utils.py: 269: Train Epoch: [2][ 30/100] | Batch Time: 2.16 (2.53) | Data Time: 0.02 (0.36) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 7.16e-03 (6.35e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:54:41,080 train_utils.py: 269: Train Epoch: [2][ 40/100] | Batch Time: 2.18 (2.45) | Data Time: 0.00 (0.28) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 8.90e+01 (6.62e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:55:02,948 train_utils.py: 269: Train Epoch: [2][ 50/100] | Batch Time: 2.16 (2.40) | Data Time: 0.01 (0.23) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 5.46e+00 (7.22e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:55:24,895 train_utils.py: 269: Train Epoch: [2][ 60/100] | Batch Time: 2.18 (2.36) | Data Time: 0.00 (0.19) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 1.02e+02 (9.02e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:55:46,798 train_utils.py: 269: Train Epoch: [2][ 70/100] | Batch Time: 2.19 (2.34) | Data Time: 0.07 (0.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 9.80e+01 (9.04e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:56:08,750 train_utils.py: 269: Train Epoch: [2][ 80/100] | Batch Time: 2.18 (2.32) | Data Time: 0.00 (0.15) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 9.43e+01 (9.88e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:56:30,696 train_utils.py: 269: Train Epoch: [2][ 90/100] | Batch Time: 2.17 (2.31) | Data Time: 0.05 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 1.17e-02 (9.15e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:56:51,677 trainer.py:1042: Estimated time remaining: 00d 00h 03m
INFO 2026-05-03 11:56:51,678 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 11:56:51,678 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 89.95281720667714, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.04026505056768656, 'Losses/train_all_loss_giou': 0.1451207035779953, 'Losses/train_all_loss_bbox_o2m': 0.21815012112259866, 'Losses/train_all_loss_giou_o2m': 0.7612495231628418, 'Losses/train_all_loss_ce': 0.007261623009108007, 'Losses/train_all_ce_f1': 0.25900000154972075, 'Losses/train_all_presence_loss': 0.32939342366897195, 'Losses/train_all_presence_dec_acc': 0.84, 'Losses/train_all_loss_ce_o2m': 0.05623949505388737, 'Losses/train_all_ce_f1_o2m': 0.40539223805069924, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002477635785471648, 'Losses/train_all_loss_dice': 0.2832613205909729, 'Losses/train_all_loss_mask_o2m': 0.014607875563087873, 'Losses/train_all_loss_dice_o2m': 1.944580272436142, 'Losses/train_all_loss_bbox_aux_0': 0.04959763122722507, 'Losses/train_all_loss_giou_aux_0': 0.20464245557785035, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.0785187805071473, 'Losses/train_all_loss_giou_aux_0_o2m': 0.33338996410369875, 'Losses/train_all_loss_ce_aux_0': 0.006558102383278311, 'Losses/train_all_ce_f1_aux_0': 0.23500000119209288, 'Losses/train_all_presence_loss_aux_0': 0.3239968458193744, 'Losses/train_all_presence_dec_acc_aux_0': 0.85, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026567472890019418, 'Losses/train_all_ce_f1_aux_0_o2m': 0.16510317742824554, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.04273260509595275, 'Losses/train_all_loss_giou_aux_1': 0.16240006625652315, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.0785991545766592, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2972207236289978, 'Losses/train_all_loss_ce_aux_1': 0.006880104392766952, 'Losses/train_all_ce_f1_aux_1': 0.24666666805744172, 'Losses/train_all_presence_loss_aux_1': 0.3292687957901785, 'Losses/train_all_presence_dec_acc_aux_1': 0.85, 'Losses/train_all_loss_ce_aux_1_o2m': 0.030301325060427188, 'Losses/train_all_ce_f1_aux_1_o2m': 0.19230736255645753, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04164204947650432, 'Losses/train_all_loss_giou_aux_2': 0.15808942914009094, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.07315688621252775, 'Losses/train_all_loss_giou_aux_2_o2m': 0.2873944365978241, 'Losses/train_all_loss_ce_aux_2': 0.007110292548313737, 'Losses/train_all_ce_f1_aux_2': 0.25566666811704636, 'Losses/train_all_presence_loss_aux_2': 0.3244200101884354, 'Losses/train_all_presence_dec_acc_aux_2': 0.85, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03130872119218111, 'Losses/train_all_ce_f1_aux_2_o2m': 0.19063492387533187, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04096817729063332, 'Losses/train_all_loss_giou_aux_3': 0.14945721566677095, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.0660071418993175, 'Losses/train_all_loss_giou_aux_3_o2m': 0.24652913570404053, 'Losses/train_all_loss_ce_aux_3': 0.007117085442878306, 'Losses/train_all_ce_f1_aux_3': 0.24566666841506957, 'Losses/train_all_presence_loss_aux_3': 0.3263225226404856, 'Losses/train_all_presence_dec_acc_aux_3': 0.84, 'Losses/train_all_loss_ce_aux_3_o2m': 0.032084954902529716, 'Losses/train_all_ce_f1_aux_3_o2m': 0.17364879846572875, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.0396204517967999, 'Losses/train_all_loss_giou_aux_4': 0.1469300627708435, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06469207022339106, 'Losses/train_all_loss_giou_aux_4_o2m': 0.24145516395568847, 'Losses/train_all_loss_ce_aux_4': 0.007095216396264732, 'Losses/train_all_ce_f1_aux_4': 0.24233333468437196, 'Losses/train_all_presence_loss_aux_4': 0.33168520348698904, 'Losses/train_all_presence_dec_acc_aux_4': 0.84, 'Losses/train_all_loss_ce_aux_4_o2m': 0.032776065431535245, 'Losses/train_all_ce_f1_aux_4_o2m': 0.1691457462310791, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 89.95281720667714, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.008728420486440881, 'Losses/train_all_loss_semantic_dice': 0.31058256059885025, 'Losses/train_all_miou_semantic_seg': 0.6268302228115499, 'Trainer/where': 0.7475, 'Trainer/epoch': 2, 'Trainer/steps_train': 300}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 11:57:24,549 train_utils.py: 269: Train Epoch: [3][  0/100] | Batch Time: 12.19 (12.19) | Data Time: 8.90 (8.90) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 3.30e+02 (3.30e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:57:46,424 train_utils.py: 269: Train Epoch: [3][ 10/100] | Batch Time: 2.37 (3.10) | Data Time: 0.01 (0.83) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 6.67e+01 (1.19e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:58:08,133 train_utils.py: 269: Train Epoch: [3][ 20/100] | Batch Time: 2.15 (2.66) | Data Time: 0.00 (0.44) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 5.12e-03 (1.22e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:58:29,901 train_utils.py: 269: Train Epoch: [3][ 30/100] | Batch Time: 2.16 (2.50) | Data Time: 0.00 (0.30) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 4.15e-03 (1.04e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:58:51,591 train_utils.py: 269: Train Epoch: [3][ 40/100] | Batch Time: 2.17 (2.42) | Data Time: 0.00 (0.23) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 1.19e+02 (9.34e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:59:13,311 train_utils.py: 269: Train Epoch: [3][ 50/100] | Batch Time: 2.18 (2.37) | Data Time: 0.00 (0.19) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 9.95e+01 (9.70e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:59:35,200 train_utils.py: 269: Train Epoch: [3][ 60/100] | Batch Time: 2.17 (2.34) | Data Time: 0.00 (0.16) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 9.40e+01 (9.07e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 11:59:57,113 train_utils.py: 269: Train Epoch: [3][ 70/100] | Batch Time: 2.18 (2.32) | Data Time: 0.02 (0.14) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 1.26e+02 (9.97e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:00:18,848 train_utils.py: 269: Train Epoch: [3][ 80/100] | Batch Time: 2.17 (2.30) | Data Time: 0.00 (0.12) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 1.93e-04 (9.08e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:00:40,817 train_utils.py: 269: Train Epoch: [3][ 90/100] | Batch Time: 2.17 (2.29) | Data Time: 0.01 (0.11) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 5.22e-03 (9.27e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:01:01,776 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:01:01,776 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:01:01,776 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 90.90647735283586, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03147955853492022, 'Losses/train_all_loss_giou': 0.13442789196968077, 'Losses/train_all_loss_bbox_o2m': 0.1446243955940008, 'Losses/train_all_loss_giou_o2m': 0.6500396513938904, 'Losses/train_all_loss_ce': 0.007202094732783735, 'Losses/train_all_ce_f1': 0.27966666787862776, 'Losses/train_all_presence_loss': 0.3644474658007728, 'Losses/train_all_presence_dec_acc': 0.81, 'Losses/train_all_loss_ce_o2m': 0.05847378302365541, 'Losses/train_all_ce_f1_o2m': 0.3933324027061462, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.001685604016383877, 'Losses/train_all_loss_dice': 0.27268225491046905, 'Losses/train_all_loss_mask_o2m': 0.013196006233338267, 'Losses/train_all_loss_dice_o2m': 1.8364989733695984, 'Losses/train_all_loss_bbox_aux_0': 0.044985726727172735, 'Losses/train_all_loss_giou_aux_0': 0.1821509552001953, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.07111918792128563, 'Losses/train_all_loss_giou_aux_0_o2m': 0.304740891456604, 'Losses/train_all_loss_ce_aux_0': 0.0069214180018752815, 'Losses/train_all_ce_f1_aux_0': 0.20666666805744172, 'Losses/train_all_presence_loss_aux_0': 0.364661204037551, 'Losses/train_all_presence_dec_acc_aux_0': 0.81, 'Losses/train_all_loss_ce_aux_0_o2m': 0.02660202346742153, 'Losses/train_all_ce_f1_aux_0_o2m': 0.16102830827236175, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03722656556405127, 'Losses/train_all_loss_giou_aux_1': 0.15039316236972808, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06929871054366231, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2679903829097748, 'Losses/train_all_loss_ce_aux_1': 0.007005037143826485, 'Losses/train_all_ce_f1_aux_1': 0.2400000011920929, 'Losses/train_all_presence_loss_aux_1': 0.35114257615525984, 'Losses/train_all_presence_dec_acc_aux_1': 0.83, 'Losses/train_all_loss_ce_aux_1_o2m': 0.030231303684413433, 'Losses/train_all_ce_f1_aux_1_o2m': 0.18225297212600708, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03326060795225203, 'Losses/train_all_loss_giou_aux_2': 0.13994006872177123, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.07497873447835446, 'Losses/train_all_loss_giou_aux_2_o2m': 0.27945889711380006, 'Losses/train_all_loss_ce_aux_2': 0.0072024979349225755, 'Losses/train_all_ce_f1_aux_2': 0.2523333349823952, 'Losses/train_all_presence_loss_aux_2': 0.3622065616246071, 'Losses/train_all_presence_dec_acc_aux_2': 0.82, 'Losses/train_all_loss_ce_aux_2_o2m': 0.030692116878926753, 'Losses/train_all_ce_f1_aux_2_o2m': 0.20881502121686935, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.030199873754754664, 'Losses/train_all_loss_giou_aux_3': 0.1327785247564316, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06294987734407187, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2552546560764313, 'Losses/train_all_loss_ce_aux_3': 0.007239948222413659, 'Losses/train_all_ce_f1_aux_3': 0.26400000125169754, 'Losses/train_all_presence_loss_aux_3': 0.36522724156850683, 'Losses/train_all_presence_dec_acc_aux_3': 0.82, 'Losses/train_all_loss_ce_aux_3_o2m': 0.031664549484848974, 'Losses/train_all_ce_f1_aux_3_o2m': 0.21318254202604295, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03287124891765416, 'Losses/train_all_loss_giou_aux_4': 0.13867886781692504, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06224482018500566, 'Losses/train_all_loss_giou_aux_4_o2m': 0.2516138458251953, 'Losses/train_all_loss_ce_aux_4': 0.007112879175692797, 'Losses/train_all_ce_f1_aux_4': 0.2780000016093254, 'Losses/train_all_presence_loss_aux_4': 0.36775559721170237, 'Losses/train_all_presence_dec_acc_aux_4': 0.81, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03217337425798178, 'Losses/train_all_ce_f1_aux_4_o2m': 0.20824359238147735, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 90.90647735283586, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.00857825594721362, 'Losses/train_all_loss_semantic_dice': 0.2952136915922165, 'Losses/train_all_miou_semantic_seg': 0.641318936678581, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_train': 400}
INFO 2026-05-03 12:01:22,910 train_utils.py: 269: Val Epoch: [3][ 0/94] | Batch Time: 1.22 (1.22) | Data Time: 0.16 (0.16) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:01:31,190 train_utils.py: 269: Val Epoch: [3][10/94] | Batch Time: 0.75 (0.86) | Data Time: 0.11 (0.11) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 12:01:39,641 train_utils.py: 269: Val Epoch: [3][20/94] | Batch Time: 0.67 (0.85) | Data Time: 0.03 (0.11) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:01:46,547 train_utils.py: 269: Val Epoch: [3][30/94] | Batch Time: 0.67 (0.80) | Data Time: 0.03 (0.09) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:01:53,325 train_utils.py: 269: Val Epoch: [3][40/94] | Batch Time: 0.69 (0.77) | Data Time: 0.04 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:00,192 train_utils.py: 269: Val Epoch: [3][50/94] | Batch Time: 0.68 (0.75) | Data Time: 0.04 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:07,379 train_utils.py: 269: Val Epoch: [3][60/94] | Batch Time: 0.81 (0.75) | Data Time: 0.17 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:14,139 train_utils.py: 269: Val Epoch: [3][70/94] | Batch Time: 0.66 (0.74) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:20,954 train_utils.py: 269: Val Epoch: [3][80/94] | Batch Time: 0.68 (0.73) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:27,868 train_utils.py: 269: Val Epoch: [3][90/94] | Batch Time: 0.67 (0.73) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:02:29,936 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:02:29,936 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:02:29,936 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:02:29,936 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:02:30,151 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 12:02:30,559 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 12:02:30,661 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.03s)
creating index...
index created!
INFO 2026-05-03 12:02:30,693 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.14s).
Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.065
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.232
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.026
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.046
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.113
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.400
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.117
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.138
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.151
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.077
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.215
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 12:02:30,884 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.06489993118418685, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.23190516375669734, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.02629114262777629, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.04644215292314351, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.11312695407322458, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.4, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.11702127659574468, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.13829787234042554, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.15106382978723404, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.07692307692307693, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.215, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_val': 94}

[rank0]:[W503 12:02:31.479784715 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: single_tb_50shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_single_tb_50shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 12:02:33] TEST EVAL: single_tb_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_single_tb_50shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Single-TB
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/50_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/50_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Single-TB/50_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:02:47,105 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:02:47,114 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:02:47,114 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=42005
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:02:47,115 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:02:47,116 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:03:03,867 trainer.py:1150: ====================
INFO 2026-05-03 12:03:03,867 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:03:03,871 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:03:08,430 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Single-TB/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 12:03:08,431 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:03:08,431 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:03:08,439 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 12:03:08.471914221 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:04:49,805 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 12:04:49,808 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:04:49,808 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:04:49,815 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 208
Raw dataset length = 10

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 12:06:34,667 train_utils.py: 269: Train Epoch: [0][ 0/10] | Batch Time: 104.24 (104.24) | Data Time: 10.05 (10.05) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 2.56e+00 (2.56e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:06:56,726 trainer.py:1042: Estimated time remaining: 00d 00h 06m
INFO 2026-05-03 12:06:56,726 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:06:56,726 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 61.787595653533934, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.024603774026036262, 'Losses/train_all_loss_giou': 0.06827906370162964, 'Losses/train_all_loss_bbox_o2m': 0.20779926851391792, 'Losses/train_all_loss_giou_o2m': 0.5625617623329162, 'Losses/train_all_loss_ce': 0.004725485295057297, 'Losses/train_all_ce_f1': 0.3666666686534882, 'Losses/train_all_presence_loss': 0.18330154847353697, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.04009932074695825, 'Losses/train_all_ce_f1_o2m': 0.678787887096405, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0025799612398259343, 'Losses/train_all_loss_dice': 0.20065224170684814, 'Losses/train_all_loss_mask_o2m': 0.02555679129436612, 'Losses/train_all_loss_dice_o2m': 1.584309208393097, 'Losses/train_all_loss_bbox_aux_0': 0.035825992934405804, 'Losses/train_all_loss_giou_aux_0': 0.10027117729187011, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.030393609218299387, 'Losses/train_all_loss_giou_aux_0_o2m': 0.13961952924728394, 'Losses/train_all_loss_ce_aux_0': 0.006086826696991921, 'Losses/train_all_ce_f1_aux_0': 0.26666666865348815, 'Losses/train_all_presence_loss_aux_0': 0.17338615115731953, 'Losses/train_all_presence_dec_acc_aux_0': 0.8, 'Losses/train_all_loss_ce_aux_0_o2m': 0.027624163404107095, 'Losses/train_all_ce_f1_aux_0_o2m': 0.1566666692495346, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.023773277271538974, 'Losses/train_all_loss_giou_aux_1': 0.06817005872726441, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.03954685349017382, 'Losses/train_all_loss_giou_aux_1_o2m': 0.11824556589126586, 'Losses/train_all_loss_ce_aux_1': 0.004892700514756143, 'Losses/train_all_ce_f1_aux_1': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_1': 0.16934196073561908, 'Losses/train_all_presence_dec_acc_aux_1': 0.8, 'Losses/train_all_loss_ce_aux_1_o2m': 0.029643291234970094, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2711111158132553, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.024038838129490613, 'Losses/train_all_loss_giou_aux_2': 0.0703271508216858, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03347120229154825, 'Losses/train_all_loss_giou_aux_2_o2m': 0.12046774625778198, 'Losses/train_all_loss_ce_aux_2': 0.004791550058871508, 'Losses/train_all_ce_f1_aux_2': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_2': 0.17731391899287702, 'Losses/train_all_presence_dec_acc_aux_2': 0.8, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03253854066133499, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2711111158132553, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.023898481298238038, 'Losses/train_all_loss_giou_aux_3': 0.06719809770584106, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.03546242415904999, 'Losses/train_all_loss_giou_aux_3_o2m': 0.11971033811569214, 'Losses/train_all_loss_ce_aux_3': 0.004770253412425518, 'Losses/train_all_ce_f1_aux_3': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_3': 0.17178718373179436, 'Losses/train_all_presence_dec_acc_aux_3': 0.8, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03313579708337784, 'Losses/train_all_ce_f1_aux_3_o2m': 0.25444444715976716, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.024171469174325465, 'Losses/train_all_loss_giou_aux_4': 0.06780059337615967, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.03707774039357901, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1191100001335144, 'Losses/train_all_loss_ce_aux_4': 0.004769760416820645, 'Losses/train_all_ce_f1_aux_4': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_4': 0.1758926335722208, 'Losses/train_all_presence_dec_acc_aux_4': 0.8, 'Losses/train_all_loss_ce_aux_4_o2m': 0.034076881408691403, 'Losses/train_all_ce_f1_aux_4_o2m': 0.26158730685710907, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 61.787595653533934, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005686184042133391, 'Losses/train_all_loss_semantic_dice': 0.22298375368118287, 'Losses/train_all_miou_semantic_seg': 0.7250971391797065, 'Trainer/where': 0.225, 'Trainer/epoch': 0, 'Trainer/steps_train': 10}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:07:34,391 train_utils.py: 269: Train Epoch: [1][ 0/10] | Batch Time: 16.15 (16.15) | Data Time: 13.81 (13.81) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 6.30e+01 (6.30e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:07:55,316 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 12:07:55,319 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:07:55,319 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 48.117148065567015, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.027633298933506013, 'Losses/train_all_loss_giou': 0.07238361239433289, 'Losses/train_all_loss_bbox_o2m': 0.21940154246985913, 'Losses/train_all_loss_giou_o2m': 0.6067472100257874, 'Losses/train_all_loss_ce': 0.004185295384377241, 'Losses/train_all_ce_f1': 0.4333333373069763, 'Losses/train_all_presence_loss': 0.10606193244457245, 'Losses/train_all_presence_dec_acc': 0.9, 'Losses/train_all_loss_ce_o2m': 0.035362062975764275, 'Losses/train_all_ce_f1_o2m': 0.8711111187934876, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0017969542997889221, 'Losses/train_all_loss_dice': 0.1838637411594391, 'Losses/train_all_loss_mask_o2m': 0.015279208589345217, 'Losses/train_all_loss_dice_o2m': 1.5095754861831665, 'Losses/train_all_loss_bbox_aux_0': 0.029864343628287316, 'Losses/train_all_loss_giou_aux_0': 0.11390442252159119, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05655290819704532, 'Losses/train_all_loss_giou_aux_0_o2m': 0.23624874353408815, 'Losses/train_all_loss_ce_aux_0': 0.005374075751751662, 'Losses/train_all_ce_f1_aux_0': 0.5, 'Losses/train_all_presence_loss_aux_0': 0.08664630241692066, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.02599879540503025, 'Losses/train_all_ce_f1_aux_0_o2m': 0.30158731043338777, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.024782139249145983, 'Losses/train_all_loss_giou_aux_1': 0.07169880867004394, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05245989039540291, 'Losses/train_all_loss_giou_aux_1_o2m': 0.14542957544326782, 'Losses/train_all_loss_ce_aux_1': 0.0042088564019650224, 'Losses/train_all_ce_f1_aux_1': 0.46666666865348816, 'Losses/train_all_presence_loss_aux_1': 0.09251930303871632, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.028953714296221733, 'Losses/train_all_ce_f1_aux_1_o2m': 0.33333334028720857, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.02747829705476761, 'Losses/train_all_loss_giou_aux_2': 0.07253665924072265, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.052811119705438614, 'Losses/train_all_loss_giou_aux_2_o2m': 0.13557111024856566, 'Losses/train_all_loss_ce_aux_2': 0.00416949694044888, 'Losses/train_all_ce_f1_aux_2': 0.46666666865348816, 'Losses/train_all_presence_loss_aux_2': 0.0908380787819624, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03186091855168342, 'Losses/train_all_ce_f1_aux_2_o2m': 0.343030309677124, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02784192403778434, 'Losses/train_all_loss_giou_aux_3': 0.074876469373703, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.05443300940096378, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1367395043373108, 'Losses/train_all_loss_ce_aux_3': 0.0041460692649707195, 'Losses/train_all_ce_f1_aux_3': 0.46666666865348816, 'Losses/train_all_presence_loss_aux_3': 0.09745374210178852, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03219050802290439, 'Losses/train_all_ce_f1_aux_3_o2m': 0.33333334028720857, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.02778131002560258, 'Losses/train_all_loss_giou_aux_4': 0.07279436588287354, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05448626317083836, 'Losses/train_all_loss_giou_aux_4_o2m': 0.14164658784866332, 'Losses/train_all_loss_ce_aux_4': 0.0041543029248714445, 'Losses/train_all_ce_f1_aux_4': 0.4333333373069763, 'Losses/train_all_presence_loss_aux_4': 0.10084263198077678, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03296979442238808, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3466666728258133, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 48.117148065567015, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004989859950728715, 'Losses/train_all_loss_semantic_dice': 0.16234079152345657, 'Losses/train_all_miou_semantic_seg': 0.7729769051074982, 'Trainer/where': 0.475, 'Trainer/epoch': 1, 'Trainer/steps_train': 20}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:08:29,187 train_utils.py: 269: Train Epoch: [2][ 0/10] | Batch Time: 11.31 (11.31) | Data Time: 8.93 (8.93) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.42e+02 (2.42e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:08:49,979 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:08:49,980 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:08:49,981 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 55.83038867712021, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.025257679540663956, 'Losses/train_all_loss_giou': 0.07156944274902344, 'Losses/train_all_loss_bbox_o2m': 0.2257887374609709, 'Losses/train_all_loss_giou_o2m': 0.6148015975952148, 'Losses/train_all_loss_ce': 0.004406593227759004, 'Losses/train_all_ce_f1': 0.46666666865348816, 'Losses/train_all_presence_loss': 0.13356930315494536, 'Losses/train_all_presence_dec_acc': 0.9, 'Losses/train_all_loss_ce_o2m': 0.03690151702612639, 'Losses/train_all_ce_f1_o2m': 0.8577777802944183, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0021701512043364344, 'Losses/train_all_loss_dice': 0.20614143013954161, 'Losses/train_all_loss_mask_o2m': 0.022644072910770772, 'Losses/train_all_loss_dice_o2m': 1.6509253263473511, 'Losses/train_all_loss_bbox_aux_0': 0.03341554068028927, 'Losses/train_all_loss_giou_aux_0': 0.12878919243812562, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.0462175264954567, 'Losses/train_all_loss_giou_aux_0_o2m': 0.1953175187110901, 'Losses/train_all_loss_ce_aux_0': 0.006019262783229351, 'Losses/train_all_ce_f1_aux_0': 0.4, 'Losses/train_all_presence_loss_aux_0': 0.1226336053572595, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.02659773305058479, 'Losses/train_all_ce_f1_aux_0_o2m': 0.18303030729293823, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.025149279553443194, 'Losses/train_all_loss_giou_aux_1': 0.0773072063922882, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.039770000614225864, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1626142978668213, 'Losses/train_all_loss_ce_aux_1': 0.004645983688533306, 'Losses/train_all_ce_f1_aux_1': 0.4, 'Losses/train_all_presence_loss_aux_1': 0.13430758314207197, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.02752975784242153, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2671428620815277, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.025979793071746825, 'Losses/train_all_loss_giou_aux_2': 0.07176820635795593, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.049910662695765495, 'Losses/train_all_loss_giou_aux_2_o2m': 0.13476909399032594, 'Losses/train_all_loss_ce_aux_2': 0.004718632949516177, 'Losses/train_all_ce_f1_aux_2': 0.3, 'Losses/train_all_presence_loss_aux_2': 0.13539146995171905, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.02786702886223793, 'Losses/train_all_ce_f1_aux_2_o2m': 0.48380953073501587, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.025380357820540666, 'Losses/train_all_loss_giou_aux_3': 0.07021377682685852, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.05116666480898857, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1449057340621948, 'Losses/train_all_loss_ce_aux_3': 0.004341974901035428, 'Losses/train_all_ce_f1_aux_3': 0.5, 'Losses/train_all_presence_loss_aux_3': 0.13036724478006362, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0279645137488842, 'Losses/train_all_ce_f1_aux_3_o2m': 0.47666667103767396, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.02488600304350257, 'Losses/train_all_loss_giou_aux_4': 0.07026044726371765, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05090723596513271, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15163979530334473, 'Losses/train_all_loss_ce_aux_4': 0.004310324811376632, 'Losses/train_all_ce_f1_aux_4': 0.5, 'Losses/train_all_presence_loss_aux_4': 0.13177542081102728, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.028376595675945283, 'Losses/train_all_ce_f1_aux_4_o2m': 0.4971428632736206, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 55.83038867712021, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004049384966492653, 'Losses/train_all_loss_semantic_dice': 0.18247792422771453, 'Losses/train_all_miou_semantic_seg': 0.7618562430143356, 'Trainer/where': 0.725, 'Trainer/epoch': 2, 'Trainer/steps_train': 30}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:09:29,362 train_utils.py: 269: Train Epoch: [3][ 0/10] | Batch Time: 14.28 (14.28) | Data Time: 11.81 (11.81) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 4.10e+00 (4.10e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:09:49,726 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:09:49,727 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:09:49,727 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 56.93411602973938, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03202593745663762, 'Losses/train_all_loss_giou': 0.0919347882270813, 'Losses/train_all_loss_bbox_o2m': 0.23936258181929587, 'Losses/train_all_loss_giou_o2m': 0.7075031995773315, 'Losses/train_all_loss_ce': 0.0046124562155455354, 'Losses/train_all_ce_f1': 0.4, 'Losses/train_all_presence_loss': 0.1052014909684658, 'Losses/train_all_presence_dec_acc': 0.9, 'Losses/train_all_loss_ce_o2m': 0.03687231540679932, 'Losses/train_all_ce_f1_o2m': 0.7777777791023255, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0047711516497656705, 'Losses/train_all_loss_dice': 0.2047205924987793, 'Losses/train_all_loss_mask_o2m': 0.034386988077312705, 'Losses/train_all_loss_dice_o2m': 1.6361413598060608, 'Losses/train_all_loss_bbox_aux_0': 0.03425549641251564, 'Losses/train_all_loss_giou_aux_0': 0.11960711479187011, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.042674299143254754, 'Losses/train_all_loss_giou_aux_0_o2m': 0.1922982692718506, 'Losses/train_all_loss_ce_aux_0': 0.006095516588538885, 'Losses/train_all_ce_f1_aux_0': 0.3, 'Losses/train_all_presence_loss_aux_0': 0.11715359054505825, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026266244053840638, 'Losses/train_all_ce_f1_aux_0_o2m': 0.23158730566501617, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.028774892166256904, 'Losses/train_all_loss_giou_aux_1': 0.07727940678596497, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05128409620374441, 'Losses/train_all_loss_giou_aux_1_o2m': 0.16891556978225708, 'Losses/train_all_loss_ce_aux_1': 0.004556303611025214, 'Losses/train_all_ce_f1_aux_1': 0.5, 'Losses/train_all_presence_loss_aux_1': 0.09695470314472913, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.02967199608683586, 'Losses/train_all_ce_f1_aux_1_o2m': 0.28380953073501586, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.01576763726770878, 'Losses/train_all_loss_giou_aux_2': 0.07662887573242187, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05068367272615433, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1562723398208618, 'Losses/train_all_loss_ce_aux_2': 0.005262907175347209, 'Losses/train_all_ce_f1_aux_2': 0.4, 'Losses/train_all_presence_loss_aux_2': 0.09977794392034411, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.030401057004928587, 'Losses/train_all_ce_f1_aux_2_o2m': 0.30666667222976685, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03187717171385884, 'Losses/train_all_loss_giou_aux_3': 0.09007946252822877, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.034461664222180846, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1578670859336853, 'Losses/train_all_loss_ce_aux_3': 0.00455123889259994, 'Losses/train_all_ce_f1_aux_3': 0.4, 'Losses/train_all_presence_loss_aux_3': 0.10070350216701626, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.030900520086288453, 'Losses/train_all_ce_f1_aux_3_o2m': 0.3200000047683716, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03225808693096042, 'Losses/train_all_loss_giou_aux_4': 0.09210457801818847, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.050755195505917075, 'Losses/train_all_loss_giou_aux_4_o2m': 0.17345132827758789, 'Losses/train_all_loss_ce_aux_4': 0.004677178477868438, 'Losses/train_all_ce_f1_aux_4': 0.4, 'Losses/train_all_presence_loss_aux_4': 0.10481119332835079, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.030842529982328414, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3200000047683716, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 56.93411602973938, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.01120617245323956, 'Losses/train_all_loss_semantic_dice': 0.20849008709192277, 'Losses/train_all_miou_semantic_seg': 0.7342670824378729, 'Trainer/where': 0.975, 'Trainer/epoch': 3, 'Trainer/steps_train': 40}
INFO 2026-05-03 12:10:12,528 train_utils.py: 269: Val Epoch: [3][  0/208] | Batch Time: 0.77 (0.77) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 05m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:19,307 train_utils.py: 269: Val Epoch: [3][ 10/208] | Batch Time: 0.68 (0.69) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 05m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:26,014 train_utils.py: 269: Val Epoch: [3][ 20/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 05m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:32,872 train_utils.py: 269: Val Epoch: [3][ 30/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 05m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:39,655 train_utils.py: 269: Val Epoch: [3][ 40/208] | Batch Time: 0.69 (0.68) | Data Time: 0.05 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:46,448 train_utils.py: 269: Val Epoch: [3][ 50/208] | Batch Time: 0.78 (0.68) | Data Time: 0.14 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:53,209 train_utils.py: 269: Val Epoch: [3][ 60/208] | Batch Time: 0.69 (0.68) | Data Time: 0.05 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:10:59,895 train_utils.py: 269: Val Epoch: [3][ 70/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:06,810 train_utils.py: 269: Val Epoch: [3][ 80/208] | Batch Time: 0.68 (0.68) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:13,614 train_utils.py: 269: Val Epoch: [3][ 90/208] | Batch Time: 0.65 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:20,308 train_utils.py: 269: Val Epoch: [3][100/208] | Batch Time: 0.66 (0.68) | Data Time: 0.02 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 12:11:27,075 train_utils.py: 269: Val Epoch: [3][110/208] | Batch Time: 0.69 (0.68) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:34,032 train_utils.py: 269: Val Epoch: [3][120/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:40,931 train_utils.py: 269: Val Epoch: [3][130/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:47,841 train_utils.py: 269: Val Epoch: [3][140/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:11:54,654 train_utils.py: 269: Val Epoch: [3][150/208] | Batch Time: 0.68 (0.68) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:01,980 train_utils.py: 269: Val Epoch: [3][160/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:08,751 train_utils.py: 269: Val Epoch: [3][170/208] | Batch Time: 0.66 (0.68) | Data Time: 0.02 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:15,455 train_utils.py: 269: Val Epoch: [3][180/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:22,188 train_utils.py: 269: Val Epoch: [3][190/208] | Batch Time: 0.68 (0.68) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:29,027 train_utils.py: 269: Val Epoch: [3][200/208] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:12:33,756 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:12:33,756 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:12:33,756 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:12:33,756 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:12:34,020 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 12:12:34,494 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
INFO 2026-05-03 12:12:34,641 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.23s)
creating index...
index created!
INFO 2026-05-03 12:12:34,871 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.33s).
Accumulating evaluation results...
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.118
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.265
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.128
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.227
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.165
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.203
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.214
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.072
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.288
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.350
INFO 2026-05-03 12:12:35,309 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.11840979049029607, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.2646392756825358, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.12772336793279734, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.0222812238413915, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.2273546130989869, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.002456583847060163, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.16538461538461538, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.20288461538461539, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.21442307692307697, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.07222222222222222, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.28787878787878785, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.35, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.975, 'Trainer/epoch': 3, 'Trainer/steps_val': 208}

[rank0]:[W503 12:12:35.797269046 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_5shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 12:12:37] TEST EVAL: shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_5shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/5_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 5
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/5_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/5_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/5_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:12:49,379 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:12:49,394 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:12:49,395 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=45223
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:12:49,395 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:12:49,396 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:13:08,954 trainer.py:1150: ====================
INFO 2026-05-03 12:13:08,954 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:13:08,958 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:13:11,300 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 12:13:11,301 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:13:11,301 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:13:11,309 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 12:13:11.291929732 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 12:13:11,595 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 12:13:42,894 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 20.31 (20.31) | Data Time: 0.06 (0.06) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:13:51,099 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.66 (2.59) | Data Time: 0.03 (0.08) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:13:58,745 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.66 (1.72) | Data Time: 0.04 (0.11) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:14:05,261 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.65 (1.38) | Data Time: 0.03 (0.09) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:14:12,077 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.78 (1.21) | Data Time: 0.15 (0.08) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:14:16,710 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:14:16,711 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:14:16,711 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:14:16,711 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:14:17,001 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 12:14:17,091 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 12:14:17,113 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
INFO 2026-05-03 12:14:17,129 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.018
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.025
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.020
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.400
INFO 2026-05-03 12:14:17,232 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.004798380198528909, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.030754166933871858, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.000544010445000544, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.010437049622121974, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.010801786060959037, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.017588932806324106, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.025, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.054166666666666675, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.054166666666666675, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.02, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.075, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.4, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 12:14:18.092260876 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 6/12: shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1 (Shift-TA_TC-to-TB_10pct, 10-shot)
Selected experiment: shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_10shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 12:14:20] TRAIN: shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_10shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:14:33,693 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:14:33,703 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:14:33,703 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=19724
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:14:33,705 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:14:33,724 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:14:45,261 trainer.py:1150: ====================
INFO 2026-05-03 12:14:45,261 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:14:45,265 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:14:47,781 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 12:14:47,784 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:14:47,784 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:14:47,791 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 208
Raw dataset length = 20

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 12:16:33,423 train_utils.py: 269: Train Epoch: [0][ 0/20] | Batch Time: 105.17 (105.17) | Data Time: 9.90 (9.90) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 1.64e+02 (1.64e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:16:55,894 train_utils.py: 269: Train Epoch: [0][10/20] | Batch Time: 2.35 (11.60) | Data Time: 0.00 (0.91) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 6.34e+01 (7.50e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:17:17,445 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 12:17:17,446 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:17:17,446 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 59.790814930200575, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.027239945298060775, 'Losses/train_all_loss_giou': 0.07990886569023133, 'Losses/train_all_loss_bbox_o2m': 0.21465332321822644, 'Losses/train_all_loss_giou_o2m': 0.6106578648090363, 'Losses/train_all_loss_ce': 0.004563761397730559, 'Losses/train_all_ce_f1': 0.4333333343267441, 'Losses/train_all_presence_loss': 0.14430557782761752, 'Losses/train_all_presence_dec_acc': 0.9, 'Losses/train_all_loss_ce_o2m': 0.037559567112475635, 'Losses/train_all_ce_f1_o2m': 0.8800000011920929, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0021641417464707048, 'Losses/train_all_loss_dice': 0.23939078748226167, 'Losses/train_all_loss_mask_o2m': 0.018342566955834628, 'Losses/train_all_loss_dice_o2m': 1.8924893617630005, 'Losses/train_all_loss_bbox_aux_0': 0.030569878593087196, 'Losses/train_all_loss_giou_aux_0': 0.1265357404947281, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06823965422809124, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2104577362537384, 'Losses/train_all_loss_ce_aux_0': 0.00552919520996511, 'Losses/train_all_ce_f1_aux_0': 0.4, 'Losses/train_all_presence_loss_aux_0': 0.11651553371921182, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.025171958655118943, 'Losses/train_all_ce_f1_aux_0_o2m': 0.3522222265601158, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.029831274366006254, 'Losses/train_all_loss_giou_aux_1': 0.09477056562900543, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05629668282344937, 'Losses/train_all_loss_giou_aux_1_o2m': 0.16333110332489015, 'Losses/train_all_loss_ce_aux_1': 0.004516137880273163, 'Losses/train_all_ce_f1_aux_1': 0.4, 'Losses/train_all_presence_loss_aux_1': 0.12363111204467714, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.028799417801201342, 'Losses/train_all_ce_f1_aux_1_o2m': 0.36333333849906924, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.02873423327691853, 'Losses/train_all_loss_giou_aux_2': 0.0874693363904953, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05348168034106493, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1649082362651825, 'Losses/train_all_loss_ce_aux_2': 0.004525182116776705, 'Losses/train_all_ce_f1_aux_2': 0.45, 'Losses/train_all_presence_loss_aux_2': 0.12796725686639548, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03024713359773159, 'Losses/train_all_ce_f1_aux_2_o2m': 0.3585714340209961, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.028704337263479828, 'Losses/train_all_loss_giou_aux_3': 0.08191850781440735, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.053093117009848353, 'Losses/train_all_loss_giou_aux_3_o2m': 0.14689265489578246, 'Losses/train_all_loss_ce_aux_3': 0.004590749752242118, 'Losses/train_all_ce_f1_aux_3': 0.4333333343267441, 'Losses/train_all_presence_loss_aux_3': 0.13407186823897063, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03069907184690237, 'Losses/train_all_ce_f1_aux_3_o2m': 0.35333333909511566, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.029125197743996977, 'Losses/train_all_loss_giou_aux_4': 0.08157429695129395, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.050654143653810026, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1404030978679657, 'Losses/train_all_loss_ce_aux_4': 0.004544374835677445, 'Losses/train_all_ce_f1_aux_4': 0.45, 'Losses/train_all_presence_loss_aux_4': 0.14063624450936912, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03104412034153938, 'Losses/train_all_ce_f1_aux_4_o2m': 0.35333333909511566, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 59.790814930200575, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005432513414416462, 'Losses/train_all_loss_semantic_dice': 0.2317626565694809, 'Losses/train_all_miou_semantic_seg': 0.7111904378980398, 'Trainer/where': 0.2375, 'Trainer/epoch': 0, 'Trainer/steps_train': 20}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:17:55,852 train_utils.py: 269: Train Epoch: [1][ 0/20] | Batch Time: 15.16 (15.16) | Data Time: 12.76 (12.76) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.73e+02 (1.73e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:18:17,412 train_utils.py: 269: Train Epoch: [1][10/20] | Batch Time: 2.16 (3.34) | Data Time: 0.00 (1.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 9.52e+01 (7.23e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:18:37,761 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 12:18:37,761 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:18:37,761 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 58.28076351284981, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.02579846130684018, 'Losses/train_all_loss_giou': 0.07767691016197205, 'Losses/train_all_loss_bbox_o2m': 0.20963029228150845, 'Losses/train_all_loss_giou_o2m': 0.5813096106052399, 'Losses/train_all_loss_ce': 0.004162164579611272, 'Losses/train_all_ce_f1': 0.4833333343267441, 'Losses/train_all_presence_loss': 0.13307552016340196, 'Losses/train_all_presence_dec_acc': 0.85, 'Losses/train_all_loss_ce_o2m': 0.035570011287927625, 'Losses/train_all_ce_f1_o2m': 0.9, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.00218071342096664, 'Losses/train_all_loss_dice': 0.22862042486667633, 'Losses/train_all_loss_mask_o2m': 0.01888700951822102, 'Losses/train_all_loss_dice_o2m': 1.8362602710723877, 'Losses/train_all_loss_bbox_aux_0': 0.03169056279584766, 'Losses/train_all_loss_giou_aux_0': 0.10604578852653504, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05770562971010804, 'Losses/train_all_loss_giou_aux_0_o2m': 0.22256603837013245, 'Losses/train_all_loss_ce_aux_0': 0.0060405708383768795, 'Losses/train_all_ce_f1_aux_0': 0.27500000298023225, 'Losses/train_all_presence_loss_aux_0': 0.12450356492772699, 'Losses/train_all_presence_dec_acc_aux_0': 0.85, 'Losses/train_all_loss_ce_aux_0_o2m': 0.025832540914416315, 'Losses/train_all_ce_f1_aux_0_o2m': 0.30380952954292295, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.026668466720730068, 'Losses/train_all_loss_giou_aux_1': 0.08430591523647309, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.056165619567036626, 'Losses/train_all_loss_giou_aux_1_o2m': 0.15760254263877868, 'Losses/train_all_loss_ce_aux_1': 0.004595306585542858, 'Losses/train_all_ce_f1_aux_1': 0.4333333343267441, 'Losses/train_all_presence_loss_aux_1': 0.12694075950421393, 'Losses/train_all_presence_dec_acc_aux_1': 0.85, 'Losses/train_all_loss_ce_aux_1_o2m': 0.02824531402438879, 'Losses/train_all_ce_f1_aux_1_o2m': 0.360000005364418, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.02673641899600625, 'Losses/train_all_loss_giou_aux_2': 0.07584588825702668, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.051078449189662936, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1498727798461914, 'Losses/train_all_loss_ce_aux_2': 0.004297770920675248, 'Losses/train_all_ce_f1_aux_2': 0.45, 'Losses/train_all_presence_loss_aux_2': 0.13534371331334114, 'Losses/train_all_presence_dec_acc_aux_2': 0.85, 'Losses/train_all_loss_ce_aux_2_o2m': 0.028466215915977956, 'Losses/train_all_ce_f1_aux_2_o2m': 0.360000005364418, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.025752883683890105, 'Losses/train_all_loss_giou_aux_3': 0.07869720757007599, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.051273382268846035, 'Losses/train_all_loss_giou_aux_3_o2m': 0.14187833070755004, 'Losses/train_all_loss_ce_aux_3': 0.004190164094325155, 'Losses/train_all_ce_f1_aux_3': 0.4833333343267441, 'Losses/train_all_presence_loss_aux_3': 0.12862578248605133, 'Losses/train_all_presence_dec_acc_aux_3': 0.85, 'Losses/train_all_loss_ce_aux_3_o2m': 0.029467644169926643, 'Losses/train_all_ce_f1_aux_3_o2m': 0.35333333909511566, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.025808843038976192, 'Losses/train_all_loss_giou_aux_4': 0.07797113955020904, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.050904256850481035, 'Losses/train_all_loss_giou_aux_4_o2m': 0.14698994159698486, 'Losses/train_all_loss_ce_aux_4': 0.00412595298839733, 'Losses/train_all_ce_f1_aux_4': 0.4833333343267441, 'Losses/train_all_presence_loss_aux_4': 0.13135942532680928, 'Losses/train_all_presence_dec_acc_aux_4': 0.85, 'Losses/train_all_loss_ce_aux_4_o2m': 0.029726060666143896, 'Losses/train_all_ce_f1_aux_4_o2m': 0.360000005364418, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 58.28076351284981, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005152803543023765, 'Losses/train_all_loss_semantic_dice': 0.22087975218892097, 'Losses/train_all_miou_semantic_seg': 0.7139608025550842, 'Trainer/where': 0.4875, 'Trainer/epoch': 1, 'Trainer/steps_train': 40}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:19:17,207 train_utils.py: 269: Train Epoch: [2][ 0/20] | Batch Time: 14.27 (14.27) | Data Time: 11.87 (11.87) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.61e+00 (2.61e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:19:38,913 train_utils.py: 269: Train Epoch: [2][10/20] | Batch Time: 2.35 (3.27) | Data Time: 0.03 (1.09) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.95e+02 (8.23e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:19:59,599 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:19:59,600 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:19:59,600 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 59.779199983179566, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.04597336119040847, 'Losses/train_all_loss_giou': 0.09973981380462646, 'Losses/train_all_loss_bbox_o2m': 0.3422825248911977, 'Losses/train_all_loss_giou_o2m': 0.6981889367103576, 'Losses/train_all_loss_ce': 0.004852603969629854, 'Losses/train_all_ce_f1': 0.3666666686534882, 'Losses/train_all_presence_loss': 0.12760816584341228, 'Losses/train_all_presence_dec_acc': 0.85, 'Losses/train_all_loss_ce_o2m': 0.042276293598115446, 'Losses/train_all_ce_f1_o2m': 0.6936507999897004, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002318595114047639, 'Losses/train_all_loss_dice': 0.23801373243331908, 'Losses/train_all_loss_mask_o2m': 0.018191152438521384, 'Losses/train_all_loss_dice_o2m': 1.8745077192783355, 'Losses/train_all_loss_bbox_aux_0': 0.049970459565520285, 'Losses/train_all_loss_giou_aux_0': 0.1298624634742737, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.09096955973654985, 'Losses/train_all_loss_giou_aux_0_o2m': 0.23495168685913087, 'Losses/train_all_loss_ce_aux_0': 0.005956715205684304, 'Losses/train_all_ce_f1_aux_0': 0.31666666865348814, 'Losses/train_all_presence_loss_aux_0': 0.11523756126407533, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.025748082250356675, 'Losses/train_all_ce_f1_aux_0_o2m': 0.29690476655960085, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.040710590314120054, 'Losses/train_all_loss_giou_aux_1': 0.09708478450775146, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06476612640544772, 'Losses/train_all_loss_giou_aux_1_o2m': 0.18342170715332032, 'Losses/train_all_loss_ce_aux_1': 0.005452403135132044, 'Losses/train_all_ce_f1_aux_1': 0.2833333373069763, 'Losses/train_all_presence_loss_aux_1': 0.11342520599719137, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.030260116420686246, 'Losses/train_all_ce_f1_aux_1_o2m': 0.24412698894739152, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04736513523384929, 'Losses/train_all_loss_giou_aux_2': 0.0946853905916214, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.06614225115627051, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1731935977935791, 'Losses/train_all_loss_ce_aux_2': 0.004852296644821763, 'Losses/train_all_ce_f1_aux_2': 0.35000000298023226, 'Losses/train_all_presence_loss_aux_2': 0.1174011267721653, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.031008553877472877, 'Losses/train_all_ce_f1_aux_2_o2m': 0.25412698835134506, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.04563873391598463, 'Losses/train_all_loss_giou_aux_3': 0.09656115770339965, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.06218323735520244, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1513062000274658, 'Losses/train_all_loss_ce_aux_3': 0.004895411420147866, 'Losses/train_all_ce_f1_aux_3': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_3': 0.11752624994842335, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03213188722729683, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2505555585026741, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.04571697870269418, 'Losses/train_all_loss_giou_aux_4': 0.09862437546253204, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.06551904398947954, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15570108294487, 'Losses/train_all_loss_ce_aux_4': 0.004842630529310554, 'Losses/train_all_ce_f1_aux_4': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_4': 0.12171264978824184, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.032185017876327035, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2477777808904648, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 59.779199983179566, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005187905963975936, 'Losses/train_all_loss_semantic_dice': 0.2145996078848839, 'Losses/train_all_miou_semantic_seg': 0.7271377585828305, 'Trainer/where': 0.7375, 'Trainer/epoch': 2, 'Trainer/steps_train': 60}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:20:42,989 train_utils.py: 269: Train Epoch: [3][ 0/20] | Batch Time: 13.73 (13.73) | Data Time: 11.49 (11.49) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 2.13e+00 (2.13e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:21:04,395 train_utils.py: 269: Train Epoch: [3][10/20] | Batch Time: 2.16 (3.19) | Data Time: 0.02 (1.06) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 7.68e+01 (5.02e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:21:25,490 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:21:25,491 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:21:25,491 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 58.18748380094767, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.026953233033418657, 'Losses/train_all_loss_giou': 0.08513537943363189, 'Losses/train_all_loss_bbox_o2m': 0.19560386687517167, 'Losses/train_all_loss_giou_o2m': 0.5996776819229126, 'Losses/train_all_loss_ce': 0.004949111788300797, 'Losses/train_all_ce_f1': 0.3666666686534882, 'Losses/train_all_presence_loss': 0.13276833773124963, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.04122473848983645, 'Losses/train_all_ce_f1_o2m': 0.7262315571308136, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0019212578947190196, 'Losses/train_all_loss_dice': 0.23585566878318787, 'Losses/train_all_loss_mask_o2m': 0.01615194664336741, 'Losses/train_all_loss_dice_o2m': 1.89213427901268, 'Losses/train_all_loss_bbox_aux_0': 0.02687168214470148, 'Losses/train_all_loss_giou_aux_0': 0.14520969986915588, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05414840765297413, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2196202516555786, 'Losses/train_all_loss_ce_aux_0': 0.00580645427107811, 'Losses/train_all_ce_f1_aux_0': 0.3833333343267441, 'Losses/train_all_presence_loss_aux_0': 0.1119538534549065, 'Losses/train_all_presence_dec_acc_aux_0': 0.9, 'Losses/train_all_loss_ce_aux_0_o2m': 0.027144421078264713, 'Losses/train_all_ce_f1_aux_0_o2m': 0.25738095939159394, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.028265893273055554, 'Losses/train_all_loss_giou_aux_1': 0.11215430200099945, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.048228006437420846, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1816134572029114, 'Losses/train_all_loss_ce_aux_1': 0.005155273992568254, 'Losses/train_all_ce_f1_aux_1': 0.3833333343267441, 'Losses/train_all_presence_loss_aux_1': 0.12666327024926433, 'Losses/train_all_presence_dec_acc_aux_1': 0.85, 'Losses/train_all_loss_ce_aux_1_o2m': 0.02935111355036497, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2672222271561623, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.024311517644673587, 'Losses/train_all_loss_giou_aux_2': 0.0922599583864212, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.04902546349912882, 'Losses/train_all_loss_giou_aux_2_o2m': 0.15616257190704347, 'Losses/train_all_loss_ce_aux_2': 0.005179154395591468, 'Losses/train_all_ce_f1_aux_2': 0.4, 'Losses/train_all_presence_loss_aux_2': 0.11834470093599521, 'Losses/train_all_presence_dec_acc_aux_2': 0.85, 'Losses/train_all_loss_ce_aux_2_o2m': 0.030014172196388245, 'Losses/train_all_ce_f1_aux_2_o2m': 0.29460318237543104, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03228712873533368, 'Losses/train_all_loss_giou_aux_3': 0.09267989397048951, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.0462802492082119, 'Losses/train_all_loss_giou_aux_3_o2m': 0.14281848073005676, 'Losses/train_all_loss_ce_aux_3': 0.004816502996254713, 'Losses/train_all_ce_f1_aux_3': 0.3833333343267441, 'Losses/train_all_presence_loss_aux_3': 0.12014083521789871, 'Losses/train_all_presence_dec_acc_aux_3': 0.8, 'Losses/train_all_loss_ce_aux_3_o2m': 0.031665824539959433, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2977777823805809, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03130381954833865, 'Losses/train_all_loss_giou_aux_4': 0.09097708761692047, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.04560401700437069, 'Losses/train_all_loss_giou_aux_4_o2m': 0.14571405053138733, 'Losses/train_all_loss_ce_aux_4': 0.004726372606819495, 'Losses/train_all_ce_f1_aux_4': 0.3666666686534882, 'Losses/train_all_presence_loss_aux_4': 0.12685496459016576, 'Losses/train_all_presence_dec_acc_aux_4': 0.8, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03205572068691254, 'Losses/train_all_ce_f1_aux_4_o2m': 0.27666667103767395, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 58.18748380094767, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004764575569424778, 'Losses/train_all_loss_semantic_dice': 0.22829647362232208, 'Losses/train_all_miou_semantic_seg': 0.7115157522261143, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_train': 80}
INFO 2026-05-03 12:22:00,219 train_utils.py: 269: Val Epoch: [3][  0/208] | Batch Time: 0.92 (0.92) | Data Time: 0.19 (0.19) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:07,285 train_utils.py: 269: Val Epoch: [3][ 10/208] | Batch Time: 0.66 (0.73) | Data Time: 0.04 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:13,999 train_utils.py: 269: Val Epoch: [3][ 20/208] | Batch Time: 0.68 (0.70) | Data Time: 0.05 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:20,771 train_utils.py: 269: Val Epoch: [3][ 30/208] | Batch Time: 0.64 (0.69) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:28,789 train_utils.py: 269: Val Epoch: [3][ 40/208] | Batch Time: 0.65 (0.72) | Data Time: 0.03 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:35,291 train_utils.py: 269: Val Epoch: [3][ 50/208] | Batch Time: 0.65 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:41,994 train_utils.py: 269: Val Epoch: [3][ 60/208] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:48,796 train_utils.py: 269: Val Epoch: [3][ 70/208] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:22:55,467 train_utils.py: 269: Val Epoch: [3][ 80/208] | Batch Time: 0.65 (0.69) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:03,317 train_utils.py: 269: Val Epoch: [3][ 90/208] | Batch Time: 0.66 (0.70) | Data Time: 0.04 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 12:23:10,296 train_utils.py: 269: Val Epoch: [3][100/208] | Batch Time: 0.73 (0.70) | Data Time: 0.10 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:17,245 train_utils.py: 269: Val Epoch: [3][110/208] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:24,341 train_utils.py: 269: Val Epoch: [3][120/208] | Batch Time: 0.65 (0.70) | Data Time: 0.02 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:31,113 train_utils.py: 269: Val Epoch: [3][130/208] | Batch Time: 0.65 (0.70) | Data Time: 0.02 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:38,070 train_utils.py: 269: Val Epoch: [3][140/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:44,789 train_utils.py: 269: Val Epoch: [3][150/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:52,767 train_utils.py: 269: Val Epoch: [3][160/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:23:59,673 train_utils.py: 269: Val Epoch: [3][170/208] | Batch Time: 0.79 (0.70) | Data Time: 0.15 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:24:06,890 train_utils.py: 269: Val Epoch: [3][180/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:24:13,930 train_utils.py: 269: Val Epoch: [3][190/208] | Batch Time: 0.90 (0.70) | Data Time: 0.26 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:24:20,834 train_utils.py: 269: Val Epoch: [3][200/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:24:25,624 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:24:25,624 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:24:25,624 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:24:25,624 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:24:25,907 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 12:24:26,235 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 12:24:26,361 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.22s)
creating index...
index created!
INFO 2026-05-03 12:24:26,580 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.34s).
Accumulating evaluation results...
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.127
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.275
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.135
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.242
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.168
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.213
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.227
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.306
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.350
INFO 2026-05-03 12:24:27,028 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.12666407487091674, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.27495351138971724, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.13538118140408303, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.021825897703505858, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.24229677078645953, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.0013518730459109393, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.16826923076923078, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.21346153846153845, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.22692307692307692, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.075, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.30606060606060603, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.35, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_val': 208}

[rank0]:[W503 12:24:27.636231925 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_10shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 12:24:29] TEST EVAL: shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_10shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/10_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/10_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/10_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:24:41,215 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:24:41,232 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:24:41,232 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=36296
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:24:41,233 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:24:41,233 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:24:56,637 trainer.py:1150: ====================
INFO 2026-05-03 12:24:56,637 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:24:56,641 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:25:00,678 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 12:25:00,679 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:25:00,679 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:25:00,686 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 12:25:00.714676401 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 12:25:01,019 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 12:25:54,831 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 20.73 (20.73) | Data Time: 0.10 (0.10) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:26:01,854 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.67 (2.52) | Data Time: 0.04 (0.05) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:26:08,542 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.68 (1.64) | Data Time: 0.04 (0.05) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:26:15,330 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.67 (1.33) | Data Time: 0.03 (0.05) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:26:22,138 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.67 (1.17) | Data Time: 0.03 (0.05) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:26:26,826 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:26:26,826 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:26:26,826 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:26:26,826 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:26:27,018 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 12:26:27,114 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.43s)
creating index...
index created!
INFO 2026-05-03 12:26:27,560 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 12:26:27,575 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.017
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.014
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.029
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.062
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.027
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.087
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.400
INFO 2026-05-03 12:26:27,676 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.0067754096004319355, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.03143247643463334, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.0005266484095218033, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.017357174956148615, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.010926292629262927, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.013991221365710913, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.029166666666666664, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.054166666666666675, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.0625, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.026666666666666665, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.0875, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.4, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 12:26:28.091131395 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 7/12: shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1 (Shift-TA_TC-to-TB_10pct, 25-shot)
Selected experiment: shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_25shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 12:26:29] TRAIN: shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_25shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/25_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 25
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:26:43,905 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:26:43,918 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:26:43,918 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=22809
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:26:43,919 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:26:43,930 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:26:54,241 trainer.py:1150: ====================
INFO 2026-05-03 12:26:54,242 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:26:54,245 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:26:57,134 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 12:26:57,136 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:26:57,136 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:26:57,144 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 208
Raw dataset length = 50

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 12:28:43,364 train_utils.py: 269: Train Epoch: [0][ 0/50] | Batch Time: 105.57 (105.57) | Data Time: 9.00 (9.00) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 1.32e+02 (1.32e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:29:05,887 train_utils.py: 269: Train Epoch: [0][10/50] | Batch Time: 2.35 (11.64) | Data Time: 0.00 (0.84) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 1.01e+02 (7.84e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:29:27,492 train_utils.py: 269: Train Epoch: [0][20/50] | Batch Time: 2.17 (7.13) | Data Time: 0.00 (0.44) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 9.01e+01 (7.32e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:29:49,324 train_utils.py: 269: Train Epoch: [0][30/50] | Batch Time: 2.18 (5.53) | Data Time: 0.00 (0.31) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 9.09e+01 (6.76e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:30:11,168 train_utils.py: 269: Train Epoch: [0][40/50] | Batch Time: 2.16 (4.72) | Data Time: 0.00 (0.23) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.52e+00 (7.17e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:30:32,551 trainer.py:1042: Estimated time remaining: 00d 00h 10m
INFO 2026-05-03 12:30:32,552 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:30:32,552 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 68.45642926216125, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.02240733804181218, 'Losses/train_all_loss_giou': 0.07612448334693908, 'Losses/train_all_loss_bbox_o2m': 0.16555967435240745, 'Losses/train_all_loss_giou_o2m': 0.5823697161674499, 'Losses/train_all_loss_ce': 0.005404804483987391, 'Losses/train_all_ce_f1': 0.3333333337306976, 'Losses/train_all_presence_loss': 0.20099826203659177, 'Losses/train_all_presence_dec_acc': 0.78, 'Losses/train_all_loss_ce_o2m': 0.04594504524022341, 'Losses/train_all_ce_f1_o2m': 0.609428573846817, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0022118696314282716, 'Losses/train_all_loss_dice': 0.2508156514167786, 'Losses/train_all_loss_mask_o2m': 0.018154051918536425, 'Losses/train_all_loss_dice_o2m': 1.9428932976722717, 'Losses/train_all_loss_bbox_aux_0': 0.03387947231531143, 'Losses/train_all_loss_giou_aux_0': 0.12374139189720154, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.04870784495025873, 'Losses/train_all_loss_giou_aux_0_o2m': 0.21710525035858155, 'Losses/train_all_loss_ce_aux_0': 0.006274783443659544, 'Losses/train_all_ce_f1_aux_0': 0.2666666674613953, 'Losses/train_all_presence_loss_aux_0': 0.1971173955127597, 'Losses/train_all_presence_dec_acc_aux_0': 0.82, 'Losses/train_all_loss_ce_aux_0_o2m': 0.027036189660429956, 'Losses/train_all_ce_f1_aux_0_o2m': 0.24460606455802916, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03000572429969907, 'Losses/train_all_loss_giou_aux_1': 0.10209015130996704, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.04275033567100763, 'Losses/train_all_loss_giou_aux_1_o2m': 0.17552956342697143, 'Losses/train_all_loss_ce_aux_1': 0.005699837449938059, 'Losses/train_all_ce_f1_aux_1': 0.29666666746139525, 'Losses/train_all_presence_loss_aux_1': 0.1901670495700091, 'Losses/train_all_presence_dec_acc_aux_1': 0.8, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03099278524518013, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2558730202913284, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.02368064334616065, 'Losses/train_all_loss_giou_aux_2': 0.08764586329460144, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03941484373062849, 'Losses/train_all_loss_giou_aux_2_o2m': 0.14043471336364746, 'Losses/train_all_loss_ce_aux_2': 0.005488014663569629, 'Losses/train_all_ce_f1_aux_2': 0.3000000011920929, 'Losses/train_all_presence_loss_aux_2': 0.19651607628446072, 'Losses/train_all_presence_dec_acc_aux_2': 0.82, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03208753988146782, 'Losses/train_all_ce_f1_aux_2_o2m': 0.27822222709655764, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.021164752896875142, 'Losses/train_all_loss_giou_aux_3': 0.08114836573600769, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.03994361083954573, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1397019100189209, 'Losses/train_all_loss_ce_aux_3': 0.005358036938123405, 'Losses/train_all_ce_f1_aux_3': 0.2933333349227905, 'Losses/train_all_presence_loss_aux_3': 0.1926771842315793, 'Losses/train_all_presence_dec_acc_aux_3': 0.8, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03312302529811859, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2655555593967438, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.021539458204060793, 'Losses/train_all_loss_giou_aux_4': 0.07445586204528809, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.04051432434469462, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1414521861076355, 'Losses/train_all_loss_ce_aux_4': 0.00541039120638743, 'Losses/train_all_ce_f1_aux_4': 0.3266666674613953, 'Losses/train_all_presence_loss_aux_4': 0.1973430076800287, 'Losses/train_all_presence_dec_acc_aux_4': 0.8, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03359170019626617, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2555555593967438, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 68.45642926216125, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.009090215244796127, 'Losses/train_all_loss_semantic_dice': 0.250276300907135, 'Losses/train_all_miou_semantic_seg': 0.6964339027949609, 'Trainer/where': 0.245, 'Trainer/epoch': 0, 'Trainer/steps_train': 50}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:31:04,585 train_utils.py: 269: Train Epoch: [1][ 0/50] | Batch Time: 15.10 (15.10) | Data Time: 12.73 (12.73) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.78e+02 (1.78e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:31:26,165 train_utils.py: 269: Train Epoch: [1][10/50] | Batch Time: 2.15 (3.33) | Data Time: 0.00 (1.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.27e+00 (6.31e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:31:47,959 train_utils.py: 269: Train Epoch: [1][20/50] | Batch Time: 2.17 (2.78) | Data Time: 0.06 (0.62) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.50e+02 (6.98e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:32:09,701 train_utils.py: 269: Train Epoch: [1][30/50] | Batch Time: 2.17 (2.59) | Data Time: 0.00 (0.42) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.49e+02 (5.78e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:32:31,484 train_utils.py: 269: Train Epoch: [1][40/50] | Batch Time: 2.17 (2.49) | Data Time: 0.06 (0.32) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 9.10e+01 (5.64e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:32:52,200 trainer.py:1042: Estimated time remaining: 00d 00h 04m
INFO 2026-05-03 12:32:52,200 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:32:52,201 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 63.78285602737218, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.02470089351758361, 'Losses/train_all_loss_giou': 0.06591214895248414, 'Losses/train_all_loss_bbox_o2m': 0.20973901357501745, 'Losses/train_all_loss_giou_o2m': 0.5000247097015381, 'Losses/train_all_loss_ce': 0.00541440837085247, 'Losses/train_all_ce_f1': 0.34666666746139524, 'Losses/train_all_presence_loss': 0.18151774438505527, 'Losses/train_all_presence_dec_acc': 0.84, 'Losses/train_all_loss_ce_o2m': 0.044974730610847474, 'Losses/train_all_ce_f1_o2m': 0.6257777810096741, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0019346597802359612, 'Losses/train_all_loss_dice': 0.23065967440605165, 'Losses/train_all_loss_mask_o2m': 0.016924939258024095, 'Losses/train_all_loss_dice_o2m': 1.8314845228195191, 'Losses/train_all_loss_bbox_aux_0': 0.03677282623946667, 'Losses/train_all_loss_giou_aux_0': 0.11321734428405762, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05449858661741018, 'Losses/train_all_loss_giou_aux_0_o2m': 0.18071473598480225, 'Losses/train_all_loss_ce_aux_0': 0.0060965685825794935, 'Losses/train_all_ce_f1_aux_0': 0.2800000011920929, 'Losses/train_all_presence_loss_aux_0': 0.17351931757235434, 'Losses/train_all_presence_dec_acc_aux_0': 0.84, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026617366746068002, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2263015913963318, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03318905811756849, 'Losses/train_all_loss_giou_aux_1': 0.08443445563316346, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05153210874646902, 'Losses/train_all_loss_giou_aux_1_o2m': 0.12555392742156982, 'Losses/train_all_loss_ce_aux_1': 0.005256947097368538, 'Losses/train_all_ce_f1_aux_1': 0.33466666758060454, 'Losses/train_all_presence_loss_aux_1': 0.17695614618598485, 'Losses/train_all_presence_dec_acc_aux_1': 0.84, 'Losses/train_all_loss_ce_aux_1_o2m': 0.030349035188555716, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2692727315425873, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.0324528243765235, 'Losses/train_all_loss_giou_aux_2': 0.07204581260681152, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.051359368190169334, 'Losses/train_all_loss_giou_aux_2_o2m': 0.12055468797683716, 'Losses/train_all_loss_ce_aux_2': 0.005335238538682461, 'Losses/train_all_ce_f1_aux_2': 0.35333333373069764, 'Losses/train_all_presence_loss_aux_2': 0.1789279650474782, 'Losses/train_all_presence_dec_acc_aux_2': 0.84, 'Losses/train_all_loss_ce_aux_2_o2m': 0.031246647015213968, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2793333375453949, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.025831885524094104, 'Losses/train_all_loss_giou_aux_3': 0.06630281686782837, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.03528191298246384, 'Losses/train_all_loss_giou_aux_3_o2m': 0.10305039167404174, 'Losses/train_all_loss_ce_aux_3': 0.0054634163761511445, 'Losses/train_all_ce_f1_aux_3': 0.35333333373069764, 'Losses/train_all_presence_loss_aux_3': 0.1788386452503619, 'Losses/train_all_presence_dec_acc_aux_3': 0.84, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03233337439596653, 'Losses/train_all_ce_f1_aux_3_o2m': 0.24888889312744142, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.030117685347795485, 'Losses/train_all_loss_giou_aux_4': 0.06821093797683715, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.03505366120487451, 'Losses/train_all_loss_giou_aux_4_o2m': 0.10725186109542846, 'Losses/train_all_loss_ce_aux_4': 0.005221271007321775, 'Losses/train_all_ce_f1_aux_4': 0.3400000011920929, 'Losses/train_all_presence_loss_aux_4': 0.18470291569363326, 'Losses/train_all_presence_dec_acc_aux_4': 0.86, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03248237378895283, 'Losses/train_all_ce_f1_aux_4_o2m': 0.24488889276981354, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 63.78285602737218, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.006197355862241238, 'Losses/train_all_loss_semantic_dice': 0.22810894787311553, 'Losses/train_all_miou_semantic_seg': 0.710787921641022, 'Trainer/where': 0.495, 'Trainer/epoch': 1, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:33:24,726 train_utils.py: 269: Train Epoch: [2][ 0/50] | Batch Time: 12.88 (12.88) | Data Time: 9.86 (9.86) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 3.56e-01 (3.56e-01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:33:46,473 train_utils.py: 269: Train Epoch: [2][10/50] | Batch Time: 2.35 (3.15) | Data Time: 0.00 (0.91) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 3.21e+01 (4.19e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:34:08,103 train_utils.py: 269: Train Epoch: [2][20/50] | Batch Time: 2.16 (2.68) | Data Time: 0.02 (0.49) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 8.09e+01 (6.65e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:34:29,728 train_utils.py: 269: Train Epoch: [2][30/50] | Batch Time: 2.17 (2.51) | Data Time: 0.00 (0.34) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.53e+02 (7.05e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:34:51,482 train_utils.py: 269: Train Epoch: [2][40/50] | Batch Time: 2.17 (2.43) | Data Time: 0.02 (0.26) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 1.21e+02 (5.71e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:35:12,463 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 12:35:12,464 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:35:12,464 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 57.31577420796734, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.025969688780605793, 'Losses/train_all_loss_giou': 0.06336185932159424, 'Losses/train_all_loss_bbox_o2m': 0.20550735585391522, 'Losses/train_all_loss_giou_o2m': 0.5096477746963501, 'Losses/train_all_loss_ce': 0.005497841576579958, 'Losses/train_all_ce_f1': 0.3433333349227905, 'Losses/train_all_presence_loss': 0.15685801407667896, 'Losses/train_all_presence_dec_acc': 0.88, 'Losses/train_all_loss_ce_o2m': 0.04647893641144037, 'Losses/train_all_ce_f1_o2m': 0.6848638063669205, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.001521823939983733, 'Losses/train_all_loss_dice': 0.20586616396903992, 'Losses/train_all_loss_mask_o2m': 0.012778339320793747, 'Losses/train_all_loss_dice_o2m': 1.652662456035614, 'Losses/train_all_loss_bbox_aux_0': 0.030185912922024726, 'Losses/train_all_loss_giou_aux_0': 0.10156179904937744, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.04928268324583769, 'Losses/train_all_loss_giou_aux_0_o2m': 0.1925493049621582, 'Losses/train_all_loss_ce_aux_0': 0.006204202165827155, 'Losses/train_all_ce_f1_aux_0': 0.30333333611488345, 'Losses/train_all_presence_loss_aux_0': 0.1458063199440221, 'Losses/train_all_presence_dec_acc_aux_0': 0.88, 'Losses/train_all_loss_ce_aux_0_o2m': 0.027057201042771338, 'Losses/train_all_ce_f1_aux_0_o2m': 0.22955844640731812, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.023023639395833014, 'Losses/train_all_loss_giou_aux_1': 0.07136884570121765, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06726071309298277, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1659414839744568, 'Losses/train_all_loss_ce_aux_1': 0.006236281041055918, 'Losses/train_all_ce_f1_aux_1': 0.3033333349227905, 'Losses/train_all_presence_loss_aux_1': 0.1517970641698048, 'Losses/train_all_presence_dec_acc_aux_1': 0.88, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03089333638548851, 'Losses/train_all_ce_f1_aux_1_o2m': 0.3108282881975174, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.022822253741323947, 'Losses/train_all_loss_giou_aux_2': 0.06776437878608704, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05168446142226458, 'Losses/train_all_loss_giou_aux_2_o2m': 0.14438058137893678, 'Losses/train_all_loss_ce_aux_2': 0.005810631737112999, 'Losses/train_all_ce_f1_aux_2': 0.3300000011920929, 'Losses/train_all_presence_loss_aux_2': 0.14828158205429645, 'Losses/train_all_presence_dec_acc_aux_2': 0.88, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03203389123082161, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2884713113307953, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.024614893682301044, 'Losses/train_all_loss_giou_aux_3': 0.06534635305404662, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.046217047311365604, 'Losses/train_all_loss_giou_aux_3_o2m': 0.12404166936874389, 'Losses/train_all_loss_ce_aux_3': 0.00565556519664824, 'Losses/train_all_ce_f1_aux_3': 0.3300000023841858, 'Losses/train_all_presence_loss_aux_3': 0.15129801747676538, 'Losses/train_all_presence_dec_acc_aux_3': 0.88, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03363766752183437, 'Losses/train_all_ce_f1_aux_3_o2m': 0.26815385043621065, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.027658559009432794, 'Losses/train_all_loss_giou_aux_4': 0.06619417190551757, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.03715896490961313, 'Losses/train_all_loss_giou_aux_4_o2m': 0.11640100955963134, 'Losses/train_all_loss_ce_aux_4': 0.005430885315872729, 'Losses/train_all_ce_f1_aux_4': 0.3500000011920929, 'Losses/train_all_presence_loss_aux_4': 0.15655690945241077, 'Losses/train_all_presence_dec_acc_aux_4': 0.88, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03428310364484787, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2509157556295395, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 57.31577420796734, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004740896299481392, 'Losses/train_all_loss_semantic_dice': 0.21150795474648476, 'Losses/train_all_miou_semantic_seg': 0.7245817467570305, 'Trainer/where': 0.745, 'Trainer/epoch': 2, 'Trainer/steps_train': 150}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:35:51,096 train_utils.py: 269: Train Epoch: [3][ 0/50] | Batch Time: 18.69 (18.69) | Data Time: 16.46 (16.46) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 3.10e-02 (3.10e-02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:36:12,928 train_utils.py: 269: Train Epoch: [3][10/50] | Batch Time: 2.36 (3.68) | Data Time: 0.00 (1.51) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 9.88e+01 (1.94e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:36:34,566 train_utils.py: 269: Train Epoch: [3][20/50] | Batch Time: 2.15 (2.96) | Data Time: 0.00 (0.80) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 2.65e-02 (3.25e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:36:56,340 train_utils.py: 269: Train Epoch: [3][30/50] | Batch Time: 2.16 (2.71) | Data Time: 0.00 (0.55) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.30e+02 (4.11e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:37:18,048 train_utils.py: 269: Train Epoch: [3][40/50] | Batch Time: 2.16 (2.58) | Data Time: 0.02 (0.42) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 5.55e+01 (5.27e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:37:39,072 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:37:39,072 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:37:39,072 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 65.07615188427386, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.023742581140249967, 'Losses/train_all_loss_giou': 0.07265982031822205, 'Losses/train_all_loss_bbox_o2m': 0.19520045265555383, 'Losses/train_all_loss_giou_o2m': 0.5576066279411316, 'Losses/train_all_loss_ce': 0.005012789459433406, 'Losses/train_all_ce_f1': 0.34666666746139524, 'Losses/train_all_presence_loss': 0.22727940987004103, 'Losses/train_all_presence_dec_acc': 0.86, 'Losses/train_all_loss_ce_o2m': 0.04260309439152479, 'Losses/train_all_ce_f1_o2m': 0.6760805881023407, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.001353759296471253, 'Losses/train_all_loss_dice': 0.20471795439720153, 'Losses/train_all_loss_mask_o2m': 0.011609836127609014, 'Losses/train_all_loss_dice_o2m': 1.6083148956298827, 'Losses/train_all_loss_bbox_aux_0': 0.033879840187728404, 'Losses/train_all_loss_giou_aux_0': 0.12363973498344422, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.049630357138812545, 'Losses/train_all_loss_giou_aux_0_o2m': 0.18240938186645508, 'Losses/train_all_loss_ce_aux_0': 0.005963914431631565, 'Losses/train_all_ce_f1_aux_0': 0.30666666746139526, 'Losses/train_all_presence_loss_aux_0': 0.22639606165679652, 'Losses/train_all_presence_dec_acc_aux_0': 0.86, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026075457334518434, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2661538505554199, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.027637318540364504, 'Losses/train_all_loss_giou_aux_1': 0.08987898230552674, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.04508566930890083, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1528134536743164, 'Losses/train_all_loss_ce_aux_1': 0.005555973830632865, 'Losses/train_all_ce_f1_aux_1': 0.3300000011920929, 'Losses/train_all_presence_loss_aux_1': 0.2214581597871029, 'Losses/train_all_presence_dec_acc_aux_1': 0.88, 'Losses/train_all_loss_ce_aux_1_o2m': 0.02906705066561699, 'Losses/train_all_ce_f1_aux_1_o2m': 0.27155555963516237, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.025338927246630193, 'Losses/train_all_loss_giou_aux_2': 0.08183275103569031, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05415404822677374, 'Losses/train_all_loss_giou_aux_2_o2m': 0.16087860822677613, 'Losses/train_all_loss_ce_aux_2': 0.005153784425929188, 'Losses/train_all_ce_f1_aux_2': 0.34333333373069763, 'Losses/train_all_presence_loss_aux_2': 0.2300192750851261, 'Losses/train_all_presence_dec_acc_aux_2': 0.88, 'Losses/train_all_loss_ce_aux_2_o2m': 0.0299503018707037, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2706666707992554, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02431705320253968, 'Losses/train_all_loss_giou_aux_3': 0.07327315330505371, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.03744433831423521, 'Losses/train_all_loss_giou_aux_3_o2m': 0.13220567703247071, 'Losses/train_all_loss_ce_aux_3': 0.00514657536521554, 'Losses/train_all_ce_f1_aux_3': 0.3366666674613953, 'Losses/train_all_presence_loss_aux_3': 0.22971420075189827, 'Losses/train_all_presence_dec_acc_aux_3': 0.88, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0313540256768465, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2657777816057205, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.023610689248889684, 'Losses/train_all_loss_giou_aux_4': 0.0720449948310852, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.0360934080183506, 'Losses/train_all_loss_giou_aux_4_o2m': 0.12140219926834106, 'Losses/train_all_loss_ce_aux_4': 0.005084743648767471, 'Losses/train_all_ce_f1_aux_4': 0.34666666746139524, 'Losses/train_all_presence_loss_aux_4': 0.2335621175878282, 'Losses/train_all_presence_dec_acc_aux_4': 0.86, 'Losses/train_all_loss_ce_aux_4_o2m': 0.031746501475572585, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2678046441078186, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 65.07615188427386, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004216958985198289, 'Losses/train_all_loss_semantic_dice': 0.19746440812945365, 'Losses/train_all_miou_semantic_seg': 0.7374976205918938, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_train': 200}
INFO 2026-05-03 12:38:08,050 train_utils.py: 269: Val Epoch: [3][  0/208] | Batch Time: 0.77 (0.77) | Data Time: 0.05 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:14,679 train_utils.py: 269: Val Epoch: [3][ 10/208] | Batch Time: 0.66 (0.67) | Data Time: 0.03 (0.03) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:21,936 train_utils.py: 269: Val Epoch: [3][ 20/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:28,702 train_utils.py: 269: Val Epoch: [3][ 30/208] | Batch Time: 0.73 (0.69) | Data Time: 0.10 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:36,680 train_utils.py: 269: Val Epoch: [3][ 40/208] | Batch Time: 0.66 (0.72) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:43,434 train_utils.py: 269: Val Epoch: [3][ 50/208] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:38:50,031 train_utils.py: 269: Val Epoch: [3][ 60/208] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 12:38:56,897 train_utils.py: 269: Val Epoch: [3][ 70/208] | Batch Time: 0.69 (0.70) | Data Time: 0.06 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:03,821 train_utils.py: 269: Val Epoch: [3][ 80/208] | Batch Time: 0.74 (0.70) | Data Time: 0.11 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:11,692 train_utils.py: 269: Val Epoch: [3][ 90/208] | Batch Time: 0.91 (0.71) | Data Time: 0.10 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:19,061 train_utils.py: 269: Val Epoch: [3][100/208] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:25,828 train_utils.py: 269: Val Epoch: [3][110/208] | Batch Time: 0.68 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:32,511 train_utils.py: 269: Val Epoch: [3][120/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:39,200 train_utils.py: 269: Val Epoch: [3][130/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:46,109 train_utils.py: 269: Val Epoch: [3][140/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:52,754 train_utils.py: 269: Val Epoch: [3][150/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:39:59,674 train_utils.py: 269: Val Epoch: [3][160/208] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:40:06,409 train_utils.py: 269: Val Epoch: [3][170/208] | Batch Time: 0.68 (0.70) | Data Time: 0.04 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:40:13,507 train_utils.py: 269: Val Epoch: [3][180/208] | Batch Time: 0.73 (0.70) | Data Time: 0.09 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:40:20,455 train_utils.py: 269: Val Epoch: [3][190/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:40:27,411 train_utils.py: 269: Val Epoch: [3][200/208] | Batch Time: 0.68 (0.70) | Data Time: 0.04 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:40:32,079 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:40:32,080 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:40:32,080 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:40:32,080 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:40:32,347 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 12:40:32,701 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 12:40:32,780 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.22s)
creating index...
index created!
INFO 2026-05-03 12:40:33,004 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.34s).
Accumulating evaluation results...
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.141
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.356
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.125
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.024
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.270
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.202
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.237
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.256
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.092
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.450
INFO 2026-05-03 12:40:33,456 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.14108937468697383, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.3555570471997096, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.12472176309879282, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.023986622995412578, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.2696824096415549, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.0008781699290471408, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.20192307692307693, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.23653846153846153, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.25576923076923075, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.09166666666666666, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.3393939393939394, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.45, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_val': 208}

[rank0]:[W503 12:40:34.872155794 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_25shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 12:40:35] TEST EVAL: shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_25shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/25_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 25
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/25_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/25_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/25_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:40:48,799 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:40:48,816 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:40:48,816 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=11127
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:40:48,817 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:40:48,818 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:41:06,926 trainer.py:1150: ====================
INFO 2026-05-03 12:41:06,927 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:41:06,932 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:41:09,818 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 12:41:09,819 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:41:09,819 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:41:09,826 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 12:41:09.812412638 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 12:41:10,111 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 12:41:59,375 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 20.08 (20.08) | Data Time: 0.25 (0.25) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:42:06,275 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.67 (2.45) | Data Time: 0.03 (0.05) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:42:13,030 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.67 (1.61) | Data Time: 0.02 (0.04) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:42:19,712 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.66 (1.30) | Data Time: 0.02 (0.04) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:42:26,693 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.77 (1.16) | Data Time: 0.13 (0.04) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 12:42:31,919 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 12:42:31,920 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:42:31,920 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 12:42:31,920 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 12:42:32,170 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 12:42:32,447 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 12:42:32,487 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
INFO 2026-05-03 12:42:32,505 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.009
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.024
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.014
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.033
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.058
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.071
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.040
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.300
INFO 2026-05-03 12:42:32,606 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.008725472533502667, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.03110502340831225, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.0005380972879896685, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.024336906979319572, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.009299154572991545, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.013636363636363636, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.03333333333333333, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.058333333333333334, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.07083333333333333, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.039999999999999994, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.1, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.3, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 12:42:34.245228642 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 8/12: shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1 (Shift-TA_TC-to-TB_10pct, 50-shot)
Selected experiment: shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_50shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 12:42:35] TRAIN: shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_50shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 12:42:47,353 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 12:42:47,363 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 12:42:47,363 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=36660
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 12:42:47,364 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:42:47,379 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 12:43:03,233 trainer.py:1150: ====================
INFO 2026-05-03 12:43:03,309 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 12:43:03,314 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 12:43:05,463 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 12:43:05,464 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 12:43:05,464 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 12:43:05,471 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 208
Raw dataset length = 100

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 12:44:50,243 train_utils.py: 269: Train Epoch: [0][  0/100] | Batch Time: 104.42 (104.42) | Data Time: 8.06 (8.06) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 1.00e+02 (1.00e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:45:12,554 train_utils.py: 269: Train Epoch: [0][ 10/100] | Batch Time: 2.16 (11.52) | Data Time: 0.00 (0.74) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 9.17e-01 (5.42e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:45:34,471 train_utils.py: 269: Train Epoch: [0][ 20/100] | Batch Time: 2.18 (7.08) | Data Time: 0.00 (0.40) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 2.47e+02 (7.92e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:45:56,373 train_utils.py: 269: Train Epoch: [0][ 30/100] | Batch Time: 2.18 (5.50) | Data Time: 0.00 (0.27) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.69e+02 (9.24e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:46:18,246 train_utils.py: 269: Train Epoch: [0][ 40/100] | Batch Time: 2.16 (4.69) | Data Time: 0.00 (0.21) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.54e+00 (8.11e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:46:40,001 train_utils.py: 269: Train Epoch: [0][ 50/100] | Batch Time: 2.18 (4.20) | Data Time: 0.00 (0.17) | Mem (GB): 16.00 (16.53/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.37e+02 (8.55e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:47:01,888 train_utils.py: 269: Train Epoch: [0][ 60/100] | Batch Time: 2.16 (3.87) | Data Time: 0.00 (0.15) | Mem (GB): 16.00 (16.44/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 2.44e+00 (7.53e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:47:23,861 train_utils.py: 269: Train Epoch: [0][ 70/100] | Batch Time: 2.19 (3.63) | Data Time: 0.00 (0.13) | Mem (GB): 16.00 (16.38/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 5.28e+01 (6.99e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:47:45,687 train_utils.py: 269: Train Epoch: [0][ 80/100] | Batch Time: 2.18 (3.46) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.33/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 3.25e+02 (7.36e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:48:07,642 train_utils.py: 269: Train Epoch: [0][ 90/100] | Batch Time: 2.19 (3.32) | Data Time: 0.00 (0.10) | Mem (GB): 16.00 (16.30/43.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 9.61e+01 (7.17e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:48:29,210 trainer.py:1042: Estimated time remaining: 00d 00h 16m
INFO 2026-05-03 12:48:29,210 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:48:29,211 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 70.17155973836779, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03458424016833305, 'Losses/train_all_loss_giou': 0.09962418258190155, 'Losses/train_all_loss_bbox_o2m': 0.19804838635027408, 'Losses/train_all_loss_giou_o2m': 0.6430772244930267, 'Losses/train_all_loss_ce': 0.005397029621526599, 'Losses/train_all_ce_f1': 0.3716666680574417, 'Losses/train_all_presence_loss': 0.19538262389483863, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.047041632402688265, 'Losses/train_all_ce_f1_o2m': 0.6259184676408768, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002463164136861451, 'Losses/train_all_loss_dice': 0.24655978083610536, 'Losses/train_all_loss_mask_o2m': 0.020715750423260033, 'Losses/train_all_loss_dice_o2m': 1.9877967870235442, 'Losses/train_all_loss_bbox_aux_0': 0.0410386717505753, 'Losses/train_all_loss_giou_aux_0': 0.14129723131656646, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06221882466226816, 'Losses/train_all_loss_giou_aux_0_o2m': 0.22824865818023682, 'Losses/train_all_loss_ce_aux_0': 0.006330272443592549, 'Losses/train_all_ce_f1_aux_0': 0.2700000017881393, 'Losses/train_all_presence_loss_aux_0': 0.19140658239572075, 'Losses/train_all_presence_dec_acc_aux_0': 0.82, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026198323778808118, 'Losses/train_all_ce_f1_aux_0_o2m': 0.27341270327568057, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03648019596934318, 'Losses/train_all_loss_giou_aux_1': 0.11137665450572967, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06491503838449716, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1925201916694641, 'Losses/train_all_loss_ce_aux_1': 0.005728423048276454, 'Losses/train_all_ce_f1_aux_1': 0.323333335518837, 'Losses/train_all_presence_loss_aux_1': 0.19340954963932744, 'Losses/train_all_presence_dec_acc_aux_1': 0.81, 'Losses/train_all_loss_ce_aux_1_o2m': 0.030752068273723124, 'Losses/train_all_ce_f1_aux_1_o2m': 0.28939438849687577, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.0337157629057765, 'Losses/train_all_loss_giou_aux_2': 0.10186563372612, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.060694880727678535, 'Losses/train_all_loss_giou_aux_2_o2m': 0.18528900861740114, 'Losses/train_all_loss_ce_aux_2': 0.0055333054927177725, 'Losses/train_all_ce_f1_aux_2': 0.3450000011920929, 'Losses/train_all_presence_loss_aux_2': 0.19663181020645426, 'Losses/train_all_presence_dec_acc_aux_2': 0.81, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03177357081323862, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2826984176039696, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.033419690877199176, 'Losses/train_all_loss_giou_aux_3': 0.10141387462615967, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.0599623041972518, 'Losses/train_all_loss_giou_aux_3_o2m': 0.17642019152641297, 'Losses/train_all_loss_ce_aux_3': 0.0054240004462189975, 'Losses/train_all_ce_f1_aux_3': 0.3666666680574417, 'Losses/train_all_presence_loss_aux_3': 0.19048462450387887, 'Losses/train_all_presence_dec_acc_aux_3': 0.8, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03273710001260042, 'Losses/train_all_ce_f1_aux_3_o2m': 0.29103463619947434, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.031786688175052404, 'Losses/train_all_loss_giou_aux_4': 0.09572135329246521, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05910821858793497, 'Losses/train_all_loss_giou_aux_4_o2m': 0.18281190752983092, 'Losses/train_all_loss_ce_aux_4': 0.005430236069951206, 'Losses/train_all_ce_f1_aux_4': 0.3616666680574417, 'Losses/train_all_presence_loss_aux_4': 0.1926287716103252, 'Losses/train_all_presence_dec_acc_aux_4': 0.81, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03289772018790245, 'Losses/train_all_ce_f1_aux_4_o2m': 0.27858486384153364, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 70.17155973836779, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.00569095112150535, 'Losses/train_all_loss_semantic_dice': 0.23584805823862554, 'Losses/train_all_miou_semantic_seg': 0.7004305864870548, 'Trainer/where': 0.2475, 'Trainer/epoch': 0, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:49:01,934 train_utils.py: 269: Train Epoch: [1][  0/100] | Batch Time: 11.54 (11.54) | Data Time: 9.12 (9.12) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 8.19e+01 (8.19e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:49:23,767 train_utils.py: 269: Train Epoch: [1][ 10/100] | Batch Time: 2.34 (3.03) | Data Time: 0.00 (0.84) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 3.72e-01 (5.13e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:49:45,419 train_utils.py: 269: Train Epoch: [1][ 20/100] | Batch Time: 2.17 (2.62) | Data Time: 0.05 (0.45) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 2.80e+02 (5.81e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:50:07,172 train_utils.py: 269: Train Epoch: [1][ 30/100] | Batch Time: 2.17 (2.48) | Data Time: 0.00 (0.31) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 3.01e+01 (4.91e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:50:29,051 train_utils.py: 269: Train Epoch: [1][ 40/100] | Batch Time: 2.16 (2.41) | Data Time: 0.05 (0.24) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 2.64e-02 (5.50e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:50:50,898 train_utils.py: 269: Train Epoch: [1][ 50/100] | Batch Time: 2.16 (2.36) | Data Time: 0.00 (0.19) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 4.17e-02 (5.12e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:51:12,782 train_utils.py: 269: Train Epoch: [1][ 60/100] | Batch Time: 2.16 (2.33) | Data Time: 0.06 (0.16) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 2.54e-02 (5.06e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:51:34,734 train_utils.py: 269: Train Epoch: [1][ 70/100] | Batch Time: 2.17 (2.31) | Data Time: 0.00 (0.14) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 1.47e-03 (7.96e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:51:56,647 train_utils.py: 269: Train Epoch: [1][ 80/100] | Batch Time: 2.19 (2.30) | Data Time: 0.07 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 1.49e+02 (7.36e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:52:18,593 train_utils.py: 269: Train Epoch: [1][ 90/100] | Batch Time: 2.35 (2.29) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 2.06e-02 (7.80e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:52:38,997 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 12:52:38,998 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:52:38,998 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 79.05091281322616, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.027287408225238324, 'Losses/train_all_loss_giou': 0.08271016895771027, 'Losses/train_all_loss_bbox_o2m': 0.1631074969097972, 'Losses/train_all_loss_giou_o2m': 0.5532835400104523, 'Losses/train_all_loss_ce': 0.005326731109526008, 'Losses/train_all_ce_f1': 0.3250000011920929, 'Losses/train_all_presence_loss': 0.32870998632824694, 'Losses/train_all_presence_dec_acc': 0.8, 'Losses/train_all_loss_ce_o2m': 0.047395600378513335, 'Losses/train_all_ce_f1_o2m': 0.5776168948411942, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0014701633647200652, 'Losses/train_all_loss_dice': 0.22195025861263276, 'Losses/train_all_loss_mask_o2m': 0.012145758774131536, 'Losses/train_all_loss_dice_o2m': 1.7565030610561372, 'Losses/train_all_loss_bbox_aux_0': 0.030150480903685092, 'Losses/train_all_loss_giou_aux_0': 0.1268316924571991, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.04782048113644123, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2089085066318512, 'Losses/train_all_loss_ce_aux_0': 0.00616998525802046, 'Losses/train_all_ce_f1_aux_0': 0.25666666746139527, 'Losses/train_all_presence_loss_aux_0': 0.32596388350956657, 'Losses/train_all_presence_dec_acc_aux_0': 0.8, 'Losses/train_all_loss_ce_aux_0_o2m': 0.024859220385551453, 'Losses/train_all_ce_f1_aux_0_o2m': 0.21511255860328674, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.027269745822995902, 'Losses/train_all_loss_giou_aux_1': 0.09731420159339904, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.047973388209939, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1639561128616333, 'Losses/train_all_loss_ce_aux_1': 0.005744199852924794, 'Losses/train_all_ce_f1_aux_1': 0.31000000059604643, 'Losses/train_all_presence_loss_aux_1': 0.32176781005316796, 'Losses/train_all_presence_dec_acc_aux_1': 0.8, 'Losses/train_all_loss_ce_aux_1_o2m': 0.029044380150735377, 'Losses/train_all_ce_f1_aux_1_o2m': 0.24964835613965988, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.026210835529491307, 'Losses/train_all_loss_giou_aux_2': 0.08645951867103577, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.04639360439032316, 'Losses/train_all_loss_giou_aux_2_o2m': 0.15807264924049377, 'Losses/train_all_loss_ce_aux_2': 0.005645515499636531, 'Losses/train_all_ce_f1_aux_2': 0.30666666746139526, 'Losses/train_all_presence_loss_aux_2': 0.3207387727986202, 'Losses/train_all_presence_dec_acc_aux_2': 0.81, 'Losses/train_all_loss_ce_aux_2_o2m': 0.030082575418055056, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2395213723182678, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02713933788239956, 'Losses/train_all_loss_giou_aux_3': 0.08440449595451355, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.04063593031838536, 'Losses/train_all_loss_giou_aux_3_o2m': 0.14132775902748107, 'Losses/train_all_loss_ce_aux_3': 0.00547972044441849, 'Losses/train_all_ce_f1_aux_3': 0.3200000011920929, 'Losses/train_all_presence_loss_aux_3': 0.32097602989970936, 'Losses/train_all_presence_dec_acc_aux_3': 0.81, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03164881885051727, 'Losses/train_all_ce_f1_aux_3_o2m': 0.23774359434843062, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.02758586226031184, 'Losses/train_all_loss_giou_aux_4': 0.08309223592281341, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.04432351414114237, 'Losses/train_all_loss_giou_aux_4_o2m': 0.14222745299339296, 'Losses/train_all_loss_ce_aux_4': 0.00534733384149149, 'Losses/train_all_ce_f1_aux_4': 0.3233333343267441, 'Losses/train_all_presence_loss_aux_4': 0.32798676774640173, 'Losses/train_all_presence_dec_acc_aux_4': 0.79, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03206444002687931, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2539181971549988, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 79.05091281322616, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.00464861947868485, 'Losses/train_all_loss_semantic_dice': 0.21048406526446342, 'Losses/train_all_miou_semantic_seg': 0.7233279831707478, 'Trainer/where': 0.4975, 'Trainer/epoch': 1, 'Trainer/steps_train': 200}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:53:08,701 train_utils.py: 269: Train Epoch: [2][  0/100] | Batch Time: 10.37 (10.37) | Data Time: 7.77 (7.77) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.16e-04 (1.16e-04) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:53:30,308 train_utils.py: 269: Train Epoch: [2][ 10/100] | Batch Time: 2.16 (2.91) | Data Time: 0.00 (0.73) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 2.41e-02 (7.34e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:53:52,124 train_utils.py: 269: Train Epoch: [2][ 20/100] | Batch Time: 2.15 (2.56) | Data Time: 0.01 (0.39) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 7.51e-05 (4.99e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:54:13,923 train_utils.py: 269: Train Epoch: [2][ 30/100] | Batch Time: 2.16 (2.44) | Data Time: 0.00 (0.27) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 2.74e-05 (4.29e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:54:35,795 train_utils.py: 269: Train Epoch: [2][ 40/100] | Batch Time: 2.17 (2.38) | Data Time: 0.00 (0.21) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 3.86e+02 (5.67e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:54:57,664 train_utils.py: 269: Train Epoch: [2][ 50/100] | Batch Time: 2.16 (2.34) | Data Time: 0.00 (0.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 1.35e-04 (7.00e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:55:19,618 train_utils.py: 269: Train Epoch: [2][ 60/100] | Batch Time: 2.17 (2.32) | Data Time: 0.00 (0.14) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 9.99e+01 (7.04e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:55:41,561 train_utils.py: 269: Train Epoch: [2][ 70/100] | Batch Time: 2.19 (2.30) | Data Time: 0.00 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 5.90e+01 (7.38e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:56:03,535 train_utils.py: 269: Train Epoch: [2][ 80/100] | Batch Time: 2.19 (2.29) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 3.73e+01 (7.97e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:56:25,383 train_utils.py: 269: Train Epoch: [2][ 90/100] | Batch Time: 2.17 (2.28) | Data Time: 0.00 (0.10) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 5.48e-05 (8.12e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:56:45,889 trainer.py:1042: Estimated time remaining: 00d 00h 03m
INFO 2026-05-03 12:56:45,889 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 12:56:45,890 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 86.99539060528808, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03161864979192615, 'Losses/train_all_loss_giou': 0.09308682799339295, 'Losses/train_all_loss_bbox_o2m': 0.18872253477573395, 'Losses/train_all_loss_giou_o2m': 0.5236552333831788, 'Losses/train_all_loss_ce': 0.005036337453639135, 'Losses/train_all_ce_f1': 0.3640000012516975, 'Losses/train_all_presence_loss': 0.40166631260412144, 'Losses/train_all_presence_dec_acc': 0.83, 'Losses/train_all_loss_ce_o2m': 0.0458066551759839, 'Losses/train_all_ce_f1_o2m': 0.6052149116992951, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0013234635710250586, 'Losses/train_all_loss_dice': 0.2136245435476303, 'Losses/train_all_loss_mask_o2m': 0.010268149808980524, 'Losses/train_all_loss_dice_o2m': 1.6574933385849, 'Losses/train_all_loss_bbox_aux_0': 0.03555758768692613, 'Losses/train_all_loss_giou_aux_0': 0.1475323420763016, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.055380364954471586, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2129463529586792, 'Losses/train_all_loss_ce_aux_0': 0.005961896288208663, 'Losses/train_all_ce_f1_aux_0': 0.2766666674613953, 'Losses/train_all_presence_loss_aux_0': 0.40147026553467297, 'Losses/train_all_presence_dec_acc_aux_0': 0.82, 'Losses/train_all_loss_ce_aux_0_o2m': 0.023640992362052204, 'Losses/train_all_ce_f1_aux_0_o2m': 0.21485714733600617, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.029591982355341315, 'Losses/train_all_loss_giou_aux_1': 0.10366405010223388, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05568446302786469, 'Losses/train_all_loss_giou_aux_1_o2m': 0.18071779608726501, 'Losses/train_all_loss_ce_aux_1': 0.0054619190399535, 'Losses/train_all_ce_f1_aux_1': 0.3366666674613953, 'Losses/train_all_presence_loss_aux_1': 0.4054217774111426, 'Losses/train_all_presence_dec_acc_aux_1': 0.83, 'Losses/train_all_loss_ce_aux_1_o2m': 0.026251657009124754, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2573824003338814, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.02722633578814566, 'Losses/train_all_loss_giou_aux_2': 0.0860417401790619, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.050177879463881254, 'Losses/train_all_loss_giou_aux_2_o2m': 0.15989905714988709, 'Losses/train_all_loss_ce_aux_2': 0.005505625933874398, 'Losses/train_all_ce_f1_aux_2': 0.3316666674613953, 'Losses/train_all_presence_loss_aux_2': 0.39972204106497783, 'Losses/train_all_presence_dec_acc_aux_2': 0.83, 'Losses/train_all_loss_ce_aux_2_o2m': 0.027442367244511844, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2885411298274994, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.029583094399422406, 'Losses/train_all_loss_giou_aux_3': 0.08957775712013244, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.04821341063827276, 'Losses/train_all_loss_giou_aux_3_o2m': 0.14979455828666688, 'Losses/train_all_loss_ce_aux_3': 0.005208651626016945, 'Losses/train_all_ce_f1_aux_3': 0.34833333432674407, 'Losses/train_all_presence_loss_aux_3': 0.4022341007424285, 'Losses/train_all_presence_dec_acc_aux_3': 0.83, 'Losses/train_all_loss_ce_aux_3_o2m': 0.028419420272111893, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2916507983207703, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.031555117750540373, 'Losses/train_all_loss_giou_aux_4': 0.09408007025718688, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.042517735585570336, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1349048435688019, 'Losses/train_all_loss_ce_aux_4': 0.005078074946068227, 'Losses/train_all_ce_f1_aux_4': 0.3640000012516975, 'Losses/train_all_presence_loss_aux_4': 0.40926178534940705, 'Losses/train_all_presence_dec_acc_aux_4': 0.83, 'Losses/train_all_loss_ce_aux_4_o2m': 0.0290829704888165, 'Losses/train_all_ce_f1_aux_4_o2m': 0.28775946706533434, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 86.99539060528808, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004228297991212457, 'Losses/train_all_loss_semantic_dice': 0.20489735081791877, 'Losses/train_all_miou_semantic_seg': 0.7299920289218426, 'Trainer/where': 0.7475, 'Trainer/epoch': 2, 'Trainer/steps_train': 300}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 12:57:12,777 train_utils.py: 269: Train Epoch: [3][  0/100] | Batch Time: 9.31 (9.31) | Data Time: 6.71 (6.71) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 2.29e+01 (2.29e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:57:34,616 train_utils.py: 269: Train Epoch: [3][ 10/100] | Batch Time: 2.35 (2.83) | Data Time: 0.00 (0.63) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 7.41e+01 (4.11e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:57:56,254 train_utils.py: 269: Train Epoch: [3][ 20/100] | Batch Time: 2.16 (2.51) | Data Time: 0.02 (0.34) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 4.65e-05 (4.35e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:58:17,897 train_utils.py: 269: Train Epoch: [3][ 30/100] | Batch Time: 2.15 (2.40) | Data Time: 0.00 (0.23) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 5.60e-05 (6.30e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:58:39,732 train_utils.py: 269: Train Epoch: [3][ 40/100] | Batch Time: 2.18 (2.35) | Data Time: 0.02 (0.18) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 1.71e+02 (6.05e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:59:01,638 train_utils.py: 269: Train Epoch: [3][ 50/100] | Batch Time: 2.19 (2.32) | Data Time: 0.00 (0.15) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 4.64e+02 (9.04e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:59:23,781 train_utils.py: 269: Train Epoch: [3][ 60/100] | Batch Time: 2.18 (2.30) | Data Time: 0.02 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 3.78e+01 (8.04e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 12:59:45,793 train_utils.py: 269: Train Epoch: [3][ 70/100] | Batch Time: 2.19 (2.29) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 6.88e+01 (7.48e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:00:07,967 train_utils.py: 269: Train Epoch: [3][ 80/100] | Batch Time: 2.19 (2.28) | Data Time: 0.01 (0.10) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 4.17e-05 (6.76e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:00:29,956 train_utils.py: 269: Train Epoch: [3][ 90/100] | Batch Time: 2.17 (2.27) | Data Time: 0.00 (0.09) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 2.85e-04 (6.36e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:00:50,592 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:00:50,593 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:00:50,593 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 68.60281810815823, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.024651945373043417, 'Losses/train_all_loss_giou': 0.08253265798091888, 'Losses/train_all_loss_bbox_o2m': 0.16635204486548902, 'Losses/train_all_loss_giou_o2m': 0.5408692824840545, 'Losses/train_all_loss_ce': 0.00487223879317753, 'Losses/train_all_ce_f1': 0.37166666746139526, 'Losses/train_all_presence_loss': 0.26483994817315126, 'Losses/train_all_presence_dec_acc': 0.86, 'Losses/train_all_loss_ce_o2m': 0.043742524106055496, 'Losses/train_all_ce_f1_o2m': 0.6477625748515129, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0012598271330352873, 'Losses/train_all_loss_dice': 0.2051531219482422, 'Losses/train_all_loss_mask_o2m': 0.010856042834930121, 'Losses/train_all_loss_dice_o2m': 1.586596702337265, 'Losses/train_all_loss_bbox_aux_0': 0.031724338494241236, 'Losses/train_all_loss_giou_aux_0': 0.12132824182510377, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.050436123795807364, 'Losses/train_all_loss_giou_aux_0_o2m': 0.1968410301208496, 'Losses/train_all_loss_ce_aux_0': 0.005808966648764909, 'Losses/train_all_ce_f1_aux_0': 0.2966666668653488, 'Losses/train_all_presence_loss_aux_0': 0.2642573128593244, 'Losses/train_all_presence_dec_acc_aux_0': 0.86, 'Losses/train_all_loss_ce_aux_0_o2m': 0.023081829231232406, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2648095288872719, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.026361821554601192, 'Losses/train_all_loss_giou_aux_1': 0.09101568639278412, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.043136884048581126, 'Losses/train_all_loss_giou_aux_1_o2m': 0.1569897389411926, 'Losses/train_all_loss_ce_aux_1': 0.005384328584186733, 'Losses/train_all_ce_f1_aux_1': 0.3500000011920929, 'Losses/train_all_presence_loss_aux_1': 0.26216851512300493, 'Losses/train_all_presence_dec_acc_aux_1': 0.86, 'Losses/train_all_loss_ce_aux_1_o2m': 0.026484457459300757, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2762063539028168, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.026124705700203775, 'Losses/train_all_loss_giou_aux_2': 0.08483061492443085, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03870995163917541, 'Losses/train_all_loss_giou_aux_2_o2m': 0.13705155968666077, 'Losses/train_all_loss_ce_aux_2': 0.005100666645448655, 'Losses/train_all_ce_f1_aux_2': 0.3550000011920929, 'Losses/train_all_presence_loss_aux_2': 0.2598922217038088, 'Losses/train_all_presence_dec_acc_aux_2': 0.86, 'Losses/train_all_loss_ce_aux_2_o2m': 0.027570840436965227, 'Losses/train_all_ce_f1_aux_2_o2m': 0.27377778172492984, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02567505246028304, 'Losses/train_all_loss_giou_aux_3': 0.08520689964294434, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.03871720151975751, 'Losses/train_all_loss_giou_aux_3_o2m': 0.13767929196357728, 'Losses/train_all_loss_ce_aux_3': 0.0049479484464973215, 'Losses/train_all_ce_f1_aux_3': 0.3533333343267441, 'Losses/train_all_presence_loss_aux_3': 0.26324520894503944, 'Losses/train_all_presence_dec_acc_aux_3': 0.86, 'Losses/train_all_loss_ce_aux_3_o2m': 0.02837260775268078, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2750000038743019, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.025349777303636075, 'Losses/train_all_loss_giou_aux_4': 0.083390092253685, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.040143645722419026, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1348379921913147, 'Losses/train_all_loss_ce_aux_4': 0.004844004162587226, 'Losses/train_all_ce_f1_aux_4': 0.3683333343267441, 'Losses/train_all_presence_loss_aux_4': 0.26811523347988975, 'Losses/train_all_presence_dec_acc_aux_4': 0.86, 'Losses/train_all_loss_ce_aux_4_o2m': 0.02900466063991189, 'Losses/train_all_ce_f1_aux_4_o2m': 0.27254257261753084, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 68.60281810815823, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004541197578073479, 'Losses/train_all_loss_semantic_dice': 0.19815288573503495, 'Losses/train_all_miou_semantic_seg': 0.7355461829528213, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_train': 400}
INFO 2026-05-03 13:01:09,478 train_utils.py: 269: Val Epoch: [3][  0/208] | Batch Time: 0.76 (0.76) | Data Time: 0.03 (0.03) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:16,204 train_utils.py: 269: Val Epoch: [3][ 10/208] | Batch Time: 0.68 (0.68) | Data Time: 0.03 (0.03) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 13:01:22,952 train_utils.py: 269: Val Epoch: [3][ 20/208] | Batch Time: 0.68 (0.68) | Data Time: 0.04 (0.03) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:29,789 train_utils.py: 269: Val Epoch: [3][ 30/208] | Batch Time: 0.66 (0.68) | Data Time: 0.02 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:37,153 train_utils.py: 269: Val Epoch: [3][ 40/208] | Batch Time: 0.67 (0.69) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:44,561 train_utils.py: 269: Val Epoch: [3][ 50/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:51,562 train_utils.py: 269: Val Epoch: [3][ 60/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:01:58,264 train_utils.py: 269: Val Epoch: [3][ 70/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:05,376 train_utils.py: 269: Val Epoch: [3][ 80/208] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:12,652 train_utils.py: 269: Val Epoch: [3][ 90/208] | Batch Time: 0.70 (0.70) | Data Time: 0.06 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:19,317 train_utils.py: 269: Val Epoch: [3][100/208] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:26,051 train_utils.py: 269: Val Epoch: [3][110/208] | Batch Time: 0.69 (0.70) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:33,316 train_utils.py: 269: Val Epoch: [3][120/208] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:40,511 train_utils.py: 269: Val Epoch: [3][130/208] | Batch Time: 0.81 (0.70) | Data Time: 0.17 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:47,814 train_utils.py: 269: Val Epoch: [3][140/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:02:54,473 train_utils.py: 269: Val Epoch: [3][150/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:01,285 train_utils.py: 269: Val Epoch: [3][160/208] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:08,364 train_utils.py: 269: Val Epoch: [3][170/208] | Batch Time: 0.73 (0.70) | Data Time: 0.09 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:15,373 train_utils.py: 269: Val Epoch: [3][180/208] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:22,351 train_utils.py: 269: Val Epoch: [3][190/208] | Batch Time: 0.78 (0.70) | Data Time: 0.13 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:29,366 train_utils.py: 269: Val Epoch: [3][200/208] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:03:34,357 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:03:34,357 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:03:34,357 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:03:34,357 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:03:34,617 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 13:03:34,916 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:03:34,999 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.21s)
creating index...
index created!
INFO 2026-05-03 13:03:35,212 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.33s).
Accumulating evaluation results...
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.142
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.385
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.128
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.025
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.270
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.196
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.236
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.252
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.103
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.326
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.500
INFO 2026-05-03 13:03:35,646 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.1424811421165328, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.3851369985585896, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.12824881786711584, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.024767704142547916, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.27025879980816836, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.00040921746282490977, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.19615384615384618, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.23557692307692307, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.2519230769230769, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.10277777777777777, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.3257575757575758, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.5, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_val': 208}

[rank0]:[W503 13:03:36.048053495 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_50shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 13:03:37] TEST EVAL: shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tc_to_tb_10pct_50shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TC-to-TB_10pct
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/50_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/50_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TC-to-TB_10pct/50_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:03:43,854 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:03:43,859 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:03:43,859 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=42568
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:03:43,860 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:03:43,860 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:04:00,316 trainer.py:1150: ====================
INFO 2026-05-03 13:04:00,316 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:04:00,320 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 13:04:02,159 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 13:04:02,160 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:04:02,160 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 13:04:02,168 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 13:04:02.136109718 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 48
INFO 2026-05-03 13:04:02,454 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 13:04:30,863 train_utils.py: 269: Val Epoch: [4][ 0/48] | Batch Time: 20.27 (20.27) | Data Time: 0.18 (0.18) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:04:38,646 train_utils.py: 269: Val Epoch: [4][10/48] | Batch Time: 0.69 (2.55) | Data Time: 0.04 (0.07) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:04:45,710 train_utils.py: 269: Val Epoch: [4][20/48] | Batch Time: 0.67 (1.67) | Data Time: 0.03 (0.07) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:04:53,060 train_utils.py: 269: Val Epoch: [4][30/48] | Batch Time: 0.67 (1.37) | Data Time: 0.03 (0.07) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:05:00,333 train_utils.py: 269: Val Epoch: [4][40/48] | Batch Time: 0.81 (1.21) | Data Time: 0.17 (0.08) | Mem (GB): 7.00 (7.85/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:05:05,015 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:05:05,015 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:05:05,016 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:05:05,016 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:05:05,212 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 13:05:05,395 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:05:05,416 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 13:05:05,429 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.08s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.015
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.067
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.030
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.046
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.079
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.073
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.125
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.300
INFO 2026-05-03 13:05:05,529 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.014775788825474305, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.06695660159375505, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.000556235398820781, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.030299584542549992, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.019441924550927105, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.013488964346349745, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.04583333333333333, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.07916666666666666, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.1, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.07333333333333333, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.125, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.3, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 48}

[rank0]:[W503 13:05:06.950284340 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TC-to-TB_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 9/12: shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1 (Shift-TA_TB-to-TC_10pct, 5-shot)
Selected experiment: shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_5shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/5_shot_per_class_stable_lowlr_v1
Skipping train because checkpoint already exists: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Selected experiment: shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_5shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/5_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Skipping eval because prediction file already exists: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/5_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json

####################################################################################################
Batch item 10/12: shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1 (Shift-TA_TB-to-TC_10pct, 10-shot)
Selected experiment: shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_10shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 13:05:07] TRAIN: shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_10shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TB-to-TC_10pct
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:05:14,322 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:05:14,329 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:05:14,329 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=64178
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:05:14,330 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:05:14,333 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:05:26,566 trainer.py:1150: ====================
INFO 2026-05-03 13:05:26,566 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:05:26,570 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 13:05:28,139 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 13:05:28,139 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:05:28,139 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 13:05:28,147 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

Raw dataset length = 228
Raw dataset length = 20

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 13:07:07,952 train_utils.py: 269: Train Epoch: [0][ 0/20] | Batch Time: 99.39 (99.39) | Data Time: 5.93 (5.93) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 1.43e+02 (1.43e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:07:30,387 train_utils.py: 269: Train Epoch: [0][10/20] | Batch Time: 2.35 (11.08) | Data Time: 0.00 (0.55) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 4.17e+01 (6.74e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:07:50,701 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 13:07:50,702 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:07:50,702 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 47.63475280404091, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.013910817913711071, 'Losses/train_all_loss_giou': 0.0838250070810318, 'Losses/train_all_loss_bbox_o2m': 0.13023347929120063, 'Losses/train_all_loss_giou_o2m': 0.6991445243358612, 'Losses/train_all_loss_ce': 0.004709751415066421, 'Losses/train_all_ce_f1': 0.375, 'Losses/train_all_presence_loss': 0.0846819382160902, 'Losses/train_all_presence_dec_acc': 0.95, 'Losses/train_all_loss_ce_o2m': 0.03821613932959735, 'Losses/train_all_ce_f1_o2m': 0.7253246784210206, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0017909643822349608, 'Losses/train_all_loss_dice': 0.18923969864845275, 'Losses/train_all_loss_mask_o2m': 0.016329625388607383, 'Losses/train_all_loss_dice_o2m': 1.4292564690113068, 'Losses/train_all_loss_bbox_aux_0': 0.030046402104198934, 'Losses/train_all_loss_giou_aux_0': 0.1396665781736374, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.05288377031683922, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2596812903881073, 'Losses/train_all_loss_ce_aux_0': 0.005147598369512707, 'Losses/train_all_ce_f1_aux_0': 0.4333333343267441, 'Losses/train_all_presence_loss_aux_0': 0.08262122492305934, 'Losses/train_all_presence_dec_acc_aux_0': 0.95, 'Losses/train_all_loss_ce_aux_0_o2m': 0.0288540119305253, 'Losses/train_all_ce_f1_aux_0_o2m': 0.31079365611076354, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.01736196633428335, 'Losses/train_all_loss_giou_aux_1': 0.10600459575653076, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.04086912870407104, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2156987190246582, 'Losses/train_all_loss_ce_aux_1': 0.004812317050527782, 'Losses/train_all_ce_f1_aux_1': 0.35000000298023226, 'Losses/train_all_presence_loss_aux_1': 0.07961311852559447, 'Losses/train_all_presence_dec_acc_aux_1': 0.95, 'Losses/train_all_loss_ce_aux_1_o2m': 0.038603634014725684, 'Losses/train_all_ce_f1_aux_1_o2m': 0.30103896707296374, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.021272049099206925, 'Losses/train_all_loss_giou_aux_2': 0.10901008546352386, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03754960596561432, 'Losses/train_all_loss_giou_aux_2_o2m': 0.20254846811294555, 'Losses/train_all_loss_ce_aux_2': 0.004676428204402327, 'Losses/train_all_ce_f1_aux_2': 0.39500000029802323, 'Losses/train_all_presence_loss_aux_2': 0.08169185542501509, 'Losses/train_all_presence_dec_acc_aux_2': 0.95, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03840042445808649, 'Losses/train_all_ce_f1_aux_2_o2m': 0.31095238626003263, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.019878042861819267, 'Losses/train_all_loss_giou_aux_3': 0.10692073106765747, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.033320105820894244, 'Losses/train_all_loss_giou_aux_3_o2m': 0.19312852025032043, 'Losses/train_all_loss_ce_aux_3': 0.004506128106731922, 'Losses/train_all_ce_f1_aux_3': 0.39500000029802323, 'Losses/train_all_presence_loss_aux_3': 0.08053890587761998, 'Losses/train_all_presence_dec_acc_aux_3': 0.95, 'Losses/train_all_loss_ce_aux_3_o2m': 0.04044320546090603, 'Losses/train_all_ce_f1_aux_3_o2m': 0.31000000461935995, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.013275361992418766, 'Losses/train_all_loss_giou_aux_4': 0.08555562198162078, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.03754948228597641, 'Losses/train_all_loss_giou_aux_4_o2m': 0.20346508622169496, 'Losses/train_all_loss_ce_aux_4': 0.004720296047162264, 'Losses/train_all_ce_f1_aux_4': 0.375, 'Losses/train_all_presence_loss_aux_4': 0.08321058470755816, 'Losses/train_all_presence_dec_acc_aux_4': 0.95, 'Losses/train_all_loss_ce_aux_4_o2m': 0.04006818439811468, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3139869324862957, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 47.63475280404091, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.00502772955223918, 'Losses/train_all_loss_semantic_dice': 0.19215843379497527, 'Losses/train_all_miou_semantic_seg': 0.7442689321935176, 'Trainer/where': 0.2375, 'Trainer/epoch': 0, 'Trainer/steps_train': 20}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:08:18,307 train_utils.py: 269: Train Epoch: [1][ 0/20] | Batch Time: 10.02 (10.02) | Data Time: 7.60 (7.60) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 5.31e+01 (5.31e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:08:39,991 train_utils.py: 269: Train Epoch: [1][10/20] | Batch Time: 2.18 (2.88) | Data Time: 0.00 (0.70) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 4.15e+01 (4.68e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:09:01,050 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 13:09:01,051 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:09:01,051 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 45.27080622315407, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.011824143305420875, 'Losses/train_all_loss_giou': 0.07631577253341675, 'Losses/train_all_loss_bbox_o2m': 0.1198628768324852, 'Losses/train_all_loss_giou_o2m': 0.560499656200409, 'Losses/train_all_loss_ce': 0.004418113071005791, 'Losses/train_all_ce_f1': 0.3833333343267441, 'Losses/train_all_presence_loss': 0.0722888682037592, 'Losses/train_all_presence_dec_acc': 1.0, 'Losses/train_all_loss_ce_o2m': 0.039493766985833643, 'Losses/train_all_ce_f1_o2m': 0.7166666686534882, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.001763751549879089, 'Losses/train_all_loss_dice': 0.18356720805168153, 'Losses/train_all_loss_mask_o2m': 0.016019561607390643, 'Losses/train_all_loss_dice_o2m': 1.4883743584156037, 'Losses/train_all_loss_bbox_aux_0': 0.024360621348023415, 'Losses/train_all_loss_giou_aux_0': 0.1222871720790863, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.04389370083808899, 'Losses/train_all_loss_giou_aux_0_o2m': 0.21382651329040528, 'Losses/train_all_loss_ce_aux_0': 0.005021697375923395, 'Losses/train_all_ce_f1_aux_0': 0.35000000298023226, 'Losses/train_all_presence_loss_aux_0': 0.06682275515049696, 'Losses/train_all_presence_dec_acc_aux_0': 1.0, 'Losses/train_all_loss_ce_aux_0_o2m': 0.028600215353071688, 'Losses/train_all_ce_f1_aux_0_o2m': 0.3022222265601158, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.016109512001276017, 'Losses/train_all_loss_giou_aux_1': 0.09458235800266265, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.02318321093916893, 'Losses/train_all_loss_giou_aux_1_o2m': 0.14483054280281066, 'Losses/train_all_loss_ce_aux_1': 0.004532574815675617, 'Losses/train_all_ce_f1_aux_1': 0.3583333343267441, 'Losses/train_all_presence_loss_aux_1': 0.07210485180839896, 'Losses/train_all_presence_dec_acc_aux_1': 1.0, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03740177229046822, 'Losses/train_all_ce_f1_aux_1_o2m': 0.30500000417232515, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.01716654226183891, 'Losses/train_all_loss_giou_aux_2': 0.10099618434906006, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.02244488149881363, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1479105234146118, 'Losses/train_all_loss_ce_aux_2': 0.0041681606904603544, 'Losses/train_all_ce_f1_aux_2': 0.40833333432674407, 'Losses/train_all_presence_loss_aux_2': 0.07379456562921405, 'Losses/train_all_presence_dec_acc_aux_2': 1.0, 'Losses/train_all_loss_ce_aux_2_o2m': 0.038609992153942584, 'Losses/train_all_ce_f1_aux_2_o2m': 0.3022222265601158, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.01673195939511061, 'Losses/train_all_loss_giou_aux_3': 0.09881840348243713, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.02424744889140129, 'Losses/train_all_loss_giou_aux_3_o2m': 0.15394338369369506, 'Losses/train_all_loss_ce_aux_3': 0.004196117876563221, 'Losses/train_all_ce_f1_aux_3': 0.40833333432674407, 'Losses/train_all_presence_loss_aux_3': 0.06903010718524456, 'Losses/train_all_presence_dec_acc_aux_3': 1.0, 'Losses/train_all_loss_ce_aux_3_o2m': 0.04014190062880516, 'Losses/train_all_ce_f1_aux_3_o2m': 0.3022222265601158, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.011450795643031596, 'Losses/train_all_loss_giou_aux_4': 0.07322977781295777, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.023671764135360717, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15270593166351318, 'Losses/train_all_loss_ce_aux_4': 0.004464590898714959, 'Losses/train_all_ce_f1_aux_4': 0.3833333343267441, 'Losses/train_all_presence_loss_aux_4': 0.07210979498922825, 'Losses/train_all_presence_dec_acc_aux_4': 1.0, 'Losses/train_all_loss_ce_aux_4_o2m': 0.04081926308572292, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3022222265601158, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 45.27080622315407, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005097504076547921, 'Losses/train_all_loss_semantic_dice': 0.18925894647836686, 'Losses/train_all_miou_semantic_seg': 0.7480624135583639, 'Trainer/where': 0.4875, 'Trainer/epoch': 1, 'Trainer/steps_train': 40}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:09:29,532 train_utils.py: 269: Train Epoch: [2][ 0/20] | Batch Time: 10.12 (10.12) | Data Time: 7.64 (7.64) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.12e+01 (1.12e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:09:51,069 train_utils.py: 269: Train Epoch: [2][10/20] | Batch Time: 2.16 (2.88) | Data Time: 0.00 (0.70) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 7.63e+01 (5.38e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:10:11,597 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:10:11,598 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:10:11,598 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 42.77841193974018, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.013756097666919232, 'Losses/train_all_loss_giou': 0.07566912174224853, 'Losses/train_all_loss_bbox_o2m': 0.11959930099546909, 'Losses/train_all_loss_giou_o2m': 0.639474606513977, 'Losses/train_all_loss_ce': 0.0046828696737065915, 'Losses/train_all_ce_f1': 0.39500000029802323, 'Losses/train_all_presence_loss': 0.06620485559105874, 'Losses/train_all_presence_dec_acc': 1.0, 'Losses/train_all_loss_ce_o2m': 0.039291825331747535, 'Losses/train_all_ce_f1_o2m': 0.7783333346247673, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0014807766245212405, 'Losses/train_all_loss_dice': 0.18399084210395814, 'Losses/train_all_loss_mask_o2m': 0.013100627111271024, 'Losses/train_all_loss_dice_o2m': 1.3973014414310456, 'Losses/train_all_loss_bbox_aux_0': 0.027106375060975553, 'Losses/train_all_loss_giou_aux_0': 0.1432407468557358, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.0418820932507515, 'Losses/train_all_loss_giou_aux_0_o2m': 0.21133761405944823, 'Losses/train_all_loss_ce_aux_0': 0.005800050566904247, 'Losses/train_all_ce_f1_aux_0': 0.31666666865348814, 'Losses/train_all_presence_loss_aux_0': 0.06537054835353047, 'Losses/train_all_presence_dec_acc_aux_0': 0.95, 'Losses/train_all_loss_ce_aux_0_o2m': 0.030307980254292488, 'Losses/train_all_ce_f1_aux_0_o2m': 0.25769841820001604, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.014824645593762398, 'Losses/train_all_loss_giou_aux_1': 0.08056516945362091, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.043643644079566, 'Losses/train_all_loss_giou_aux_1_o2m': 0.20869724154472352, 'Losses/train_all_loss_ce_aux_1': 0.005259733973070979, 'Losses/train_all_ce_f1_aux_1': 0.3583333343267441, 'Losses/train_all_presence_loss_aux_1': 0.062463258183561264, 'Losses/train_all_presence_dec_acc_aux_1': 0.95, 'Losses/train_all_loss_ce_aux_1_o2m': 0.034075620397925374, 'Losses/train_all_ce_f1_aux_1_o2m': 0.32888889461755755, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.01741346102207899, 'Losses/train_all_loss_giou_aux_2': 0.0867537498474121, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.03146365806460381, 'Losses/train_all_loss_giou_aux_2_o2m': 0.1664769947528839, 'Losses/train_all_loss_ce_aux_2': 0.004747542599216103, 'Losses/train_all_ce_f1_aux_2': 0.375, 'Losses/train_all_presence_loss_aux_2': 0.06526924504432827, 'Losses/train_all_presence_dec_acc_aux_2': 0.95, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03577825948596001, 'Losses/train_all_ce_f1_aux_2_o2m': 0.31818182319402694, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.015652358904480933, 'Losses/train_all_loss_giou_aux_3': 0.07920482158660888, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.029938015341758727, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1565691590309143, 'Losses/train_all_loss_ce_aux_3': 0.0047555540106259285, 'Losses/train_all_ce_f1_aux_3': 0.39500000029802323, 'Losses/train_all_presence_loss_aux_3': 0.06358140234369784, 'Losses/train_all_presence_dec_acc_aux_3': 0.95, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03696302622556687, 'Losses/train_all_ce_f1_aux_3_o2m': 0.3166666716337204, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.014188742823898792, 'Losses/train_all_loss_giou_aux_4': 0.0765961229801178, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.027640759572386743, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15018963813781738, 'Losses/train_all_loss_ce_aux_4': 0.004678145493380725, 'Losses/train_all_ce_f1_aux_4': 0.4, 'Losses/train_all_presence_loss_aux_4': 0.06305210688151419, 'Losses/train_all_presence_dec_acc_aux_4': 1.0, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03719987608492374, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2966666713356972, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 42.77841193974018, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004328376986086369, 'Losses/train_all_loss_semantic_dice': 0.1745968632400036, 'Losses/train_all_miou_semantic_seg': 0.7587876357138157, 'Trainer/where': 0.7375, 'Trainer/epoch': 2, 'Trainer/steps_train': 60}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:10:48,581 train_utils.py: 269: Train Epoch: [3][ 0/20] | Batch Time: 15.68 (15.68) | Data Time: 12.86 (12.86) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 6.74e-01 (6.74e-01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:11:09,995 train_utils.py: 269: Train Epoch: [3][10/20] | Batch Time: 2.16 (3.37) | Data Time: 0.02 (1.18) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 5.24e+01 (3.34e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:11:30,458 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:11:30,459 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:11:30,459 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 37.450111001729965, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.011271291598677634, 'Losses/train_all_loss_giou': 0.07798207700252532, 'Losses/train_all_loss_bbox_o2m': 0.08148356489837169, 'Losses/train_all_loss_giou_o2m': 0.5866004705429078, 'Losses/train_all_loss_ce': 0.004408008453901857, 'Losses/train_all_ce_f1': 0.4, 'Losses/train_all_presence_loss': 0.040395866800099614, 'Losses/train_all_presence_dec_acc': 1.0, 'Losses/train_all_loss_ce_o2m': 0.038369083777070045, 'Losses/train_all_ce_f1_o2m': 0.7565079405903816, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0014665114926174284, 'Losses/train_all_loss_dice': 0.1600147843360901, 'Losses/train_all_loss_mask_o2m': 0.012624197080731392, 'Losses/train_all_loss_dice_o2m': 1.2659741401672364, 'Losses/train_all_loss_bbox_aux_0': 0.02517968788743019, 'Losses/train_all_loss_giou_aux_0': 0.13667849600315093, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.04361457824707031, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2432192087173462, 'Losses/train_all_loss_ce_aux_0': 0.005170845449902118, 'Losses/train_all_ce_f1_aux_0': 0.4333333343267441, 'Losses/train_all_presence_loss_aux_0': 0.034462646069005134, 'Losses/train_all_presence_dec_acc_aux_0': 1.0, 'Losses/train_all_loss_ce_aux_0_o2m': 0.02934003807604313, 'Losses/train_all_ce_f1_aux_0_o2m': 0.33380953073501585, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.016146382503211498, 'Losses/train_all_loss_giou_aux_1': 0.10536056160926818, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.028867388889193536, 'Losses/train_all_loss_giou_aux_1_o2m': 0.19283028244972228, 'Losses/train_all_loss_ce_aux_1': 0.005139703105669469, 'Losses/train_all_ce_f1_aux_1': 0.38666666895151136, 'Losses/train_all_presence_loss_aux_1': 0.03561776485294103, 'Losses/train_all_presence_dec_acc_aux_1': 1.0, 'Losses/train_all_loss_ce_aux_1_o2m': 0.035753664560616016, 'Losses/train_all_ce_f1_aux_1_o2m': 0.31818182319402694, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.01564491242170334, 'Losses/train_all_loss_giou_aux_2': 0.10093300640583039, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.020549924671649934, 'Losses/train_all_loss_giou_aux_2_o2m': 0.14061327576637267, 'Losses/train_all_loss_ce_aux_2': 0.004288145573809743, 'Losses/train_all_ce_f1_aux_2': 0.4, 'Losses/train_all_presence_loss_aux_2': 0.03691129519138485, 'Losses/train_all_presence_dec_acc_aux_2': 1.0, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03718352671712637, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2900000050663948, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.01548472959548235, 'Losses/train_all_loss_giou_aux_3': 0.10191134512424468, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.021955950185656548, 'Losses/train_all_loss_giou_aux_3_o2m': 0.1401757001876831, 'Losses/train_all_loss_ce_aux_3': 0.004258733417373151, 'Losses/train_all_ce_f1_aux_3': 0.4283333346247673, 'Losses/train_all_presence_loss_aux_3': 0.038248165789991614, 'Losses/train_all_presence_dec_acc_aux_3': 1.0, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0393737118691206, 'Losses/train_all_ce_f1_aux_3_o2m': 0.310000005364418, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.015314405597746373, 'Losses/train_all_loss_giou_aux_4': 0.10185036361217499, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.021737800166010856, 'Losses/train_all_loss_giou_aux_4_o2m': 0.14726063013076782, 'Losses/train_all_loss_ce_aux_4': 0.004196129960473627, 'Losses/train_all_ce_f1_aux_4': 0.4200000002980232, 'Losses/train_all_presence_loss_aux_4': 0.038925764197483656, 'Losses/train_all_presence_dec_acc_aux_4': 1.0, 'Losses/train_all_loss_ce_aux_4_o2m': 0.04030390717089176, 'Losses/train_all_ce_f1_aux_4_o2m': 0.30969697535037993, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 37.450111001729965, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004310164600610733, 'Losses/train_all_loss_semantic_dice': 0.17006175220012665, 'Losses/train_all_miou_semantic_seg': 0.7650713413953781, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_train': 80}
INFO 2026-05-03 13:11:52,289 train_utils.py: 269: Val Epoch: [3][  0/228] | Batch Time: 0.86 (0.86) | Data Time: 0.14 (0.14) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:11:59,703 train_utils.py: 269: Val Epoch: [3][ 10/228] | Batch Time: 0.65 (0.75) | Data Time: 0.03 (0.09) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:06,403 train_utils.py: 269: Val Epoch: [3][ 20/228] | Batch Time: 0.79 (0.71) | Data Time: 0.17 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:13,089 train_utils.py: 269: Val Epoch: [3][ 30/228] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 06m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:19,613 train_utils.py: 269: Val Epoch: [3][ 40/228] | Batch Time: 0.65 (0.69) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:26,258 train_utils.py: 269: Val Epoch: [3][ 50/228] | Batch Time: 0.65 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:32,793 train_utils.py: 269: Val Epoch: [3][ 60/228] | Batch Time: 0.66 (0.68) | Data Time: 0.03 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:39,519 train_utils.py: 269: Val Epoch: [3][ 70/228] | Batch Time: 0.65 (0.68) | Data Time: 0.02 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:46,312 train_utils.py: 269: Val Epoch: [3][ 80/228] | Batch Time: 0.65 (0.68) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:12:53,362 train_utils.py: 269: Val Epoch: [3][ 90/228] | Batch Time: 0.65 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 13:13:00,303 train_utils.py: 269: Val Epoch: [3][100/228] | Batch Time: 0.67 (0.68) | Data Time: 0.04 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:06,849 train_utils.py: 269: Val Epoch: [3][110/228] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:13,531 train_utils.py: 269: Val Epoch: [3][120/228] | Batch Time: 0.65 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 07m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:20,385 train_utils.py: 269: Val Epoch: [3][130/228] | Batch Time: 0.66 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:27,519 train_utils.py: 269: Val Epoch: [3][140/228] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:34,337 train_utils.py: 269: Val Epoch: [3][150/228] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:41,008 train_utils.py: 269: Val Epoch: [3][160/228] | Batch Time: 0.66 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:47,785 train_utils.py: 269: Val Epoch: [3][170/228] | Batch Time: 0.67 (0.68) | Data Time: 0.02 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:13:54,583 train_utils.py: 269: Val Epoch: [3][180/228] | Batch Time: 0.68 (0.68) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:14:01,849 train_utils.py: 269: Val Epoch: [3][190/228] | Batch Time: 0.81 (0.68) | Data Time: 0.17 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:14:08,858 train_utils.py: 269: Val Epoch: [3][200/228] | Batch Time: 0.67 (0.68) | Data Time: 0.03 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 08m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:14:15,737 train_utils.py: 269: Val Epoch: [3][210/228] | Batch Time: 0.67 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:14:22,485 train_utils.py: 269: Val Epoch: [3][220/228] | Batch Time: 0.67 (0.68) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 09m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:14:27,510 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:14:27,510 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:14:27,511 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:14:27,511 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:14:27,801 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 13:14:28,295 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:14:28,381 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.23s)
creating index...
index created!
INFO 2026-05-03 13:14:28,612 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.38s).
Accumulating evaluation results...
DONE (t=0.10s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.120
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.301
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.120
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.029
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.241
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.239
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.176
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.211
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.219
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.333
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 13:14:29,104 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.11979975584501935, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.30148447203264916, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.12018728451791007, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.028959877909453122, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.24091446942311961, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.23928571428571424, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.17631578947368423, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.21052631578947367, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.21929824561403505, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.041304347826086954, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.3328358208955224, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9875, 'Trainer/epoch': 3, 'Trainer/steps_val': 228}

[rank0]:[W503 13:14:29.576715531 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_10shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 13:14:31] TEST EVAL: shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_10shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/10_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TB-to-TC_10pct
  shot_per_class: 10
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/10_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/10_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/10_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:14:38,074 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:14:38,080 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:14:38,080 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=49283
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:14:38,082 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:14:38,083 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/10_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:14:58,972 trainer.py:1150: ====================
INFO 2026-05-03 13:14:58,972 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:14:58,976 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 13:18:14,364 train_utils.py: 269: Train Epoch: [0][ 0/50] | Batch Time: 102.21 (102.21) | Data Time: 6.09 (6.09) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 7.35e+01 (7.35e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:18:36,716 train_utils.py: 269: Train Epoch: [0][10/50] | Batch Time: 2.17 (11.32) | Data Time: 0.00 (0.56) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 1.81e+02 (7.98e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:18:58,577 train_utils.py: 269: Train Epoch: [0][20/50] | Batch Time: 2.18 (6.97) | Data Time: 0.04 (0.30) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 5.78e+01 (6.26e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:19:20,475 train_utils.py: 269: Train Epoch: [0][30/50] | Batch Time: 2.18 (5.43) | Data Time: 0.00 (0.21) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.37e+02 (6.34e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:19:42,369 train_utils.py: 269: Train Epoch: [0][40/50] | Batch Time: 2.16 (4.64) | Data Time: 0.06 (0.16) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 1.94e+01 (5.87e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:20:03,744 trainer.py:1042: Estimated time remaining: 00d 00h 10m
INFO 2026-05-03 13:20:03,745 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:20:03,745 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 58.785733046531675, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03540850453078747, 'Losses/train_all_loss_giou': 0.1317414629459381, 'Losses/train_all_loss_bbox_o2m': 0.16229018449783325, 'Losses/train_all_loss_giou_o2m': 0.7038283705711365, 'Losses/train_all_loss_ce': 0.005435206899419427, 'Losses/train_all_ce_f1': 0.38333333551883697, 'Losses/train_all_presence_loss': 0.11480612603947521, 'Losses/train_all_presence_dec_acc': 0.94, 'Losses/train_all_loss_ce_o2m': 0.04629225181415677, 'Losses/train_all_ce_f1_o2m': 0.6588071721792221, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002584488287102431, 'Losses/train_all_loss_dice': 0.2264505457878113, 'Losses/train_all_loss_mask_o2m': 0.02026262551546097, 'Losses/train_all_loss_dice_o2m': 1.6677947521209717, 'Losses/train_all_loss_bbox_aux_0': 0.03990714550018311, 'Losses/train_all_loss_giou_aux_0': 0.15722408175468444, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.07482000261545181, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2960815477371216, 'Losses/train_all_loss_ce_aux_0': 0.0062938297260552644, 'Losses/train_all_ce_f1_aux_0': 0.35000000238418577, 'Losses/train_all_presence_loss_aux_0': 0.10854324165731669, 'Losses/train_all_presence_dec_acc_aux_0': 0.94, 'Losses/train_all_loss_ce_aux_0_o2m': 0.03133780933916569, 'Losses/train_all_ce_f1_aux_0_o2m': 0.25630447804927825, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.042250010818243026, 'Losses/train_all_loss_giou_aux_1': 0.13286788105964661, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.0688598632067442, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2542807412147522, 'Losses/train_all_loss_ce_aux_1': 0.005798666262999177, 'Losses/train_all_ce_f1_aux_1': 0.3780000025033951, 'Losses/train_all_presence_loss_aux_1': 0.10993228318169714, 'Losses/train_all_presence_dec_acc_aux_1': 0.92, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03712165921926498, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2809497544169426, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03592615008354187, 'Losses/train_all_loss_giou_aux_2': 0.12846882820129393, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.07229644879698753, 'Losses/train_all_loss_giou_aux_2_o2m': 0.265669424533844, 'Losses/train_all_loss_ce_aux_2': 0.0055431546363979576, 'Losses/train_all_ce_f1_aux_2': 0.38666666865348814, 'Losses/train_all_presence_loss_aux_2': 0.11069455996155739, 'Losses/train_all_presence_dec_acc_aux_2': 0.92, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03785895854234696, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2940929451584816, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.035424171872437, 'Losses/train_all_loss_giou_aux_3': 0.12992833375930787, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.07050510324537754, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2570636701583862, 'Losses/train_all_loss_ce_aux_3': 0.0054722353164106605, 'Losses/train_all_ce_f1_aux_3': 0.3813333356380463, 'Losses/train_all_presence_loss_aux_3': 0.11107100384309888, 'Losses/train_all_presence_dec_acc_aux_3': 0.94, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03928344614803791, 'Losses/train_all_ce_f1_aux_3_o2m': 0.29620076328516004, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03548341177403927, 'Losses/train_all_loss_giou_aux_4': 0.13135676264762877, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.07642505057156086, 'Losses/train_all_loss_giou_aux_4_o2m': 0.23259661912918092, 'Losses/train_all_loss_ce_aux_4': 0.00539342325180769, 'Losses/train_all_ce_f1_aux_4': 0.38333333551883697, 'Losses/train_all_presence_loss_aux_4': 0.113538787253201, 'Losses/train_all_presence_dec_acc_aux_4': 0.94, 'Losses/train_all_loss_ce_aux_4_o2m': 0.04026026882231235, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3035457926988602, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 58.785733046531675, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.006910494342446327, 'Losses/train_all_loss_semantic_dice': 0.23506377190351485, 'Losses/train_all_miou_semantic_seg': 0.7015812253579498, 'Trainer/where': 0.245, 'Trainer/epoch': 0, 'Trainer/steps_train': 50}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:20:36,148 train_utils.py: 269: Train Epoch: [1][ 0/50] | Batch Time: 12.97 (12.97) | Data Time: 10.74 (10.74) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 7.47e+01 (7.47e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:20:57,796 train_utils.py: 269: Train Epoch: [1][10/50] | Batch Time: 2.16 (3.15) | Data Time: 0.00 (0.98) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.74e+01 (6.38e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:21:19,827 train_utils.py: 269: Train Epoch: [1][20/50] | Batch Time: 2.17 (2.70) | Data Time: 0.00 (0.53) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 1.11e+02 (6.38e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:21:41,552 train_utils.py: 269: Train Epoch: [1][30/50] | Batch Time: 2.16 (2.53) | Data Time: 0.03 (0.36) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 4.39e+01 (5.34e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:22:03,270 train_utils.py: 269: Train Epoch: [1][40/50] | Batch Time: 2.18 (2.44) | Data Time: 0.00 (0.28) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 3.24e+01 (5.14e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:22:24,912 trainer.py:1042: Estimated time remaining: 00d 00h 03m
INFO 2026-05-03 13:22:24,912 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:22:24,912 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 49.67811601579189, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03241057332605123, 'Losses/train_all_loss_giou': 0.1193022882938385, 'Losses/train_all_loss_bbox_o2m': 0.16849936082959174, 'Losses/train_all_loss_giou_o2m': 0.6428071784973145, 'Losses/train_all_loss_ce': 0.005578181529417634, 'Losses/train_all_ce_f1': 0.3700000011920929, 'Losses/train_all_presence_loss': 0.06425618586596102, 'Losses/train_all_presence_dec_acc': 0.96, 'Losses/train_all_loss_ce_o2m': 0.04841819668188691, 'Losses/train_all_ce_f1_o2m': 0.6133632153272629, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.002059759614057839, 'Losses/train_all_loss_dice': 0.2157117807865143, 'Losses/train_all_loss_mask_o2m': 0.016500796545296906, 'Losses/train_all_loss_dice_o2m': 1.5651258254051208, 'Losses/train_all_loss_bbox_aux_0': 0.03892615396529436, 'Losses/train_all_loss_giou_aux_0': 0.15130216717720033, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.08316426411271095, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2427007055282593, 'Losses/train_all_loss_ce_aux_0': 0.006192229799926281, 'Losses/train_all_ce_f1_aux_0': 0.26666666865348815, 'Losses/train_all_presence_loss_aux_0': 0.058321699431398887, 'Losses/train_all_presence_dec_acc_aux_0': 0.98, 'Losses/train_all_loss_ce_aux_0_o2m': 0.0306204554438591, 'Losses/train_all_ce_f1_aux_0_o2m': 0.24800000488758087, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03300852656364441, 'Losses/train_all_loss_giou_aux_1': 0.12763968467712403, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.08351994212716818, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2425800681114197, 'Losses/train_all_loss_ce_aux_1': 0.005444481032900512, 'Losses/train_all_ce_f1_aux_1': 0.31333333492279053, 'Losses/train_all_presence_loss_aux_1': 0.059095131300855426, 'Losses/train_all_presence_dec_acc_aux_1': 1.0, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03493793644011021, 'Losses/train_all_ce_f1_aux_1_o2m': 0.30131746411323546, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.029692740850150584, 'Losses/train_all_loss_giou_aux_2': 0.1204440200328827, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.07356613416224718, 'Losses/train_all_loss_giou_aux_2_o2m': 0.21184380054473878, 'Losses/train_all_loss_ce_aux_2': 0.0056249944027513266, 'Losses/train_all_ce_f1_aux_2': 0.3200000011920929, 'Losses/train_all_presence_loss_aux_2': 0.060725733984727415, 'Losses/train_all_presence_dec_acc_aux_2': 1.0, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03660404831171036, 'Losses/train_all_ce_f1_aux_2_o2m': 0.277111114859581, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03331143604591489, 'Losses/train_all_loss_giou_aux_3': 0.12542112231254576, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.07491490848362446, 'Losses/train_all_loss_giou_aux_3_o2m': 0.20528897762298584, 'Losses/train_all_loss_ce_aux_3': 0.005494609270244837, 'Losses/train_all_ce_f1_aux_3': 0.3666666680574417, 'Losses/train_all_presence_loss_aux_3': 0.06271934540942312, 'Losses/train_all_presence_dec_acc_aux_3': 1.0, 'Losses/train_all_loss_ce_aux_3_o2m': 0.037997513338923455, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2932727313041687, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.0323028527200222, 'Losses/train_all_loss_giou_aux_4': 0.11961495280265808, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.07466986648738384, 'Losses/train_all_loss_giou_aux_4_o2m': 0.20759353637695313, 'Losses/train_all_loss_ce_aux_4': 0.005507071274332702, 'Losses/train_all_ce_f1_aux_4': 0.3600000011920929, 'Losses/train_all_presence_loss_aux_4': 0.06299914208706468, 'Losses/train_all_presence_dec_acc_aux_4': 0.98, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03857835896313191, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2836488002538681, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 49.67811601579189, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.006774187698028982, 'Losses/train_all_loss_semantic_dice': 0.2205609332025051, 'Losses/train_all_miou_semantic_seg': 0.7149468989895104, 'Trainer/where': 0.495, 'Trainer/epoch': 1, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:22:51,602 train_utils.py: 269: Train Epoch: [2][ 0/50] | Batch Time: 9.75 (9.75) | Data Time: 7.46 (7.46) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 2.05e+00 (2.05e+00) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:23:13,129 train_utils.py: 269: Train Epoch: [2][10/50] | Batch Time: 2.17 (2.84) | Data Time: 0.00 (0.69) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 3.14e+01 (4.54e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:23:34,945 train_utils.py: 269: Train Epoch: [2][20/50] | Batch Time: 2.16 (2.53) | Data Time: 0.03 (0.37) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.74e+02 (5.81e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:23:56,862 train_utils.py: 269: Train Epoch: [2][30/50] | Batch Time: 2.17 (2.42) | Data Time: 0.00 (0.25) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 6.67e+01 (5.90e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:24:18,564 train_utils.py: 269: Train Epoch: [2][40/50] | Batch Time: 2.17 (2.36) | Data Time: 0.04 (0.20) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 3.12e+01 (4.87e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:24:38,874 trainer.py:1042: Estimated time remaining: 00d 00h 01m
INFO 2026-05-03 13:24:38,874 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:24:38,874 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 48.66223239835352, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.036061513628810646, 'Losses/train_all_loss_giou': 0.12221376299858093, 'Losses/train_all_loss_bbox_o2m': 0.16768890127539635, 'Losses/train_all_loss_giou_o2m': 0.6279121780395508, 'Losses/train_all_loss_ce': 0.005350971724838018, 'Losses/train_all_ce_f1': 0.37666666865348813, 'Losses/train_all_presence_loss': 0.0917145896157308, 'Losses/train_all_presence_dec_acc': 0.92, 'Losses/train_all_loss_ce_o2m': 0.04578943617641926, 'Losses/train_all_ce_f1_o2m': 0.6604444468021393, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0017459391674492508, 'Losses/train_all_loss_dice': 0.20092151761054994, 'Losses/train_all_loss_mask_o2m': 0.012966521875932812, 'Losses/train_all_loss_dice_o2m': 1.439949722290039, 'Losses/train_all_loss_bbox_aux_0': 0.03590291861444712, 'Losses/train_all_loss_giou_aux_0': 0.12926220297813415, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06117914330214262, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2391953444480896, 'Losses/train_all_loss_ce_aux_0': 0.006406653486192226, 'Losses/train_all_ce_f1_aux_0': 0.2600000023841858, 'Losses/train_all_presence_loss_aux_0': 0.07593431650908315, 'Losses/train_all_presence_dec_acc_aux_0': 0.92, 'Losses/train_all_loss_ce_aux_0_o2m': 0.028788438886404037, 'Losses/train_all_ce_f1_aux_0_o2m': 0.22257431864738464, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03244195060804486, 'Losses/train_all_loss_giou_aux_1': 0.1259813678264618, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06179167103022337, 'Losses/train_all_loss_giou_aux_1_o2m': 0.22397859811782836, 'Losses/train_all_loss_ce_aux_1': 0.005317131672054529, 'Losses/train_all_ce_f1_aux_1': 0.3300000011920929, 'Losses/train_all_presence_loss_aux_1': 0.0800786476819485, 'Losses/train_all_presence_dec_acc_aux_1': 0.92, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03342602327466011, 'Losses/train_all_ce_f1_aux_1_o2m': 0.25739683032035826, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03156139330938459, 'Losses/train_all_loss_giou_aux_2': 0.11871222496032714, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05509947758167982, 'Losses/train_all_loss_giou_aux_2_o2m': 0.20658310890197754, 'Losses/train_all_loss_ce_aux_2': 0.0053441230114549395, 'Losses/train_all_ce_f1_aux_2': 0.3633333349227905, 'Losses/train_all_presence_loss_aux_2': 0.08146946274864604, 'Losses/train_all_presence_dec_acc_aux_2': 0.92, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03471439726650715, 'Losses/train_all_ce_f1_aux_2_o2m': 0.258000003695488, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.030129132512956857, 'Losses/train_all_loss_giou_aux_3': 0.11676723003387451, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.05741918813437223, 'Losses/train_all_loss_giou_aux_3_o2m': 0.21530471324920655, 'Losses/train_all_loss_ce_aux_3': 0.005349356895312667, 'Losses/train_all_ce_f1_aux_3': 0.3800000023841858, 'Losses/train_all_presence_loss_aux_3': 0.08585034601943335, 'Losses/train_all_presence_dec_acc_aux_3': 0.92, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03593762621283531, 'Losses/train_all_ce_f1_aux_3_o2m': 0.25720635294914246, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.030186419282108544, 'Losses/train_all_loss_giou_aux_4': 0.12183284282684326, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05949366848915815, 'Losses/train_all_loss_giou_aux_4_o2m': 0.21190886020660402, 'Losses/train_all_loss_ce_aux_4': 0.00524284609593451, 'Losses/train_all_ce_f1_aux_4': 0.3733333361148834, 'Losses/train_all_presence_loss_aux_4': 0.0873979476756358, 'Losses/train_all_presence_dec_acc_aux_4': 0.92, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03605088457465172, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2613333374261856, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 48.66223239835352, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005547434685286135, 'Losses/train_all_loss_semantic_dice': 0.1994244223833084, 'Losses/train_all_miou_semantic_seg': 0.7361112799741386, 'Trainer/where': 0.745, 'Trainer/epoch': 2, 'Trainer/steps_train': 150}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:25:16,430 train_utils.py: 269: Train Epoch: [3][ 0/50] | Batch Time: 13.96 (13.96) | Data Time: 11.57 (11.57) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 9.91e-02 (9.91e-02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:25:38,094 train_utils.py: 269: Train Epoch: [3][10/50] | Batch Time: 2.34 (3.24) | Data Time: 0.00 (1.07) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 6.89e+01 (2.69e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:25:59,627 train_utils.py: 269: Train Epoch: [3][20/50] | Batch Time: 2.14 (2.72) | Data Time: 0.00 (0.57) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 2.66e-01 (3.14e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:26:21,355 train_utils.py: 269: Train Epoch: [3][30/50] | Batch Time: 2.16 (2.54) | Data Time: 0.00 (0.39) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 2.72e+02 (5.17e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:26:43,083 train_utils.py: 269: Train Epoch: [3][40/50] | Batch Time: 2.17 (2.45) | Data Time: 0.00 (0.30) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 2.19e+02 (5.15e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:27:04,121 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:27:04,121 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:27:04,121 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 51.061550246751864, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.04206354668363929, 'Losses/train_all_loss_giou': 0.11974218010902404, 'Losses/train_all_loss_bbox_o2m': 0.18178329095244408, 'Losses/train_all_loss_giou_o2m': 0.5880921339988708, 'Losses/train_all_loss_ce': 0.0051017985050566496, 'Losses/train_all_ce_f1': 0.3980000013113022, 'Losses/train_all_presence_loss': 0.10451312726377182, 'Losses/train_all_presence_dec_acc': 0.88, 'Losses/train_all_loss_ce_o2m': 0.04414007365703583, 'Losses/train_all_ce_f1_o2m': 0.6321280062198639, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0017221758142113685, 'Losses/train_all_loss_dice': 0.19036978006362915, 'Losses/train_all_loss_mask_o2m': 0.014207316562533379, 'Losses/train_all_loss_dice_o2m': 1.451734938621521, 'Losses/train_all_loss_bbox_aux_0': 0.043670429587364196, 'Losses/train_all_loss_giou_aux_0': 0.14505452036857605, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.07560335163027049, 'Losses/train_all_loss_giou_aux_0_o2m': 0.24608229875564575, 'Losses/train_all_loss_ce_aux_0': 0.006084013236686587, 'Losses/train_all_ce_f1_aux_0': 0.3366666674613953, 'Losses/train_all_presence_loss_aux_0': 0.10150580239032933, 'Losses/train_all_presence_dec_acc_aux_0': 0.88, 'Losses/train_all_loss_ce_aux_0_o2m': 0.027536288499832154, 'Losses/train_all_ce_f1_aux_0_o2m': 0.27789988338947297, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.0387018733844161, 'Losses/train_all_loss_giou_aux_1': 0.11095981001853943, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.07283102262765169, 'Losses/train_all_loss_giou_aux_1_o2m': 0.22998193979263307, 'Losses/train_all_loss_ce_aux_1': 0.00560474444180727, 'Losses/train_all_ce_f1_aux_1': 0.35133333384990695, 'Losses/train_all_presence_loss_aux_1': 0.09183270603940401, 'Losses/train_all_presence_dec_acc_aux_1': 0.92, 'Losses/train_all_loss_ce_aux_1_o2m': 0.0320352827757597, 'Losses/train_all_ce_f1_aux_1_o2m': 0.28441070556640624, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.04261998061090708, 'Losses/train_all_loss_giou_aux_2': 0.11968315720558166, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.0761352153122425, 'Losses/train_all_loss_giou_aux_2_o2m': 0.21478421449661256, 'Losses/train_all_loss_ce_aux_2': 0.005008710045367479, 'Losses/train_all_ce_f1_aux_2': 0.39466666758060454, 'Losses/train_all_presence_loss_aux_2': 0.09600927177712947, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03224115714430809, 'Losses/train_all_ce_f1_aux_2_o2m': 0.3235189300775528, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.0426500116288662, 'Losses/train_all_loss_giou_aux_3': 0.12047161102294922, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.08109343398362398, 'Losses/train_all_loss_giou_aux_3_o2m': 0.22975870370864868, 'Losses/train_all_loss_ce_aux_3': 0.005043226694688201, 'Losses/train_all_ce_f1_aux_3': 0.3966666674613953, 'Losses/train_all_presence_loss_aux_3': 0.09944588317031958, 'Losses/train_all_presence_dec_acc_aux_3': 0.88, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03301436237990856, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2917142897844315, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.04207153480499983, 'Losses/train_all_loss_giou_aux_4': 0.11996561527252197, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.07620952643454075, 'Losses/train_all_loss_giou_aux_4_o2m': 0.224820032119751, 'Losses/train_all_loss_ce_aux_4': 0.005011863762047142, 'Losses/train_all_ce_f1_aux_4': 0.4000000011920929, 'Losses/train_all_presence_loss_aux_4': 0.10080513750553109, 'Losses/train_all_presence_dec_acc_aux_4': 0.88, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03400756426155567, 'Losses/train_all_ce_f1_aux_4_o2m': 0.29603175044059754, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 51.061550246751864, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.005002625668421388, 'Losses/train_all_loss_semantic_dice': 0.19199243649840356, 'Losses/train_all_miou_semantic_seg': 0.7431749475933611, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_train': 200}
INFO 2026-05-03 13:27:22,614 train_utils.py: 269: Val Epoch: [3][  0/228] | Batch Time: 0.78 (0.78) | Data Time: 0.04 (0.04) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:27:29,654 train_utils.py: 269: Val Epoch: [3][ 10/228] | Batch Time: 0.69 (0.71) | Data Time: 0.04 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:27:37,047 train_utils.py: 269: Val Epoch: [3][ 20/228] | Batch Time: 0.67 (0.72) | Data Time: 0.02 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:27:45,038 train_utils.py: 269: Val Epoch: [3][ 30/228] | Batch Time: 0.68 (0.75) | Data Time: 0.03 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:27:52,053 train_utils.py: 269: Val Epoch: [3][ 40/228] | Batch Time: 0.66 (0.74) | Data Time: 0.02 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:27:59,155 train_utils.py: 269: Val Epoch: [3][ 50/228] | Batch Time: 0.74 (0.73) | Data Time: 0.11 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:05,915 train_utils.py: 269: Val Epoch: [3][ 60/228] | Batch Time: 0.67 (0.72) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 13:28:12,913 train_utils.py: 269: Val Epoch: [3][ 70/228] | Batch Time: 0.67 (0.72) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:19,984 train_utils.py: 269: Val Epoch: [3][ 80/228] | Batch Time: 0.70 (0.72) | Data Time: 0.06 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:26,981 train_utils.py: 269: Val Epoch: [3][ 90/228] | Batch Time: 0.76 (0.72) | Data Time: 0.13 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:33,669 train_utils.py: 269: Val Epoch: [3][100/228] | Batch Time: 0.67 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:40,400 train_utils.py: 269: Val Epoch: [3][110/228] | Batch Time: 0.67 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:47,052 train_utils.py: 269: Val Epoch: [3][120/228] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:28:53,664 train_utils.py: 269: Val Epoch: [3][130/228] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.05) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:01,140 train_utils.py: 269: Val Epoch: [3][140/228] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:08,073 train_utils.py: 269: Val Epoch: [3][150/228] | Batch Time: 0.66 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:15,255 train_utils.py: 269: Val Epoch: [3][160/228] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:22,226 train_utils.py: 269: Val Epoch: [3][170/228] | Batch Time: 0.68 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:29,337 train_utils.py: 269: Val Epoch: [3][180/228] | Batch Time: 0.68 (0.70) | Data Time: 0.04 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:36,257 train_utils.py: 269: Val Epoch: [3][190/228] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:43,508 train_utils.py: 269: Val Epoch: [3][200/228] | Batch Time: 0.67 (0.70) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:50,800 train_utils.py: 269: Val Epoch: [3][210/228] | Batch Time: 0.67 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:29:58,123 train_utils.py: 269: Val Epoch: [3][220/228] | Batch Time: 0.66 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 13m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:30:03,153 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:30:03,153 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:30:03,153 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:30:03,153 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:30:03,435 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 13:30:03,774 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:30:03,859 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.23s)
creating index...
index created!
INFO 2026-05-03 13:30:04,089 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.36s).
Accumulating evaluation results...
DONE (t=0.10s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.137
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.376
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.114
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.040
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.255
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.187
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.228
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.065
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.352
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 13:30:04,570 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.1367685588880395, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.3758476530665115, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.11422898745171546, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.039843026727419156, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.25516187958532704, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.3392857142857143, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.1868421052631579, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.22807017543859648, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.24035087719298245, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.06521739130434782, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.3522388059701492, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.995, 'Trainer/epoch': 3, 'Trainer/steps_val': 228}

[rank0]:[W503 13:30:05.017883597 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_25shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 13:30:06] TEST EVAL: shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_25shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/25_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TB-to-TC_10pct
  shot_per_class: 25
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/25_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/25_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/25_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:30:13,290 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:30:13,293 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:30:13,294 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=54125
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:30:13,294 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:30:13,295 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:30:33,771 trainer.py:1150: ====================
INFO 2026-05-03 13:30:33,771 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:30:33,775 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 13:30:35,257 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 13:30:35,258 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:30:35,258 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 13:30:35,266 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 13:30:35.233942202 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 38
INFO 2026-05-03 13:30:35,538 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 13:31:06,047 train_utils.py: 269: Val Epoch: [4][ 0/38] | Batch Time: 19.61 (19.61) | Data Time: 0.05 (0.05) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:31:15,632 train_utils.py: 269: Val Epoch: [4][10/38] | Batch Time: 0.83 (2.65) | Data Time: 0.18 (0.18) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:31:22,701 train_utils.py: 269: Val Epoch: [4][20/38] | Batch Time: 0.66 (1.73) | Data Time: 0.03 (0.13) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 11m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:31:30,230 train_utils.py: 269: Val Epoch: [4][30/38] | Batch Time: 0.81 (1.41) | Data Time: 0.17 (0.12) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 12m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:31:35,004 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:31:35,005 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:31:35,005 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:31:35,005 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:31:35,199 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 13:31:35,259 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:31:35,283 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 13:31:35,295 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.06s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.017
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.100
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.013
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.016
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.036
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.158
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.174
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.200
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.155
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
INFO 2026-05-03 13:31:35,374 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.01721326517395142, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.10020913294677249, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.013179749347483768, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.016236657999099968, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.03588437567160971, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': -1.0, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.1, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.15789473684210525, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.17368421052631577, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.2, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.15454545454545454, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': -1.0, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 38}

[rank0]:[W503 13:31:35.765817500 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/25_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

####################################################################################################
Batch item 12/12: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1 (Shift-TA_TB-to-TC_10pct, 50-shot)
Selected experiment: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1
Training config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_50shot_textseg_stable_lowlr_v1.yaml
Output dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1
====================================================================================================
[2026-05-03 13:31:37] TRAIN: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_50shot_textseg_stable_lowlr_v1.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TB-to-TC_10pct
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: train
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: ${ttd_fewshot.val_img_folder}
        ann_file: ${ttd_fewshot.val_ann_file}
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: false
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/val
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: ${ttd_fewshot.val_ann_file}
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:31:44,270 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:31:44,275 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:31:44,275 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=27172
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:31:44,276 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:31:44,279 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:31:56,957 trainer.py:1150: ====================
INFO 2026-05-03 13:31:56,957 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:31:56,961 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 13:31:58,388 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val
INFO 2026-05-03 13:31:58,389 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:31:58,389 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 13:31:58,397 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

Raw dataset length = 228
Raw dataset length = 100

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:869: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1024, 1024]
bucket_view.sizes() = [256, 1024, 1, 1], strides() = [1024, 1, 1, 1] (Triggered internally at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:332.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

INFO 2026-05-03 13:33:40,000 train_utils.py: 269: Train Epoch: [0][  0/100] | Batch Time: 101.12 (101.12) | Data Time: 5.71 (5.71) | Mem (GB): 43.00 (43.00/43.00) | Time Elapsed: 00d 00h 01m | Losses/train_all_loss: 4.49e+01 (4.49e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:34:02,858 train_utils.py: 269: Train Epoch: [0][ 10/100] | Batch Time: 2.43 (11.27) | Data Time: 0.00 (0.53) | Mem (GB): 16.00 (18.45/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 5.20e+00 (3.39e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:34:24,748 train_utils.py: 269: Train Epoch: [0][ 20/100] | Batch Time: 2.19 (6.95) | Data Time: 0.05 (0.28) | Mem (GB): 16.00 (17.29/43.00) | Time Elapsed: 00d 00h 02m | Losses/train_all_loss: 7.76e+01 (5.18e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:34:46,912 train_utils.py: 269: Train Epoch: [0][ 30/100] | Batch Time: 2.20 (5.42) | Data Time: 0.00 (0.20) | Mem (GB): 16.00 (16.87/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 8.93e+01 (5.13e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:35:08,733 train_utils.py: 269: Train Epoch: [0][ 40/100] | Batch Time: 2.17 (4.63) | Data Time: 0.05 (0.15) | Mem (GB): 16.00 (16.66/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 4.36e+00 (5.00e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:35:30,800 train_utils.py: 269: Train Epoch: [0][ 50/100] | Batch Time: 2.19 (4.16) | Data Time: 0.00 (0.13) | Mem (GB): 16.00 (16.53/43.00) | Time Elapsed: 00d 00h 03m | Losses/train_all_loss: 2.73e+02 (5.65e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:35:52,852 train_utils.py: 269: Train Epoch: [0][ 60/100] | Batch Time: 2.18 (3.84) | Data Time: 0.02 (0.11) | Mem (GB): 16.00 (16.44/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.58e+00 (5.12e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:36:14,760 train_utils.py: 269: Train Epoch: [0][ 70/100] | Batch Time: 2.20 (3.60) | Data Time: 0.00 (0.09) | Mem (GB): 16.00 (16.38/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 3.71e+01 (5.25e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:36:36,937 train_utils.py: 269: Train Epoch: [0][ 80/100] | Batch Time: 2.20 (3.43) | Data Time: 0.02 (0.09) | Mem (GB): 16.00 (16.33/43.00) | Time Elapsed: 00d 00h 04m | Losses/train_all_loss: 1.27e+02 (5.44e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:36:59,020 train_utils.py: 269: Train Epoch: [0][ 90/100] | Batch Time: 2.21 (3.30) | Data Time: 0.00 (0.08) | Mem (GB): 16.00 (16.30/43.00) | Time Elapsed: 00d 00h 05m | Losses/train_all_loss: 2.61e+01 (5.40e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:37:20,069 trainer.py:1042: Estimated time remaining: 00d 00h 16m
INFO 2026-05-03 13:37:20,069 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:37:20,070 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 55.064891469962895, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03174667472019792, 'Losses/train_all_loss_giou': 0.1012119871377945, 'Losses/train_all_loss_bbox_o2m': 0.17757758751511574, 'Losses/train_all_loss_giou_o2m': 0.6257050013542176, 'Losses/train_all_loss_ce': 0.005067909362260252, 'Losses/train_all_ce_f1': 0.37400000244379045, 'Losses/train_all_presence_loss': 0.11666400838381379, 'Losses/train_all_presence_dec_acc': 0.92, 'Losses/train_all_loss_ce_o2m': 0.04205583502538502, 'Losses/train_all_ce_f1_o2m': 0.6546155248582363, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0020962124306242915, 'Losses/train_all_loss_dice': 0.20589840769767762, 'Losses/train_all_loss_mask_o2m': 0.017695202527102084, 'Losses/train_all_loss_dice_o2m': 1.5679956245422364, 'Losses/train_all_loss_bbox_aux_0': 0.03821246594190598, 'Losses/train_all_loss_giou_aux_0': 0.14170552551746368, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.0665187492966652, 'Losses/train_all_loss_giou_aux_0_o2m': 0.23794906020164489, 'Losses/train_all_loss_ce_aux_0': 0.005944759766571224, 'Losses/train_all_ce_f1_aux_0': 0.343333335518837, 'Losses/train_all_presence_loss_aux_0': 0.1120936017553322, 'Losses/train_all_presence_dec_acc_aux_0': 0.94, 'Losses/train_all_loss_ce_aux_0_o2m': 0.029119106642901897, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2484227278828621, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03488324712961912, 'Losses/train_all_loss_giou_aux_1': 0.11271882593631745, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06287451889365911, 'Losses/train_all_loss_giou_aux_1_o2m': 0.2150048530101776, 'Losses/train_all_loss_ce_aux_1': 0.005336265709483996, 'Losses/train_all_ce_f1_aux_1': 0.3680000019073486, 'Losses/train_all_presence_loss_aux_1': 0.11277532435167814, 'Losses/train_all_presence_dec_acc_aux_1': 0.94, 'Losses/train_all_loss_ce_aux_1_o2m': 0.03419502731412649, 'Losses/train_all_ce_f1_aux_1_o2m': 0.28431631669402124, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03369674074463546, 'Losses/train_all_loss_giou_aux_2': 0.11396882593631745, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.06405543038621545, 'Losses/train_all_loss_giou_aux_2_o2m': 0.2169135344028473, 'Losses/train_all_loss_ce_aux_2': 0.005032707029022277, 'Losses/train_all_ce_f1_aux_2': 0.3830000013113022, 'Losses/train_all_presence_loss_aux_2': 0.11363384778203908, 'Losses/train_all_presence_dec_acc_aux_2': 0.92, 'Losses/train_all_loss_ce_aux_2_o2m': 0.034829695373773575, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2884102615714073, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.03205476921983063, 'Losses/train_all_loss_giou_aux_3': 0.10197818398475647, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.057871930114924905, 'Losses/train_all_loss_giou_aux_3_o2m': 0.2015355384349823, 'Losses/train_all_loss_ce_aux_3': 0.005071257839445025, 'Losses/train_all_ce_f1_aux_3': 0.3873333343863487, 'Losses/train_all_presence_loss_aux_3': 0.11287994892190908, 'Losses/train_all_presence_dec_acc_aux_3': 0.92, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03607561945915222, 'Losses/train_all_ce_f1_aux_3_o2m': 0.27756105482578275, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03210040640085936, 'Losses/train_all_loss_giou_aux_4': 0.10148179054260253, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05884942334145307, 'Losses/train_all_loss_giou_aux_4_o2m': 0.20212231516838075, 'Losses/train_all_loss_ce_aux_4': 0.005039912910433486, 'Losses/train_all_ce_f1_aux_4': 0.36833333551883696, 'Losses/train_all_presence_loss_aux_4': 0.11525428878812818, 'Losses/train_all_presence_dec_acc_aux_4': 0.92, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03645581625401974, 'Losses/train_all_ce_f1_aux_4_o2m': 0.2725610545277595, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 55.064891469962895, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.0056127039773855355, 'Losses/train_all_loss_semantic_dice': 0.21693714551627635, 'Losses/train_all_miou_semantic_seg': 0.7221242241188883, 'Trainer/where': 0.2475, 'Trainer/epoch': 0, 'Trainer/steps_train': 100}

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:37:50,045 train_utils.py: 269: Train Epoch: [1][  0/100] | Batch Time: 12.18 (12.18) | Data Time: 9.08 (9.08) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 1.77e+02 (1.77e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:38:11,867 train_utils.py: 269: Train Epoch: [1][ 10/100] | Batch Time: 2.21 (3.09) | Data Time: 0.00 (0.84) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 8.01e+00 (3.05e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:38:34,049 train_utils.py: 269: Train Epoch: [1][ 20/100] | Batch Time: 2.19 (2.68) | Data Time: 0.08 (0.45) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 06m | Losses/train_all_loss: 5.28e+01 (5.58e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:38:56,069 train_utils.py: 269: Train Epoch: [1][ 30/100] | Batch Time: 2.19 (2.52) | Data Time: 0.00 (0.31) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.40e+02 (5.66e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:39:18,109 train_utils.py: 269: Train Epoch: [1][ 40/100] | Batch Time: 2.17 (2.44) | Data Time: 0.05 (0.24) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.46e+00 (5.25e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:39:39,906 train_utils.py: 269: Train Epoch: [1][ 50/100] | Batch Time: 2.17 (2.39) | Data Time: 0.00 (0.19) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 07m | Losses/train_all_loss: 1.03e-02 (5.05e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:40:02,061 train_utils.py: 269: Train Epoch: [1][ 60/100] | Batch Time: 2.18 (2.36) | Data Time: 0.05 (0.16) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 1.58e-02 (4.84e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:40:24,192 train_utils.py: 269: Train Epoch: [1][ 70/100] | Batch Time: 2.18 (2.34) | Data Time: 0.00 (0.14) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 08m | Losses/train_all_loss: 1.50e-01 (4.92e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:40:46,263 train_utils.py: 269: Train Epoch: [1][ 80/100] | Batch Time: 2.20 (2.33) | Data Time: 0.05 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 6.44e+01 (4.80e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:41:08,441 train_utils.py: 269: Train Epoch: [1][ 90/100] | Batch Time: 2.20 (2.31) | Data Time: 0.00 (0.12) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 09m | Losses/train_all_loss: 6.85e-02 (4.75e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:41:30,092 trainer.py:1042: Estimated time remaining: 00d 00h 07m
INFO 2026-05-03 13:41:30,092 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:41:30,092 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 48.603189602758505, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03405750436708331, 'Losses/train_all_loss_giou': 0.10493920624256134, 'Losses/train_all_loss_bbox_o2m': 0.16959923028945922, 'Losses/train_all_loss_giou_o2m': 0.5963849818706513, 'Losses/train_all_loss_ce': 0.004988166822586209, 'Losses/train_all_ce_f1': 0.3683333343267441, 'Losses/train_all_presence_loss': 0.10425333071627847, 'Losses/train_all_presence_dec_acc': 0.91, 'Losses/train_all_loss_ce_o2m': 0.0409086275100708, 'Losses/train_all_ce_f1_o2m': 0.657608671784401, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0015498633368406444, 'Losses/train_all_loss_dice': 0.18902053117752074, 'Losses/train_all_loss_mask_o2m': 0.011745133055374026, 'Losses/train_all_loss_dice_o2m': 1.3515281248092652, 'Losses/train_all_loss_bbox_aux_0': 0.03951209783554077, 'Losses/train_all_loss_giou_aux_0': 0.1363707083463669, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06548372309654951, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2363431239128113, 'Losses/train_all_loss_ce_aux_0': 0.005662866830825806, 'Losses/train_all_ce_f1_aux_0': 0.33833333492279055, 'Losses/train_all_presence_loss_aux_0': 0.09939042645676636, 'Losses/train_all_presence_dec_acc_aux_0': 0.91, 'Losses/train_all_loss_ce_aux_0_o2m': 0.0273857656121254, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2416007375717163, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03870918223634362, 'Losses/train_all_loss_giou_aux_1': 0.12454560935497284, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05741980034857988, 'Losses/train_all_loss_giou_aux_1_o2m': 0.20328917384147643, 'Losses/train_all_loss_ce_aux_1': 0.005165570557583123, 'Losses/train_all_ce_f1_aux_1': 0.3600000011920929, 'Losses/train_all_presence_loss_aux_1': 0.0954628280700581, 'Losses/train_all_presence_dec_acc_aux_1': 0.92, 'Losses/train_all_loss_ce_aux_1_o2m': 0.032703036125749346, 'Losses/train_all_ce_f1_aux_1_o2m': 0.2592014694213867, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03540922533720732, 'Losses/train_all_loss_giou_aux_2': 0.11013895094394684, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.0638514606654644, 'Losses/train_all_loss_giou_aux_2_o2m': 0.19783777356147766, 'Losses/train_all_loss_ce_aux_2': 0.005033489618217573, 'Losses/train_all_ce_f1_aux_2': 0.37666666746139527, 'Losses/train_all_presence_loss_aux_2': 0.10046218778031289, 'Losses/train_all_presence_dec_acc_aux_2': 0.91, 'Losses/train_all_loss_ce_aux_2_o2m': 0.03360598972067237, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2905386886000633, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.0348417435772717, 'Losses/train_all_loss_giou_aux_3': 0.10903935849666596, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.060749446600675584, 'Losses/train_all_loss_giou_aux_3_o2m': 0.20563746452331544, 'Losses/train_all_loss_ce_aux_3': 0.004988036274444312, 'Losses/train_all_ce_f1_aux_3': 0.37666666746139527, 'Losses/train_all_presence_loss_aux_3': 0.10339175157887893, 'Losses/train_all_presence_dec_acc_aux_3': 0.91, 'Losses/train_all_loss_ce_aux_3_o2m': 0.03439932750537991, 'Losses/train_all_ce_f1_aux_3_o2m': 0.2861418628692627, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03234180644154549, 'Losses/train_all_loss_giou_aux_4': 0.10580549538135528, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05389825850725174, 'Losses/train_all_loss_giou_aux_4_o2m': 0.19138206481933595, 'Losses/train_all_loss_ce_aux_4': 0.004995260965079069, 'Losses/train_all_ce_f1_aux_4': 0.3600000011920929, 'Losses/train_all_presence_loss_aux_4': 0.10646188441209688, 'Losses/train_all_presence_dec_acc_aux_4': 0.91, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03503647841513157, 'Losses/train_all_ce_f1_aux_4_o2m': 0.27709424316883086, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 48.603189602758505, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004856812953948975, 'Losses/train_all_loss_semantic_dice': 0.18276239559054375, 'Losses/train_all_miou_semantic_seg': 0.7529146344400942, 'Trainer/where': 0.4975, 'Trainer/epoch': 1, 'Trainer/steps_train': 200}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:42:01,503 train_utils.py: 269: Train Epoch: [2][  0/100] | Batch Time: 12.56 (12.56) | Data Time: 9.69 (9.69) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 6.48e-02 (6.48e-02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:42:23,279 train_utils.py: 269: Train Epoch: [2][ 10/100] | Batch Time: 2.20 (3.12) | Data Time: 0.00 (0.89) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 10m | Losses/train_all_loss: 1.45e-04 (2.92e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:42:45,193 train_utils.py: 269: Train Epoch: [2][ 20/100] | Batch Time: 2.17 (2.68) | Data Time: 0.02 (0.48) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 3.92e-04 (3.18e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:43:07,079 train_utils.py: 269: Train Epoch: [2][ 30/100] | Batch Time: 2.16 (2.52) | Data Time: 0.00 (0.33) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 4.05e-05 (3.47e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:43:29,056 train_utils.py: 269: Train Epoch: [2][ 40/100] | Batch Time: 2.19 (2.44) | Data Time: 0.03 (0.25) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 11m | Losses/train_all_loss: 1.46e+02 (3.77e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:43:51,031 train_utils.py: 269: Train Epoch: [2][ 50/100] | Batch Time: 2.17 (2.39) | Data Time: 0.00 (0.20) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 8.67e-02 (3.59e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:44:13,132 train_utils.py: 269: Train Epoch: [2][ 60/100] | Batch Time: 2.18 (2.36) | Data Time: 0.02 (0.17) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 9.39e+01 (5.39e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:44:35,202 train_utils.py: 269: Train Epoch: [2][ 70/100] | Batch Time: 2.19 (2.34) | Data Time: 0.00 (0.15) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 12m | Losses/train_all_loss: 4.28e+01 (6.15e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:44:57,347 train_utils.py: 269: Train Epoch: [2][ 80/100] | Batch Time: 2.20 (2.33) | Data Time: 0.02 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 2.71e+02 (6.39e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:45:19,512 train_utils.py: 269: Train Epoch: [2][ 90/100] | Batch Time: 2.19 (2.31) | Data Time: 0.00 (0.12) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 13m | Losses/train_all_loss: 1.04e-03 (6.02e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:45:40,724 trainer.py:1042: Estimated time remaining: 00d 00h 03m
INFO 2026-05-03 13:45:40,725 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:45:40,725 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 56.19035321522808, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03192434219643474, 'Losses/train_all_loss_giou': 0.10114624321460725, 'Losses/train_all_loss_bbox_o2m': 0.14941522598266602, 'Losses/train_all_loss_giou_o2m': 0.5389446341991424, 'Losses/train_all_loss_ce': 0.005003381473943591, 'Losses/train_all_ce_f1': 0.37400000214576723, 'Losses/train_all_presence_loss': 0.17547044255655891, 'Losses/train_all_presence_dec_acc': 0.91, 'Losses/train_all_loss_ce_o2m': 0.042869756864383816, 'Losses/train_all_ce_f1_o2m': 0.6297741189599038, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.0014002930658170954, 'Losses/train_all_loss_dice': 0.17883409500122072, 'Losses/train_all_loss_mask_o2m': 0.011797667653299869, 'Losses/train_all_loss_dice_o2m': 1.3734255349636078, 'Losses/train_all_loss_bbox_aux_0': 0.040699126049876216, 'Losses/train_all_loss_giou_aux_0': 0.14460058093070985, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.059478821586817505, 'Losses/train_all_loss_giou_aux_0_o2m': 0.21901944398880005, 'Losses/train_all_loss_ce_aux_0': 0.00563575429841876, 'Losses/train_all_ce_f1_aux_0': 0.3633333349227905, 'Losses/train_all_presence_loss_aux_0': 0.16779758921641588, 'Losses/train_all_presence_dec_acc_aux_0': 0.92, 'Losses/train_all_loss_ce_aux_0_o2m': 0.026513854898512365, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2889062103629112, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03225910160690546, 'Losses/train_all_loss_giou_aux_1': 0.11281586587429046, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.05607599087059498, 'Losses/train_all_loss_giou_aux_1_o2m': 0.19451003074645995, 'Losses/train_all_loss_ce_aux_1': 0.00514662794303149, 'Losses/train_all_ce_f1_aux_1': 0.3751904779672623, 'Losses/train_all_presence_loss_aux_1': 0.16770813049043595, 'Losses/train_all_presence_dec_acc_aux_1': 0.9, 'Losses/train_all_loss_ce_aux_1_o2m': 0.029061663877218962, 'Losses/train_all_ce_f1_aux_1_o2m': 0.29375702545046806, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.030669466964900492, 'Losses/train_all_loss_giou_aux_2': 0.10988828778266907, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.055046838521957395, 'Losses/train_all_loss_giou_aux_2_o2m': 0.19104267358779908, 'Losses/train_all_loss_ce_aux_2': 0.0050470921047963205, 'Losses/train_all_ce_f1_aux_2': 0.36233333498239517, 'Losses/train_all_presence_loss_aux_2': 0.1685489169200686, 'Losses/train_all_presence_dec_acc_aux_2': 0.9, 'Losses/train_all_loss_ce_aux_2_o2m': 0.029965610951185228, 'Losses/train_all_ce_f1_aux_2_o2m': 0.2951797494292259, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.02974911231547594, 'Losses/train_all_loss_giou_aux_3': 0.0959504371881485, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.05547818694263697, 'Losses/train_all_loss_giou_aux_3_o2m': 0.18963006258010864, 'Losses/train_all_loss_ce_aux_3': 0.005156923695467413, 'Losses/train_all_ce_f1_aux_3': 0.3533333352208137, 'Losses/train_all_presence_loss_aux_3': 0.17079916430246006, 'Losses/train_all_presence_dec_acc_aux_3': 0.9, 'Losses/train_all_loss_ce_aux_3_o2m': 0.031063052117824553, 'Losses/train_all_ce_f1_aux_3_o2m': 0.299327934384346, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.03181145750917494, 'Losses/train_all_loss_giou_aux_4': 0.1015238630771637, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.053463926762342455, 'Losses/train_all_loss_giou_aux_4_o2m': 0.1857650661468506, 'Losses/train_all_loss_ce_aux_4': 0.005006002767477185, 'Losses/train_all_ce_f1_aux_4': 0.37000000208616257, 'Losses/train_all_presence_loss_aux_4': 0.17331095679401276, 'Losses/train_all_presence_dec_acc_aux_4': 0.9, 'Losses/train_all_loss_ce_aux_4_o2m': 0.03169591885060072, 'Losses/train_all_ce_f1_aux_4_o2m': 0.28831061750650405, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 56.19035321522808, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004446996249025687, 'Losses/train_all_loss_semantic_dice': 0.18410586800426246, 'Losses/train_all_miou_semantic_seg': 0.7531858915649354, 'Trainer/where': 0.7475, 'Trainer/epoch': 2, 'Trainer/steps_train': 300}

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

INFO 2026-05-03 13:46:11,720 train_utils.py: 269: Train Epoch: [3][  0/100] | Batch Time: 12.49 (12.49) | Data Time: 8.97 (8.97) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 4.01e+02 (4.01e+02) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:46:33,746 train_utils.py: 269: Train Epoch: [3][ 10/100] | Batch Time: 2.43 (3.14) | Data Time: 0.00 (0.83) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 14m | Losses/train_all_loss: 3.01e+01 (8.62e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:46:55,585 train_utils.py: 269: Train Epoch: [3][ 20/100] | Batch Time: 2.17 (2.68) | Data Time: 0.06 (0.44) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 3.10e-05 (6.36e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:47:17,421 train_utils.py: 269: Train Epoch: [3][ 30/100] | Batch Time: 2.16 (2.52) | Data Time: 0.00 (0.30) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 4.41e-05 (4.80e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:47:39,447 train_utils.py: 269: Train Epoch: [3][ 40/100] | Batch Time: 2.20 (2.44) | Data Time: 0.06 (0.23) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 15m | Losses/train_all_loss: 4.06e+01 (4.38e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:48:01,699 train_utils.py: 269: Train Epoch: [3][ 50/100] | Batch Time: 2.19 (2.40) | Data Time: 0.00 (0.19) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 4.58e+01 (4.73e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:48:23,796 train_utils.py: 269: Train Epoch: [3][ 60/100] | Batch Time: 2.20 (2.37) | Data Time: 0.07 (0.16) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 16m | Losses/train_all_loss: 1.43e+02 (5.20e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:48:45,803 train_utils.py: 269: Train Epoch: [3][ 70/100] | Batch Time: 2.20 (2.35) | Data Time: 0.00 (0.14) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 2.60e+01 (4.99e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:49:07,719 train_utils.py: 269: Train Epoch: [3][ 80/100] | Batch Time: 2.19 (2.33) | Data Time: 0.05 (0.13) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 5.13e-05 (4.63e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:49:29,870 train_utils.py: 269: Train Epoch: [3][ 90/100] | Batch Time: 2.20 (2.31) | Data Time: 0.00 (0.11) | Mem (GB): 16.00 (16.00/16.00) | Time Elapsed: 00d 00h 17m | Losses/train_all_loss: 1.34e-04 (4.77e+01) | Losses/train_default_loss: 0.00e+00 (0.00e+00)
INFO 2026-05-03 13:49:51,204 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:49:51,204 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:49:51,205 trainer.py: 901: Losses and meters: {'Losses/train_all_loss': 55.11601492941496, 'Losses/train_default_loss': 0, 'Losses/train_all_loss_bbox': 0.03489445679821074, 'Losses/train_all_loss_giou': 0.10977335512638092, 'Losses/train_all_loss_bbox_o2m': 0.16800703547894955, 'Losses/train_all_loss_giou_o2m': 0.5166844034194946, 'Losses/train_all_loss_ce': 0.0045860489620827135, 'Losses/train_all_ce_f1': 0.41400000065565107, 'Losses/train_all_presence_loss': 0.18410827411484865, 'Losses/train_all_presence_dec_acc': 0.89, 'Losses/train_all_loss_ce_o2m': 0.03850355149246752, 'Losses/train_all_ce_f1_o2m': 0.6888787907361984, 'Losses/train_all_presence_loss_o2m': 0.0, 'Losses/train_all_presence_dec_acc_o2m': 0.0, 'Losses/train_all_loss_mask': 0.00137415317381965, 'Losses/train_all_loss_dice': 0.17675697267055512, 'Losses/train_all_loss_mask_o2m': 0.01099532631924376, 'Losses/train_all_loss_dice_o2m': 1.2729674625396727, 'Losses/train_all_loss_bbox_aux_0': 0.03365265926346183, 'Losses/train_all_loss_giou_aux_0': 0.12016476929187775, 'Losses/train_all_loss_bbox_aux_0_o2m': 0.06565324964001774, 'Losses/train_all_loss_giou_aux_0_o2m': 0.2373772394657135, 'Losses/train_all_loss_ce_aux_0': 0.0055970142688602205, 'Losses/train_all_ce_f1_aux_0': 0.29666666746139525, 'Losses/train_all_presence_loss_aux_0': 0.17679767597794638, 'Losses/train_all_presence_dec_acc_aux_0': 0.89, 'Losses/train_all_loss_ce_aux_0_o2m': 0.023098616246134043, 'Losses/train_all_ce_f1_aux_0_o2m': 0.2707619094848633, 'Losses/train_all_presence_loss_aux_0_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_0_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_1': 0.03435945341363549, 'Losses/train_all_loss_giou_aux_1': 0.10055925071239472, 'Losses/train_all_loss_bbox_aux_1_o2m': 0.06076325800269842, 'Losses/train_all_loss_giou_aux_1_o2m': 0.19252677798271178, 'Losses/train_all_loss_ce_aux_1': 0.004974504266865552, 'Losses/train_all_ce_f1_aux_1': 0.3823333343863487, 'Losses/train_all_presence_loss_aux_1': 0.1745227610489635, 'Losses/train_all_presence_dec_acc_aux_1': 0.89, 'Losses/train_all_loss_ce_aux_1_o2m': 0.025514152813702822, 'Losses/train_all_ce_f1_aux_1_o2m': 0.30841270357370376, 'Losses/train_all_presence_loss_aux_1_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_1_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_2': 0.03357138774357736, 'Losses/train_all_loss_giou_aux_2': 0.1037777054309845, 'Losses/train_all_loss_bbox_aux_2_o2m': 0.05990671243518591, 'Losses/train_all_loss_giou_aux_2_o2m': 0.18460243701934814, 'Losses/train_all_loss_ce_aux_2': 0.004825817025266588, 'Losses/train_all_ce_f1_aux_2': 0.4190000006556511, 'Losses/train_all_presence_loss_aux_2': 0.1788337287737337, 'Losses/train_all_presence_dec_acc_aux_2': 0.89, 'Losses/train_all_loss_ce_aux_2_o2m': 0.026373907197266816, 'Losses/train_all_ce_f1_aux_2_o2m': 0.33208081364631653, 'Losses/train_all_presence_loss_aux_2_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_2_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_3': 0.027012913431972266, 'Losses/train_all_loss_giou_aux_3': 0.10032215416431427, 'Losses/train_all_loss_bbox_aux_3_o2m': 0.061200492773205044, 'Losses/train_all_loss_giou_aux_3_o2m': 0.17531813859939574, 'Losses/train_all_loss_ce_aux_3': 0.004712507106596604, 'Losses/train_all_ce_f1_aux_3': 0.3956666675209999, 'Losses/train_all_presence_loss_aux_3': 0.18031307653836, 'Losses/train_all_presence_dec_acc_aux_3': 0.89, 'Losses/train_all_loss_ce_aux_3_o2m': 0.0270373878069222, 'Losses/train_all_ce_f1_aux_3_o2m': 0.35577922642230986, 'Losses/train_all_presence_loss_aux_3_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_3_o2m': 0.0, 'Losses/train_all_loss_bbox_aux_4': 0.028909352021291853, 'Losses/train_all_loss_giou_aux_4': 0.10690590500831604, 'Losses/train_all_loss_bbox_aux_4_o2m': 0.05417957674711943, 'Losses/train_all_loss_giou_aux_4_o2m': 0.15960897922515868, 'Losses/train_all_loss_ce_aux_4': 0.004599134554155171, 'Losses/train_all_ce_f1_aux_4': 0.3956666675209999, 'Losses/train_all_presence_loss_aux_4': 0.1843615754648626, 'Losses/train_all_presence_dec_acc_aux_4': 0.89, 'Losses/train_all_loss_ce_aux_4_o2m': 0.027760168462991716, 'Losses/train_all_ce_f1_aux_4_o2m': 0.3135093840956688, 'Losses/train_all_presence_loss_aux_4_o2m': 0.0, 'Losses/train_all_presence_dec_acc_aux_4_o2m': 0.0, 'Losses/train_all_core_loss': 55.11601492941496, 'Losses/train_all_loss_semantic_presence': 0.0, 'Losses/train_all_presence_acc': 0.0, 'Losses/train_all_loss_semantic_seg': 0.004342534685274586, 'Losses/train_all_loss_semantic_dice': 0.16672770157456399, 'Losses/train_all_miou_semantic_seg': 0.7679636664688587, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_train': 400}
INFO 2026-05-03 13:50:09,990 train_utils.py: 269: Val Epoch: [3][  0/228] | Batch Time: 1.08 (1.08) | Data Time: 0.20 (0.20) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:16,971 train_utils.py: 269: Val Epoch: [3][ 10/228] | Batch Time: 0.66 (0.73) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000

INFO 2026-05-03 13:50:23,840 train_utils.py: 269: Val Epoch: [3][ 20/228] | Batch Time: 0.66 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:31,155 train_utils.py: 269: Val Epoch: [3][ 30/228] | Batch Time: 0.66 (0.72) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:37,873 train_utils.py: 269: Val Epoch: [3][ 40/228] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:44,960 train_utils.py: 269: Val Epoch: [3][ 50/228] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:52,253 train_utils.py: 269: Val Epoch: [3][ 60/228] | Batch Time: 0.68 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:50:59,132 train_utils.py: 269: Val Epoch: [3][ 70/228] | Batch Time: 0.66 (0.71) | Data Time: 0.02 (0.06) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:06,326 train_utils.py: 269: Val Epoch: [3][ 80/228] | Batch Time: 0.80 (0.71) | Data Time: 0.17 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:13,187 train_utils.py: 269: Val Epoch: [3][ 90/228] | Batch Time: 0.77 (0.71) | Data Time: 0.13 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:20,088 train_utils.py: 269: Val Epoch: [3][100/228] | Batch Time: 0.66 (0.70) | Data Time: 0.02 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:27,174 train_utils.py: 269: Val Epoch: [3][110/228] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:34,381 train_utils.py: 269: Val Epoch: [3][120/228] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:41,475 train_utils.py: 269: Val Epoch: [3][130/228] | Batch Time: 0.65 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:48,905 train_utils.py: 269: Val Epoch: [3][140/228] | Batch Time: 0.75 (0.71) | Data Time: 0.11 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:51:56,709 train_utils.py: 269: Val Epoch: [3][150/228] | Batch Time: 0.67 (0.71) | Data Time: 0.04 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:03,620 train_utils.py: 269: Val Epoch: [3][160/228] | Batch Time: 0.67 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:10,608 train_utils.py: 269: Val Epoch: [3][170/228] | Batch Time: 0.66 (0.71) | Data Time: 0.03 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:18,373 train_utils.py: 269: Val Epoch: [3][180/228] | Batch Time: 0.92 (0.72) | Data Time: 0.29 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:25,730 train_utils.py: 269: Val Epoch: [3][190/228] | Batch Time: 0.67 (0.72) | Data Time: 0.03 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:32,622 train_utils.py: 269: Val Epoch: [3][200/228] | Batch Time: 0.66 (0.72) | Data Time: 0.02 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:39,337 train_utils.py: 269: Val Epoch: [3][210/228] | Batch Time: 0.66 (0.71) | Data Time: 0.02 (0.07) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 20m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:47,435 train_utils.py: 269: Val Epoch: [3][220/228] | Batch Time: 0.66 (0.72) | Data Time: 0.02 (0.08) | Mem (GB): 14.00 (14.00/14.00) | Time Elapsed: 00d 00h 21m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:52:52,273 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:52:52,274 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:52:52,274 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:52:52,274 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:52:52,607 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/val/coco_predictions_segm.json
INFO 2026-05-03 13:52:52,950 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:52:53,036 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.25s)
creating index...
index created!
INFO 2026-05-03 13:52:53,289 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.39s).
Accumulating evaluation results...
DONE (t=0.11s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.144
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.402
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.116
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.046
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.263
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.207
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.241
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.250
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.078
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.360
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.800
INFO 2026-05-03 13:52:53,800 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.1440110734204145, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.40159095152369945, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.11593216609966746, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.04573260145134919, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.26250617645399804, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': 0.3392857142857143, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.20701754385964916, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.24122807017543857, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.25, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.07826086956521738, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.3597014925373134, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': 0.8, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.9975, 'Trainer/epoch': 3, 'Trainer/steps_val': 228}

[rank0]:[W503 13:52:54.374100947 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
Checkpoint exists: True
Selected experiment: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1
Test eval config: configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_50shot_textseg_stable_lowlr_v1_test_eval.yaml
Using checkpoint: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
====================================================================================================
[2026-05-03 13:52:57] TEST EVAL: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1
Command: /users/7/yu001011/csci5527/.venv/bin/python -m sam3.train.train -c configs/ttd_fewshot/ttd_shift_ta_tb_to_tc_10pct_50shot_textseg_stable_lowlr_v1_test_eval.yaml --use-cluster 0 --num-gpus 1

/users/7/yu001011/csci5527/sam3/sam3/model_builder.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

###################### Train App Config ####################
paths:
  dataset_root: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class
  experiment_log_dir: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1
  bpe_path: /users/7/yu001011/csci5527/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  sam3_checkpoint: /users/7/yu001011/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
ttd_fewshot:
  experiment_name: Shift-TA_TB-to-TC_10pct
  shot_per_class: 50
  prompt_text: crack
  train_img_folder: ${paths.dataset_root}/train/images
  train_ann_file: ${paths.dataset_root}/train/_annotations.coco.json
  val_img_folder: ${paths.dataset_root}/val/images
  val_ann_file: ${paths.dataset_root}/val/_annotations.coco.json
  test_img_folder: ${paths.dataset_root}/test/images
  test_ann_file: ${paths.dataset_root}/test/_annotations.coco.json
scratch:
  enable_segmentation: true
  d_model: 256
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 200
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 4
  num_val_workers: 0
  hybrid_repeats: 1
  gather_pred_via_filesys: false
  val_batch_size: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  lr_scale: 0.1
  lr_transformer: 2.0e-06
  lr_vision_backbone: 5.0e-07
  lr_language_backbone: 1.0e-07
  lrd_vision_backbone: 0.9
  wd: 0.01
  scheduler_timescale: 50
  scheduler_warmup: 50
  scheduler_cooldown: 50
  scale_by_find_batch_size: false
  use_presence_eval: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  original_mask_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    use_presence: ${scratch.use_presence_eval}
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: all
    with_seg_masks: ${scratch.enable_segmentation}
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: ${scratch.hybrid_repeats}
    dict_key: ttd
    with_seg_masks: ${scratch.enable_segmentation}
ttd_train:
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.point_sampling.RandomizeInputBbox
      box_noise_std: 0.1
      box_noise_max: 20
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: ${scratch.resolution}
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: ${scratch.resolution}
      consistent_transform: ${scratch.consistent_transform}
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.train_norm_mean}
      std: ${scratch.train_norm_std}
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
  - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
    query_filter:
      _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
      max_num_objects: ${scratch.max_ann_per_img}
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: ${scratch.resolution}
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: ${scratch.resolution}
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean: ${scratch.val_norm_mean}
      std: ${scratch.val_norm_std}
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 20.0
        presence_loss: 20.0
      pos_weight: 3.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 200.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      presence_head: true
      presence_loss: false
      focal: true
      focal_alpha: 0.6
      focal_gamma: 2.0
      downsample: false
      weight_dict:
        loss_semantic_seg: 20.0
        loss_semantic_presence: 1.0
        loss_semantic_dice: 30.0
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}
trainer:
  _target_: sam3.train.trainer.Trainer
  mode: val
  max_epochs: 4
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 5
  gradient_accumulation_steps: ${scratch.gradient_accumulation_steps}
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: true
  distributed:
    backend: nccl
    find_unused_parameters: true
    gradient_as_bucket_view: true
  loss:
    all: ${ttd_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        transforms: ${ttd_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 100000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: false
        img_folder: ${ttd_fewshot.train_img_folder}
        ann_file: ${ttd_fewshot.train_ann_file}
      shuffle: true
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: false
      drop_last: true
      collate_fn: ${scratch.collate_fn}
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class/test/images
        ann_file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class/test/_annotations.coco.json
        transforms: ${ttd_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: false
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: true
      drop_last: false
      collate_fn: ${scratch.collate_fn_val}
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    checkpoint_path: ${paths.sam3_checkpoint}
    load_from_HF: false
    device: cuda
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}
  meters:
    val:
      ttd:
        segmentation:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: segm
          dump_dir: ${launcher.experiment_log_dir}/dumps/ttd/test
          merge_predictions: true
          postprocessor: ${scratch.original_mask_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
          - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
            gt_path: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class/test/_annotations.coco.json
            tide: false
            iou_type: segm
  optim:
    amp:
      enabled: false
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: ${scratch.lrd_vision_backbone}
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_transformer}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_vision_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: ${scratch.lr_language_backbone}
          timescale: ${scratch.scheduler_timescale}
          warmup_steps: ${scratch.scheduler_warmup}
          cooldown_steps: ${scratch.scheduler_cooldown}
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: ${scratch.wd}
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 0
    resume_from: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 24
  use_cluster: false
  cpus_per_task: 4
  port_range:
  - 10000
  - 65000

############################################################
Experiment Log Dir:
/users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1
INFO 2026-05-03 13:53:04,772 train_utils.py: 106: MACHINE SEED: 492
INFO 2026-05-03 13:53:04,787 train_utils.py: 152: Logging ENV_VARIABLES
INFO 2026-05-03 13:53:04,787 train_utils.py: 153: BASH_FUNC__module_raw%%=() {  unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" ] && [ "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "$(eval 'echo ${'"$_mlv"'+x}')" ]; then
 _mlre="${_mlre:-}__MODULES_QUAR_${_mlv}='$(eval 'echo ${'"$_mlv"'}')' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='$(eval 'echo ${'"$_mlrv"':-}')' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 _mlre="${_mlre:-}__MODULES_QUARANTINE_SET=1 ";
 eval "$(eval ${_mlre} /usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash '"$@"')";
 else
 eval "$(/usr/bin/tclsh '/usr/share/Modules/libexec/modulecmd.tcl' bash "$@")";
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 return $_mlstatus
}
BASH_FUNC_create_passwd%%=() {  ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
}
BASH_FUNC_find_port%%=() {  local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
}
BASH_FUNC_ml%%=() {  module ml "$@"
}
BASH_FUNC_module%%=() {  local _mlredir=0;
 if [ -n "${MODULES_REDIRECT_OUTPUT+x}" ]; then
 if [ "$MODULES_REDIRECT_OUTPUT" = '0' ]; then
 _mlredir=0;
 else
 if [ "$MODULES_REDIRECT_OUTPUT" = '1' ]; then
 _mlredir=1;
 fi;
 fi;
 fi;
 case " $@ " in
 *' --no-redirect '*)
 _mlredir=0
 ;;
 *' --redirect '*)
 _mlredir=1
 ;;
 esac;
 if [ $_mlredir -eq 0 ]; then
 _module_raw "$@";
 else
 _module_raw "$@" 2>&1;
 fi
}
BASH_FUNC_path_to_project%%=() {  ( local assume_pan=false;
 while (( $# > 1 )); do
 case "${1:-}" in
 '--help' | '-h')
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 0
 ;;
 '--assume-pan-on-miss')
 assume_pan=true;
 shift
 ;;
 *)
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1
 ;;
 esac;
 done;
 if (( $# != 1 )); then
 echo "Usage: ${FUNCNAME[0]} PROJECT_NAME" 1>&2;
 return 1;
 fi;
 shopt -s nullglob;
 local project_path=(/projects/*/$1);
 if [[ ! -z "${project_path[0]:-}" ]]; then
 echo ${project_path[0]:-};
 return 0;
 fi;
 if $assume_pan; then
 echo "/home/$1";
 return 0;
 else
 if [[ -d "/home/$1" ]]; then
 echo "/home/$1";
 return 0;
 else
 return 1;
 fi;
 fi )
}
BASH_FUNC_port_used%%=() {  local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
}
BASH_FUNC_random_number%%=() {  shuf -i ${1}-${2} -n 1
}
BASH_FUNC_s3cmd%%=() {  source '/opt/msi/bin/s3cmd' "$@"
}
BASH_FUNC_source_helpers%%=() {  function random_number ()
 {
 shuf -i ${1}-${2} -n 1
 };
 export -f random_number;
 function port_used_python ()
 {
 python -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_python3 ()
 {
 python3 -c "import socket; socket.socket().connect(('$1',$2))" > /dev/null 2>&1
 };
 function port_used_nc ()
 {
 nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
 };
 function port_used_lsof ()
 {
 lsof -i :"$2" > /dev/null 2>&1
 };
 function port_used_bash ()
 {
 local bash_supported=$(strings /bin/bash 2>/dev/null | grep tcp);
 if [ "$bash_supported" == "/dev/tcp/*/*" ]; then
 ( : < /dev/tcp/$1/$2 ) > /dev/null 2>&1;
 else
 return 127;
 fi
 };
 function port_used ()
 {
 local port="${1#*:}";
 local host=$((expr "${1}" : '\(.*\):' || echo "localhost") | awk 'END{print $NF}');
 local port_strategies=(port_used_nc port_used_lsof port_used_bash port_used_python port_used_python3);
 for strategy in ${port_strategies[@]};
 do
 $strategy $host $port;
 status=$?;
 if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
 return $status;
 fi;
 done;
 return 127
 };
 export -f port_used;
 function find_port ()
 {
 local host="${1:-localhost}";
 local min_port=${2:-2000};
 local max_port=${3:-65535};
 local port_range=($(shuf -i ${min_port}-${max_port}));
 local retries=1;
 for ((attempt=0; attempt<=$retries; attempt++))
 do
 for port in "${port_range[@]}";
 do
 if port_used "${host}:${port}"; then
 continue;
 fi;
 echo "${port}";
 return 0;
 done;
 done;
 echo "error: failed to find available port in range ${min_port}..${max_port}" 1>&2;
 return 1
 };
 export -f find_port;
 function wait_until_port_used ()
 {
 local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
 };
 export -f wait_until_port_used;
 function create_passwd ()
 {
 ( set +o pipefail;
 tr -cd 'a-zA-Z0-9' < /dev/urandom 2> /dev/null | head -c${1:-8} )
 };
 export -f create_passwd
}
BASH_FUNC_wait_until_port_used%%=() {  local port="${1}";
 local time="${2:-30}";
 for ((i=1; i<=time*2; i++))
 do
 port_used "${port}";
 port_status=$?;
 if [ "$port_status" == "0" ]; then
 return 0;
 else
 if [ "$port_status" == "127" ]; then
 echo "commands to find port were either not found or inaccessible.";
 echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib.";
 return 127;
 fi;
 fi;
 sleep 0.5;
 done;
 return 1
}
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
CLICOLOR=1
CLICOLOR_FORCE=1
CONDA_SSL_VERIFY=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/ssl/cert.pem
CONFIG_FILE=/tmp/jupyter-config.py
CPATH=/common/software/install/migrated/cuda/10.0/include
CPLUS_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
CUDA_HOME=/common/software/install/migrated/cuda/10.0
CUDA_INSTALL_PATH=/common/software/install/migrated/cuda/10.0
CUDA_SDK_VERSION=10.0
CUDA_VISIBLE_DEVICES=0
C_INCLUDE_PATH=/common/software/install/migrated/cuda/10.0/include
DEBUGINFOD_URLS=https://debuginfod.centos.org/
ENVIRONMENT=BATCH
FORCE_COLOR=1
FPATH=/common/software/install/migrated/cuda/10.0/include
GIT_PAGER=cat
GPU_DEVICE_ORDINAL=0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/users/7/yu001011
HOSTNAME=agc04
HYDRA_BOOTSTRAP=slurm
HYDRA_FULL_ERROR=1
HYDRA_LAUNCHER_EXTRA_ARGS=--external-launcher
INCLUDE=/common/software/install/migrated/cuda/10.0/include
I_MPI_HYDRA_BOOTSTRAP=slurm
I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS=--external-launcher
JPY_PARENT_PID=3800063
JUPYTERLAB_WORKSPACES_DIR=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
LANG=C.UTF-8
LD_LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/common/software/install/migrated/cuda/10.0/lib64
LOADEDMODULES=anaconda/miniconda3_4.8.3-jupyter:cuda/10.0
LOCAL_RANK=0
LOGNAME=yu001011
MAIL=/var/spool/mail/yu001011
MANPATH=:/opt/puppetlabs/puppet/share/man:/opt/slurm/rocky8/ofed-25.10/x86_64/25.05.6/share/man
MASTER_ADDR=localhost
MASTER_PORT=36337
MODULEPATH=/common/software/modulefiles/manual/mangi:/common/software/modulefiles/migrated/mangi:/common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:/common/software/modulefiles/singularity-hpc:/common/software/modulefiles/manual/k40:/common/software/modulefiles/migrated/k40:/common/software/modulefiles/manual/v100:/common/software/modulefiles/migrated/v100:/common/software/modulefiles/manual/hpc:/common/software/modulefiles/migrated/hpc:/common/software/modulefiles/migrated/intel:/common/software/modulefiles/manual/common:/common/software/modulefiles/migrated/common:/common/software/modulefiles/migrated/centos7:/common/software/modulefiles/bundle/views/common
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD
MPLBACKEND=module://matplotlib_inline.backend_inline
MSIPROJECT=/projects/standard/csci5527
NOTEBOOK_ROOT=/users/7/yu001011
OLDHOME=/projects/standard/csci5527/yu001011
OLDPWD=/users/7/yu001011/ondemand/data/sys/dashboard/batch_connect/sys/bc_msi_jupyter/output/c71b406a-0d82-47ea-bee9-3ca7dddad90a
OMPI_MCA_plm_slurm_args=--external-launcher
PAGER=cat
PASSWORD_SHA1=e9c75bd383753d0da0a59d0ce05f0918670fb0fd
PATH=/common/software/install/migrated/cuda/10.0/bin:/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin:/opt/msi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
PRIMARY_GROUP=csci5527
PRTE_MCA_plm_slurm_args=--external-launcher
PUBLIC=/projects/standard/csci5527/public
PWD=/users/7/yu001011
PYDEVD_USE_FRAME_EVAL=NO
RANK=0
ROCR_VISIBLE_DEVICES=0
SALT=PkxLXexKKhVrnKXf
SCRATCH=/scratch.global
SCRATCH_GLOBAL=/scratch.global
SCRATCH_LOCAL=/scratch.local
SHARED=/projects/standard/csci5527/shared
SHELL=/bin/bash
SHLVL=3
SLURMD_NODENAME=agc04
SLURM_CLUSTER_NAME=agate
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_CPUS_ON_NODE=4
SLURM_EXPORT_ENV=NONE
SLURM_GET_USER_ENV=1
SLURM_GPUS_ON_NODE=1
SLURM_GTIDS=0
SLURM_JOBID=8142995
SLURM_JOB_ACCOUNT=csci5527
SLURM_JOB_CPUS_PER_NODE=4
SLURM_JOB_END_TIME=1777881335
SLURM_JOB_GID=12949
SLURM_JOB_GPUS=3
SLURM_JOB_ID=8142995
SLURM_JOB_NAME=ondemand/sys/dashboard/sys/bc_msi_jupyter
SLURM_JOB_NODELIST=agc04
SLURM_JOB_NUM_NODES=1
SLURM_JOB_PARTITION=interactive-gpu
SLURM_JOB_QOS=normal
SLURM_JOB_START_TIME=1777794934
SLURM_JOB_UID=83857
SLURM_JOB_USER=yu001011
SLURM_LOCALID=0
SLURM_MEM_PER_NODE=16384
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=agc04
SLURM_NPROCS=4
SLURM_NTASKS=4
SLURM_NTASKS_PER_NODE=4
SLURM_OOM_KILL_STEP=0
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_SCRIPT_CONTEXT=prolog_task
SLURM_SUBMIT_DIR=/var/www/ood/apps/sys/dashboard
SLURM_SUBMIT_HOST=harbor.msi.umn.edu
SLURM_TASKS_PER_NODE=4
SLURM_TASK_PID=3799937
SLURM_TOPOLOGY_ADDR=ibspine..ibl7.agc04
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.switch.node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
S_COLORS=auto
TERM=xterm-color
TMPDIR=/tmp
TOKENIZERS_PARALLELISM=false
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_yu001011
TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER=yu001011
VGL_DISPLAY=/dev/dri/card4
WORLD_SIZE=1
XDG_DATA_DIRS=/users/7/yu001011/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/tmp
ZE_AFFINITY_MASK=0
_=/common/software/install/migrated/anaconda/miniconda3_4.8.3-jupyter/bin/jupyter
_LMFILES_=/common/software/modulefiles/migrated/hpc/anaconda/miniconda3_4.8.3-jupyter:/common/software/modulefiles/migrated/hpc/cuda/10.0
__MODULES_LMALTNAME=anaconda/miniconda3_4.8.3-jupyter&as|anaconda/latest
__MODULES_LMINIT=module use --append /common/software/modulefiles/manual/mangi:module use --append /common/software/modulefiles/migrated/mangi:module use --append /common/software/modulefiles/spack.tcl/linux-centos7-ivybridge:module use --append /common/software/modulefiles/singularity-hpc:module use --append /common/software/modulefiles/manual/k40:module use --append /common/software/modulefiles/migrated/k40:module use --append /common/software/modulefiles/manual/v100:module use --append /common/software/modulefiles/migrated/v100:module use --append /common/software/modulefiles/manual/hpc:module use --append /common/software/modulefiles/migrated/hpc:module use --append /common/software/modulefiles/migrated/intel:module use --append /common/software/modulefiles/manual/common:module use --append /common/software/modulefiles/migrated/common:module use --append /common/software/modulefiles/migrated/centos7:module use --append /common/software/modulefiles/bundle/views/common
host=agc04.agate.msi.umn.edu
port=39666
which_declare=declare -f

INFO 2026-05-03 13:53:04,788 trainer.py:1080: Setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:53:04,788 logger.py:  61: TensorBoard SummaryWriter instantiated. Files will be stored in: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/tensorboard

INFO 2026-05-03 13:53:23,222 trainer.py:1150: ====================
INFO 2026-05-03 13:53:23,222 trainer.py:1151: Summary for model <class 'sam3.model.sam3_image.Sam3Image'>
INFO 2026-05-03 13:53:23,226 trainer.py:1152: Model is Sam3Image(
  (backbone): SAM3VLBackbone(
    (vision_backbone): Sam3DualViTDetNeck(
      (trunk): ViT(
        (patch_embed): PatchEmbed(
          (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        )
        (blocks): ModuleList(
          (0): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): Identity()
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.003)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (2): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.006)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (3): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.010)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (4): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (5): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.016)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (6): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.019)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (7): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.023)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (8): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (9): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.029)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (10): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.032)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (11): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.035)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (12): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (13): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.042)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (14): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.045)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (15): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.048)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (16): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (17): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.055)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (18): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.058)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (19): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.061)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (20): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): Attention(
              (qkv): Linear(in_features=1024, out_features=3072, bias=True)
              (proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (ls1): Identity()
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=1024, out_features=4736, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (norm): Identity()
              (fc2): Linear(in_features=4736, out_features=1024, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (ls2): Identity()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (21): Block(
            (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)

WARNING: TIDE not installed. Detailed analysis will not be available.
INFO 2026-05-03 13:53:27,043 coco_writer.py:  93: Created prediction dump directory: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test
INFO 2026-05-03 13:53:27,044 trainer.py:1114: Finished setting up components: Model, loss, optim, meters etc.
INFO 2026-05-03 13:53:27,044 trainer.py: 323: Moving components to device cuda:0 and local rank 0.
INFO 2026-05-03 13:53:27,052 trainer.py: 329: Done moving components to device cuda:0 and local rank 0.

/users/7/yu001011/csci5527/.venv/lib/python3.11/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
[rank0]:[W503 13:53:27.049634644 ProcessGroupNCCL.cpp:5188] Guessing device ID based on global rank. This can cause a hang if rank to GPU mapping is heterogeneous. You can specify device_id in init_process_group()

Raw dataset length = 38
INFO 2026-05-03 13:53:27,332 trainer.py: 437: Resuming training from /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/checkpoints/checkpoint.pt
INFO 2026-05-03 13:53:54,751 train_utils.py: 269: Val Epoch: [4][ 0/38] | Batch Time: 20.39 (20.39) | Data Time: 0.08 (0.08) | Mem (GB): 42.00 (42.00/42.00) | Time Elapsed: 00d 00h 18m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:54:02,236 train_utils.py: 269: Val Epoch: [4][10/38] | Batch Time: 0.71 (2.53) | Data Time: 0.03 (0.05) | Mem (GB): 7.00 (10.18/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:54:09,669 train_utils.py: 269: Val Epoch: [4][20/38] | Batch Time: 0.70 (1.68) | Data Time: 0.03 (0.06) | Mem (GB): 7.00 (8.67/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:54:16,819 train_utils.py: 269: Val Epoch: [4][30/38] | Batch Time: 0.70 (1.37) | Data Time: 0.02 (0.05) | Mem (GB): 7.00 (8.13/42.00) | Time Elapsed: 00d 00h 19m | Losses/val_all_loss: 0.00e+00 (0.00e+00) | Losses/val_default_loss: 0.00e+00 (0.00e+00) | val_ttd/segmentation/: 0.0000
INFO 2026-05-03 13:54:22,472 trainer.py:1042: Estimated time remaining: 00d 00h 00m
INFO 2026-05-03 13:54:22,473 trainer.py: 984: Synchronizing meters
INFO 2026-05-03 13:54:22,473 coco_writer.py: 131: Prediction Dumper: Synchronizing between processes
INFO 2026-05-03 13:54:22,473 coco_writer.py: 166: Prediction Dumper: Gathering predictions from all processes
INFO 2026-05-03 13:54:22,845 coco_writer.py: 147: Prediction Dumper: Dumping merged predictions to /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
INFO 2026-05-03 13:54:23,056 coco_eval_offline.py: 147: OfflineCoco evaluator: Loading groundtruth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO 2026-05-03 13:54:23,077 coco_eval_offline.py: 162: Coco evaluator: Creating the result file
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
INFO 2026-05-03 13:54:23,090 coco_eval_offline.py: 166: Coco evaluator: Running evaluation
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.07s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.008
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.065
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.016
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.116
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.126
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.153
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.150
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.155
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
INFO 2026-05-03 13:54:23,175 trainer.py: 765: Meters: {'Meters_train/val_ttd/segmentation/coco_eval_segm_AP': 0.007990574293319171, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_50': 0.06492153880260289, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_75': 0.002685310963911101, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_small': 0.0013415499562835543, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_medium': 0.01580337992389356, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AP_large': -1.0, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@1': 0.11578947368421053, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@10': 0.12631578947368421, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_maxDets@100': 0.1526315789473684, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_small': 0.15, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_medium': 0.15454545454545454, 'Meters_train/val_ttd/segmentation/coco_eval_segm_AR_large': -1.0, 'Losses/val_all_loss': 0, 'Losses/val_default_loss': 0, 'Losses/val_ttd_core_loss': 0.0, 'Trainer/where': 0.0, 'Trainer/epoch': 4, 'Trainer/steps_val': 38}

[rank0]:[W503 13:54:23.718849867 ProcessGroupNCCL.cpp:1575] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Prediction exists: True

,experiment_key,experiment_name,shot_per_class,run_tag,train_status,eval_status,checkpoint,prediction_json,error
0,single_tb_5shot_stable_lowlr_v1,Single-TB,5,stable_lowlr_v1,skipped,skipped,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
1,single_tb_10shot_stable_lowlr_v1,Single-TB,10,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
2,single_tb_25shot_stable_lowlr_v1,Single-TB,25,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
3,single_tb_50shot_stable_lowlr_v1,Single-TB,50,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
4,shift_ta_tc_to_tb_10pct_5shot_stable_lowlr_v1,Shift-TA_TC-to-TB_10pct,5,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
5,shift_ta_tc_to_tb_10pct_10shot_stable_lowlr_v1,Shift-TA_TC-to-TB_10pct,10,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
6,shift_ta_tc_to_tb_10pct_25shot_stable_lowlr_v1,Shift-TA_TC-to-TB_10pct,25,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
7,shift_ta_tc_to_tb_10pct_50shot_stable_lowlr_v1,Shift-TA_TC-to-TB_10pct,50,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
8,shift_ta_tb_to_tc_10pct_5shot_stable_lowlr_v1,Shift-TA_TB-to-TC_10pct,5,stable_lowlr_v1,skipped,skipped,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
9,shift_ta_tb_to_tc_10pct_10shot_stable_lowlr_v1,Shift-TA_TB-to-TC_10pct,10,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
10,shift_ta_tb_to_tc_10pct_25shot_stable_lowlr_v1,Shift-TA_TB-to-TC_10pct,25,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None
11,shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1,Shift-TA_TB-to-TC_10pct,50,stable_lowlr_v1,trained,evaluated,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,/users/7/yu001011/csci5527/CSCI5527-final/SAM3...,None

## IoU Analysis: How to Read It

COCO AP already uses IoU internally, but it does not show direct overlap statistics. This cell adds a more literal mask-overlap view for the test set.

- **mean_best_iou_gt**: for each ground-truth crack mask, find the best overlapping predicted mask; higher means masks overlap the objects better.
- **gt_recall@0.50 / gt_recall@0.75**: fraction of ground-truth objects that have at least one prediction with mask IoU above the threshold. This answers, “how many real cracks did we find?”
- **pred_precision@0.50 / pred_precision@0.75**: fraction of predictions that match a ground-truth object above the threshold. This answers, “how many predicted cracks were credible?”
- **f1@threshold**: harmonic mean of recall and precision at that IoU threshold.
- **matched_mean_iou@threshold**: mean IoU of one-to-one greedy matches at that threshold; this ignores unmatched false positives/false negatives, so read it together with recall and precision.

A common interpretation is: IoU@0.50 is a loose localization check, IoU@0.75 is a stricter mask-quality check. If recall@0.50 is much higher than recall@0.75, the model is roughly finding objects but mask boundaries/localization are weak.

The score-threshold table is important because the prediction dump keeps many low-confidence masks. Very low precision at `score >= 0.00` can simply mean there are many low-confidence extra masks; check whether precision improves as the score threshold increases.

In [4]:
# IoU Analysis: direct mask-overlap metrics on the test predictions
import numpy as np
import pandas as pd
from pycocotools.coco import COCO
from pycocotools import mask as mask_utils

if "EXPERIMENT" not in globals():
    raise RuntimeError("Run the Experiment Selection cell first.")

PRED_JSON = RUN_DIR / "dumps" / "ttd" / "test" / "coco_predictions_segm.json"
GT_JSON = RUN_ROOT / "test" / "_annotations.coco.json"

print("Selected experiment:", EXPERIMENT_KEY)
print("Prediction file:", PRED_JSON)
print("Ground truth file:", GT_JSON)

if not PRED_JSON.exists():
    raise FileNotFoundError(f"Prediction file not found. Run the Test Eval cell first: {PRED_JSON}")
if PRED_JSON.stat().st_size <= 2:
    raise ValueError(f"Prediction file is empty. Re-run Test Eval after the config fixes: {PRED_JSON}")

coco_gt = COCO(str(GT_JSON))
coco_dt = coco_gt.loadRes(str(PRED_JSON))

cat_ids = coco_gt.getCatIds()
img_ids = coco_gt.getImgIds()
cat_name = {cat["id"]: cat["name"] for cat in coco_gt.loadCats(cat_ids)}

def ann_to_rle(coco, ann):
    """Return a COCO RLE dict for one annotation segmentation."""
    h, w = coco.imgs[ann["image_id"]]["height"], coco.imgs[ann["image_id"]]["width"]
    seg = ann["segmentation"]
    if isinstance(seg, list):
        rles = mask_utils.frPyObjects(seg, h, w)
        return mask_utils.merge(rles)
    if isinstance(seg.get("counts"), list):
        return mask_utils.frPyObjects(seg, h, w)
    return seg

def greedy_match_ious(iou_matrix, threshold):
    """Greedy one-to-one matching by descending IoU."""
    if iou_matrix.size == 0:
        return []
    pairs = []
    for pred_idx, gt_idx in zip(*np.where(iou_matrix >= threshold)):
        pairs.append((float(iou_matrix[pred_idx, gt_idx]), int(pred_idx), int(gt_idx)))
    pairs.sort(reverse=True)
    used_pred, used_gt, matched = set(), set(), []
    for iou, pred_idx, gt_idx in pairs:
        if pred_idx in used_pred or gt_idx in used_gt:
            continue
        used_pred.add(pred_idx)
        used_gt.add(gt_idx)
        matched.append(iou)
    return matched

def summarize_iou(cat_id=None, score_threshold=0.0, thresholds=(0.50, 0.75)):
    best_iou_per_gt = []
    best_iou_per_pred = []
    matched_by_threshold = {thr: [] for thr in thresholds}
    total_gt = 0
    total_pred = 0
    images_with_gt = 0
    images_with_pred = 0

    cats = [cat_id] if cat_id is not None else cat_ids
    for img_id in img_ids:
        for cur_cat_id in cats:
            gt_anns = coco_gt.loadAnns(coco_gt.getAnnIds(imgIds=[img_id], catIds=[cur_cat_id], iscrowd=None))
            dt_anns = coco_dt.loadAnns(coco_dt.getAnnIds(imgIds=[img_id], catIds=[cur_cat_id]))
            dt_anns = [ann for ann in dt_anns if ann.get("score", 0.0) >= score_threshold]
            dt_anns = sorted(dt_anns, key=lambda ann: ann.get("score", 0.0), reverse=True)

            if gt_anns:
                images_with_gt += 1
            if dt_anns:
                images_with_pred += 1
            total_gt += len(gt_anns)
            total_pred += len(dt_anns)

            if not gt_anns and not dt_anns:
                continue
            if not gt_anns:
                best_iou_per_pred.extend([0.0] * len(dt_anns))
                continue
            if not dt_anns:
                best_iou_per_gt.extend([0.0] * len(gt_anns))
                continue

            gt_rles = [ann_to_rle(coco_gt, ann) for ann in gt_anns]
            dt_rles = [ann["segmentation"] for ann in dt_anns]
            iscrowd = [int(ann.get("iscrowd", 0)) for ann in gt_anns]
            ious = mask_utils.iou(dt_rles, gt_rles, iscrowd)

            best_iou_per_gt.extend(ious.max(axis=0).tolist())
            best_iou_per_pred.extend(ious.max(axis=1).tolist())
            for thr in thresholds:
                matched_by_threshold[thr].extend(greedy_match_ious(ious, thr))

    best_iou_per_gt = np.asarray(best_iou_per_gt, dtype=float)
    best_iou_per_pred = np.asarray(best_iou_per_pred, dtype=float)

    row = {
        "category": "all" if cat_id is None else cat_name.get(cat_id, str(cat_id)),
        "score_threshold": score_threshold,
        "images": len(img_ids),
        "images_with_gt": images_with_gt,
        "images_with_pred": images_with_pred,
        "gt_instances": total_gt,
        "pred_instances": total_pred,
        "mean_best_iou_gt": float(best_iou_per_gt.mean()) if total_gt else np.nan,
        "median_best_iou_gt": float(np.median(best_iou_per_gt)) if total_gt else np.nan,
        "mean_best_iou_pred": float(best_iou_per_pred.mean()) if total_pred else np.nan,
    }

    for thr in thresholds:
        matched = matched_by_threshold[thr]
        recall = len(matched) / total_gt if total_gt else np.nan
        precision = len(matched) / total_pred if total_pred else np.nan
        f1 = (2 * precision * recall / (precision + recall)) if precision + recall > 0 else 0.0
        row[f"gt_recall@{thr:.2f}"] = recall
        row[f"pred_precision@{thr:.2f}"] = precision
        row[f"f1@{thr:.2f}"] = f1
        row[f"matched_mean_iou@{thr:.2f}"] = float(np.mean(matched)) if matched else 0.0

    return row, best_iou_per_gt, best_iou_per_pred

def rounded_df(rows):
    df = pd.DataFrame(rows)
    for col in df.columns:
        if df[col].dtype.kind in "fc":
            df[col] = df[col].round(4)
    return df

print(f"Prediction file: {PRED_JSON}")
print(f"Ground truth file: {GT_JSON}")

rows = []
overall_row, best_gt, best_pred = summarize_iou(cat_id=None, score_threshold=0.0)
rows.append(overall_row)
for cat_id in cat_ids:
    row, _, _ = summarize_iou(cat_id=cat_id, score_threshold=0.0)
    rows.append(row)

print("Overall/category IoU summary using all predictions:")
display(rounded_df(rows))

threshold_rows = []
for score_thr in [0.0, 0.01, 0.05, 0.10, 0.25, 0.50]:
    row, _, _ = summarize_iou(cat_id=None, score_threshold=score_thr)
    threshold_rows.append(row)

print("IoU summary at different prediction score thresholds:")
display(rounded_df(threshold_rows))

hist_bins = [0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0]
hist_counts, bin_edges = np.histogram(best_gt, bins=hist_bins)
hist_df = pd.DataFrame({
    "best_gt_iou_bin": [f"[{bin_edges[i]:.2f}, {bin_edges[i+1]:.2f})" for i in range(len(hist_counts))],
    "gt_count": hist_counts,
})
hist_df.loc[len(hist_df) - 1, "best_gt_iou_bin"] = f"[{bin_edges[-2]:.2f}, {bin_edges[-1]:.2f}]"
print("Best-IoU distribution over ground-truth instances:")
display(hist_df)

Selected experiment: shift_ta_tb_to_tc_10pct_50shot_stable_lowlr_v1
Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Ground truth file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class/test/_annotations.coco.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Prediction file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/outputs/fewshot_runs/Shift-TA_TB-to-TC_10pct/50_shot_per_class_stable_lowlr_v1/dumps/ttd/test/coco_predictions_segm.json
Ground truth file: /users/7/yu001011/csci5527/CSCI5527-final/SAM3/fewshot_data/Shift-TA_TB-to-TC_10pct/50_shot_per_class/test/_annotations.coco.json
Overall/category IoU summary using all predictions:

,category,score_threshold,images,images_with_gt,images_with_pred,gt_instances,pred_instances,mean_best_iou_gt,median_best_iou_gt,mean_best_iou_pred,gt_recall@0.50,pred_precision@0.50,f1@0.50,matched_mean_iou@0.50,gt_recall@0.75,pred_precision@0.75,f1@0.75,matched_mean_iou@0.75
0,all,0.0,38,19,38,19,3800,0.4589,0.4805,0.0406,0.4211,0.0021,0.0042,0.6532,0.1579,0.0008,0.0016,0.7879
1,crack,0.0,38,19,38,19,3800,0.4589,0.4805,0.0406,0.4211,0.0021,0.0042,0.6532,0.1579,0.0008,0.0016,0.7879

IoU summary at different prediction score thresholds:

,category,score_threshold,images,images_with_gt,images_with_pred,gt_instances,pred_instances,mean_best_iou_gt,median_best_iou_gt,mean_best_iou_pred,gt_recall@0.50,pred_precision@0.50,f1@0.50,matched_mean_iou@0.50,gt_recall@0.75,pred_precision@0.75,f1@0.75,matched_mean_iou@0.75
0,all,0.00,38,19,38,19,3800,0.4589,0.4805,0.0406,0.4211,0.0021,0.0042,0.6532,0.1579,0.0008,0.0016,0.7879
1,all,0.01,38,19,10,19,682,0.2305,0.0000,0.1202,0.1579,0.0044,0.0086,0.7017,0.1053,0.0029,0.0057,0.8000
2,all,0.05,38,19,8,19,310,0.1915,0.0000,0.1480,0.1579,0.0097,0.0182,0.6969,0.1053,0.0065,0.0122,0.7927
3,all,0.10,38,19,7,19,86,0.1498,0.0000,0.1942,0.1053,0.0233,0.0381,0.6497,0.0526,0.0116,0.0190,0.7941
4,all,0.25,38,19,6,19,11,0.1047,0.0000,0.2565,0.0526,0.0909,0.0667,0.5052,0.0000,0.0000,0.0000,0.0000
5,all,0.50,38,19,3,19,3,0.0675,0.0000,0.4274,0.0526,0.3333,0.0909,0.5052,0.0000,0.0000,0.0000,0.0000

Best-IoU distribution over ground-truth instances:

  best_gt_iou_bin  gt_count
0    [0.00, 0.10)         1
1    [0.10, 0.25)         3
2    [0.25, 0.50)         7
3    [0.50, 0.75)         5
4    [0.75, 0.90)         3
5    [0.90, 1.00]         0